### ISSUE TITLE
Where the trained model will save?

### ISSUE THREAD

**Issue by isalirezag** [junyanz/pytorch-CycleGAN-and-pix2pix#100]
Naive question.
Where does the train model will be saved? what folder and with what name?
I am trying to find it to load it but I cannot

**Comment by khryang** [comment]
There is in the directory of 'checkpoints'
when you run the code with train.py, the 'checkpoints' directory will be created in the directory where you run the 'train.py' code.

And the results of test are in the 'results' directory. It is also created when you run the 'test.py' code.

**Comment by isalirezag** [comment]
@khryang So it will not save the trained model, right? it is just saving the images in checkpoints

**Comment by khryang** [comment]
@isalirezag In checkpoints directory, you can see the file of *.pth. I know that this file is the trained network. every 5 epoch, it will be saved.

is this answer what you mean?

**Comment by isalirezag** [comment]
@khryang Soo I can reload this *.pth file letter if I want to reload the trained model?

**Comment by khryang** [comment]
@isalirezag  when you test the trained model, the latest trained network which named 'latest_net*.pth' will be loaded and used for test!
