### ISSUE TITLE
Can you please describe about the GAN mode in details?

### ISSUE THREAD

**Issue by kalai2033** [junyanz/pytorch-CycleGAN-and-pix2pix#1011]
Hi,
   I would like to know the difference between each of the GAN mode. Can you please explain in short? I understand that vanilla GAN is used for pix2pix, lsGAN for cycleGAN. I have a paired dataset and using pix2pix model for kind of segmentation task. I get decent results with vanilla GAN but id like to improve the results. Before that id like to understand fully about each of the loss objectives.

**Comment by junyanz** [comment]
I think LSGAN is a more stable loss compared to vanilla GAN. It has a better gradient property. I encourage you to read the original [work](https://arxiv.org/abs/1611.04076). You are free to use LSGAN in your task. Maybe you want to change `--lambda_L1` to 10 or 25, as LSGAN's GAN loss has a larger range compared to vanilla GANs.
