### ISSUE TITLE
About direction

### ISSUE THREAD

**Issue by PhoneSix** [junyanz/pytorch-CycleGAN-and-pix2pix#1014]
Does direction affect the final model of CycleGAN? It seems that no matter what the direction is,  we will get both generator A and generator B, and the length of training dataset  is the maximum of A and B.
BTW, it seems that increasing batch_size will not decrease iterations per epoch. It's kind of confusing for me.

**Comment by junyanz** [comment]
The direction should not matter for CycleGAN. It matters in the pix2pix setting.

**Comment by PhoneSix** [comment]
@junyanz Thank you for your reply. And what about the relationship between batch_size and iterations/epoch? 

> BTW, it seems that increasing batch_size will not decrease iterations per epoch. It's kind of confusing for me.

**Comment by junyanz** [comment]
We multiply the training iteration by batch_size. See this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/train.py#L49).

**Comment by PhoneSix** [comment]
Thanks!
