### ISSUE TITLE
Tips for fixing what might be over generalization?

### ISSUE THREAD

**Issue by JohanRaniseth** [junyanz/pytorch-CycleGAN-and-pix2pix#1015]
Hey,

I tried training a pix2pix model on a small training set of around 300 images cropped in different ways from a ~4000x4000 pixel image. The  image is the topography of a landscape where each pixel represents a height. [4000x4000](https://gyazo.com/4982027fd94578fb9ba0da8fca254dd2).
The goals is to translate from topography without snow to topography with snow.

During training when it generates samples it seems to reproduce the height profile of the real image well. [training sample](https://gyazo.com/1e7e32c6f33065a9b7968c81f6cb9a8c).
But when testing on an image from the validation dataset the resulting height profile is wrong but with somewhat the same shape. [validation/testing sample](https://gyazo.com/641249d04ce984676b8269dc464c5759)

The pix2pix model seems to generalize well for training images but not unseen images. Does anyone know of methods or other models that possibly might give better results for my type of image translation task?

Best,
Johan

**Comment by junyanz** [comment]
You probably need to collect more than 1 training image. Even you sample 300 patches, the model still only sees one image.

**Comment by JohanRaniseth** [comment]
Thank you @junyanz. When you say that I need more training images do you mean just a larger area? Or the same area with different snow distributions?

**Comment by junyanz** [comment]
It can be both. Make sure that your training inputs' distribution is similar to test inputs' distribution.
