### ISSUE TITLE
AttributeError: 'ResnetGenerator' object has no attribute 'module'

### ISSUE THREAD

**Issue by absagargupta** [junyanz/pytorch-CycleGAN-and-pix2pix#1019]
Hello there
On running the test.py I am getting this error. AttributeError: 'ResnetGenerator' object has no attribute 'module'. I am training it on gpu 0 and have trained the model myself.

**Comment by absagargupta** [comment]
My full traceback is as such
         aspect_ratio: 1.0                          
               batch_size: 8                            
          checkpoints_dir: ./checkpoints                
                crop_size: 384                          
                 dataroot: ./datasets/sysuresults        
             dataset_mode: unaligned                    
                direction: AtoB                          
          display_winsize: 256                          
                    epoch: latest                        
                     eval: False                        
                  gpu_ids: 0                            
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 21                            
                  isTrain: False                                [default: None]
                load_iter: 0                                    [default: 0]
                load_size: 384                          
         max_dataset_size: inf                          
                    model: cycle_gan                    
               n_layers_D: 3                            
                     name: simplecyclegan_nopose        
                      ndf: 64                            
                     netD: basic                        
                     netG: resnet_6blocks                
                      ngf: 64                            
               no_dropout: True                          
                  no_flip: False                        
                     norm: batch                        
                    ntest: inf                          
                 num_test: 6289                          
              num_threads: 4                            
                output_nc: 3                            
                    phase: test                          
               preprocess: resize_and_crop              
              results_dir: ./results/                    
           serial_batches: False                        
                   suffix:                              
                  verbose: False                        
----------------- End -------------------
dataset [UnalignedDataset] was created
initialize network with normal
initialize network with normal
model [CycleGANModel] was created
loading the model from ./checkpoints/simplecyclegan_nopose/latest_net_G_A.pth
Traceback (most recent call last):

  File "<ipython-input-2-2c53477dc693>", line 1, in <module>
    runfile('/home/sagar18174/Thesis/person_RE-identification/pytorch-CycleGAN-and-pix2pix-master_with_pose_gpu_troubleshoot/test.py', wdir='/home/sagar18174/Thesis/person_RE-identification/pytorch-CycleGAN-and-pix2pix-master_with_pose_gpu_troubleshoot')

  File "/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/sagar18174/Thesis/person_RE-identification/pytorch-CycleGAN-and-pix2pix-master_with_pose_gpu_troubleshoot/test.py", line 48, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers

  File "/home/sagar18174/Thesis/person_RE-identification/pytorch-CycleGAN-and-pix2pix-master_with_pose_gpu_troubleshoot/models/base_model.py", line 88, in setup
    self.load_networks(load_suffix)

  File "/home/sagar18174/Thesis/person_RE-identification/pytorch-CycleGAN-and-pix2pix-master_with_pose_gpu_troubleshoot/models/base_model.py", line 194, in load_networks
    self.__patch_instance_norm_state_dict(state_dict, net, key.split('.'))

  File "/home/sagar18174/Thesis/person_RE-identification/pytorch-CycleGAN-and-pix2pix-master_with_pose_gpu_troubleshoot/models/base_model.py", line 170, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)

  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))

AttributeError: 'ResnetGenerator' object has no attribute 'module'

**Comment by junyanz** [comment]
See this [Q&A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#runtimeerror-errors-in-loading-state_dict-812-671461-296). Make sure that you specify the `--netG` and `--norm`.

**Comment by absagargupta** [comment]
I am using resnet_6block and norm as batch

**Comment by absagargupta** [comment]
I still have this issue even after giving --netG and --norm. Do you know why this problem is occuring

**Comment by junyanz** [comment]
I don't have a clue. Have you used the same dropout flag `----no_dropout` during training and test?

**Comment by absagargupta** [comment]
I redownloaded and ran the code again. It worked properly this time.

**Comment by EWJGH** [comment]
you should check your steoGAN's parameters; if you have "--fusionblock" in your train.py parameters;you should add "--fusionblock" in your test.py parameters too
