### ISSUE TITLE
When Test Model: AttributeError: 'Namespace' object has no attribute 'identity'

### ISSUE THREAD

**Issue by wlwsea** [junyanz/pytorch-CycleGAN-and-pix2pix#102]
Hello @andyli @phillipi @taesung89 @alanyee @junyanz  ,

When I used the following command,
`python test.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --phase test --no_dropout`
It showed the following error. What's the reason of that? And how can i solve this problem?

Thanks a ton!

```
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    visuals = model.get_current_visuals()
  File "/pytorch-CycleGAN-and-pix2pix-master/models/cycle_gan_model.py", line 193, in get_current_visuals
    if self.opt.identity > 0.0:
AttributeError: 'Namespace' object has no attribute 'identity'
```

**Comment by PraveerSINGH** [comment]
@wlwsea: Were you able to resolve this error ? I am having similar issue.

**Comment by wlwsea** [comment]
@PraveerSINGH 
I didn't find the reason of that error, so I just commented out the code that cause  the error.

**Comment by skatset** [comment]
The problem starts from [commit ee5d38e287](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/ee5d38e287e3dda25fa159baa7232d6f6588267a). You can copy and paste changes from file options/train_options.py to options/test_options.py. This workaround fix problem for me.

**Comment by wlwsea** [comment]
@skatset 
Thanks for your help!

**Comment by junyanz** [comment]
It should be fixed now.
