### ISSUE TITLE
The image is blurry and has a lot of noise (pix2pix)

### ISSUE THREAD

**Issue by ArtScanner** [junyanz/pytorch-CycleGAN-and-pix2pix#1021]
The image of the test result has a lot of noise and blur(pix2pix)

**Comment by junyanz** [comment]
Hard to know the reason without seeing the script, data, and results.

**Comment by ArtScanner** [comment]
![20200509182600](https://user-images.githubusercontent.com/64313883/81471278-971c9e80-9222-11ea-8821-84302cd94698.png)

**Comment by junyanz** [comment]
See this [post](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/190) on checkboard artifacts. Sometimes it will disappear after many training epochs. If it still exists, you can consider replacing `ConvTranspose2d` with `Upsample` and `Conv2d`. You can also try some conv blocks from [StyleGANv2](https://github.com/NVlabs/stylegan2).

**Comment by ArtScanner** [comment]
Thanks for your reply :)
