### ISSUE TITLE
Implementation of cycle consistency loss is different from the paper Eq.(2)

### ISSUE THREAD

**Issue by EvaFlower** [junyanz/pytorch-CycleGAN-and-pix2pix#1023]
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/482947685f2e6fdf586edffc6154041951db89fe/models/cycle_gan_model.py#L91

Hi there,

The implementation of your consistency loss is divided by the size of the image because the default option of nn.L1Loss is reduction="mean". So the lambda_cycle is set to be 10*image_size, right, if the l1 norm is implemented in an original way (sum of the absolute difference).

**Comment by junyanz** [comment]
Yes. It is normalized by the size of the image. The GAN loss is also an average rather than a sum. Most of the papers implement the norm as an average rather than a sum so that the image size does not matter.

**Comment by EvaFlower** [comment]
Thanks for your reply.
