### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by xywftbt** [junyanz/pytorch-CycleGAN-and-pix2pix#103]
when I run the train.py as written in the README
python test.py --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --which_model_netG unet_256 --which_direction BtoA --dataset_mode aligned --norm batch

there are two errors:
------------ Options -------------
batchSize: 1
beta1: 0.5
checkpoints_dir: ./checkpoints
continue_train: False
dataroot: /home/1trynew/pytorch-CycleGAN-and-pix2pix/datasets/facades128
dataset_mode: aligned
display_freq: 100
display_id: 1
display_port: 8097
display_single_pane_ncols: 0
display_winsize: 128
epoch_count: 1
fineSize: 128
gpu_ids: [0]
identity: 0.0
input_nc: 3
isTrain: True
lambda_A: 10.0
lambda_B: 10.0
loadSize: 128
lr: 0.0002
max_dataset_size: inf
model: pix2pix
nThreads: 2
n_layers_D: 3
name: facades_pix2pix
ndf: 64
ngf: 64
niter: 100
niter_decay: 100
no_dropout: False
no_flip: False
no_html: False
no_lsgan: False
norm: instance
output_nc: 3
phase: train
pool_size: 50
print_freq: 100
resize_or_crop: resize_and_crop
save_epoch_freq: 5
save_latest_freq: 5000
serial_batches: False
which_direction: BtoA
which_epoch: latest
which_model_netD: basic
which_model_netG: resnet_9blocks
-------------- End ----------------
CustomDatasetDataLoader
dataset [AlignedDataset] was created
#training images = 400
pix2pix

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)  
or 
------------ Options -------------
batchSize: 1
beta1: 0.5
checkpoints_dir: ./checkpoints
......
-------------- End ----------------
CustomDatasetDataLoader
dataset [AlignedDataset] was created
#training images = 400
pix2pix
*** Error in `/home/as/anaconda3/bin/python': corrupted double-linked list: 0x0000000001253570 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f0acc79d7e5]
......
7f0acdd53000-7f0acdd54000 rw-p 00000000 00:00 0 
7ffcb813f000-7ffcb8160000 rw-p 00000000 00:00 0                          [stack]
7ffcb81a7000-7ffcb81a9000 r--p 00000000 00:00 0                          [vvar]
7ffcb81a9000-7ffcb81ab000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

Two errors appear alternately
how can I resolve these errors?

**Comment by junyanz** [comment]
Not sure about that. Are you using the latest pytorch (v0.2)?
