### ISSUE TITLE
Citation Issue

### ISSUE THREAD

**Issue by hellosaumil** [junyanz/pytorch-CycleGAN-and-pix2pix#1030]
Hi Jun-yan, @junyanz 

I love your CycleGAN paper and have used your code-base to create a CycleGAN that can synthesize dolphin whistle spectrograms. 

Also, I'm finishing up my thesis writing and wanted to cite your github repo specifically your [tips docs](https://github.com/hellosaumil/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md).

Could you please guide me on how to cite this? 

Thank you.

**Comment by junyanz** [comment]
Maybe just cite the original paper. If you want, you can add a footnote and include this repo's link.

**Comment by hellosaumil** [comment]
Sure, will do. Thank you! 👍🏻
