### ISSUE TITLE
RGB to Thermal image conversion pix2pix

### ISSUE THREAD

**Issue by durgesh17media** [junyanz/pytorch-CycleGAN-and-pix2pix#1038]
has anyone performed pix2pix approach for RGB to Thermal image translation?
I am getting very bad results while testing. anyone can help? 
 I used this command for testing:
python3 test.py --dataroot ./datasets/combine_faces/ --name face4_pix2pix --model pix2pix --direction AtoB

results: 
**Real A**

![1100_real_A](https://user-images.githubusercontent.com/65701365/82530185-63af0d80-9b5a-11ea-91a2-9fe9e420c0f9.png)

**Real B**
![1100_real_B](https://user-images.githubusercontent.com/65701365/82530188-6447a400-9b5a-11ea-979d-f40530845e28.png)

**FakeB**
![1100_fake_B](https://user-images.githubusercontent.com/65701365/82530180-61e54a00-9b5a-11ea-971d-b6d0505124d1.png)

**Comment by durgesh17media** [comment]
@junyanz sir

**Comment by junyanz** [comment]
I closed this issue. I replied to you at #1037.
