### ISSUE TITLE
Which part of channels in ConvTransposed2d comes from the bottleneck in Unet model?

### ISSUE THREAD

**Issue by LambdaWill** [junyanz/pytorch-CycleGAN-and-pix2pix#104]
As the channels are concatenated before the ConvTransposed2d.  Does the first half channels receive the data from the bottleneck or th latter half?

**Comment by taesung89** [comment]
[As you can see in this line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py#L314), the first half is the skip connection, and the later half comes from the bottleneck.
