### ISSUE TITLE
removing tiling artifacts

### ISSUE THREAD

**Issue by coded5282** [junyanz/pytorch-CycleGAN-and-pix2pix#1040]
Do you have any suggestions for removing tile artifacts on the generated images using CycleGAN? I've been using the PatchGAN discriminator and have tried a version of it with the 70x70 receptive field as well as one with 142x142 receptive field, but both still have tiles.

Any other suggestions would be greatly appreciated, thanks!

**Comment by MarioProjects** [comment]
Did you solved that?
