### ISSUE TITLE
Super resolution by pix2pix

### ISSUE THREAD

**Issue by xcyquan** [junyanz/pytorch-CycleGAN-and-pix2pix#1041]
I want to create a super resolution project by pix2pix . I use the default parameters for training but the effect is not ideal.Are there any training parameters that can make the training results better or where can I modify your project to improve the results.
Thank you in advance!
Best regards.

**Comment by junyanz** [comment]
The super-res network is often different from the image-to-image translation network. I recommend that you use the super-res network as the generator. A basic [version](https://github.com/eriklindernoren/PyTorch-GAN) is included in the PyTorch examples.
