### ISSUE TITLE
Pix2pix single data test mode error

### ISSUE THREAD

**Issue by Jungmin81** [junyanz/pytorch-CycleGAN-and-pix2pix#1042]
Here is my train code
!python3 train.py --dataroot data1/ --model pix2pix --name realm3 --direction BtoA --input_nc 1 --output_nc 1 
and here is my test code
!python3 test.py --dataroot test/ts1 --name realm3 --model pix2pix --netG unet_256 --direction BtoA --dataset_mode single --norm batch --input_nc 1 --output_nc 1 

But it occured error 
Traceback (most recent call last):
  File "test.py", line 62, in <module>
    model.set_input(data)  # unpack data from data loader
  File "/home/young0719/JM/p2p/pytorch-CycleGAN-and-pix2pix-master/pytorch-CycleGAN-and-pix2pix/models/pix2pix_model.py", line 82, in set_input
    self.real_A = input['A' if AtoB else 'B'].to(self.device)
KeyError: 'B'

My files already in that directory,, 
![image](https://user-images.githubusercontent.com/39875941/82753749-0c7f9600-9e03-11ea-8e38-f664f85c37b5.png)

Can u tell me what is the problem??
Thank you..

**Comment by Jungmin81** [comment]
I already solve!!

**Comment by Jungmin81** [comment]
--model pix2pix (x)
--model test

**Comment by rbunn80110** [comment]
> --model pix2pix (x)
> --model test(0)

I'm not sure I understand what you are using fox x and 0 here.
