### ISSUE TITLE
Issue in random cropping: differently located crops for RealA and RealB in "unaligned_dataset"

### ISSUE THREAD

**Issue by sohaib023** [junyanz/pytorch-CycleGAN-and-pix2pix#1061]
While training pix2pix for a custom dataset I noticed that the images stored in training directory to show the progress, had some weird RealB images, which did not correspond to the RealA images. 
With that I delved into the code to see what was going on while cropping. 
Two separate transforms are created for A and B images (which include the RandomCrop transform too), these are applied separately to both images thus producing different random crop for the image A then the image B.

**Comment by junyanz** [comment]
Yes, we applied different crops for `unaligned_dataset`. We applied the same crop for the `aligned_dataset`. Feel free to modify the data loader `unaligned_dataset`. See this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/aligned_dataset.py#L49).

**Comment by sohaib023** [comment]
Ok, thanks a lot for your response, I will edit my code to cater for it.
However, in the original code is it a desired behavior for some reason, or just something that needs to be fixed?

**Comment by sohaib023** [comment]
I believe the unaligned_dataset might need some additional documentation. The A and B images read by the class are not corresponding to each other unless --serial_batches flag is passed. As the description of the flag implies if this flag is false batches are taken randomly, and not that A and B are taken randomly, hence its not very clear.

**Comment by junyanz** [comment]
For `unaligned_dataset`, we assume that there is no correspondence between input and output. We don't know the pairing information of A and B at all. Otherwise, you should use `aligned_dataset`.  Please refer to Figure 2 of the original [paper](https://arxiv.org/pdf/1703.10593.pdf) for more details.
