### ISSUE TITLE
The direction of picture would be reversed sometimes

### ISSUE THREAD

**Issue by Orange199609** [junyanz/pytorch-CycleGAN-and-pix2pix#1062]
I found that during the training step, the direction of the input data would be reversed at times. That is the left side of the input picture would become the right side of the output picture in the temporary print stage. If the picture is colored, the color of the pictures would also be reversed at times. How can I solve such problem?

**Comment by junyanz** [comment]
1. You can use `--no_flip`. 2. Not sure about the color.

**Comment by Orange199609** [comment]
> 1. You can use `--no_flip`. 2. Not sure about the color.

Thanks a lot!
