### ISSUE TITLE
loading tensorflow datasets into google colab

### ISSUE THREAD

**Issue by randlelim** [junyanz/pytorch-CycleGAN-and-pix2pix#1063]
I am a student currently working on a project to make low quality images to high quality images using CycleGan. I have found a dataset on Tensorflow called div2k which have images that are of high and low resolution. I tried downloading it into my computer from the main website of the dataset and moved it into my google drive to link the dataset into colab.

However, I can't  use it as a dataroot from the file on drive. it says it is not a valid directory. I tried moving the file from drive into the cyclegan folder but, i does not work. What can i do to solve this issue?
![Capture](https://user-images.githubusercontent.com/66714229/84229951-69768e00-ab1d-11ea-8927-2afe4745246a.PNG)

**Comment by junyanz** [comment]
Doe the directory exist?

**Comment by randlelim** [comment]
yes it does

**Comment by randlelim** [comment]
![image](https://user-images.githubusercontent.com/66714229/84625023-06b63580-af15-11ea-84cc-000fd7a967c0.png)

i tried again and got this

**Comment by junyanz** [comment]
what is your training command?

**Comment by randlelim** [comment]
!git clone https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix
import os
os.chdir('pytorch-CycleGAN-and-pix2pix/')
!pip install -r requirements.txt
!python train.py --dataroot /content/drive/My Drive/div2k --name div2k --model cycle_gan

**Comment by randlelim** [comment]
!python train.
py --dataroot /content/drive/My Drive/div2k --name div2k --model cycle_gan

i only have this in my command.

**Comment by junyanz** [comment]
You have an empty space between `My` and `Drive`.

**Comment by randlelim** [comment]
[image: image.png]
this is what i got. i copied the path to the folder that is why the there
was a space in between my drive.

**Comment by junyanz** [comment]
See this [post](https://superuser.com/questions/256985/how-to-cd-to-a-directory-that-contains-a-space-in-its-name)

**Comment by randlelim** [comment]
Thank you so much it works now!
