### ISSUE TITLE
how to use pix2pix to train unpaired datasets

### ISSUE THREAD

**Issue by xcyquan** [junyanz/pytorch-CycleGAN-and-pix2pix#1064]
Hello, I want to train pix2pix with a small number of paired images first and then train a large number of unpaired images. Can the training of unpaired images use --dataset_mode aligned, or simply set L1_loss in pix2pix_model to 0? Do you have any useful suggestions, thanks！

**Comment by junyanz** [comment]
Your solution may not work. Setting L1_loss to 0 will not automatically enable unpaired training. You need to use several training scripts: (1) two pix2pix training scripts: both A->B and B->A, and (2) cyclegan training script with pre-trained models from step (1).

**Comment by xcyquan** [comment]
Thanks for your answer, I renamed the four latest_net.pth generated by the pix2pix model with ‘--input_nc 1 --output_nc 1’ and put it in cyclegan, using the script 
```
python train.py --dataroot ./datasets/HGCycleGAN --name HG_CycleGAN --model cycle_gan --netG unet_256 --norm batch  --gan_mode  vanilla    --no_dropout  --input_nc 1 --output_nc 1  --continue_train 
```
it does not work,The error is as follows.So how can I fix it

```
initialize network with normal
model [CycleGANModel] was created
loading the model from ./checkpoints\HG14_CycleGAN\latest_net_G_A.pth
loading the model from ./checkpoints\HG14_CycleGAN\latest_net_G_B.pth
loading the model from ./checkpoints\HG14_CycleGAN\latest_net_D_A.pth
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "E:\PycharmProjects\pytorch-CycleGAN-and-pix2pix\models\base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "E:\PycharmProjects\pytorch-CycleGAN-and-pix2pix\models\base_model.py", line 198, in load_networks
    net.load_state_dict(state_dict)
  File "E:\anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NLayerDiscriminator:
        size mismatch for model.0.weight: copying a param with shape torch.Size([64, 2, 4, 4]) from checkpoint, the shape in current model is torch.Size([64, 1, 4, 4]).
```

**Comment by junyanz** [comment]
You might have used the conditional discriminator in the pix2pix setting. The conditional discriminator takes both the input and output. Therefore, the number of input channels is 2. You can either skip the weights of the first layer during network loading or training pix2pix models with unconditional disseminators. Both require some minor modification of the code.

**Comment by xcyquan** [comment]
Thanks. I will try to do it.
