### ISSUE TITLE
what does mean 'index' in 'unaligned_dataset.py' code

### ISSUE THREAD

**Issue by khryang** [junyanz/pytorch-CycleGAN-and-pix2pix#107]
in unaligned_dataset.py code, there is __getitem__ method.
this 'getitem' need the value of index.
I cannot fine the mean of index.
is it from any option.py code??
please let me know anybody!

**Comment by junyanz** [comment]
It's not. It is called by DataLoader. See [here](http://www.diveintopython.net/object_oriented_framework/special_class_methods.html) for more details on `getitem` function in python.
