### ISSUE TITLE
Fixed correct pixels while training

### ISSUE THREAD

**Issue by yjs0704** [junyanz/pytorch-CycleGAN-and-pix2pix#1071]
Hi, thanks for the nice build.

I am wondering that is that a method to fix the correct pixels during the paired pix2pix training? What I mean is that G(A)->B, but A is already the same with B for most of the pixels, what I desire is to change some inconsistent parts to add in / change the very details. 

I have tried pixel-level discriminator + instance norm + strong L1 loss but it does not converge properly. Do you know any architecture that can do the above? Or probably I should skip the the normalisation layers?

Thanks again.

**Comment by junyanz** [comment]
If you know the mask `m`, you can modify the generation process as `G(x)*m+x*(1-m)`.

**Comment by yjs0704** [comment]
Thanks for your reply. My problem is a bit more complex than that the A and B only differ at certain parts. The difference exists all over the image -- it's quite like a super-resolution problem but A and B are samely high resolutional while B contains more minor structures here and there..
