### ISSUE TITLE
About hyper-parameters

### ISSUE THREAD

**Issue by SJLeo** [junyanz/pytorch-CycleGAN-and-pix2pix#1072]
My training effect on edges2shoes is very poor. Could you provide hyper-parameters for training?

**Comment by junyanz** [comment]
Did you mean the pix2pix experiment? `--load_size 256 --crop_size 256 --no_flip`.

**Comment by SJLeo** [comment]
Yeah! I will try this hyper-parameter. Thanks!

**Comment by SJLeo** [comment]
Could you provide train_opt.txt file? I still can't achieve the desired effect.
