### ISSUE TITLE
Template Dataset Doubt

### ISSUE THREAD

**Issue by SurbhiKhushu** [junyanz/pytorch-CycleGAN-and-pix2pix#1082]
Hello,
I am working with cycle gans ,on grayscale images. 
I changed the channels to 1 and wrote the custom dataloader. My data is stored as tensors i.e as .pt files after being preprocessed  and not into the training and testing folders in any directory. 
I have split the training A and training B dataset in my dataloader and want to pass it to the model.
Can you tell me which lines I will have to change?

**Comment by junyanz** [comment]
We provide a dataset [template](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/template_dataset.py) with step-by-step instructions. You need to implement functions such as `__init__`, and `__getitem__`.

**Comment by SurbhiKhushu** [comment]
Thank you,. When I run the train.py I am getting this error
usage: train.py [-h] --dataroot DATAROOT [--name NAME] [--gpu_ids GPU_IDS]
                [--checkpoints_dir CHECKPOINTS_DIR] [--model MODEL]
                [--input_nc INPUT_NC] [--output_nc OUTPUT_NC] [--ngf NGF]
                [--ndf NDF] [--netD NETD] [--netG NETG]
                [--n_layers_D N_LAYERS_D] [--norm NORM]
                [--init_type INIT_TYPE] [--init_gain INIT_GAIN] [--no_dropout]
                [--dataset_mode DATASET_MODE] [--direction DIRECTION]
                [--serial_batches] [--num_threads NUM_THREADS]
                [--batch_size BATCH_SIZE] [--preprocess PREPROCESS]
                [--no_flip] [--display_winsize DISPLAY_WINSIZE]
                [--epoch EPOCH] [--load_iter LOAD_ITER] [--verbose]
                [--suffix SUFFIX] [--display_freq DISPLAY_FREQ]
                [--display_ncols DISPLAY_NCOLS] [--display_id DISPLAY_ID]
                [--display_server DISPLAY_SERVER] [--display_env DISPLAY_ENV]
                [--display_port DISPLAY_PORT]
                [--update_html_freq UPDATE_HTML_FREQ]
                [--print_freq PRINT_FREQ] [--no_html]
                [--save_latest_freq SAVE_LATEST_FREQ]
                [--save_epoch_freq SAVE_EPOCH_FREQ] [--save_by_iter]
                [--continue_train] [--epoch_count EPOCH_COUNT] [--phase PHASE]
                [--n_epochs N_EPOCHS] [--n_epochs_decay N_EPOCHS_DECAY]
                [--beta1 BETA1] [--lr LR] [--gan_mode GAN_MODE]
                [--pool_size POOL_SIZE] [--lr_policy LR_POLICY]
                [--lr_decay_iters LR_DECAY_ITERS]
train.py: error: the following arguments are required: --dataroot

but I already added the dataroot path in base options:
parser.add_argument('--dataroot', type=str, default='./datasets/PETtoCT', required=True, help='path to images (should have subfolders trainA, trainB, valA, valB, etc)')

**Comment by junyanz** [comment]
Maybe remove `required=True`.

**Comment by SurbhiKhushu** [comment]
Hello,
I solved this error. Thank you so much. I have one doubt ,since my image size is 143 x 143, do I require to padd it before or if I choose the none parameter for preprocessing ,it will make it to a multpile of 4. I dont want to resize, become my medical image might loose the data. Kindly suggest !

**Comment by SurbhiKhushu** [comment]
Error Can't pickle local object 'get_transform.<locals>.<lambda>' 
Can you please tell me what can be the possible reason for this error?

Setting up a new session...
create web directory ./checkpoints\maps_cyclegan\web...
Traceback (most recent call last):
  File "C:/Users/Surbhi/Downloads/pytorch-CycleGAN-and-pix2pix-master/train.py", line 44, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "C:\Users\Surbhi\Downloads\pytorch-CycleGAN-and-pix2pix-master\data\__init__.py", line 90, in __iter__
    for i, data in enumerate(self.dataloader):
  File "C:\Users\Surbhi\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Surbhi\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\Surbhi\anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Surbhi\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Surbhi\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Surbhi\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Surbhi\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_transform.<locals>.<lambda>'

Process finished with exit code 1

**Comment by SurbhiKhushu** [comment]
Hello,

I changed the number of workers to 0. to make this work. I guess this is because, of missing multiprocessor support on windows.So changing number of workers to 0 made it  work.

**Comment by junyanz** [comment]
> Hello,
> I solved this error. Thank you so much. I have one doubt ,since my image size is 143 x 143, do I require to padd it before or if I choose the none parameter for preprocessing ,it will make it to a multpile of 4. I dont want to resize, become my medical image might loose the data. Kindly suggest !

Yes. you can pad 1 pixel by yourself before feeding it to the network.
