### ISSUE TITLE
Can pix2pix fine tune the geometry structure of the image

### ISSUE THREAD

**Issue by suishicity** [junyanz/pytorch-CycleGAN-and-pix2pix#1085]
I am trying to beautify the teeth using GAN.  In the upper picture, the teeth are not very straight. I want to use GAN to generate the straight teeth just like the teeth in the lower picture. Can pix2pix or CycleGAN do this job ?
![02737](https://user-images.githubusercontent.com/15273348/86459817-ee8a4700-bd59-11ea-9317-d0e7a4982916.png)
![02737](https://user-images.githubusercontent.com/15273348/86459844-f813af00-bd59-11ea-96ef-59996579cf34.png)

**Comment by junyanz** [comment]
It might be possible. If you have paired data, you can use pix2pix (otherwise, CycleGAN). You might need a generator that can warp an image such as [STN](https://arxiv.org/abs/1506.02025). See a related [projct](https://arxiv.org/pdf/1804.00064.pdf) in dental restoration.

**Comment by suishicity** [comment]
I ran the pix2pix code to train cityscapes data. There are many blurs and artifacts in the generated images. The similar problems can also be found in horse2zerbra trained by CycleGAN. Is there any method to solve this problem?

**Comment by junyanz** [comment]
For Cityscapes, you can use more recent models such as [pix2pixHD](https://github.com/NVIDIA/pix2pixHD) and [SPADE](https://github.com/NVlabs/SPADE). 

For GAN loss, you may want to change the lambda for other losses (e.g., `lambda_L1`) as different GAN losses have different ranges. (For example, use `lambda_L1 10` for LSGAN). It's hard to know in advance which loss works better for a new task.
