### ISSUE TITLE
What dose loss look like if training gose well 

### ISSUE THREAD

**Issue by liyiwei979621500** [junyanz/pytorch-CycleGAN-and-pix2pix#1086]
What should these following losses approach if training gose well 
D_A
G_A
cycle_A
idt_A
D_B
G_B
cycle_B
idt_B

**Comment by junyanz** [comment]
@taesungp Taeusng might have one.

**Comment by abhinavkashyap** [comment]
@junyanz and @taesungp Is there any updates on this? :) Thank you!
