### ISSUE TITLE
Can pix2pix learn the digital watermark (invisible, not common watermarks) embeded in a picture?

### ISSUE THREAD

**Issue by SleepSupreme** [junyanz/pytorch-CycleGAN-and-pix2pix#1087]
For example, I have paired images( original and watermarked ). Visually they are alomost the same.
Watermark algorithms  can be LSB (replaces the least significant 2 bits of original images by the most significant 2 bits of watermark) or other more complex algorithms in spatial and frequency domain.

After training with paired images, can pix2pix fine learn the watermark algorithm and translate the original images to the embeded ? I'm not sure whether this idea works or not.

Thank you very much.

**Comment by junyanz** [comment]
I am not sure. It seems to be not easy. But feel free to try it.

**Comment by SleepSupreme** [comment]
OK, I'll have a try. There are not many research results in this area, so I'm a little confused. Thank you very much.
