### ISSUE TITLE
During the training, the pictures in the folder【checkpoints/horse2zebra/web/index.html】 are strange

### ISSUE THREAD

**Issue by xuhaohao86** [junyanz/pytorch-CycleGAN-and-pix2pix#1089]
I am running with your newly released code and data run Cyclegan,But i I met a problem。During the training, the pictures in the folder【checkpoints/horse2zebra/web/index.html】 are strange.look like this 
![image](https://user-images.githubusercontent.com/30650224/87138645-4df3d400-c2d1-11ea-81a0-2bb58a02bf87.png)

please help me .I want to konw why?

**Comment by junyanz** [comment]
Not sure about it. It seems that your image display is not functioning. At least images named `real_A` should look normal. Could you manually check if the images under the directory `checkpoints/horsee2zebra/web/images` look normal?

**Comment by xuhaohao86** [comment]
@junyanz  Thank you for your reply ， The images under   the directory checkpoints/horsee2zebra/web/images  are same as checkpoints/horse2zebra/web/index.html. it also looks strange. In addition, I did not modify the code that you release.I donot kow why? Thanks.

**Comment by xuhaohao86** [comment]
@junyanz  I change the server to run this code, and the result was normal. But I still don't know why on the first server,the output is so strange ?

**Comment by xuhaohao86** [comment]
@junyanz  Thank you very much
