### ISSUE TITLE
Generated Images become (1-input) in first several iterations

### ISSUE THREAD

**Issue by layumi** [junyanz/pytorch-CycleGAN-and-pix2pix#109]
Hi @junyanz 
It's a nice code. But I wonder about the initialisation.
In my experiments, I notice sometime the network will fall in some strange local minimum.
The generated image is  just like (1-input). But the recover image still seems good. 
Can I draw the conclusion that the initialisation really matters?

**Comment by junyanz** [comment]
We include a few popular initialization methods. Please use `--init_type` to choose the method.
