### ISSUE TITLE
[Qustion]Why dose pix2pix use gan_mode='vanilla' as default?

### ISSUE THREAD

**Issue by liyiwei979621500** [junyanz/pytorch-CycleGAN-and-pix2pix#1099]
Cyclegan uses gan_mode='lsgan' as default
I'm wondering if 'vanilla' works for pix2pix better than 'lsgan'?

**Comment by junyanz** [comment]
Not necessary. It uses the `vanilla`, as it is done in the original paper. Feel free to try other modes. You may want to reduce L1 loss when you use `lsgan`, as the range of `lsgan` is smaller than `vanilla`.

**Comment by liyiwei979621500** [comment]
Thanks for your tip.
