### ISSUE TITLE
Using part of the dataset

### ISSUE THREAD

**Issue by erdemarpaci** [junyanz/pytorch-CycleGAN-and-pix2pix#1108]
While downloading data from the source, how can I specify the number of data?  Is there a way to train only some parts of the dataset? I am using pix2pix, night2day.

**Comment by junyanz** [comment]
Please refer to `max_dataset_size` [[line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L48)].
