### ISSUE TITLE
postprocessing steps

### ISSUE THREAD

**Issue by b-delfino** [junyanz/pytorch-CycleGAN-and-pix2pix#1109]
Hi, 

Thank you for your repository, it's really amazing. 
I would like to make some post processing steps (tweak the size of the output image) both after training and testing. I can't find the output of the network in train.py and test.py. What is the name of the output image of the network? I can only see the lines that display the output on visdom, but not an image file that I can use for my post processing. Am I missing something? Thank you

**Comment by junyanz** [comment]
After you run the test code, you can find images saved at the directory `./results/{your_experiment_name}/latest_test/indeximages`. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#cyclegan-traintest) for more details.

**Comment by b-delfino** [comment]
The output images after training and testing are called differently than what they are as input (e.g. epoch001_realA.jpg). Is it possible to have them keep the same name as what I choose in the input? I don't understand in the code where the name is changed.

**Comment by lucyLLLL** [comment]
> The output images after training and testing are called differently than what they are as input (e.g. epoch001_realA.jpg). Is it possible to have them keep the same name as what I choose in the input? I don't understand in the code where the name is changed.

**Comment by junyanz** [comment]
You can change the file name in this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/test.py#L65).
