### ISSUE TITLE
--input_nc 3 --output_nc 1  --lambda_identity 0

### ISSUE THREAD

**Issue by lucyLLLL** [junyanz/pytorch-CycleGAN-and-pix2pix#1114]
i use` python train.py --dataroot ./datasets/data --name sar_cyclegan --model cycle_gan --input_nc 3 --output_nc 1  --lambda_identity 0` train the model
and `python test.py --dataroot ./datasets/data --name sar_cyclegan --model cycle_gan  --output_nc 1` to test
 
but i get the image is 3 channel，i don't konw why

**Comment by junyanz** [comment]
We converted grayscale images to 3-channels image using `np.tile`. You can just take the first channel of saved images OR change this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/9e6fff7b7d5215a38be3cac074ca7087041bea0d/util/util.py#L22).
