### ISSUE TITLE
Sudden Stops of Colab and Checkpoints Problem

### ISSUE THREAD

**Issue by erdemarpaci** [junyanz/pytorch-CycleGAN-and-pix2pix#1116]
Since Colab has a time limit, sometimes I don't have enough time to finish all my epochs. I want to use my checkpoints folder(I'm using --checkpoints_dir) and continue from training where it stops, but since my problem is Colab suddenly ends the session, I can't download or use again my checkpoints folder. What should I do to not lose my checkpoints, and continue from where it stops?

**Comment by junyanz** [comment]
I am not sure. Maybe you can manually download them periodically or write a script to send the checkpoints files to your local machine periodically.

**Comment by erdemarpaci** [comment]
Will uploading my checkpoints folder be sufficient to use --continue_train? I'm using some part of the dataset. When training stops and I restart with my uploaded checkpoints folder, will be the same part of the data? If it's not the same part of the dataset, will it cause a problem? 

Thank you

**Comment by junyanz** [comment]
For `--continue_train`, yes. 

No worry for the data loader, as the data loader will read images randomly from the dataset.

**Comment by zbeibei31** [comment]
Hello, I am experiencing the same problem. How can I solve it?
Do you mind sharing the instruction for adding checkpoints?
