### ISSUE TITLE
How do I get the generated jpg images？

### ISSUE THREAD

**Issue by QHLang** [junyanz/pytorch-CycleGAN-and-pix2pix#1117]
After I trained  a model, I got fake images with png format, when I tested my model. But I want to get some fake images with jpg format. Can you tell me how to set to change the format of fake imsges? And what is the impact of the different image format? Thanks a lot.

**Comment by junyanz** [comment]
Change this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/dca9002f598fada785b92d496fcdc7b04528b393/util/visualizer.py#L37).

**Comment by QHLang** [comment]
> Change this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/dca9002f598fada785b92d496fcdc7b04528b393/util/visualizer.py#L37).

OK. Thanks a lot.
