### ISSUE TITLE
Always out of memory when testing

### ISSUE THREAD

**Issue by GuoLanqing** [junyanz/pytorch-CycleGAN-and-pix2pix#1119]
Hi,
My testing set has about 7,000 images in all. Some images in the testing set are very large, like 2,000*3,000 pixels. The memory is always overflow. The testing program can only run on one gpu instead of multi-gpu. How can I fix this problem? Many thanks!

**Comment by junyanz** [comment]
The current test code is on a single GPU. You need to change the `test.py` if you would like to support multi-GPUs. For 2000*3000 images, you might get out of memory. It's hard to fix unless you use a GPU with more memory. But you can also use CPU mode just for a few large images while using GPUs for the rest of test set. (you can just create two test sets)

**Comment by GuoLanqing** [comment]
Thanks for your reply.


________________________________
发件人: Jun-Yan Zhu <notifications@github.com>
发送时间: 2020年8月7日 0:07
收件人: junyanz/pytorch-CycleGAN-and-pix2pix <pytorch-CycleGAN-and-pix2pix@noreply.github.com>
抄送: #GUO LANQING# <LANQING001@e.ntu.edu.sg>; Author <author@noreply.github.com>
主题: Re: [junyanz/pytorch-CycleGAN-and-pix2pix] Always out of memory when testing (#1119)


The current test code is on a single GPU. You need to change the test.py if you would like to support multi-GPUs. For 2000*3000 images, you might get out of memory. It's hard to fix unless you use a GPU with more memory. But you can also use CPU mode just for a few large images while using GPUs for the rest of test set. (you can just create two test sets)

―
