### ISSUE TITLE
failing to combine dataset (from A and B to AB)

### ISSUE THREAD

**Issue by shivom9713** [junyanz/pytorch-CycleGAN-and-pix2pix#1121]
please help me out i tried several times....A is the set of infrared images while B is its corresponding RGB image.
Even after several attempts no images were available in AB folder ...after running the code
![Capture](https://user-images.githubusercontent.com/56249279/89713349-d4750180-d9b4-11ea-89ee-8a1a947eb826.PNG)

**Comment by junyanz** [comment]
Have you checked the folder `AB/train` and `AB/test`? You may also want to remove the .ipynb_checkpoints

**Comment by shivom9713** [comment]
Yes sir , i had checked AB/train and AB/test.
Is resolution mismatch causing the problem of paired images??

**Comment by junyanz** [comment]
Yes, the code assumes that input and output images have the same size.

**Comment by shivom9713** [comment]
Thanks a lot..!!
