### ISSUE TITLE
is exact image  registration for image pairs compulsory to get good results in pix2pix?

### ISSUE THREAD

**Issue by shivom9713** [junyanz/pytorch-CycleGAN-and-pix2pix#1134]
Sir , 
     I have a doubt as to whether exact image registration is compulsory to get good results or results wont be affected by slight misregistration in paired dataset

**Comment by junyanz** [comment]
Slight misalignment should be fine. But you are right that better alignment can lead to better results.

**Comment by liyiwei979621500** [comment]
Pix2pix has a L1 loss. I think it's better to align images.
