### ISSUE TITLE
Question：relation between pix2pix and cGAN

### ISSUE THREAD

**Issue by liyiwei979621500** [junyanz/pytorch-CycleGAN-and-pix2pix#1137]
1、
![image](https://user-images.githubusercontent.com/16919236/91786315-efe0ce80-ec39-11ea-95f4-315a5dc519ba.png)
Why dose pix2pix pair (g(x),x) and (y,x) then feed them to the discriminator?
Since (g(x),x) is labeled fake and (y,x) is labeled real, 
We can easily tell that the x term is irrelevant. 
I think the discriminator will just learn to ignore the x part.

2.
The loss of cGAN discriminator has 2 parts:
1. whether the input image is real.
2. whether the output and condition are matched.

However, I can't find the second part in pix2pix_model.py.

Am I misunderstanding something?

**Comment by junyanz** [comment]
x is relevant and can be used to check if the output and input condition match or not. For example, in the task of the semantic layout (e.g., tree labels, road labels) -> image in the Cityscapes, if the discriminator knows that the generator wants to synthesize a tree region (from x), the discriminator can determine whether it looks like a real or fake tree region.

**Comment by liyiwei979621500** [comment]
I see.Thanks!
