### ISSUE TITLE
out of memory with resnet as netG

### ISSUE THREAD

**Issue by mfazampour** [junyanz/pytorch-CycleGAN-and-pix2pix#1145]
I ran the code with `unet_256` as `netG` vs. `resnet_6blocks`. For `unet_256` I can run it with batch size of 50 and it will consume 6.5 GB of GPU ram. but when I switch to resnet I get out of memory with the same batch size. The maximum I can fit is 25 for the batch size. My GPU is a 2080 RTX (11GB). Below are the commands I used for training the two versions:

for unet:
`python train.py --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --direction BtoA --batch 50 --gpu_ids 1 --netG unet_256`
for resnet:
`python train.py --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --direction BtoA --batch 25 --gpu_ids 1 --netG resnet_6blocks`

this is strange to me since resnet model has less parameters than the unet one. Is this behavior expected? 

while this is not a big deal in 2D, the reason I am asking is that for 3D, using resnet for either pix2pix or cycleGAN would result in out of memory error.

**Comment by junyanz** [comment]
Resnet-based generators are more memory-intensive as it has fewer downsampling layers and the bottleneck is bigger. It keeps the resolution of the tensor after 3 downsampling layers. For U-net, it has more downsampling layers (6 or 7), and the resolution of the tensor becomes quite small.
