### ISSUE TITLE
can the cyclegan model be applied to paired images

### ISSUE THREAD

**Issue by yianzhongguo** [junyanz/pytorch-CycleGAN-and-pix2pix#1149]
I have some paired images, thus I want to know it the cyclegan model has a pair-image mode, can it be applied to paired images, thank you very much!

**Comment by junyanz** [comment]
You can apply CycleGAN to paired images. But I think pix2pix or more recent models such as GauGAN should work better.

**Comment by yianzhongguo** [comment]
@junyanz, thank you very much for your suggestions, I'll try it!
