### ISSUE TITLE
Using pre-trained maps model on unpaired input images

### ISSUE THREAD

**Issue by blindfish** [junyanz/pytorch-CycleGAN-and-pix2pix#115]
Tried to follow [documentation](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) on how to apply a pre-trained model to unpaired single input images. 

Example is for pix2pix: "If you would like to apply a pre-trained model to a collection of input photos (without image pairs), please use --dataset_mode single and --model test options."

```
#!./scripts/test_single.sh
python test.py --dataroot ./datasets/facades/testB/ --name facades_pix2pix --model test --which_model_netG unet_256 --which_direction BtoA --dataset_mode single
```

Tried to adapt to CycleGan model trained on maps dataset, with this line

```
python test.py --dataroot ./datasets/maps/test_solo --name maps_cyclegan --mod
el cycle_gan --phase test --which_direction AtoB --dataset_mode single
```
Got error: 

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    model = create_model(opt)
  File "/home/user/pytorch-CycleGAN-and-pix2pix/models/models.py", line 6, in create_model
    assert(opt.dataset_mode == 'unaligned')
AssertionError

Not sure of right command. Anyone get CycleGan working for single unpaired images know the right ones?

**Comment by soumyadeepg** [comment]
I am having the same problem. I used the following command....

python test.py --dataroot ./datasets/full_vis_hr/testB/ --name load150fine128inp1out1_new_btoa_350iter --model test --which_model_netG unet_256 --which_direction AtoB --dataset_mode single --norm batch

The error i am getting is this...

File "test.py", line 17, in <module>
    model = create_model(opt)
  File "/home/iiitd/soumyadeep/pytorch-CycleGAN-and-pix2pix-master/models/models.py", line 19, in create_model
    model.initialize(opt)
  File "/home/iiitd/soumyadeep/pytorch-CycleGAN-and-pix2pix-master/models/test_model.py", line 22, in initialize
    self.load_network(self.netG, 'G', which_epoch)
  File "/home/iiitd/soumyadeep/pytorch-CycleGAN-and-pix2pix-master/models/base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/home/iiitd/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 355, in load_state_dict
    .format(name))
KeyError: 'unexpected key "model.1.weight" in state_dict'



Also when I remove --which_model_netG unet_256 from the command I am getting some outputs but all the images have grey horizontal stripes and these outputs are not desirable. Please let me know if someone has successfully cracked this testing thing.

**Comment by junyanz** [comment]
@blindfish You need to use `--model test --dataset_mode single`. You got the error as you used `--model cycle_gan` with `--dataset_mode single`.

**Comment by junyanz** [comment]
@soumyadeepg What's your training script? Your errors sometimes happen when you have different architectures/normalization configuration between training and test scripts. Also the test script with `--model test` will load the model `*_G.pth`. If you train a cyclegan model, you model will be named as `*_G_A.pth` and `*_G_A.pth`. So you have to change the name manually.

**Comment by soumyadeepg** [comment]
[index.zip](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/files/1363332/index.zip)
@junyanz My training script is as follows:


import os
import time
from options.train_options import TrainOptions
from data.data_loader import CreateDataLoader
from models.models import create_model
from util.visualizer import Visualizer

os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   
os.environ["CUDA_VISIBLE_DEVICES"]="0"

opt = TrainOptions().parse()
data_loader = CreateDataLoader(opt)
dataset = data_loader.load_data()
dataset_size = len(data_loader)
print('#training images = %d' % dataset_size)

model = create_model(opt)
visualizer = Visualizer(opt)
total_steps = 0

for epoch in range(opt.epoch_count, opt.niter + opt.niter_decay + 1):
    epoch_start_time = time.time()
    epoch_iter = 0
    for i, data in enumerate(dataset):
        iter_start_time = time.time()
        total_steps += opt.batchSize
        epoch_iter += opt.batchSize
        model.set_input(data)
        model.optimize_parameters()

        if total_steps % opt.display_freq == 0:
            visualizer.display_current_results(model.get_current_visuals(), epoch)

        if total_steps % opt.print_freq == 0:
            errors = model.get_current_errors()
            t = (time.time() - iter_start_time) / opt.batchSize
            visualizer.print_current_errors(epoch, epoch_iter, errors, t)
            if opt.display_id > 0:
                visualizer.plot_current_errors(epoch, float(epoch_iter)/dataset_size, opt, errors)

        if total_steps % opt.save_latest_freq == 0:
            print('saving the latest model (epoch %d, total_steps %d)' %
                  (epoch, total_steps))
            model.save('latest')

    if epoch % opt.save_epoch_freq == 0:
        print('saving the model at the end of epoch %d, iters %d' %
              (epoch, total_steps))
        model.save('latest')
        model.save(epoch)

    print('End of epoch %d / %d \t Time Taken: %d sec' %
          (epoch, opt.niter + opt.niter_decay, time.time() - epoch_start_time))

    if epoch > opt.niter:
        model.update_learning_rate()


###----------------THE END OF SCRIPT---------------------------############
****

When I renamed *_G_A.pth to *_G.pth I got output images in the **result** folder like these.

**Comment by soumyadeepg** [comment]
Also I am not being able to understand what is the difference between testing the cyclegan model and applying a pretrained cyclegan model to generate data from either A to B or B to A ??
In the readme file these two things are mentioned separately. 

I tried to test the model by the following command:
 
python test.py --dataroot ./datasets/casia_full_vis_hr_nir_hr/ --name load150fine128inp1out1_visHR_visLR_FULL_CASIA_new_atob_350iter --model cycle_gan --phase test --no_dropout

I got this error:

Traceback (most recent call last):
  File "test.py", line 17, in <module>
    model = create_model(opt)
  File "/home/iiitd/soumyadeep/pytorch-CycleGAN-and-pix2pix-master/models/models.py", line 19, in create_model
    model.initialize(opt)
  File "/home/iiitd/soumyadeep/pytorch-CycleGAN-and-pix2pix-master/models/cycle_gan_model.py", line 45, in initialize
    self.load_network(self.netG_A, 'G_A', which_epoch)
  File "/home/iiitd/soumyadeep/pytorch-CycleGAN-and-pix2pix-master/models/base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/home/iiitd/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 355, in load_state_dict
    .format(name))
KeyError: 'unexpected key "model.2.weight" in state_dict'


somebody please help !!!

Thanks in advance :)

**Comment by junyanz** [comment]
If you train a cyclegan model, you can either use `cyclegan` or `test` for `--model` flags. The difference is that the flag `cyclegan` takes image pairs (A,B) as inputs while the `test` takes only input images A.

**Comment by isaacmg** [comment]
Yes I get the same on a monet2photo that I trained myself. 
`CustomDatasetDataLoader
dataset [SingleImageDataset] was created
test
initialization method [xavier]
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    model = create_model(opt)
  File "/home/isaac/Desktop/pytorch-CycleGAN-and-pix2pix/models/models.py", line 19, in create_model
    model.initialize(opt)
  File "/home/isaac/Desktop/pytorch-CycleGAN-and-pix2pix/models/test_model.py", line 23, in initialize
    self.load_network(self.netG, 'G', which_epoch)
  File "/home/isaac/Desktop/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/home/isaac/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 355, in load_state_dict
    .format(name))
KeyError: 'unexpected key "model.1.weight" in state_dict'

This is the command I'm using

`python test.py --dataroot ./datasets/monet2photo/testA/ --name monet2photo --model test --which_model_netG unet_256 --which_direction AtoB --dataset_mode single`
`

**Comment by junyanz** [comment]
What is your training script? I guess that you might have used `batchnorm` during the training.

**Comment by ivjia** [comment]
I have the same problem here. I first trained my own model and tried to apply it to one image, the error above reported. Then I directly trained a map model exactly follow your README file, then it shows "
 
IOError: [Errno 2] No such file or directory: './checkpoints/map_cyclegan/latest_net_G.pth' 

"
after I manually change the name of "latest_net_G_A.pth" to "latest_net_G.pth", it shows "

KeyError: 'unexpected key "model.10.conv_block.5.weight" in state_dict'. 

It looks like a issue with the state_dict from the trained model. Please help me with it.

"

**Comment by micklexqg** [comment]
Is there any pretrained model? I want to implement the testing directly, but came across the error:
no such file latest_net_G.pth'

**Comment by SUZhaoyu** [comment]
I met the same problem as @ivjia , I got the same output:

File "test.py", line 17, in <module>
    model = create_model(opt)
  File "/media/data1/CycleGAN/new/models/models.py", line 19, in create_model
    model.initialize(opt)
  File "/media/data1/CycleGAN/new/models/test_model.py", line 23, in initialize
    self.load_network(self.netG, 'G', which_epoch)
  File "/media/data1/CycleGAN/new/models/base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/home/tan/anaconda2/envs/cyclegan/lib/python3.5/site-packages/torch/nn/modules/module.py", line 490, in load_state_dict
    .format(name))
KeyError: 'unexpected key "model.10.conv_block.5.weight" in state_dict'

after I renamed the "latest_net_G.pth" manually. Also, all the parameters used for training and testing were default values.

**Comment by junyanz** [comment]
@micklexqg  @taesung89  just uploaded the horse2zebra and zebra2horse models. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-cyclegan) for more details.

**Comment by junyanz** [comment]
@SUZhaoyu  @ivjia  Did you use `--no_dropout` in both your training and test scripts?

**Comment by SUZhaoyu** [comment]
Ok I see where's the problem and it works now. Thank you for your kind reply! @junyanz

**Comment by junyanz** [comment]
@SUZhaoyu  is it due to `--no_dropout`? Could you share the fixes?

**Comment by SUZhaoyu** [comment]
Yes, the problem is exact what you said, I only applied `--no_drop` in training phase, and did not use it for testing.
