### ISSUE TITLE
number of parameters using 64x64px

### ISSUE THREAD

**Issue by B0RJA** [junyanz/pytorch-CycleGAN-and-pix2pix#1152]
I am using pix2pix model with 64x64px images and results look great.

Checking the saved model, I notice an unexpected size compared to the default model using 256x256px images:

```
256x256px
[Network G] Total number of parameters : 54.408 M
[Network D] Total number of parameters : 2.765 M
208M latest_net_G.pth
 11M latest_net_D.pth

64x64px
[Network G] Total number of parameters : 29.238 M
[Network D] Total number of parameters : 0.662 M
112M latest_net_G.pth
2.6M latest_net_D.pth
```

I used these flags and defined a generator with fewer layers:

```
--crop_size 256 --netG unet_256 --netD n_layers --n_layers_D 3

--crop_size 64 --netG unet_64 --netD n_layers --n_layers_D 2

elif netG == 'unet_256':
    net = UnetGenerator(input_nc, output_nc, 8, ngf, norm_layer=norm_layer, use_dropout=use_dropout)
    
elif netG == 'unet_64':
    net = UnetGenerator(input_nc, output_nc, 6, ngf, norm_layer=norm_layer, use_dropout=use_dropout)
```

I expected the 64x64px model to have a lower number of parameters, at least 1/16.

I'm missing something?

Thanks in advance and especially for sharing your work!

**Comment by junyanz** [comment]
The number of parameters in the first 1-2 downsampling layers is small compared to the parameters of the entire network. Removing the first 1-2 layers will not reduce the number of parameters by 1/16.

**Comment by B0RJA** [comment]
I was expecting the model to have less weights since my images are smaller (1/16 in number of pixels).

Thanks for the clarification!
