### ISSUE TITLE
Question about using other optimizers

### ISSUE THREAD

**Issue by JohanRaniseth** [junyanz/pytorch-CycleGAN-and-pix2pix#1154]
If I want to try out other optimizers like SGD with momentum would I just need to change line 68 & 69 in pix2pix_model.py?
Or is some of the code buildt around using Adam specifically?

` # initialize optimizers; schedulers will be automatically created by function <BaseModel.setup>`
` self.optimizer_G = torch.optim.Adam(self.netG.parameters(), lr=opt.lr, betas=(opt.beta1, 0.999))`
` self.optimizer_D = torch.optim.Adam(self.netD.parameters(), lr=opt.lr, betas=(opt.beta1, 0.999))`

changed to SDG that does not use the betas parameter:

` self.optimizer_G = torch.optim.SGD(self.netG.parameters(), lr=opt.lr, momentum=0.9)`
` self.optimizer_D = torch.optim.SGD(self.netD.parameters(), lr=opt.lr, momentum=0.9)`

Thank you!

**Comment by junyanz** [comment]
Yes, looks good to me.
