### ISSUE TITLE
Save output fake images into .tiff

### ISSUE THREAD

**Issue by yichengggg** [junyanz/pytorch-CycleGAN-and-pix2pix#1158]
Hi, 

I really enjoyed implementing CycleGAN with my own dataset, this is a great work. 
Could you please let me know how can I change the format of output fake images after testing the model? For example, from default .png to .tiff. 

Thanks

**Comment by junyanz** [comment]
You can add your code [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/util/util.py#L49).

**Comment by yichengggg** [comment]
> You can add your code [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/util/util.py#L49).

Hi Junyan, 

Thank you so much for help. I actually have a follow up question about this. 

Before saving the images to disk, we call a function `util.tensor2im(im_data) at here, does this function aim to re-normalize these out images to [0, 255], as coming out from Tensor? 

https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/c94161791aaf050dfffb4f2b2fac815997b37aa6/util/visualizer.py#L35-L43

**Comment by junyanz** [comment]
It should be [0, 255].

**Comment by yichengggg** [comment]
> It should be [0, 255].
Thanks for your help. Will close this issue for now.
