### ISSUE TITLE
pix2pix What if I train data with sketch in left side?

### ISSUE THREAD

**Issue by darrenleeleelee1** [junyanz/pytorch-CycleGAN-and-pix2pix#1160]
What if I train data with sketch in left side and Face in right side? If I do so, can I still test with only sketch photo?

**Comment by junyanz** [comment]
You can use the flag `--model test`. See more details [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-pix2pix).
