### ISSUE TITLE
train.py: error: unrecognized arguments: --epoch_count 

### ISSUE THREAD

**Issue by smithee77** [junyanz/pytorch-CycleGAN-and-pix2pix#1162]
Hi, I'm trying to continue training with this options:
--continue_train --epoch_count 200

But I'm getting  "train.py: error: unrecognized arguments: --epoch_count"

Is there anything wrong with that?
Thanks

**Comment by junyanz** [comment]
It should work with `train.py` script. See this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/2595573a7c9fd5bb389a949a3f1b2f06970a4eb8/options/train_options.py#L27). Are you using the latest version?

**Comment by smithee77** [comment]
My mistake, I was using pix2pixHD repo.
