### ISSUE TITLE
Unet or Resnet, which one is better for pix2pix model?

### ISSUE THREAD

**Issue by yueruchen** [junyanz/pytorch-CycleGAN-and-pix2pix#117]
Now I am using pix2pix model on other application, and I am considering about the model for generator. Since I don't know whether to choose Resnet or Unet, could you give some advise?
By the way, will it perform better if I deepen the Unet model?
Thanks!

**Comment by junyanz** [comment]
UNet gives slightly better results than Resnet in some of the pix2pix applications. We haven't  varied the depth of the UNet model, but it might be worth trying.

**Comment by Shubhams-nd** [comment]
Hi,

Have you tried U-net blocks on Cycle-GAN generator? if yes, how were the results compared to Res blocks?

**Comment by junyanz** [comment]
We have tried. It worked worse than Resnet-based methods.

**Comment by Shubhams-nd** [comment]
Thanks @junyanz . We tested it too and it seems to be so. Maybe attention U-net would improve the results. Will update you on it...
