### ISSUE TITLE
I want to transfer my train model to other computer

### ISSUE THREAD

**Issue by darrenleeleelee1** [junyanz/pytorch-CycleGAN-and-pix2pix#1179]
Is there a way that I can transfer the model to other computer, I try to transfer it without checkpoint and it show some error, I don't want to transfer it because it is too big(but if is necessary, I will do so).

Or is there a way that I can get the result by other python file without command lines.
In this case, I'am now using
```
import subprocess
subprocess.run("python test.py --dataroot ./datasets/facades/testB/ --name facades_pix2pix --model test --netG unet_256 --direction BtoA --dataset_mode single --norm batch", shell=True)
```
but It is kind of call by cmd, I don't think it is a good way.

**Comment by junyanz** [comment]
You have to transfer the model's checkpoints.
