### ISSUE TITLE
CityScape evaluation

### ISSUE THREAD

**Issue by JunlinHan** [junyanz/pytorch-CycleGAN-and-pix2pix#1188]
Sorry for raising duplicate issues.
I have read instructions and previous issues carefully. I still have some concerns about evaluation.
python ./scripts/eval_cityscapes/evaluate.py --cityscapes_dir /path/to/original/cityscapes/dataset/ --result_dir /path/to/your/predictions/ --output_dir /path/to/output/directory/

So the cityscapes_dir should be leftImg8bit_trainvaltest/leftImg8bit/ or gtFine_trainvaltest/gtFine/?
If I use the first one, I can run it but producing all 0 outputs even using real images in results. 
If I use the second one, error "no module names labels" occur.
Sorry for bothering you at the time approaching the CVPR deadline. 
Many thanks.

**Comment by JunlinHan** [comment]
Or, if anyone is willing to help me to test some samples, please contact me,

**Comment by HuXiaokai12138** [comment]
> 很抱歉提出重复的问题。 我已仔细阅读说明和以前的问题。我对评价还是有一些顾虑。 python ./scripts/eval_cityscapes/evaluate.py --cityscapes_dir /path/to/original/cityscapes/dataset/ --result_dir /path/to/your/predictions/ --output_dir /path/to/output/directory/
> 
> 所以 cityscapes_dir 应该是 leftImg8bit_trainvaltest/leftImg8bit/ 或 gtFine_trainvaltest/gtFine/？ 如果我使用第一个，我可以运行它，但即使在结果中使用真实图像，也会产生所有 0 输出。 如果我使用第二个，则会出现错误“无模块名称标签”。 很抱歉在 CVPR 截止日期临近之际打扰您。 非常感谢。

I would like to know, how did you solve this problem, I have the same problem on my side and look forward to your reply.

**Comment by HuXiaokai12138** [comment]
> Sorry for raising duplicate issues. I have read instructions and previous issues carefully. I still have some concerns about evaluation. python ./scripts/eval_cityscapes/evaluate.py --cityscapes_dir /path/to/original/cityscapes/dataset/ --result_dir /path/to/your/predictions/ --output_dir /path/to/output/directory/
> 
> So the cityscapes_dir should be leftImg8bit_trainvaltest/leftImg8bit/ or gtFine_trainvaltest/gtFine/? If I use the first one, I can run it but producing all 0 outputs even using real images in results. If I use the second one, error "no module names labels" occur. Sorry for bothering you at the time approaching the CVPR deadline. Many thanks.

I would like to know, how did you solve this problem, I have the same problem on my side and look forward to your reply.
