### ISSUE TITLE
Load trained model to other script

### ISSUE THREAD

**Issue by darrenleeleelee1** [junyanz/pytorch-CycleGAN-and-pix2pix#1199]
Can I load trained model to other script and call predict function(test single)?

**Comment by mozartora** [comment]
Hey did you find a solution for this ??

**Comment by dyollb** [comment]
I am trying this, see issue https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/1314
However, currently the result is incorrect.

Did you implement a solution?

**Comment by junyanz** [comment]
I think it's possible. you just need to call `create_model' in [L51](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/test.py#L51) and then call `model.setup(opt)`.
