### ISSUE TITLE
pix2pix which_direction seems to always be BtoA

### ISSUE THREAD

**Issue by dribnet** [junyanz/pytorch-CycleGAN-and-pix2pix#12]
Following the directions in the README gave me good results on the facades.
```bash
python train.py \
    --display_id 0 \
    --dataroot ./datasets/facades \
    --name facades_pix2pix \
    --model pix2pix \
    --which_model_netG unet_256 \
    --which_direction BtoA \
    --lambda_A 100 \
    --align_data \
    --use_dropout \
    --no_lsgan
```
![btoa](https://cloud.githubusercontent.com/assets/945979/25313020/9e68040a-287a-11e7-9dd1-1ca702c9b594.png)

However, running it backwards in AtoB mode seems to not change the operation:
```bash
python train.py \
    --display_id 0 \
    --dataroot ./datasets/facades \
    --name facades_pix2pix_rev \
    --model pix2pix \
    --which_model_netG unet_256 \
    --which_direction AtoB \
    --lambda_A 100 \
    --align_data \
    --use_dropout \
    --no_lsgan
```
![atob](https://cloud.githubusercontent.com/assets/945979/25313053/06b25268-287b-11e7-99f1-ad52a5b80c89.png)

For reference, here is an image from the dataroot:

![100](https://cloud.githubusercontent.com/assets/945979/25313067/2d3d4082-287b-11e7-86c8-09d58c00d10e.jpg)

Not a huge deal in my case as I can update my dataset appropriately to compensate, but wanted to note this issue.

**Comment by junyanz** [comment]
Thanks for pointing out the issue. I just fixed the bug. It should support both directions now.

**Comment by dribnet** [comment]
Thanks for the quick fix. Confirmed to be working now for me.

![atobfixed](https://cloud.githubusercontent.com/assets/945979/25313203/5f855dc4-287e-11e7-8f8d-2a0080d26b4a.png)
