### ISSUE TITLE
dataset number

### ISSUE THREAD

**Issue by taki0112** [junyanz/pytorch-CycleGAN-and-pix2pix#120]
1. When running an experiment, should the number of trainA and trainB data always be the same? (Likewise, should testA and testB have the same number of data respectively?)
(i.e. #trainA = #trainB, #testA=#testB ??)

2. If it does not matter, should the number of data in trainA be more or less than trainB? Does it matter?
(i.e. #trainA > #trainB  or #trainA <#trainB, #testA > #testB or #testA < #testB ??)

**Comment by junyanz** [comment]
It should not matter so much. Currently, we use the max(#trainA, #trainB) for the dataset size. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/unaligned_dataset.py#L54) for more details.
