### ISSUE TITLE
Missing images when testing cycleGAN

### ISSUE THREAD

**Issue by dongyunkim-arch** [junyanz/pytorch-CycleGAN-and-pix2pix#1202]
Hello, I am using cycleGAN to train my personal datasets and test it.
When testing, although I have about 100 images in both testA and testB, the test created only about half of the images. 
Is there something I missed?
Thanks! :)
![11](https://user-images.githubusercontent.com/70664694/100613973-5fbb2f80-32e3-11eb-8c58-67fbe9f8222c.JPG)

**Comment by ZERO-SPACE-X** [comment]
@dongyunkim-arch hello, I have the same problem, how do you solve it, Can you tell me the detail? Thank you

**Comment by dongyunkim-arch** [comment]
Hello

There is num_test option that handle the number of test images it will generate.

Best,
Dongyun


Sent from Naver Mail app.
-----Original Message-----
