### ISSUE TITLE
How can I make the output image result bigger?

### ISSUE THREAD

**Issue by Tyotw** [junyanz/pytorch-CycleGAN-and-pix2pix#1217]
I am in high awe of your work. And I noticed that all the fake_B is 256*256, how can I make them the same size with my input image or bigger than 256*256. Looking forward to your reply.

**Comment by turian** [comment]
@Tyotw what was your solution?

**Comment by Tyotw** [comment]
> @Tyotw what was your solution?

https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md
You can find your what you want here.
