### ISSUE TITLE
About the choice of final activation

### ISSUE THREAD

**Issue by feiyangsuo** [junyanz/pytorch-CycleGAN-and-pix2pix#1219]
Noticed that in both UnetGenerator and ResnetGenerator the final activation is Tanh. The codomain of Tanh is (-1, 1) yet the BaseDataset load images as in range (0, 1). The images are put into the generators and discriminators with (0, 1) values, but the generators ouput (-1, 1) values. Could there be some inconsistency?

I didn't find a conversion constraining the generated output into (0, 1) in the code. (Or have I missed something?)

**Comment by ID56** [comment]
The BaseDataset itself is loading images into the range (-1, 1). Note the norm layer [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/base_dataset.py#L109). 

`ToTensor` first brings the input range to (0, 1), after which `Normalize` brings it to (-1, 1) range.

**Comment by feiyangsuo** [comment]
> The BaseDataset itself is loading images into the range (-1, 1). Note the norm layer [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/base_dataset.py#L109).
> 
> `ToTensor` first brings the input range to (0, 1), after which `Normalize` brings it to (-1, 1) range.

Got it. Thanks :)
