### ISSUE TITLE
test resnet_9blocks or resnet_6blocks then such error appears：KeyError: 'unexpected key "model.10.conv_block.6.weight" in state_dict'

### ISSUE THREAD

**Issue by Overtown** [junyanz/pytorch-CycleGAN-and-pix2pix#122]
When testing resnet_9blocks model, this error appeared: KeyError: 'unexpected key "model.10.conv_block.6.weight" in state_dict'
and so did the model of resnet_6blocks.
why i trained resnet model,there was no bug ,but tested it unsuccessfully？
Hoping your help.

**Comment by junyanz** [comment]
This might be caused by different flags used in training and test scripts. For example, if one might use batchnorm for training, but have instancenorm for test.

**Comment by Overtown** [comment]
Thanks a lot : )

**Comment by ssdutHB** [comment]
In my opinion, you may forget to add "--no_dropout".
