### ISSUE TITLE
Information about output on visdom?

### ISSUE THREAD

**Issue by yenai3726** [junyanz/pytorch-CycleGAN-and-pix2pix#1228]
Hello, I am a beginner of cycleGAN
I deploy my own dataset on cycleGAN
At runtime I found that there are 8 pictures on visdom
I would like to ask what rec_A, idt_B  and  rec_b, idt_A  mean respectively ?

This is the instruction I used
python train.py --dataroot ./datasets/fishboat --name fishboat_cyclegan --model cycle_gan

Thank you for your attention and answers

**Comment by JunlinHan** [comment]
Real_A ->G(A->B)-> Fake_B ->G(B->A)-> Rec_A
Real_A ->G(B->A) -> Idt_A. (or B, I forgot the naming).

**Comment by yenai3726** [comment]
Thanks for your answer !!
This helped me a lot
