### ISSUE TITLE
How to set options to train pix2pix with 128x128 data?

### ISSUE THREAD

**Issue by fire717** [junyanz/pytorch-CycleGAN-and-pix2pix#1229]
Of course I have searched and found these: 

#406
#578

However,  I didn't get any useful infomation, in #406, there is only one reply by @junyanz:
> You can resize your images to 200x200 by setting --display_winsize 200 during test time.

And @haoxiangchnchn said :
> Thank you for your reply, I have solved this problem and wish you a smooth job!

It's really weird, cause the reply said "during test time", what I want to do is "during traing time", and display_winsize just change display size, cannot change model or input data.

While I set crop_size=128, I got this error:
> ValueError: Expected more than 1 value per channel when training, got input size [1, 512, 1, 1]

So anyone can help me? Thx.

**Comment by lizard24** [comment]
Hi, could it be that you have to change the channel of your image from 3 to 1 (if greyscale)? You do this via "--input_nc 1 --output_nc 1".

**Comment by DanielXu123** [comment]
It's related to the training generator net you selected. By default, it will choose unet, it need input image size with n*256. If you want to train other size, you may need to train the model using resnet9blocks(something like that) for the generator. @fire717

**Comment by DanielXu123** [comment]
`    def modify_commandline_options(parser, is_train=True):
        """Add new dataset-specific options, and rewrite default values for existing options.

        Parameters:
            parser          -- original option parser
            is_train (bool) -- whether training phase or test phase. You can use this flag to add training-specific or test-specific options.

        Returns:
            the modified parser.

        For pix2pix, we do not use image buffer
        The training objective is: GAN Loss + lambda_L1 * ||G(A)-B||_1
        **By default, we use vanilla GAN loss, UNet with batchnorm, and aligned datasets.**
        """
        # changing the default values to match the pix2pix paper (https://phillipi.github.io/pix2pix/)
        parser.set_defaults(norm='batch', netG='unet_256', dataset_mode='aligned')
        if is_train:
            parser.set_defaults(pool_size=0, gan_mode='vanilla')
            parser.add_argument('--lambda_L1', type=float, default=100.0, help='weight for L1 loss')

        return parser`

In file pix2pix_model.py, line 29

**Comment by fire717** [comment]
thx you two! I will have a try!

**Comment by ElijahKuranets** [comment]
@fire717 did you achieved result with 128x128 images? How did you do this?

**Comment by fire717** [comment]
> n the mod
Oh its such a long time,
Unfortunately, I still did not train with 128 sucessfully, and not using this repo after that.
