### ISSUE TITLE
fineSize option for pix2pix with unet

### ISSUE THREAD

**Issue by srinlee-kyra** [junyanz/pytorch-CycleGAN-and-pix2pix#123]
I am running pix2pix with my data and sample data (facade downloaded by ./datasets/download_pix2pix_dataset.sh). Then if I change the default fineSize (256) in base_options.py to another size, I got the following errors.

........ /pytorch-CycleGAN-and-pix2pix/models/networks.py", line 382, in forward
    return torch.cat([x, self.model(x)], 1)

File "/usr/local/lib/python2.7/dist-packages/torch/autograd/_functions/tensor.py", line 317, in forward
    return torch.cat(inputs, dim)
RuntimeError: inconsistent tensor sizes at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:141

When I try the same setting with resnet, I don't get any error. Can you please check it?
Thank you.

**Comment by PraveerSINGH** [comment]
@srinlee-kyra: Hey, How do you test for a rectangular image (lets say of size 480 X 640) for a Unet pre-trained with lets say images of size 512 X 512 ? Thanks in advance.

**Comment by ShaniGam** [comment]
@srinlee-kyra That's exactly what happens to me, did you solve it?
