### ISSUE TITLE
why use random jitter for the input images?

### ISSUE THREAD

**Issue by pihulj** [junyanz/pytorch-CycleGAN-and-pix2pix#125]
and  w_offset = random.randint(0, max(0, w - self.opt.fineSize - 1))
        h_offset = random.randint(0, max(0, h - self.opt.fineSize - 1))
here w_offset and h_offset is different???
then A and B are different region of the original images? why

**Comment by junyanz** [comment]
w_offset and h_offset are the offsets for x, y directions. We use the same (w_offset, h_offset) to crop the regions from A, and B. You can see [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/7800d516596f1a25986b458cddf8b8785bcc7df8/data/aligned_dataset.py#L38) for more details.

**Comment by pihulj** [comment]
yes you are right. and i want to know why use random jitter? i mean you resize the input image to 286*286(why specific 286? reciptive field?) then crop 256*256 ？  thanks a lot

**Comment by junyanz** [comment]
Cropping and random jittering is a commonly used data augmentation technique to prevent overfitting. There is no specific reason for 286. You can try different sizes for your own applications

**Comment by jgoldfa** [comment]
Any reason for random jitter in pix2pix test?
Is there a current option to reproduce the same result in consecutive runs?

Awesome code sharing. Very inspirational.

**Comment by junyanz** [comment]
You can just set loadSize=256, fineSize=256 during the test. If you want to keep the same resolution between training and test, you can center-crop the test images in advance by yourself.
