### ISSUE TITLE
How to use Visdom to observe the loss graph in Colab?

### ISSUE THREAD

**Issue by Amazingfanta** [junyanz/pytorch-CycleGAN-and-pix2pix#1269]
I running the pytorch version of this in Colab
 display_port: 8097                          
 display_server: http://localhost   
But I can not access to the http://localhost:8097
information:Unable to access this website localhost rejected our connection request.

**Comment by xuihan** [comment]
May I ask how you solved this problem?

**Comment by junyanz** [comment]
You need to run `python -m visdom.server` first.
