### ISSUE TITLE
Horse 2 Zebra Video File

### ISSUE THREAD

**Issue by mrluker** [junyanz/pytorch-CycleGAN-and-pix2pix#127]
@junyanz how did you run your "horse 2 zebra" video through the model you created? 

Did you run a video file through, or did you convert the frames to still images?

**Comment by junyanz** [comment]
You are right. We just run our model on a horse sequence frame by frame. We first convert video to still images.

**Comment by mrgloom** [comment]
Is this model was trained on images? i.e. no additional temporal consistency constrain that is special for video was not applied?

It's known that conditioned models trained on images are flickering when they applied to video frames
Examples:
Based on pix2pixHD, conditioned on pose:
https://github.com/nyoki-mtl/pytorch-EverybodyDanceNow/blob/master/output.gif
Based on pix2pixHD, conditioned on semantic label map:
https://youtu.be/5zlcXTCpQqM?t=140

**Comment by junyanz** [comment]
This model was trained on images alone, without temporal consistency. For video generation, please check out recent work [video-to-video synthesis](https://tcwang0509.github.io/vid2vid/).
