### ISSUE TITLE
Why did I lose some of the images when running combine_A_and_B.py?

### ISSUE THREAD

**Issue by 631543791** [junyanz/pytorch-CycleGAN-and-pix2pix#1274]
I used
! python datasets/combine_A_and_B.py --fold_A datasets/WB_resize/A --fold_B datasets/WB_resize//B --fold_AB datasets/AB
Here's the output:
[fold_A] =  datasets/WB_resize/A
[fold_B] =  datasets/WB_resize//B
[fold_AB] =  datasets/AB
[num_imgs] =  1000000
[use_AB] =  False
[no_multiprocessing] =  False
split = test, use 8/8 images
split = test, number of images = 8
split = train, use 30/30 images
split = train, number of images = 30
split = val, use 8/8 images
split = val, number of images = 8

however there are only 11 combined images in datasets/AB/train and no image in other folders at all

**Comment by akamob** [comment]
Hi, @631543791, i also have this question.

May i have your suggestions to fix this problem?
Any help is much appreciated:)
