### ISSUE TITLE
My test results doesn't give me any index.html

### ISSUE THREAD

**Issue by GoncaloCJG** [junyanz/pytorch-CycleGAN-and-pix2pix#1279]
I trained the model and everything ran smoothly. But when I tested the model, it ran but didn't give me any output, not even the index.html that was supposed to.

I trained the model with the following options:

![image](https://user-images.githubusercontent.com/83720730/117178633-2a52ca80-adca-11eb-86c2-d5c34d6e7c73.png)

And I'm trying to test it with the following options:

![image](https://user-images.githubusercontent.com/83720730/117178744-46566c00-adca-11eb-8beb-dbe285d13b66.png)

This is what I'm getting when I run the test:
![image](https://user-images.githubusercontent.com/83720730/117177929-75201280-adc9-11eb-897c-a25df4c73f6f.png)

And the only thing that this generated was this test_opt.txt file.
![image](https://user-images.githubusercontent.com/83720730/117178193-af89af80-adc9-11eb-89e8-c6b7ba11eeb8.png)

Do you know what I'm doing wrong?
Thank you in advance.

**Comment by ljmf00** [comment]
Hi @GoncaloCJG,

Can you describe your running environment, such as running OS and passed arguments ? Also, consider running it with verbose logging by adding `--verbose` to your arguments list.

**Comment by GoncaloCJG** [comment]
Hi, thank you for your answer.

I'm running this on Google Colab.

These are the past arguments on training:
![image](https://user-images.githubusercontent.com/83720730/117216986-8f251980-adf8-11eb-96a4-aae8d38f0168.png)

And these are the past arguments on testing:
![image](https://user-images.githubusercontent.com/83720730/117217030-aa902480-adf8-11eb-836f-b1f1b0c95a0a.png)

When I add the `--verbose logging` it gives me this error:
![image](https://user-images.githubusercontent.com/83720730/117217173-e2976780-adf8-11eb-9ba4-f36fd9bb5c93.png)

**Comment by ljmf00** [comment]
You should only add `--verbose` option, not `logging`

**Comment by GoncaloCJG** [comment]
Ah thanks.

Just gives me this information.
![image](https://user-images.githubusercontent.com/83720730/117217942-2ccd1880-adfa-11eb-8182-b5dd3d642822.png)

Still doesn't give me any index.html

**Comment by ljmf00** [comment]
> Still doesn't give me any index.html

Verbosity only increases the log level. For further analysis by some maintainer, I would suggest you to send the log through a paste instead of partial screenshots. See here: https://paste.linux.community/ . Before sending the log, make sure there's no sensitive info on the logs.
