### ISSUE TITLE
Option: Resize or Crop - Understanding problem

### ISSUE THREAD

**Issue by PhysikerErlangen** [junyanz/pytorch-CycleGAN-and-pix2pix#128]
Hello,
thank you guys for this great piece of code. It's actually quite easy to run! 

I have one question regarding the '--resize_or_crop' option. I have prepared a dataset of images with 256x256 pixels each, so I thought I don't want any cropping or resizing to happen. Thus, I tried to use these options: '--loadSize 256 --fineSize 256', but the code fails to run.

**Comment by junyanz** [comment]
I just trained a pix2pix facades model with `--loadSize 256 --fineSize`, and it worked. Could you post more information on the errors?

**Comment by PhysikerErlangen** [comment]
Hi,

The followingg does not work
python train.py --dataroot /data/CycleGan --name shanghai_test_2 --model cycle_gan --no_dropout --display_id 0  --loadSize 256 --fineSize 256

The following does work:

python train.py --dataroot /data/CycleGan --name shanghai_test_2 --model cycle_gan --no_dropout --display_id 0 

This is the error I receive

> model [CycleGANModel] was created
create web directory ./checkpoints/test/web...
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    for i, data in enumerate(dataset):
  File "anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 40, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "PKU/pytorch-CycleGAN-and-pix2pix/data/unaligned_dataset.py", line 34, in __getitem__
    A = self.transform(A_img)
  File "anaconda3/envs/pytorch/lib/python3.6/site-packages/torchvision-0.1.9-py3.6.egg/torchvision/transforms.py", line 369, in __call__
    img = t(img)
  File "anaconda3/envs/pytorch/lib/python3.6/site-packages/torchvision-0.1.9-py3.6.egg/torchvision/transforms.py", line 611, in __call__
    i, j, h, w = self.get_params(img, self.size)
TypeError: 'Image' object is not iterable

**Comment by PhysikerErlangen** [comment]
Hello,
I have forgotten to mention that I am using CycleGan and not pix2pix. I'm using medical images of different modalities, however, they cannot be registered sufficiently, so I thought I should give CycleGan a chance.

When training the network I experienced strong grid-like artifacts as already mentioned in issue 78. I thought this might stem from preprocessing such as resizing operations. As far as I understand your frameworks loads an image (in my case 256x256 resolution) resizes it to 286 and subsequently cuts it to randomly to 256x256.

However, I don't want this to happen. I want CycleGan to directly take my images as input and don't do any further preprocessing.

Unfortunately, I don't have my own machine with a GPU. I run all the code on a cloud server, so debugging into code is actually pretty hard for me at this point ...

Best,
Florian

**Comment by junyanz** [comment]
Interesting. I can run the `--loadSize 256 --fineSize 256` on the public maps dataset. Here is my command. I wonder if you can run the same command on the maps dataset. There might be something special about your own dataset. 
```bash
python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --no_dropout --loadSize 256 --fineSize 256
```

**Comment by pihulj** [comment]
you may comment 
transform_list.append(transforms.RandomCrop(opt.fineSize)) in base_dataset.py

then try again
