### ISSUE TITLE
How can I save more experiment result in each epoch? 

### ISSUE THREAD

**Issue by Youqi970124** [junyanz/pytorch-CycleGAN-and-pix2pix#1281]
Dear sir:
        Like title, because I need the fake image generated by the Generator, I hope to store more experimental results in each epoch, but I did not find a place in the program that can be modified.

thank you very much

**Comment by yandexgirls** [comment]
Hello, as far as I've understood, you can reduce --update_html_freq and --display_freq parameters. 
For instance, if you have 1000 images in training set, setting --update_html_freq 100 --display_freq 100 will result in saving 10 experimental results each epoch.

**Comment by Youqi970124** [comment]
Thank you very much for your suggestions, I will try it. 


sincerely You Qi

**Comment by AlexWilkinsonnn** [comment]
If you want more control over storing results you can try just directly change `train.py`. You can grab the images using something like 
```
if total_iters % opt.display_freq == 0:
    if opt.model == 'pix2pix':
        model.compute_visuals()
        visuals = model.get_current_visuals()
    
        image_realA = visuals['real_A'].data
        arr_realA = image_realA[0][0].cpu().float().numpy()
```
Then you have your image as a numpy array (mine is grayscale so I remove the channel dimension with the second [0]) and you can do whatever suits you, `visuals` is a dictionary containing the images as tensors at the current iteration.
