### ISSUE TITLE
generate map

### ISSUE THREAD

**Issue by xiyufeng2** [junyanz/pytorch-CycleGAN-and-pix2pix#1282]
Hello. I want to convert my aerial photos into maps (the same types in your dataset). Do you have a code?

**Comment by junyanz** [comment]
You can download pre-trained [models](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/scripts/download_pix2pix_model.sh#L3) and use our test code. See [README](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-pix2pix) for more details.
