### ISSUE TITLE
Why can't launch the GPU?

### ISSUE THREAD

**Issue by BiQiWHU** [junyanz/pytorch-CycleGAN-and-pix2pix#1289]
Thanks for your project! I made the config following your steps, and trained the cyclegan by runing the train.py file. But I find that the project seems run on CPU, rather than using my GPU. Do you have any suggestions?

**Comment by lghasemzadeh** [comment]
As far as I know it will run on GPU by default. But it is normal to take lots of time for training if your PC has single GPU.
During the training try this command:
$ nvidia-smi 
and check the third row,last colomn of the table to see how many percent of your GPU is using, probably it shows 100%,  then it means the training uses 100% of the GPU. you need to run the model on a PC having more GPUs to get higher speed.
This is what I know but I am not sure how much it is correct.

**Comment by BiQiWHU** [comment]
Yes, I see. By using the cmd code in the Jupyter notebook, my GPU can be launched normally.
