### ISSUE TITLE
Long Train Process

### ISSUE THREAD

**Issue by lghasemzadeh** [junyanz/pytorch-CycleGAN-and-pix2pix#1291]
Hello,

I used around 300K dataset (train, test and both domains), It took 2 days for first epoch and about 50000 iterations. it was using GPU 100% but is it normal to take this long time?
I reduced the data to 6000 in total but the training stopped at epoch 27, iteration 1400, I mean it didn't move forward from epoch 27 for one day since each epoch were taking about 3 hours before that epoch, what is the reason? How can fix it?
Is there any way to make the training process faster or at least working until the end?

Thank you

**Comment by Ayushutkarsh** [comment]
Facing the same issue with a 115k dataset. It takes around 2 hours to complete a single epoch. GPU utilization is at 100%

**Comment by lghasemzadeh** [comment]
I tried training with a PC having 4 GPUs and using this command:
$ python train.py --dataroot [name of your data folder] --gpu_ids 1,2,3
and the speed increased.
