### ISSUE TITLE
Continue training on pre-trained weights

### ISSUE THREAD

**Issue by patselle** [junyanz/pytorch-CycleGAN-and-pix2pix#1294]
Hi,

I want to continue training on a pre-trained model, for example on monet2photo.
If I downloaded the latest_net_G.pth and save them in the correct directory (./checkpoints/{NAME}_pretrained/latest_net_G.pt), are they automatically loaded when I start the training with --name {NAME}_pretrained?
Because --continue_train doesn't work (looks for files for G_A, G_B, D_A, D_B).

Best regards

**Comment by junyanz** [comment]
The current `contine_train` only works for your own model training. It requires all the generators and discriminators. Unfortunately, we haven't saved the discriminators.
