### ISSUE TITLE
combine A and B in pix2pix

### ISSUE THREAD

**Issue by JiangPeiy** [junyanz/pytorch-CycleGAN-and-pix2pix#1298]
hi I met a problem
(base) G:\pythonProject1\tl\tensorlayer\pytorch-CycleGAN-and-pix2pix>python datasets/combine_A_and_B.py --fold_A ./datasets/data/mars/A/train --fold_B ./datasets/data/mars/B/train --fold_AB ./dat
asets/data/mars/train
[fold_A] =  ./datasets/data/mars/A/train
[fold_B] =  ./datasets/data/mars/B/train
[fold_AB] =  ./datasets/data/mars/train
[num_imgs] =  999
[use_AB] =  False
[no_multiprocessing] =  False
Traceback (most recent call last):
  File "datasets/combine_A_and_B.py", line 35, in <module>
    img_list = os.listdir(img_fold_A)
NotADirectoryError: [WinError 267] 目录名称无效。: './datasets/data/mars/A/train\\100_A.jpg'

Use python datasets/combine_A_and_B.py --fold_A ./datasets/data/mars/A/train --fold_B ./datasets/data/mars/B/train --fold_AB ./datasets/data/mars/train

my data is stored in A/train and B/train with 1000 jpg.

I follow the instructions carefully but there still exists problems.

**Comment by aik-lw** [comment]
First thing to try is make your slash consistent. 
See the error - './datasets/data/mars/A/train\100_A.jpg'

**Comment by junyanz** [comment]
yeah, make sure your path is consistent. We also haven't tested the code on Windows. It should work for Linux and MAC.
