### ISSUE TITLE
Load only G_A to make transformations faster

### ISSUE THREAD

**Issue by kpagels** [junyanz/pytorch-CycleGAN-and-pix2pix#1299]
Hi,

I have spend some time now on training a model. However, when I want to test the model it takes approximately 1second to transform one image. I think this is long. When my dataset is approximately 20000 images, it will take 5.5 hours to transform all the images. I am only interested in the G_A transformation. How can I speed up my transformations?

**Comment by junyanz** [comment]
You can use `--model test` to load only one model. See [FAQ](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#out-of-memory-174) for more details.  Also [README](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-cyclegan).
