### ISSUE TITLE
Model parallelism

### ISSUE THREAD

**Issue by pedropgusmao** [junyanz/pytorch-CycleGAN-and-pix2pix#13]
Hi,
I am trying to generate HD images, but results are not so good and I guess it is because I am training the models using lower resolution images (256x256). 
Unfortunately, if I try to train these networks using higher resolution images I run out of memory. So, I was wondering if it is possible to [split the networks over multiple GPUs](https://github.com/jcjohnson/neural-style/blob/07c4b8299f8fbdafec0c514fc820ff1d7ff62e46/neural_style.lua#L19) and run the model over multiple devices. 

Thanks

**Comment by junyanz** [comment]
This multi-gpu support would be a great feature.   
With the current implementation, you can also crop patches from high-res images (e.g. crop 256x256 patches from 512x512 images. Set  loadSize=512, and fineSize=256 for both training and test). This will save you gpu memory during training, while still allows you to test your model on high-res images.
