### ISSUE TITLE
The training dataset image is not square, but rectangular, the image size is 355*32, how do I adjust the parameters to make cyclegan fit my dataset?

### ISSUE THREAD

**Issue by happy20200** [junyanz/pytorch-CycleGAN-and-pix2pix#1302]
The training dataset image is not square, but rectangular, the image size is 355*32, how do I adjust the parameters to make cyclegan fit my dataset?

**Comment by junyanz** [comment]
The code will round up your input size 355 to 356. See [Training & Test tips](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#trainingtesting-with-rectangular-images) for more details on how to train on rectangular images.
