### ISSUE TITLE
Discriminator classifier: ResNet50

### ISSUE THREAD

**Issue by VishalP1975** [junyanz/pytorch-CycleGAN-and-pix2pix#1307]
Hi, First of all thank you for your great work..!! @junyanz @taesungp 

Is it possible to use ResNet50 or other classifiers instead of PatchGAN classifier in discriminator?
I am trying to segment only the fully visible objects in an image which contain a more number of objects but my model not able to detect all the completely visible objects. Do you have any suggestions on how to proceed for this task?

Thank you & Any suggestions would be appreciated.!!

**Comment by junyanz** [comment]
It's possible. But you might also need to also increase the capacity of the generator.

**Comment by VishalP1975** [comment]
Thank you for your response @junyanz.
Did you mean to increase the number of filters of the generator?  for example --ngf to 128
or should I increase the num_downs of the generator? 
I am using a (512,512) image size.

Your answer really helps me a lot...!!

**Comment by junyanz** [comment]
It is hard to say. Try both the number of filters and the number of layers. I recommend that you don't add too many downsampling layers (You can add 1 for 512x input). You can add more ResNet generator blocks

**Comment by VishalP1975** [comment]
Thank you @junyanz  for your kind reply.
I'll try with them. I have achieved notable results by using wgan-gp loss.
