### ISSUE TITLE
inference about cycleGAN

### ISSUE THREAD

**Issue by cena001plus** [junyanz/pytorch-CycleGAN-and-pix2pix#1309]
thanks for your contribution, I have trained my own cycleGAN model according to the instructions. My question is, when I plan to inference  the data which include  1000 data set (testA), do I have to have 1000 testB corresponding to testA?

**Comment by junyanz** [comment]
You don't need to have testB.  Just need to use `--model test`. See this [guideline](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-cyclegan) for more details.

**Comment by collinsrakowski** [comment]
Is this the case for pix2pix as well?
