### ISSUE TITLE
about image size

### ISSUE THREAD

**Issue by fengweie** [junyanz/pytorch-CycleGAN-and-pix2pix#1311]
I noticed that CycleGAN resizes both domain images to the same size, if I have two images with very different sizes and I don't want to resize them to the same size to avoid missing a lot of details, how should I deal with this problem, looking forward to your advice, thanks a lot.

**Comment by junyanz** [comment]
You can use different `--preprocess` options. See this [tip](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#trainingtesting-with-rectangular-images) for more details.
