### ISSUE TITLE
Dataset link not always accessible

### ISSUE THREAD

**Issue by tmabraham** [junyanz/pytorch-CycleGAN-and-pix2pix#1312]
It seems like the dataset link is region-limited?

https://people.eecs.berkeley.edu/~taesung_park/CycleGAN/datasets/horse2zebra.zip

I can download it on my computer but it doesn't work on Colab. I also asked a couple folks and some of them can access while others cannot. 

I suspect there is some sort of region limitation for being able to access this dataset?

Hopefully this can be fixed as soon as possible since many people are likely trying to use these datasets.

**Comment by taesungp** [comment]
Hello, I think the web server at Berkeley went offline for some period. I did move the link to a more stable server. Thank you for the heads up.
