### ISSUE TITLE
Could you provide the tutorial and source codes of evaluation models for CycleGAN and CyCADA?

### ISSUE THREAD

**Issue by BenoitKAO** [junyanz/pytorch-CycleGAN-and-pix2pix#1315]
Thank you for your marvelous work.

I would like to cite and produce the baseline of CycleGAN and CyCADA with customer datasets in my researches.

I have read the information from:
https://github.com/tkhkaeio/CyCADA
"...
Implementation
Code is mainly borrowed from junyanz/pytorch-CycleGAN-and-pix2pix
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix"

Could you provide the tutorial and source codes of evaluation models for CycleGAN and CyCADA?
Such as Precision, Recall, Accuracy, Confusion Matrix, IoU, F1 score, AUC, ROC, P-Value, ROC and PR Curves, Training curve, Validation Curve, ..., and so on.

Any help is appreciated.

**Comment by junyanz** [comment]
Could you check this repo (https://github.com/jhoffman/cycada_release)? 
We don't have all the segmentation metrics in this repo.
