### ISSUE TITLE
Problem about visdom.server

### ISSUE THREAD

**Issue by AugustLee93** [junyanz/pytorch-CycleGAN-and-pix2pix#1318]
Hi there, I got a problem with opening visdom.server. My OS is win11, and I use docker, which I run the code in the container. Here is the screenshot with my issue. 
![1](https://user-images.githubusercontent.com/70758744/134445074-7dc90262-14a2-4163-ad2e-c5c4e1203a9d.png)

It said Address already in use, then I use -port 12345 
![2](https://user-images.githubusercontent.com/70758744/134445165-4f125362-385d-4fdd-ac92-cf98c2212f37.png)

which it can success show the address and i got the url link. But I can't open the url link, I don't know what to do, I kind of new with code stuff, can anyone know how to solve this? 
![3](https://user-images.githubusercontent.com/70758744/134445308-380d2c68-021c-4c0d-aef2-837f80f47b38.png)

**Comment by AugustLee93** [comment]
> Not sure what happened. It might depend on your server setting. You may want to try to use `wandb` if `visdom` doesn't work for you. To log training progress and test images to W&B dashboard, set the --use_wandb flag with the train and test script

Thank you for replying!  The issue was related to the parameter that I build docker, and I already sovled it, thanks again!

**Comment by kaku2000** [comment]
Hi, how to modify the --use_wandb option if I'm running it locally.
