### ISSUE TITLE
Designing conditional GANs that produce highly stochastic output, and thereby capture the full entropy of the conditional distributions they model, is an important question left open by the present work.

### ISSUE THREAD

**Issue by qsunyuan** [junyanz/pytorch-CycleGAN-and-pix2pix#1326]
In pix2pix, section 3.1. after the formula 4. 
https://arxiv.org/pdf/1611.07004.pdf

Aim to designing conditional GANs that produce highly stochastic output.
Is there a solution to this problem now? 

Thx!

**Comment by Seyanh** [comment]
Thx it helps me a lot
