### ISSUE TITLE
How to modify code for .mat dataset

### ISSUE THREAD

**Issue by wh-isper** [junyanz/pytorch-CycleGAN-and-pix2pix#1335]
Dear author, I want to use pix2pix to implement medical image modal transformation. Because my data type is float64, I can't save them as jpg or png which will lose precision. I have to save them as  **.mat** documents. But I don't know how to process them. Could you please give me some advice on how to modify the code and which .py to modify.

**Comment by junyanz** [comment]
You can modify the data loader by adapting this data loader template [class](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/template_dataset.py) to your format.  Also, see the code [overview](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/overview.md) for more details (see the `data` directory(

**Comment by wh-isper** [comment]
> You can modify the data loader by adapting this data loader template [class](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/template_dataset.py) to your format. Also, see the code [overview](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/overview.md) for more details (see the `data` directory).

Thank you very much!
