### ISSUE TITLE
can the model support input_nc=4,ouput_nc=4?

### ISSUE THREAD

**Issue by Overtown** [junyanz/pytorch-CycleGAN-and-pix2pix#134]
can the model support input_nc=4,ouput_nc=4? I failed, I used the old vision of this model ,can it support nc = 4 now?

**Comment by junyanz** [comment]
The code only supports 1-channel and 3-channel images. You need to modify the image_loader to support 4-channel data. Here is a [modification](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/unaligned_dataset.py#L43) for the 1-channel image.

**Comment by patrick-han** [comment]
@junyanz Do you mind elaborating what the "image_loader" is referring to? I'm currently trying to add support for 4 channel data but have been running into a lot of troubles especially with saving/loading/transforms.

**Comment by junyanz** [comment]
You can write your own custom data loader. Here is a [template](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/template_dataset.py) with documentation. I recommend that you write a standalone python script to test your saving/loading/transformation function before adding them to the main program.
