### ISSUE TITLE
Aligned random horizontal image flipping

### ISSUE THREAD

**Issue by wobu** [junyanz/pytorch-CycleGAN-and-pix2pix#1346]
Hi,

after researching and tempering with the pix2pix implementation we noticed that the img flipping transformation isn't handling aligned datasets correctly.

in the original pix2pix implementation both, the input and output images are flipped together, not individually at random.
See: https://github.com/phillipi/pix2pix/blob/89ff2a81ce441fbe1f1b13eca463b87f1e539df8/data/donkey_folder.lua#L71

In this repo implementation @ UnalignedDataset and @AlignedDataset they are flipped individually at random.

**Comment by junyanz** [comment]
The AlignedDataset should apply the same flipping, as noted in this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/aligned_dataset.py#L51). You don't have to apply the same flipping to unaligned cases, as they are different images.

**Comment by wobu** [comment]
Hey junyanz,

i checked the got for Aligned Dataset again. You are right, as default the same flipping is applied to both A and B. 
At first hand i just saw https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/00d5574908eb66fe0127b32d7b030001453f21d0/data/base_dataset.py#L102
The torch transformers.RandomHorizontalFlip

But there is a param for flipping randomly initialized at https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/00d5574908eb66fe0127b32d7b030001453f21d0/data/base_dataset.py#L76
