### ISSUE TITLE
Training stop/won't start  with no error or warning message 

### ISSUE THREAD

**Issue by BianChang** [junyanz/pytorch-CycleGAN-and-pix2pix#1348]
Hi, thank you for the great repo,

May I please ask that, when I tried to train the model on my own dataset, I changed the code about input/output channels to fit my own dataset,  and when I start my training with the following command: 
'python train.py --dataroot ./datasets/mihc1 --name mihc_pix2pix --model pix2pix --direction AtoB --dataset_mode unaligned', 
the session automatically stop  after showing
 'Setting up a new session...
create web directory ./checkpoints\mihc_pix2pix\web...'

And it did not show any error or warning. 

May I please ask why it happens?

**Comment by junyanz** [comment]
Are you training the model on Linux or Windows? Could you train the model with the default dataset? It seems that you might get stuck in visdom. You can also disable the visdom by setting `--display_id 0`.

**Comment by NguyenVanThanhHust** [comment]
@junyanz I meet the same problem. I set `--display_id 0`. I run on Windows. Do you have any suggesstion?

**Comment by junyanz** [comment]
Could you share more details without us? You still have the issue even after you set ``-display_id 0``? Could you share the screenshot of your debugging output?

**Comment by NguyenVanThanhHust** [comment]
Yes, I still have the issue after setting `--display 0` . I stopped debugging and change to Linux. 
Tks anw.
