### ISSUE TITLE
resize rectange images for training phase

### ISSUE THREAD

**Issue by julingers** [junyanz/pytorch-CycleGAN-and-pix2pix#1350]
I want to ask that whether I can resize a rectangle image(for example,1920×1080)，then input the resized rectangle image to train, because my target is small, if I random crop, maybe most of crop size images is without my target.  I have tried it. CUDA error occurred. And the resized image size is 270×480. I think my GPU memory can support it. So is the network not support rectangle images? How can I input the whole rectangle images?

Hope for your reply.

**Comment by julingers** [comment]
Moreover，if network don't support rectangle images, why test phase can inferrence successfully and output a rectangle images with --preprocess none. So I think train phase can input rectangle images too. But I failed. And it should not be GPU memeory problem I think.

**Comment by junyanz** [comment]
The network can support rectangle images (in the CycleGAN setting). The height and width need to be divisible by 4. 
See this [training and test tip](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#trainingtesting-with-rectangular-images) for more details.
