### ISSUE TITLE
Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)

### ISSUE THREAD

**Issue by 1664566760** [junyanz/pytorch-CycleGAN-and-pix2pix#1356]
loading之后出现这样的问题怎么解决

**Comment by 1664566760** [comment]
File "C: \Users\wangh\anaconda3\envS\pytorch\Lib\site packages requests \adapters.py", Line 502, in send
raise ConnectionError(e, request=request)
requests . exceptions . ConnectionError: HTTPConnectionPool(host='LocaLhost', port=8097): Max retries exceeded with urL: /events (Caused by NewConnectionError('<requests . packages . urLLib
ection . HTTPConnection object at 00000024900700668>: Failed to establish a new connection: [WinError 10061]由于目标计算机积极拒绝，无法连接。',))

**Comment by duohereshui7** [comment]
命令行运行python -m visdom.server

**Comment by 1664566760** [comment]
loading之后出现的这个问题，python -m visdom.server
好像不能解决

**Comment by junyanz** [comment]
You can also just disable it. See this [Q & A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#connection-errorhttpconnectionpool-230-24-38)

**Comment by itzhuang** [comment]
![2022-03-05 16-58-10 的屏幕截图](https://user-images.githubusercontent.com/36561791/156876393-3dab8cb9-fbbd-43a2-ba78-28bd72816aca.png)
