### ISSUE TITLE
Failed to load saved pix2pix model when the model is trained with --batchSize 1 

### ISSUE THREAD

**Issue by jjcao** [junyanz/pytorch-CycleGAN-and-pix2pix#136]
Hi,

I found saved pix2pix model trained with --**batchSize > 1**, can be successfully loaded both for **testing (using test.py)** and continue training.
But the saved model with --**batchSize==1**, can only be successfully loaded for **continue training**, but failed for **testing**.

When loading saved model for testing: 
I found that the saved model with batchSize >1 does not have the key 'model.model.0.bias', but with batchSize ==1, the saved model has the key 'model.model.0.bias'. then 'unexpected key "model.model.0.bias" in state_dict' happened in load_network() of base_model.py.

When loading saved model for testing, I also find that:
1. state_dict in saved model trained with batchSize == 1 has 58 keys: len(state_dict.keys())
2. state_dict of creating a test model has 69 keys. They are different.
3. state_dict in saved model trained with batchSize == 8 has 69 keys. Hence I can successfully load the saved mode for testing.

But when loading saved model with batchSize ==1 for continual training, I found: 
state_dict in saved model trained with batchSize == 1 and state_dict of creating a train model **both have 58 keys**.

How to solve this?

**Comment by junyanz** [comment]
The problems are often caused by inconsistent flags used in the training/test.  Which kinda of `norm` parameters are you using for training and test?

**Comment by jjcao** [comment]
When testing a model trained with batchSize == 1, norm option should be instance, not batch, i.e. --norm instance.
