### ISSUE TITLE
'Visualizer' object has no attribute 'ncols'

### ISSUE THREAD

**Issue by Tyotw** [junyanz/pytorch-CycleGAN-and-pix2pix#1360]
Hi, Mr. Author I've met a question:
I use to Latest code and I want to use wandb and avoid visdom.server, so the command is :
 "python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --load_size 1920 --crop_size 400 --n_epochs 1000 --n_epochs_decay 1000 **--use_wandb --display_id 0**" 

 but the error occurs:

wandb: Currently logged in as: leseul53 (use `wandb login --relogin` to force relogin)
D:\anaconda3\envs\py37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of n
umpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\anaconda3\envs\py37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of n
umpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\anaconda3\envs\py37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of n
umpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\anaconda3\envs\py37\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of n
umpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\anaconda3\envs\py37\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of n
umpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\anaconda3\envs\py37\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of n
umpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
D:\anaconda3\envs\py37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future versi
on of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\anaconda3\envs\py37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future versi
on of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\anaconda3\envs\py37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future versi
on of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\anaconda3\envs\py37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future versi
on of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\anaconda3\envs\py37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future versi
on of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\anaconda3\envs\py37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future versi
on of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
wandb: Tracking run with wandb version 0.12.9
wandb: Syncing run maps_cyclegan
wandb:  View project at https://wandb.ai/leseul53/CycleGAN-and-pix2pix
wandb:  View run at https://wandb.ai/leseul53/CycleGAN-and-pix2pix/runs/2c95gap2
wandb: Run data is saved locally in D:\lzf\CycleGAN-fenbianlv2\wandb\run-20211229_135342-2c95gap2
wandb: Run `wandb offline` to turn off syncing.

create web directory ./checkpoints\maps_cyclegan\web...
D:\anaconda3\envs\py37\lib\site-packages\torch\optim\lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you sho
uld call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See
 more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
learning rate 0.0002000 -> 0.0002000
(epoch: 1, iters: 100, time: 0.756, data: 6.908) D_A: 0.271 G_A: 0.311 cycle_A: 2.136 idt_A: 0.675 D_B: 0.838 G_B: 1.159 cycle_B: 1.258 idt_B: 1.026
End of epoch 1 / 2000    Time Taken: 63 sec
learning rate 0.0002000 -> 0.0002000
(epoch: 2, iters: 85, time: 0.768, data: 0.001) D_A: 0.261 G_A: 0.245 cycle_A: 1.849 idt_A: 0.697 D_B: 0.282 G_B: 0.253 cycle_B: 1.418 idt_B: 0.920
End of epoch 2 / 2000    Time Taken: 59 sec
learning rate 0.0002000 -> 0.0002000
(epoch: 3, iters: 70, time: 0.801, data: 0.001) D_A: 0.264 G_A: 0.357 cycle_A: 2.066 idt_A: 0.875 D_B: 0.251 G_B: 0.372 cycle_B: 1.724 idt_B: 0.995
End of epoch 3 / 2000    Time Taken: 61 sec
learning rate 0.0002000 -> 0.0002000
Traceback (most recent call last):
  File "train.py", line 57, in <module>
    visualizer.display_current_results(model.get_current_visuals(), epoch, save_result)
  File "D:\lzf\CycleGAN-fenbianlv2\util\visualizer.py", line 122, in display_current_results
    ncols = self.ncols
**AttributeError: 'Visualizer' object has no attribute 'ncols'**

And when I don't use "--display_id 0", it runs fun.

**Comment by taesungp** [comment]
Thank you for reporting the issue. It should've been fixed by the [latest commit](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/003efc4c8819de47ff11b5a0af7ba09aee7f5fc1)
