### ISSUE TITLE
how to set multiple GPU running the train.py ？ 

### ISSUE THREAD

**Issue by improgress** [junyanz/pytorch-CycleGAN-and-pix2pix#1369]
thanks for your answer！

**Comment by junyanz** [comment]
Use ``-gpu_ids``. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L26)

**Comment by improgress** [comment]
> 利用 `-gpu_ids`. 看 [这里 ](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L26)

Many thanks

**Comment by JerryHao-art** [comment]
> Use `-gpu_ids`. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L26)

It cannot work. I set gpu_ids=0,1,2; but it only uses gpu0
