### ISSUE TITLE
About G_A,G_B,D_A,D_B,idt_A,idt_B,cycleA,cycleB at wandb.

### ISSUE THREAD

**Issue by jeong118** [junyanz/pytorch-CycleGAN-and-pix2pix#1370]
Hello!
I'm trying style transfer like horse2zebra by CycleGAN.
I used wandb and I got 8 graphs(G_A,G_B,D_A,D_B,idt_A,idt_B,cycleA,cycleB).
I saw FAQ and your paper but I can't understand perfectly about graphs.

These are the correspondence between graph and paper.
Is my recognition correct?
[graphs name : the name in your paper at Sec2 Fig3]
G_A : loss of G in (a)
G_B : loss of F in (a)
D_A : loss of Dx in (a)
D_B : loss of Dy in (a)
idt_A,idt_B : the identity loss
cycleA : the consistency loss in (b)
cycleB : the consistency loss in (c)

<img width="1050" alt="スクリーンショット 2022-01-23 11 30 44" src="https://user-images.githubusercontent.com/55468858/150662394-855fdcba-4d8a-4e22-9540-199a60fe066b.png">

**Comment by junyanz** [comment]
The naming conversion in the paper and code is different. You can find more details [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/cycle_gan_model.py#L30).
