### ISSUE TITLE
I can't see the results

### ISSUE THREAD

**Issue by Erizu91** [junyanz/pytorch-CycleGAN-and-pix2pix#1375]
When I finish the training I can't see the results by entering the URL ....

I get the following message in the training ...

Could not connect to Visdom server.
Trying to start a server....
Command: /usr/bin/python3 -m visdom.server -p 8097 &>/dev/null &
create web directory ./log/exp/web...
[Errno 99] Cannot assign requested address

**Comment by junyanz** [comment]
It seems that your visdom server has been activated. 
The error is `Cannot assign requested address`.  Try this [tip](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#connection-errorhttpconnectionpool-230-24-38) first. 
You can try a different IP address that works for you using the flag `--display_port` . 
If visdom still doesn't work for you, you can try wandb using the flag `--use_wandb` flag.

**Comment by Erizu91** [comment]
Thanks for your tips, but I still can't display the results, I tried to change the IP but I can't access the website, I also disabled visdom by setting --display_id 0 (how can I see the results if it's disabled?).

**Comment by junyanz** [comment]
You can try [wandb](https://wandb.ai/site) by setting the flag `--use_wandb`.
