### ISSUE TITLE
crush when image_height < image_width with option scale_width_and_crop

### ISSUE THREAD

**Issue by hux999** [junyanz/pytorch-CycleGAN-and-pix2pix#138]
I tried to use the option "--resize_or_crop scale_width_and_crop" and the code fail to cropping image in the image transformation stage. it is because when the height of an image smaller than its width the resized image is too small for square cropping.  i fixed this issue by adding another option "scale_and_crop" which use below resize methodology in "data/base_dataset.py".

def __scale(img, target):
    ow, oh = img.size
    if min(ow,oh) == target:
        return img
    if ow < oh:
        w = target
        h = int(target * oh / ow)
    else:
        h = target
        w = int(target * ow / oh)
    return img.resize((w, h), Image.BICUBIC)

**Comment by junyanz** [comment]
Thanks for the update. You are right. The "scale_width_and_crop" assumes that the height of the resized image is larger than the `fineSize`.
