### ISSUE TITLE
Warning: wandb package cannot be found. The option "--use_wandb" will result in error.

### ISSUE THREAD

**Issue by raylu1314coding** [junyanz/pytorch-CycleGAN-and-pix2pix#1382]
Warning: wandb package cannot be found. The option "--use_wandb" will result in error.
How can I solve the problem?
Thanks a lot.

**Comment by raylu1314coding** [comment]
I have solved it already.Thanks

**Comment by nikoCLang** [comment]
Hello, how did you solve this problem？

**Comment by kinivi** [comment]
How?

**Comment by zhaopuxi** [comment]
how?

**Comment by icelandno1** [comment]
@raylu1314coding Please tell me how this problem was solved, thank you very much

**Comment by junyanz** [comment]
If you want to use wandb, you can [install](https://docs.wandb.ai/quickstart) it before running the program. 
If you want to disable wandb, you can simply remove the flag ``-use_wandb``.
