### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by raylu1314coding** [junyanz/pytorch-CycleGAN-and-pix2pix#1383]
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002678C87A6D8>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。',))

What's the problem with this,how can I do.

Thanks.

**Comment by raylu1314coding** [comment]
I have solved it . it's work. thanks

**Comment by whyydsforever** [comment]
how did you solve this problem?
