### ISSUE TITLE
Out of memory after a few iterations 

### ISSUE THREAD

**Issue by jpmerc** [junyanz/pytorch-CycleGAN-and-pix2pix#139]
With the newest version of Pytorch, I've found that the CycleGan model has memory leaks on the GPU. The used memory (observed with nvidia-smi) increases for each forward pass of G_A and G_B in the function backward_G().

I've solved the problem by removing all global Variables and only kept the tensors as global. I've done that for generated images and losses and it worked. 

I've decided to post this in case this problem happens to anybody else. I have Pytorch installed from source (Nov 1, 2017) with Cuda 9.0.

**Comment by jpmerc** [comment]
yes, it's done.

**Comment by junyanz** [comment]
Thanks. I fixed a few issues for the pix2pix model.

**Comment by myt00seven** [comment]
Currently the CycleGAN model still has the memory leaking problem on GPU. I'm using the latest pytorch docker from [pytorch/pytorch](https://github.com/pytorch/pytorch).

**Comment by SsnL** [comment]
@myt00seven What is your environ setting? I am running cyclegan with latest PyTorch and it seems fine.
