### ISSUE TITLE
How to generate more samples from trained models? What does the number of samples generated depend on?

### ISSUE THREAD

**Issue by improgress** [junyanz/pytorch-CycleGAN-and-pix2pix#1390]
The scale of my data set is relatively small, and only more than 40 images can be generated each time using the training model..

**Comment by junyanz** [comment]
You can change `num_test`. See this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/test_options.py#L17)

**Comment by improgress** [comment]
thanks a lot! i have done it




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jun-Yan ***@***.***&gt;; 
发送时间: 2022年3月9日(星期三) 下午2:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [junyanz/pytorch-CycleGAN-and-pix2pix] How to generate more samples from trained models? What does the number of samples generated depend on? (Issue #1390)





 
You can change num_test. See this line
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
