### ISSUE TITLE
White blobs in highlights

### ISSUE THREAD

**Issue by rdurland** [junyanz/pytorch-CycleGAN-and-pix2pix#143]
I apologize at the start for my lack of knowledge and amateurism in visual machine learning. After running some test images through a model I trained, I get white blobs in some of the highlights. They wouldn't be so bad if they didn't have such a hard edge.

Is anyone aware of settings that could be changed in training/testing options to combat this? I don't know what additional info would be helpful, but am happy to pass along anything.  Thank you so much in advance!

![4t8a7133_fake_b](https://user-images.githubusercontent.com/4666339/32406360-0c19e3c0-c145-11e7-8547-468fffe97f07.png)
![4t8a7145_fake_b](https://user-images.githubusercontent.com/4666339/32406361-0c2becfa-c145-11e7-9e78-66e4f45b0195.png)

**Comment by junyanz** [comment]
It's hard to tell without further information. 
Which methods are you using? pix2pix or cyclegan? 
What does input/output data look like?

**Comment by rdurland** [comment]
Thank you for the response! I am using cyclegan for this experiment (I may try pix2pix later) for an advanced media studies project about machine editing of photos.  I provided about 2000 interior jpg images straight from a camera and about 2000 jpg images of edited interiors to try and make a model for automatic editing of building interiors.  I didn't change the options except for load and fine size.

The model is very good aside from the weird blobs/blooms. Neither the input or output images have these blobs in the highlight areas and so I'm not sure where it is coming from.

Here are a few of the input images for training:
![4g1a0498](https://user-images.githubusercontent.com/4666339/32411061-4de70e9a-c19f-11e7-98db-c044e3dc8b1f.jpg)
![4t8a1538](https://user-images.githubusercontent.com/4666339/32411062-4df26f88-c19f-11e7-9fe1-08a53948b0bd.jpg)
![4t8a9457](https://user-images.githubusercontent.com/4666339/32411063-4dfe5488-c19f-11e7-8870-e56143997e64.jpg)
![5o6a7955](https://user-images.githubusercontent.com/4666339/32411064-4e0b431e-c19f-11e7-98fd-6473fbe2a3f3.jpg)

And a few of the output images for training:
![003_7l9a1741](https://user-images.githubusercontent.com/4666339/32411065-6893f816-c19f-11e7-939a-3af5c07e8315.jpg)
![03_7l9a7351](https://user-images.githubusercontent.com/4666339/32411066-68a09e40-c19f-11e7-9974-01d4ba832edb.jpg)
![04_7l5a8682](https://user-images.githubusercontent.com/4666339/32411067-68acc8dc-c19f-11e7-91a6-a9e2bc08666a.jpg)
![4g1a1407](https://user-images.githubusercontent.com/4666339/32411068-68b8ad46-c19f-11e7-99ed-e81552696211.jpg)

**Comment by rdurland** [comment]
Sorry should have put this as well: I changed the load size to 800, fine size to 780.  Trained on a Quadro P6000.

**Comment by junyanz** [comment]
The model may try to hallucinate highlights similar to the ones in the output image domain but doesn't succeed to produce the realistic ones. For your applications, I will try to train a model with small window size. (you can set loadSize=800, fineSize=256 or 360). A model with smaller window size may tend to be conservative.

**Comment by rdurland** [comment]
Sorry for the delayed response (my daughter was born early like 12 hours after you graciously responded) but thanks so much.  The load and finesize adjustments worked to get rid of the blobs! I think I need to do some tweaking to the datasets, but this is one problem solved.

**Comment by junyanz** [comment]
Congratulations on your new baby. I am glad that you addressed it.
