### ISSUE TITLE
Google Maps precision

### ISSUE THREAD

**Issue by DerekSunYH** [junyanz/pytorch-CycleGAN-and-pix2pix#1434]
hello,can you tell me the precision of the dataset（Google Maps）that you use to achieve aerial<->maps.
That is, the actual distance represented by a pixel。thank you！

**Comment by junyanz** [comment]
@phillipi

**Comment by taesungp** [comment]
Hello @DerekSunYH , for your information, I happened to collect a larger dataset of sat2map images. 

https://github.com/taesungp/larger-google-sat2maps-dataset

It also has a script to download Google maps images, with [adjustable zoom level](https://github.com/taesungp/larger-google-sat2maps-dataset/blob/main/download_sat2maps.py#L116). Feel free to use this. 

Lastly, the map style is slightly different from our original Google Maps dataset.

**Comment by phillipi** [comment]
I didn't keep track of the actual distance in the original dataset and it would take some effort to track it down. I recommend using @taesungp's instead!

**Comment by DerekSunYH** [comment]
@taesungp @phillipi @junyanz Thank you very much!
