### ISSUE TITLE
facing problem  while following the steps to make the cyclegan works

### ISSUE THREAD

**Issue by isalirezag** [junyanz/pytorch-CycleGAN-and-pix2pix#144]
Can you please help. Im not sure why this is happening....

I noticed the code is changed a lit bit so downloaded the updated version cause I thought it would be more stable. But I face weird errors...
Then I said okay maybe I am doing something wrong, lets just do what mentioned on your github
It even does not work if we do steps that are mentioning on the github
You can try it y yoiurself for small number of images and changing the ngf/ndf.
I make the database to have 5 images in each folder and made ngf/ndg = 5 (i made ngf/ndf = 5 in the base_options.py) 
training went through but testing gives me error:

------------ Options -------------
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ./checkpoints
dataroot: ./datasets/maps
dataset_mode: unaligned
display_id: 1
display_port: 8097
display_winsize: 256
fineSize: 128
gpu_ids: [0]
how_many: 50
init_type: xavier
input_nc: 3
isTrain: False
loadSize: 128
max_dataset_size: inf
model: cycle_gan
nThreads: 2
n_layers_D: 3
name: maps_cyclegan
ndf: 5
ngf: 5
no_dropout: True
no_flip: False
norm: instance
ntest: inf
output_nc: 3
phase: test
resize_or_crop: resize_and_crop
results_dir: ./results/
serial_batches: False
which_direction: AtoB
which_epoch: latest
which_model_netD: basic
which_model_netG: resnet_9blocks

-----------------------------------------------
model [CycleGANModel] was created
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    model.test()
  File "/home/alireza/Desktop/AAA/JPEG/vision/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 101, in test
    self.fake_A = self.fake_A.data
AttributeError: CycleGANModel instance has no attribute 'fake_A'

**Comment by junyanz** [comment]
My bad. It should be fixed now. Could you try it again?

**Comment by isalirezag** [comment]
fixed :)
can i ask what was wrong?

**Comment by junyanz** [comment]
We recently updated the code to fix the gpu memory leak. There were small issues as you reported. 
I just removed the self in this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/a24e24d67d88f75869f447690f7d994fe7d42e2d).
