### ISSUE TITLE
some question about option

### ISSUE THREAD

**Issue by Satyangyl** [junyanz/pytorch-CycleGAN-and-pix2pix#1466]
hi 
  first i want to know that after i combin a and b which dataset mode should i select. aligned or unaligned? and second is why the test result split in half. the last question is my test picture is 2748*2748,i want to get the same size test result, but if i set the scale and crop size to 2748 test.py will error,how should i do

thanks

**Comment by maryam95hallal** [comment]
hello what option you used aligned or unaligned?
