### ISSUE TITLE
Using evaluate.py on Cityscapes

### ISSUE THREAD

**Issue by Woodyet** [junyanz/pytorch-CycleGAN-and-pix2pix#1475]
Hello.

What kind of folder structure does /pytorch-CycleGAN-and-pix2pix/scripts/eval_cityscapes/evaluate.py expect?

I get the following output.
![Screenshot 2022-09-01 005934](https://user-images.githubusercontent.com/43885589/187805133-19bd1fd4-243d-4e71-8453-df314027063e.png)
[evaluation_results.txt](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/files/9465812/evaluation_results.txt)

I know this is a problem picking up the pngs to process as the flag for  --save_output_images 1 was set but yet the folder is empty and the results file is also empty 

Can you please provide some clarification, or if someone has managed to get this evaluation script to run let me know the folder layout of your images.

Thanks.

**Comment by Woodyet** [comment]
Found solution in repo instructions

**Comment by HuXiaokai12138** [comment]
> repo instructions

I would like to know, how did you solve it, I have the same problem on my side and look forward to your reply.

**Comment by Woodyet** [comment]
honestly I have no idea what teh solution was...

I have found [this](https://github.com/Woodyet/Pix2Pix_Auto_Prune/blob/master/Pix2Pix_Auto_Prune/Tensorflow2.5.0/Auto_test.py) script that I used to organise the files for evaluation

Sorry i can't help more

**Comment by Woodyet** [comment]
actually I think [this](https://github.com/phillipi/pix2pix/tree/master#evaluating-labels2photos-on-cityscapes) was the solution

**Comment by HuXiaokai12138** [comment]
> honestly I have no idea what teh solution was...
> 
> I have found [this](https://github.com/Woodyet/Pix2Pix_Auto_Prune/blob/master/Pix2Pix_Auto_Prune/Tensorflow2.5.0/Auto_test.py) script that I used to organise the files for evaluation
> 
> Sorry i can't help more

Thank you very much for your reply
