### ISSUE TITLE
How to set the number of training sets

### ISSUE THREAD

**Issue by fdhyhtt** [junyanz/pytorch-CycleGAN-and-pix2pix#1482]
I'm trying to adopt the idea of CycleGAN on solving a domain mapping problem.
I have 100,000 images to do domain transformation, and about 10,000 images for domain B.
The problem now is that I don't know how much to use as training set A and training set B. I see that the training set A and B in the data set you gave only have more than 1,000 pictures.
I'm very confused right now and hope you guys can give me some advice.
thanks

**Comment by junyanz** [comment]
More data often help. You can also run the same experiment with 10K vs. 1K images and do a comparison.

**Comment by fdhyhtt** [comment]
ok,I will try it
thanks
