### ISSUE TITLE
Adding term to loss, getting "tensors are on different GPUs"

### ISSUE THREAD

**Issue by bernardohenz** [junyanz/pytorch-CycleGAN-and-pix2pix#149]
Hi,

I am trying to enforce that the low-frequency information stays similar after the mapping to another domain (i.e.,  blur(real_A) should be similar to blur(fakeB) ). But I keep getting error when trying to do so. This is my code so far (editing `cycle_gan_model.py`):

```python
class CycleGANModel(BaseModel):
     def initialize(self, opt):
        ......
        #SimpleGaussian is just a nn.Conv
        self.netGaussian = gaussian_model.SimpleGaussian()
        #Initialize weights so the Conv performs a GaussianBlur, also set requires_grad=False
        self.netGaussian.apply(gaussian_model.weights_init_Gaussian)
        #MSE as criterion
        self.criterionLowFreq = torch.nn.MSELoss()

    def forward(self):
        self.real_A = Variable(self.input_A)
        self.real_B = Variable(self.input_B)
        self.blur_real_A = self.netGaussian.forward(self.real_A)
        self.blur_real_B = self.netGaussian.forward(self.real_B)

    def backward_G(self):
        #low-frequency-losses
        loss_lowfreq_A = self.criterionLowFreq(self.netGaussian.forward(fake_B),self.blur_real_A) * lambda_A
        loss_lowfreq_B = self.criterionLowFreq(self.netGaussian.forward(fake_A),self.blur_real_B) * lambda_B
        loss_G = loss_G + loss_lowfreq_A +loss_lowfreq_B
```

But I end up getting `RuntimeError: tensors are on different GPUs` . I've tried to save the blured versions on the forward, but still got the same error.

PS: I only have 1 gpu.

**Comment by SsnL** [comment]
What does your `gaussian_model.SimpleGaussian` look like? Which line did you get the error in?

**Comment by junyanz** [comment]
I wonder if your gaussian_model is on GPU. This [issue](https://github.com/amdegroot/ssd.pytorch/issues/32)  might be related. You can use `get_device()` for debugging.

**Comment by bernardohenz** [comment]
thanks guys. @junyanz answer fixed my problem. Just putting the following just before building the model:
```python
torch.set_default_tensor_type('torch.cuda.FloatTensor')
```

PS: now I've realized that I should have used something like:
```python
if torch.cuda.is_available():
    torch.set_default_tensor_type('torch.cuda.FloatTensor')
```

**Comment by junyanz** [comment]
@bernardohenz  Great!
