### ISSUE TITLE
Transfer learning won't continue unless I also have pretrained discriminator checkpoints

### ISSUE THREAD

**Issue by AriDeutsch** [junyanz/pytorch-CycleGAN-and-pix2pix#1497]
Hi there,

I am trying to use a pretrained monet2photo model which has a similar domain to my own dataset (I theorise as such).
However, when I use the --continue_train flag, the training tries to load G_A, G_B, D_A, and D_B.
monet2photo is the only generator direction available for download as far as I can tell. So what I'm doing is copying latest_net_G from monet2photo into two identical generators which will serve as the pretrained generators for G_A and G_B.
However, the training won't continue unless I also have latest_net_D_A.pth and latest_net_D_B.pth in the checkpoint folder. How can I tell the training to not look for them, and randomly initialise new discriminators?

Thanks for your help! :)

**Comment by taesungp** [comment]
I suppose you can skip loading the discriminator weights by modifying [load_networks()](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/551117b13ff017d852d067a7fa76e138d43dada5/models/base_model.py#L189). Basically, if there is not an existing file at `load_path`, skip loading. Insert the below code block at [line 189](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/551117b13ff017d852d067a7fa76e138d43dada5/models/base_model.py#L189).

```python
if not os.path.exists(load_path):
    continue
```
