### ISSUE TITLE
Testing Sat2map

### ISSUE THREAD

**Issue by reyntors** [junyanz/pytorch-CycleGAN-and-pix2pix#1532]
I trained the model and I test my own aerial image

Why the generate result is bad, here is my output of my own aerial image
![test9_real_A](https://user-images.githubusercontent.com/97606356/212563998-483e496f-3213-445f-bb77-f4fc01119a9d.png)
![test9_fake_B](https://user-images.githubusercontent.com/97606356/212564037-a1f763ce-bc63-48dd-902f-b3801819c832.png)

Then i try to feed train images real_A in your datasets images:

![test12_real_A](https://user-images.githubusercontent.com/97606356/212564072-237965e2-8ba4-467b-9487-ec91b6b20afe.png)
![test12_fake_B](https://user-images.githubusercontent.com/97606356/212564083-2dc53aa7-6cc6-47ba-988a-aeaa8a6ec19f.png)

What is the problem of this testing is there any problem in testing? Or please help me how to proper output. Thank you

**Comment by junyanz** [comment]
You may also need to train a new model on your own aerial images, as different aerial images have different data distributions.
