### ISSUE TITLE
How to only save the conversion results of AtoB when testing?

### ISSUE THREAD

**Issue by yuninn** [junyanz/pytorch-CycleGAN-and-pix2pix#1544]
Thank you for such an excellent project, I want to output only the conversion results of AtoB when testing, not all the results, how can I do this?

**Comment by xuihan** [comment]
hello ,can you tell me how you did it

**Comment by yuninn** [comment]
&nbsp;python test.py --dataroot ___ --name ___ --model test --no_dropout






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "junyanz/pytorch-CycleGAN-and-pix2pix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 中午11:57
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [junyanz/pytorch-CycleGAN-and-pix2pix] How to only save the conversion results of AtoB when testing? (Issue #1544)





 
hello ,can you tell me how you did it

**Comment by xuihan** [comment]
thank you!
