### ISSUE TITLE
Not saving optimizers when saving networks

### ISSUE THREAD

**Issue by AugustLight** [junyanz/pytorch-CycleGAN-and-pix2pix#1555]
Hello, I found that when saving networks in method save_networks(), optimizers params ( self.optimizers.state_dict() ) are not saved to files. Can anyone explain why not save optimizers params ?

**Comment by taesungp** [comment]
There is no reason, and it's really an imperfection of the training code.

**Comment by AugustLight** [comment]
> There is no reason, and it's really an imperfection of the training code.

I got it, thank you for replying!
