### ISSUE TITLE
save output as '.npy' file

### ISSUE THREAD

**Issue by xuihan** [junyanz/pytorch-CycleGAN-and-pix2pix#1557]
hello,
I'm using the cycleGAN model for street view image (.jpg) to mel-spectrogram (.npy, range 0 to 1) conversion.So, I created the trainA folder to store jpg, and the trainB folder to store npy files I would like to know
①If I want the output npy to have the same value range as the input npy([0,1]), what should I do?

**Comment by kuhhg** [comment]
hello
do you know how to make the output save as the ".npy‘’ file format ？
