### ISSUE TITLE
Can your project be used to deblur the defocus image?

### ISSUE THREAD

**Issue by shede1988** [junyanz/pytorch-CycleGAN-and-pix2pix#157]
Can your project be used to deblur the defocus image?

**Comment by junyanz** [comment]
Possibly. But I will not expect it to work better than depth-aware methods. We have used CycleGAN to create shallow depth-of-field [effect](https://junyanz.github.io/CycleGAN/images/photo_enhancement.jpg).

**Comment by shede1988** [comment]
I took a closer look at the pictures [here](https://junyanz.github.io/CycleGAN/images/photo_enhancement.jpg)


It looks as if he's blurring the picture, not making it clear！

**Comment by shede1988** [comment]
But I wanted to make the picture clear

**Comment by junyanz** [comment]
Sure, you need to train a model from blurred images to clear images.
