### ISSUE TITLE
BtoA option not functioning?

### ISSUE THREAD

**Issue by ShangxuanWu** [junyanz/pytorch-CycleGAN-and-pix2pix#159]
Hi, 

I think the 'BtoA' option in torch version is functioning, but in pytorch version it is not.

https://github.com/junyanz/CycleGAN/blob/38a292e40627f18bed433bfb03d2aa025faa265c/models/cycle_gan_model.lua#L109

but in pytorch version, I don't think this is working.

**Comment by junyanz** [comment]
I think that we implemented it for [pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/pix2pix_model.py#L64) and [CycleGAN](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/cycle_gan_model.py#L81).
