### ISSUE TITLE
tensor2im() in util ?

### ISSUE THREAD

**Issue by douhaoexia** [junyanz/pytorch-CycleGAN-and-pix2pix#161]
I can not understand this code in the function util.tensor2im() ——
![default](https://user-images.githubusercontent.com/15043401/33693685-1cb8f92e-db2f-11e7-8b14-b347783a4f3d.png)
Why do we need "transpose" and "+1" ，"/2" ?
Look forward to your explanation.

**Comment by taesung89** [comment]
We are doing conversion between PyTorch Tensors and Numpy-formatted images.

Transpose was needed because in pytorch, channel dimension is the first dim. 

(X+1)/2.0 was needed because the Tensor values are between [-1,1], not [0,1].
