### ISSUE TITLE
losses not getting logged to wandb anymore?

### ISSUE THREAD

**Issue by wilsonjwcsu** [junyanz/pytorch-CycleGAN-and-pix2pix#1616]
Did something change recently? The current version on github isn't logging losses to wandb. Images still show up (real_A, real_B, fake_B), but all the generator, discriminator, and L1 losses are missing. Or do we need to do something to explicitly ask for those to be logged? Thanks.

**Comment by JustinasLekavicius** [comment]
I had the same issue. In my case, it was because I used the --display_id 0 parameter (as I was running the code via Colab). I removed the --display_id 0 parameter, and the loss graphs started login in wandb.

**Comment by wilsonjwcsu** [comment]
Thank you! I was using --display_id=0 to avoid errors about visdom not being installed. (I was hoping to avoid installing it since I'm using wandb instead.)
