### ISSUE TITLE
Hello, why does my own prediction script generate images with blurred edges? But not with your test script, what is the problem?

### ISSUE THREAD

**Issue by czh886** [junyanz/pytorch-CycleGAN-and-pix2pix#1635]
This is the image generated by the prediction code I wrote：
![555555](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/assets/84696414/4f7f2eec-537e-41af-8358-0a98c75a93aa)

This is the image generated by your prediction：

![YY2POX`ZH P~XWBH3`D67$X](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/assets/84696414/204f36f3-104a-4eef-aacf-148228266204)

What's going on here?

**Comment by HolicAnn** [comment]
@czh886 Hello, could I have a look at your prediction code?  There are always problems with the prediction script I wrote myself. Thanks！
