### ISSUE TITLE
how to train for two input image and one output image 

### ISSUE THREAD

**Issue by roshan2024nar** [junyanz/pytorch-CycleGAN-and-pix2pix#1660]
Hello, 
Thank you for the work.

i have a case where i have two input images and which combined give me one output image how can i do this? what part should be modified.

**Comment by tiaoteek** [comment]
Maybe you should Google it first, if you did it ,you will know that this tool is available in datasets ([combine_A_and_B.py](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/datasets/combine_A_and_B.py))

**Comment by roshan2024nar** [comment]
Thank you for the response can you share bit more details or any guide on this ?
