### ISSUE TITLE
Help with Inference

### ISSUE THREAD

**Issue by roshan2024nar** [junyanz/pytorch-CycleGAN-and-pix2pix#1675]
Hello, 

I have  trained a pix2pix model using 

python train.py --dataroot datasets/shadow --name shadow --model pix2pix --direction AtoB --load_size 2048 --crop_size 2048 --checkpoints_dir checkpoints

how can i test on a images without B paths or on a single image by providing path of it

**Comment by catyoyo** [comment]
I have read your question. Is it the case of using a single image for testing when it is not an image pair? The author has already provided a method. Using the single dataset mode is fine.Really, on GitHub, this is the first time I have seen an author who writes such detailed comments and makes module operations so simple. It is really admirable.
See a list of currently available models at ./scripts/download_pix2pix_model.sh
python test.py --dataroot ./datasets/facades/testB/ --name facades_pix2pix --model test --netG unet_256 --direction AtoB --dataset_mode single --norm batch

**Comment by roshan2024nar** [comment]
Thank you for your response i know that author has done a awesome work 
i might missed some details what i want is something where i can provide path of a single image without going through creation of data loaders etc. i tried to mimic the transformation used in the original code but it did not work well

**Comment by noooob-ody** [comment]
maybe create abunch of datasets, the process of just provide the path might be quite hard
