### ISSUE TITLE
GPU Usage becomes 0%

### ISSUE THREAD

**Issue by ShaniGam** [junyanz/pytorch-CycleGAN-and-pix2pix#168]
It seems like after some time of training the CycleGAN doesn't use the GPU - shows 0% on nvidia-smi. Also, some of the processes are killed (I get `[python] <defunct>`), even though that the main process is still running and the losses are printed to the screen.

**Comment by junyanz** [comment]
You should check if you set `--gpu_ids 0`. I also wonder if you are able to run PyTorch [examples](https://github.com/pytorch/examples) on a GPU.

**Comment by SsnL** [comment]
@ShaniGam `[python] <defunct>` are likely to be data loading processes. They are re-created at beginning of each epoch.

**Comment by SsnL** [comment]
Log the data loading time and display_visuals time in train.py. Let’s
identiy the issue first before changing anything.

**Comment by ShaniGam** [comment]
Found it! The problem was that each time it called display_visuals it loaded the entire html file and as it got bigger, this operation took more and more time. Solve the problem by disabling it (just need the images, not the html file).
Thank you!

**Comment by SsnL** [comment]
I'll try to come up with a PR to update that code when I have time :)
