### ISSUE TITLE
RuntimeError: calling resize_ on a tensor that has non-resizable storage.

### ISSUE THREAD

**Issue by electop** [junyanz/pytorch-CycleGAN-and-pix2pix#170]
When I tried to execute pix2pix with pre-trained model, an error occurred in the function of set_input.
The same error occured also when I try to make a model.
For reference, my development environment is the 3 cases below.
. VMware Workstation Pro 14.0 : Ubuntu 16.04 + Anaconda3
. Bare-metal Desktop : Ubuntu 16.04 + Anaconda3 + Geforce GFX 630
. Bare-metal Desktop : Ubuntu 16.04 + Anaconda3 + Geforce GFX 650

[ Command ]
python test.py --dataroot ./datasets/facades/ --which_direction BtoA --model pix2pix --name facades_label2photo_pretrained --dataset_mode aligned --which_model_netG unet_256 --norm batch --gpu_ids -1

[ Log ]
------------ Options -------------
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ./checkpoints
dataroot: ./datasets/facades/
dataset_mode: aligned
display_id: 1
display_port: 8097
display_winsize: 256
fineSize: 256
gpu_ids: []
how_many: 50
init_type: normal
input_nc: 3
isTrain: False
loadSize: 286
max_dataset_size: inf
model: pix2pix
nThreads: 2
n_layers_D: 3
name: facades_label2photo_pretrained
ndf: 64
ngf: 64
no_dropout: False
no_flip: False
norm: batch
ntest: inf
output_nc: 3
phase: test
resize_or_crop: resize_and_crop
results_dir: ./results/
serial_batches: False
which_direction: BtoA
which_epoch: latest
which_model_netD: basic
which_model_netG: unet_256
-------------- End ----------------
CustomDatasetDataLoader
dataset [AlignedDataset] was created
pix2pix
initialization method [normal]
---------- Networks initialized -------------
UnetGenerator(
  (model): UnetSkipConnectionBlock(
    (model): Sequential(
      (0): Conv2d (3, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
      (1): UnetSkipConnectionBlock(
        (model): Sequential(
          (0): LeakyReLU(0.2, inplace)
          (1): Conv2d (64, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
          (2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True)
          (3): UnetSkipConnectionBlock(
            (model): Sequential(
              (0): LeakyReLU(0.2, inplace)
              (1): Conv2d (128, 256, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
              (2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True)
              (3): UnetSkipConnectionBlock(
                (model): Sequential(
                  (0): LeakyReLU(0.2, inplace)
                  (1): Conv2d (256, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
                  (2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                  (3): UnetSkipConnectionBlock(
                    (model): Sequential(
                      (0): LeakyReLU(0.2, inplace)
                      (1): Conv2d (512, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
                      (2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                      (3): UnetSkipConnectionBlock(
                        (model): Sequential(
                          (0): LeakyReLU(0.2, inplace)
                          (1): Conv2d (512, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
                          (2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                          (3): UnetSkipConnectionBlock(
                            (model): Sequential(
                              (0): LeakyReLU(0.2, inplace)
                              (1): Conv2d (512, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
                              (2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                              (3): UnetSkipConnectionBlock(
                                (model): Sequential(
                                  (0): LeakyReLU(0.2, inplace)
                                  (1): Conv2d (512, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
                                  (2): ReLU(inplace)
                                  (3): ConvTranspose2d (512, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
                                  (4): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                                )
                              )
                              (4): ReLU(inplace)
                              (5): ConvTranspose2d (1024, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
                              (6): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                              (7): Dropout(p=0.5)
                            )
                          )
                          (4): ReLU(inplace)
                          (5): ConvTranspose2d (1024, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
                          (6): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                          (7): Dropout(p=0.5)
                        )
                      )
                      (4): ReLU(inplace)
                      (5): ConvTranspose2d (1024, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
                      (6): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                      (7): Dropout(p=0.5)
                    )
                  )
                  (4): ReLU(inplace)
                  (5): ConvTranspose2d (1024, 256, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
                  (6): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True)
                )
              )
              (4): ReLU(inplace)
              (5): ConvTranspose2d (512, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
              (6): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True)
            )
          )
          (4): ReLU(inplace)
          (5): ConvTranspose2d (256, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
          (6): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True)
        )
      )
      (2): ReLU(inplace)
      (3): ConvTranspose2d (128, 3, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
      (4): Tanh()
    )
  )
)
Total number of parameters: 54413955
-----------------------------------------------
model [Pix2PixModel] was created
0000: process image... ['./datasets/facades/test/1.jpg']
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    model.set_input(data)
  File "/home/ubuntu1604/workspace/pytorch-CycleGAN-and-pix2pix/models/pix2pix_model.py", line 67, in set_input
    self.input_A.resize_(input_A.size()).copy_(input_A)
RuntimeError: calling resize_ on a tensor that has non-resizable storage. Clone it first or create a new tensor instead.

**Comment by keineahnung2345** [comment]
Hello, I'm from KupynOrest/DeblurGAN and the same problem just occurred.
I've found a quick hack to the problem of resize_().
Just replace
`self.input_A.resize_(input_A.size()).copy_(input_A)`
into
```
temp = self.input_A.clone()
temp.resize_(input_A.size())
self.input_A = temp
```

**Comment by electop** [comment]
Hello, keineahnung2345
Thank you so much for your reply. Thanks to you, I solved the problem perfectly.
I think this is a problem with the torch code, but it still does not resolve the problem.
For reference, the link below is about the issue of torch code similar to my issue.
https://github.com/pytorch/pytorch/pull/4084

**Comment by keineahnung2345** [comment]
You're welcome. To the problem of pytorch, I think I'm not very familiar with it, so maybe I will leave the problem to the others.

**Comment by SsnL** [comment]
@electop @keineahnung2345 Hi all, PyTorch dev here. The default code should work just fine. What are the PyTorch versions you are using?

**Comment by nabihach** [comment]
I had this issue with PyTorch 0.2.0+. I upgraded to 0.4.0+, which resolved the issue.

**Comment by SsnL** [comment]
@nabihach That is good to hear! Btw, if you see any issues, please try our 0.3 release, as that is more stable.

**Comment by electop** [comment]
@SsnL Thanks for your attention. This problem continued to occur when I used PyTorch 0.3.0 packaged for Anaconda. Accoring to the opinion of Mr. nabihach, I will try it with PyTorch 0.40 and share the result with you.

**Comment by SsnL** [comment]
@electop It could be an issue with the tensor somehow becomes non-resizable. The way this repo does things is not super efficient anyways. So could you try this patch? It should work.

https://gist.github.com/SsnL/351720fb0fd0a43c6fdc370be402cff3

**Comment by electop** [comment]
@SsnL Thanks for your effort. I solved the problem with this patch, too. (e.g : $patch -p1 < resize_.patch)

**Comment by SsnL** [comment]
@electop That's great!

@junyanz If you don't mind, I can submit the above patch as a PR. :)

**Comment by junyanz** [comment]
@SsnL Sure. Thanks a lot.
