### ISSUE TITLE
Out of Memory on GTX 1080

### ISSUE THREAD

**Issue by AllAwake** [junyanz/pytorch-CycleGAN-and-pix2pix#171]
sorry to revisit this subject again but i'm not able to run with fineSize and loadSize higher than 172 when running cycleGAN. I'm using my own datasets but tried to run horse2zebra too... nvidia-smi shows 6481MiB during the training.
I also tried to decrease the poolSize but this didn't help...
which is all unfortunate as i see some remarkable results in texture so would love to have somewhat hi res output. 
Any parameters i can tweak to increase the size of fineSize? Also my original images are pretty high large - should i rescale them myself before they are loaded into the cycleGAN?

**Comment by sigmoidx** [comment]
What is the size of the image? I had the same issue when the database image size is 512x512. I have set --loadSize 256 --fineSize 256 --display_winsize 256 and it fixed the problem. I had a chance to run this on P40 and P100 as well. They are able to load 512x512 sized dataset without a hitch....

**Comment by SsnL** [comment]
Which pytorch version are you using? Do you have cuDNN installed?

**Comment by AllAwake** [comment]
the issue was solved by reinstalling the latest PyTorch
