### ISSUE TITLE
TypeError: cuda() got an unexpected keyword argument 'device_id'

### ISSUE THREAD

**Issue by ilei00** [junyanz/pytorch-CycleGAN-and-pix2pix#173]
When I run train.py in command line,I meet this problem. What shold I do?

(E:\programs\Anaconda\envs\python) D:\cv2\DeblurGAN-master>python train.py --dataroot blurred_sharp/ --continue_train
------------ Options -------------
batchSize: 1
beta1: 0.5
checkpoints_dir: ./checkpoints
continue_train: True
dataroot: blurred_sharp/
dataset_mode: aligned
display_freq: 100
display_id: 1
display_port: 8097
display_single_pane_ncols: 0
display_winsize: 256
epoch_count: 1
fineSize: 256
gan_type: wgan-gp
gpu_ids: [0]
identity: 0.0
input_nc: 3
isTrain: True
lambda_A: 100.0
lambda_B: 10.0
learn_residual: False
loadSizeX: 640
loadSizeY: 360
lr: 0.0001
max_dataset_size: inf
model: content_gan
nThreads: 2
n_layers_D: 3
name: experiment_name
ndf: 64
ngf: 64
niter: 150
niter_decay: 150
no_dropout: False
no_flip: False
no_html: False
norm: instance
output_nc: 3
phase: train
pool_size: 50
print_freq: 100
resize_or_crop: resize_and_crop
save_epoch_freq: 5
save_latest_freq: 5000
serial_batches: False
which_direction: AtoB
which_epoch: latest
which_model_netD: basic
which_model_netG: resnet_9blocks
-------------- End ----------------
CustomDatasetDataLoader
dataset [AlignedDataset] was created
Traceback (most recent call last):
File "train.py", line 56, in 
model = create_model(opt)
File "D:\cv2\DeblurGAN-master\models\models.py", line 11, in create_model
model.initialize(opt)
File "D:\cv2\DeblurGAN-master\models\conditional_gan_model.py", line 34, in initialize
opt.which_model_netG, opt.norm, not opt.no_dropout, self.gpu_ids, use_parallel, opt.learn_residual)
File "D:\cv2\DeblurGAN-master\models\networks.py", line 52, in define_G
netG.cuda(device_id=gpu_ids[0])
TypeError: cuda() got an unexpected keyword argument 'device_id'

**Comment by ilei00** [comment]
when I made a change in network.py ,as following:
if len(gpu_ids) > 0:
print(gpu_ids[0])
netG.cuda(gpu_ids[0]) ########################device_id=gpu_ids[0]

Errors are like this:
THCudaCheck FAIL file=d:\pytorch\pytorch\torch\lib\thc\generic/THCTensorMath.cu line=15 error=48 : no kernel image is available
for execution on the device
Traceback (most recent call last):
File "test.py", line 22, in 
model = create_model(opt)
File "D:\cv2\DeblurGAN-master\models\models.py", line 11, in create_model
model.initialize(opt)
File "D:\cv2\DeblurGAN-master\models\test_model.py", line 19, in initialize
opt.learn_residual)
File "D:\cv2\DeblurGAN-master\models\networks.py", line 54, in define_G
netG.apply(weights_init)
File "E:\programs\Anaconda\envs\python\lib\site-packages\torch\nn\modules\module.py", line 198, in apply
module.apply(fn)
File "E:\programs\Anaconda\envs\python\lib\site-packages\torch\nn\modules\module.py", line 198, in apply
module.apply(fn)
File "E:\programs\Anaconda\envs\python\lib\site-packages\torch\nn\modules\module.py", line 199, in apply
fn(self)
File "D:\cv2\DeblurGAN-master\models\networks.py", line 17, in weights_init
m.bias.data.fill_(0)
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at d:\pytorch\pytorch\torch\lib
\thc\generic/THCTensorMath.cu:15

So I really dont't know how to run this code properly on Windows 10 X64 with cuda 8.0,cudnn6, python 3.6.1,torch0.3.0 after many times' attempts

**Comment by junyanz** [comment]
I guess this cuda runtime error might not be related to this repo. Are you able to run some basic examples from pytorch examples [repo](https://github.com/pytorch/examples)?

**Comment by SsnL** [comment]
windows builds may have some weird issues as it is not as stable. your pytorch is probably not properly installed. see https://github.com/pytorch/pytorch/issues/3865

**Comment by htoyryla** [comment]
I have the same issue running on pytorch 0.3.0 on Ubuntu 14.04 using python 3.6 and cuda 8.0 .

The following works. Looks like something has changed in pytorch?

```
 netG.cuda(gpu_ids[0]) #device_id=gpu_ids[0])
```
