### ISSUE TITLE
One optimizer for both generators

### ISSUE THREAD

**Issue by ShaniGam** [junyanz/pytorch-CycleGAN-and-pix2pix#177]
Why are there two different optimizers for the discriminators and only one for the generators?

**Comment by SsnL** [comment]
Using one for two Ds is equivalent to the current scheme.

**Comment by anjali-chadha** [comment]
Case 1: Using separate optimizers for D_A and D_B
Case 2: Using the same optimizer for D_A and D_B

> Using one for two Ds is equivalent to the current scheme.
@SsnL By the above statement, do you mean Case 1 and Case 2 will give the same results?

Thank you
