### ISSUE TITLE
when running test.py   KeyError: 'unexpected key "model.10.conv_block.6.weight" in state_dict'

### ISSUE THREAD

**Issue by txysq** [junyanz/pytorch-CycleGAN-and-pix2pix#179]

**Comment by NingxiaoJian** [comment]
Hello, I met the same problem as you when I was training. May I ask how you solved it? My training instruction is python train.py --dataroot./datasets/ xx/--name xx_cyclegan --model cycle_gan --batch_size 4

The test is

 python test.py --dataroot./datasets/xx/ --name xx_cyclegan --model cycle_gan
