### ISSUE TITLE
Just a single inference

### ISSUE THREAD

**Issue by ToastMX** [junyanz/pytorch-CycleGAN-and-pix2pix#181]
Whats the best way to make just a input_image output_image inference?

The actual inferencing process in this repository is so nested that i figured i just ask.

**Comment by junyanz** [comment]
I will argue that the test code (only 33 lines) is relatively simple. You can remove the visualization part if you do not need them. Here a few steps to apply a single inference. 
- create a model [Line 15 - Line 17]
- get the data from the data loader. 
- `model.set_input(data)`
- `mode.test()`

**Comment by malinjie-hub** [comment]
where to find the test code (only 33 lines)，thanks！

**Comment by junyanz** [comment]
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/test.py
