### ISSUE TITLE
Discriminator takes AB input

### ISSUE THREAD

**Issue by adrien-le-franc** [junyanz/pytorch-CycleGAN-and-pix2pix#182]
Hi,

It is unclear to me why in pix2pix_model.py in the backward passes the discriminator takes as input the concatenation of A and B.

My guess is that it refers to https://arxiv.org/pdf/1611.07004.pdf 3.1 : is it a mean of conditioning on the observed data A to discriminate B ? Then giving only B as input would be the "unconditional" way ?

thanks for shedding light on this

Adrien

**Comment by phillipi** [comment]
That's right, it's a way to make the discriminator conditional on A. Giving only B as input is indeed the unconditional way.
