### ISSUE TITLE
Training with both unpaired and paired datasets

### ISSUE THREAD

**Issue by bernardohenz** [junyanz/pytorch-CycleGAN-and-pix2pix#185]
Hi, I am using your code for some time (the cyclegan for unpaired training), and I am wondering how difficult it would be to use a mix of unpaired+paired training.

In my problem, I have small paired datasets, and huge number of unpaired images. I am intending to train using unpaired data, while use paired ones to 'guide' the training.
How hard would it be to change your code to support so?

Sorry for the silly question, but I am new to pytorch :P

**Comment by junyanz** [comment]
I think it is possible. You can have L1+  GAN loss for the paired data and cycle-consistency loss + GAN loss for the unpaired data. Looking forward to seeing your results.
