### ISSUE TITLE
Testing 700 X 1100 on Unet architecture results in an error

### ISSUE THREAD

**Issue by PraveerSINGH** [junyanz/pytorch-CycleGAN-and-pix2pix#186]
Hey,

I have a trained a pix2pix model on crops of 512 X 512 through Unet-256.
However while testing, i get an error while testing for 700 X 1100 images.
I was wandering if the code supports validation on only square images or also rectangular images ?
How do you test it for city scape which is usually 1024 X 2048 size.
Thanks in advance.

**Comment by junyanz** [comment]
For cityscapes, we downsampled images to 256p or 512p. The model should work for rectangular images during the test time. Could you tell us the errors you got?
- try to run the model on 512x512 images.  
- try something like 640x1152 (both can be divided by 64)
- not sure if you have enough memory for the large test image.

**Comment by phillipi** [comment]
If I remember correctly, the architecture only works when each downsampling/upsampling layer operates on images/feature maps whose height and width are even numbers. For example, it will work if the dimensions of the input are powers of 2. Rectangular images should be fine. There are a few options for testing on 700x1100 images:
1. Resize to a power of 2
2. Pad or crop to a power of 2
3. Modify the architecture to handle downsampling/upsampling odd numbered dimensions

**Comment by PraveerSINGH** [comment]
Thanks @junyanz and @phillipi  for your quick replies.
I have tested various combinations of test image sizes: 
1> While test images of size 512 X 512 ,1024 X 1024 and 1024 X 2048 works fine
2> Test images of size 640 X 640 or 640 X 1152 don't work and pop up with the underlined error :
[https://gist.github.com/PraveerSINGH/4dd6d113f1a86fbbf376cefef6147d9e](url)
3> Thus only test images of height and width which are multiples of 256 work with the current architecture.

**Comment by junyanz** [comment]
Thanks for reporting the experiments. I guess other generators (e.g., resnet_6blocks or resnet_9blocks) may support more image sizes.

**Comment by addisonklinke** [comment]
>  For example, it will work if the dimensions of the input are powers of 2
> 3. Modify the architecture to handle downsampling/upsampling odd numbered dimensions

I've seen other U-Net implementations that handle arbitrary sizes - why not support that in this library? 1080p dimensions would be a great example for most video-based computer-vision applications
