### ISSUE TITLE
D loss always falls in 0.6-0.7

### ISSUE THREAD

**Issue by Naruto-Sasuke** [junyanz/pytorch-CycleGAN-and-pix2pix#188]
I change the D network, however, the D loss is always between 0.6-0.7.   I wonder whether something is wrong.

**Comment by junyanz** [comment]
Maybe you want to update D more often?

**Comment by Naruto-Sasuke** [comment]
I print out the values of the output of D and find that no matter whether the input is fake or real, it always outputs a value around 0.5.   Then what can I do ?  Complicates the model by stacking more convs or simplify it. Or just update D more often?

**Comment by junyanz** [comment]
Probably you need a stronger D.

**Comment by SsnL** [comment]
@Naruto-Sasuke Also, since D is patchGAN, depending on the dataset, you may have patches that are just as likely to occur in both datasets.

**Comment by yingdiLee** [comment]
Maybe you should change you D structure to make it stronger, like deeper net
