### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by jsjzyzc** [junyanz/pytorch-CycleGAN-and-pix2pix#189]
aniu:pytorch-CycleGAN-and-pix2pix Alan$ python3 test.py --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --which_model_netG unet_256 --which_direction BtoA --dataset_mode aligned --norm batch
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    opt = TestOptions().parse()
  File "/Users/macbook/pytorch-CycleGAN-and-pix2pix/options/base_options.py", line 60, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/cuda/__init__.py", line 223, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

**Comment by junyanz** [comment]
I wonder if you have installed PyTorch (GPU) correctly. Could you run PyTorch demo [code](https://github.com/pytorch/examples)?

**Comment by jsjzyzc** [comment]
I installed pytorch by pip3,

**Comment by junyanz** [comment]
If you install the pytorch with conda, you should use `conda install -c anaconda pytorch-gpu`.

**Comment by jsjzyzc** [comment]
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch-gpu

Current channels:

  - https://conda.anaconda.org/anaconda/osx-64
  - https://conda.anaconda.org/anaconda/noarch
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch

**Comment by SsnL** [comment]
@jsjzyzc use this: `conda install pytorch torchvision -c pytorch`.
