### ISSUE TITLE
Why I meet the problem "out of memory"

### ISSUE THREAD

**Issue by abc8350712** [junyanz/pytorch-CycleGAN-and-pix2pix#193]
I use GTX1070 to train the network.
However I meet a problem:
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1513363039688/work/torch/lib/THC/generic/THCStorage.cu:58
Can you help me?
Thanks in advance.

**Comment by junyanz** [comment]
I think your GPU doesn't have enough memory for the model training. Try to reduce the image size of training images (e.g., `--loadSize 128`, `--fineSize 128`)

**Comment by abc8350712** [comment]
Thank You @junyanz
