### ISSUE TITLE
the value of loss?

### ISSUE THREAD

**Issue by yingdiLee** [junyanz/pytorch-CycleGAN-and-pix2pix#195]
When I train my model ,the order of magnitude of lossG ,lossD and lossCyc are different,lossD is ten to the power of negative 1 while lossG is ten to the power of negative 4. Is it normal or common? I am afraid lossG is too small

**Comment by junyanz** [comment]
Your lossG is a little bit small. Maybe you want to have a stronger D (you can set ndf).

**Comment by yingdiLee** [comment]
@junyanz Thanks for your reply, to have a stronger D I have set ndf to be 64, 128, 256, 512,but the problem still remains, are there any other skills I can try to make a stronger D?
