### ISSUE TITLE
G_A is smaller than D_A

### ISSUE THREAD

**Issue by yingdiLee** [junyanz/pytorch-CycleGAN-and-pix2pix#196]
When I train the CycleGAN, I found that the G_A is much smaller than D_A. In many GAN scenes, DLoss should smaller than GLoss,so it can lead Generator to be better, but in my CycleGAN experiment, it seems different, is it normal?

**Comment by junyanz** [comment]
See this [post](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/195)
