### ISSUE TITLE
convert the PyTorch model to caffemodel

### ISSUE THREAD

**Issue by Devy001** [junyanz/pytorch-CycleGAN-and-pix2pix#197]
I have seen your caffemodel about Cityscapes,can you share the method of converting self trained .pth model by PyTorch to caffemodel? I have tried https://github.com/marvis/pytorch-caffe-darknet-convert but not succeeded, thank you. @phillipi and @junyanz

**Comment by junyanz** [comment]
@tinghuiz  We probably train the cityscapes models with caffe.

**Comment by tinghuiz** [comment]
Yes, the Cityscapes model for evaluating labels2photos was trained using Caffe.
