### ISSUE TITLE
Is there any reasons for using batch_size = 1 in CycleGAN?

### ISSUE THREAD

**Issue by TheIllusion** [junyanz/pytorch-CycleGAN-and-pix2pix#198]
Hi, 
I am a big fan of CycleGAN and its authors. 
what a great work. 

However, I have a question regarding batch size.
Is there any theoretic reasons for using batch_size = 1 in CycleGAN?

Thanks.

**Comment by junyanz** [comment]
We use `--batchSize 1` mainly due to GPU memory concern. You can train a model at a higher resolution.

**Comment by TheIllusion** [comment]
Thanks a lot. 

I'm hoping to see your upcoming works~!

**Comment by devhj014** [comment]
@junyanz  Let say if we parallelize the network across more gpus, will that be helpful?
