### ISSUE TITLE
Extending pix2pix and CycleGan to Hyperspectral images

### ISSUE THREAD

**Issue by 1eesh** [junyanz/pytorch-CycleGAN-and-pix2pix#202]
Hi,

Any advice for someone hoping to extend pix2pix and CycleGan to images with more than three channels in the input/output images ( e.g. : hyperspectral images ) ?

Thanks !

**Comment by junyanz** [comment]
Here are three steps to load your own data. 
- change the parameters `--input_nc` and `--output_nc` to the number of channels in your input/output images.
- Write a custom data loader (It is easy as long as you know how to load your data with python). Here is [one](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/single_dataset.py) we wrote. 
- Add your data_loader to the file [custom_dataset_data_loader.py](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/custom_dataset_data_loader.py#L7)
