### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by CaptainEven** [junyanz/pytorch-CycleGAN-and-pix2pix#203]
An attempt has been made to start a new process before the
  current process has finished its bootstrapping phase.

  This probably means that you are not using fork to start your
  child processes and you have forgotten to use the proper idiom
  in the main module:

      if __name__ == '__main__':
          freeze_support()
          ...

  The "freeze_support()" line can be omitted if the program
  is not going to be frozen to produce an executable.

**Comment by junyanz** [comment]
It seems that the issue is related to WIndows+PyTorch. This [post](https://medium.com/@mackie__m/running-a-cifar-10-image-classifier-on-windows-with-pytorch-9094e29089cd) might help you.

**Comment by CaptainEven** [comment]
Thanks a lot! This is very helpful.

**Comment by IsDling** [comment]
@CaptainEven How do you solve this problem? Can you give me the code that have been changed and could run in windows. Thank you

**Comment by IsDling** [comment]
I have solve this problem. we can set --nThreads to 0. May help someone.

**Comment by CaptainEven** [comment]
@IsDling just warp the train or test code in: if __name__=='__main__': will do the work.

**Comment by IsDling** [comment]
thank you !@CaptainEven

**Comment by IsDling** [comment]
Can you send me your code what have changed to 1558626040@qq.com? There are some wrong after i change.thank you@CaptainEven
