### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by CaptainEven** [junyanz/pytorch-CycleGAN-and-pix2pix#204]
when i run the "python test.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --phase test --no_dropout" command fowllowing the guidance, some error occured as follows:

RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by junyanz** [comment]
See #203.
