### ISSUE TITLE
Function of DataLoader

### ISSUE THREAD

**Issue by rishabhsahrawat** [junyanz/pytorch-CycleGAN-and-pix2pix#205]
I have been following this nice work and implementing it in Pytorch. I am having troubles with the DataLoader function.
In your code, Unaligned or Aligned Class returns a dictionary {'A': A, 'B':B, 'A Paths': A_path, 'B Paths': B_path}, where A has images let say Random landscape Photos and B has paintings of Czenne.
Then we call this Class to give as input to the utils.data.DataLoader(), so this means here dataloader is getting a dictionary as input. When I am following this same idea I am getting 'Keyerror' from DataLoader function. However if I only give A or B as input then it works fine. Please correct me where I could be wrong.
Thank You in advance!

**Comment by junyanz** [comment]
Could you give us more details? Do you have issues with the existing data_loader, or are you trying to implement a new one?

**Comment by rishabhsahrawat** [comment]
Hi, Thanks for the response. Yes I am trying to implement a new one. I am not executing your code, rather I am writing my own based on your work. I am only focusing on CycleGAN. The dataset I am using is czenne2pic. My more direct question from you is, if it is possible to give a dictionary {'A': A, 'B': B} of datasets to pytorch dataloader function?  
Thank you once again!

**Comment by junyanz** [comment]
Sure. You can modify this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/unaligned_dataset.py#L51).
