### ISSUE TITLE
Any idea about dealing with large image size ?

### ISSUE THREAD

**Issue by u10116032** [junyanz/pytorch-CycleGAN-and-pix2pix#206]
First of all, thanks for the wonderful work!! It's really awesome that can transfer cross domain without paired training examples!!

I'm wondering that what is the biggest image size you've tried? Since the application of GAN nowadays could only perform on small image size like 256x256 or 512x512 (correct me if I'm wrong).

But I want to apply this cross domain transfer on high resolution images like 4096x4096 with one GPU (I use TitanX), if I just divide it into several small patches, though it performs well on each patch but they don't show consistent while combine them into the whole image.

I will appreciate if you can give me some advices.

Thanks!!

**Comment by junyanz** [comment]
It's possible to run CycleGAN on 1024p images. The model is fully convolutional. This means that even if you train a model on 360x360 images, you can apply the model directly (without patch by patch) on 1024 images. We use `--loadSize 1024 --fineSize 360` during training, and `--loadSize 1024 --fineSize 1024` during test. Not sure about 4096.

**Comment by u10116032** [comment]
Nice point! I missed that the generator is just a model with fully convolutional layers.
Thanks for your kindly help!!!!!

**Comment by SvenShade** [comment]
On that point; is it possible to test on rectangular images? The images I'm training on are 256x256, but I'd like to test on images of the same width but arbitrary length. Thanks!

**Comment by mrluker** [comment]
@u10116032 @junyanz 

I have been able to generate test images at 2800x1880 using a 1070 (8gb VRAM) using --model cycle_gan --dataset_mode unaligned instead of --model test --dataset_mode single

using --model test appears to take more VRAM and thus can only run at a lower resolution

[(https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/236)]

**Comment by SpongeYao** [comment]
Hi, I'm confused with "**We use --loadSize 1024 --fineSize 360 during training, and --loadSize 1024 --fineSize 1024 during test.**" I see the arguments, _loadSize_ & _fineSize_, will be input to function 'load_train_data', and the image will be resize to _loadSize_ at first, and then it will be cropped according to _fineSize_. I cannot understand the meaning that training with loadSize=1024 & fineSize=360 because it only use the 360x360 parts inside the 1024x1024 image during training. Is it the case for some special data?

**Comment by junyanz** [comment]
The names are recently changed to `load_size` and `crop_size`. 
1. `load_size`. The goal is to resize all the training images to the same size. 
2. `crop_size`. Random cropping is a data argumentation that can create more training data points per input image.

**Comment by SpongeYao** [comment]
Crystal clear!! Thank you

**Comment by amrbenattia** [comment]
Hi @junyanz  what if the image is not square? I am testing size of 78x128 then the output size become 128x128. the fake image is stretched ? what is the reason of this? and how to keep the original size after testing. 
Thanks in advance

**Comment by junyanz** [comment]
You can a different `preprocess` option. (e.g., `scale_width`) See this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L49) for more details.

**Comment by amrbenattia** [comment]
@junyanz  Thanks so much However the width size must be multiple of 4 hence the output width size change a bit to be 4 times multiplication

**Comment by junyanz** [comment]
Yeah, it will change a bit. You can resize it back to the original size by yourself.

**Comment by wincle** [comment]
Hi @junyanz  ,if the training data is human face with the size 1024*1024, is it okay to crop it with 360*360 ? What will happened if crops the part of one face(eg, one mouth or one eye)?

**Comment by junyanz** [comment]
In your case, 360x360 might not be enough. Another idea would be to train a separate generator for each facial component. See this [paper](https://adoberesearch.ctlprojects.com/wp-content/uploads/2018/04/CVPR2018_Paper3623_Chang.pdf) for more details.

**Comment by wincle** [comment]
> In your case, 360x360 might not be enough. Another idea would be to train a separate generator for each facial component. See this [paper](https://adoberesearch.ctlprojects.com/wp-content/uploads/2018/04/CVPR2018_Paper3623_Chang.pdf) for more details.

Amazing Idea!

**Comment by sobhani** [comment]
I do have an image of size 2000*2000 ...and I would like to try with this size.. what do you recommend to consider for the load_size and fine_size??

**Comment by sobhani** [comment]
> The names are recently changed to `load_size` and `crop_size`.
> 
> 1. `load_size`. The goal is to resize all the training images to the same size.
> 2. `crop_size`. Random cropping is a data argumentation that can create more training data points per input image.

I do have an image of size 2000*2000 ...and I would like to try with this size.. what do you recommend to consider for the load_size and fine_size??

**Comment by junyanz** [comment]
It depends on your data. Maybe you could try `--load_size 2000` and `--crop_size 400`. Please see our [docs](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#trainingtesting-with-high-res-images) for more details.

**Comment by sobhani** [comment]
> It depends on your data. Maybe you could try `--load_size 2000` and `--crop_size 400`. Please see our [docs](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#trainingtesting-with-high-res-images) for more details.


Thanks for your reply and sorry to ask again..I'm just trying to understand ..my image size is all 2000*2000 and as it is mentioned in ur doc, I did first try the load size of 1024 and the crop size of 360 ..it works till it reaches to the print_freq, where it wants to save one sample and it gives the error of  **ValueError: Cannot feed value of shape (1, 256, 256, 6) for Tensor 'real_A_and_B_images:0', which has shape '(?, 360, 360, 6)'**.. can you please kindly help me with that?

**Comment by junyanz** [comment]
Which generator `--netG` are you using? `unet_256` only supports 256x256 inputs. You may want to use `resnet_9blocks`.

**Comment by sobhani** [comment]
> Which generator `--netG` are you using? `unet_256` only supports 256x256 inputs. You may want to use `resnet_9blocks`.

with resnet_9blocks I have that error, however I did change this line of code in **model.py**
`sample_images = [load_train_data(batch_file, is_testing=True) for batch_file in batch_files]`
to the following one
 `sample_images = [load_train_data(batch_file,load_size=1024, fine_size=360 ) for batch_file in batch_files]`

is that right????

**Comment by junyanz** [comment]
Not sure if we have a file called `model.py` and a function called `load_train_data`.
