### ISSUE TITLE
CUDNN_STATUS_BAD_PARAM with output_nc=1

### ISSUE THREAD

**Issue by adrianalbert** [junyanz/pytorch-CycleGAN-and-pix2pix#21]
Hi,

I'm testing the Cycle GAN code using 3-channel input data (A) and 1-channel output data (B). I always get the following error message: 

RuntimeError: CUDNN_STATUS_BAD_PARAM

However this works fine when I set output_nc to 3. 

I can't find any place in the code where output_nc is hard-coded to 3, so I'm guessing this must be a CUDNN issue? Is there any reason you can think of why a 1-channel output should not work with the current architecture in Cycle GAN?

Thanks! 

The full trace is below:
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    model.optimize_parameters()
  File "/home/nbserver/urbanization-patt
erns/models/pytorch-CycleGAN-and-pix2pix
/models/cycle_gan_model.py", line 159, i
n optimize_parameters
    self.backward_G()
  File "/home/nbserver/urbanization-patt
erns/models/pytorch-CycleGAN-and-pix2pix
/models/cycle_gan_model.py", line 141, i
n backward_G
    self.fake_A = self.netG_B.forward(se
lf.real_B)
  File "/home/nbserver/urbanization-patt
erns/models/pytorch-CycleGAN-and-pix2pix
/models/networks.py", line 170, in forwa
rd
    return nn.parallel.data_parallel(sel
f.model, input, self.gpu_ids)
  File "/usr/local/lib/python2.7/dist-pa
ckages/torch/nn/parallel/data_parallel.p
y", line 105, in data_parallel
    outputs = parallel_apply(replicas, i
nputs, module_kwargs)
  File "/usr/local/lib/python2.7/dist-pa
ckages/torch/nn/parallel/parallel_apply.
py", line 46, in parallel_apply
    raise output
RuntimeError: CUDNN_STATUS_BAD_PARAM

**Comment by lucy3** [comment]
In base_options, isn't the default for output_nc 3?

**Comment by junyanz** [comment]
Yes, the default output_nc = 3, you need to set --output_nc 1 for 1 channel images. I think you probably also have to modify set_input for grayscale images.

**Comment by yeguixin** [comment]
I also encounter the similar error "RuntimError: SUDNN_STATUS_BAD_PARAM". When I set --loadSize 160 and --fineSize 160 during training pix2pix model. Both the input and output images are 3-channel.
Also, When adding the parameters --resize_or_crop scale_width (python train.py --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --which_model_netG unet_256 --which_direction BtoA --lambda_A 100 --dataset_mode aligned --use_dropout --no_lsgan --loadSize 160 --fineSize 160 --resize_or_crop scale_width), the error as follows: 
-------------------------------------------------------------------------------
CustomDatasetDataLoader
dataset [AlignedDataset] was created
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    data_loader = CreateDataLoader(opt)
  File "/home/gxy/program/pytorch-CycleGAN-and-pix2pix/data/data_loader.py", line 6, in CreateDataLoader
    data_loader.initialize(opt)
  File "/home/gxy/program/pytorch-CycleGAN-and-pix2pix/data/custom_dataset_data_loader.py", line 30, in initialize
    self.dataset = CreateDataset(opt)
  File "/home/gxy/program/pytorch-CycleGAN-and-pix2pix/data/custom_dataset_data_loader.py", line 20, in CreateDataset
    dataset.initialize(opt)
  File "/home/gxy/program/pytorch-CycleGAN-and-pix2pix/data/aligned_dataset.py", line 18, in initialize
    assert(opt.resize_or_crop == 'resize_and_crop')
AssertionError
-------------------------------------------------------------------------------------------------------------------
Note that the size of train images is 160*70pix

**Comment by taesung89** [comment]
Hi @yeguixin, 

unfortunately, for aligned_dataset.py, we did not implement modes other than 'resize_and_crop'. Feel free to implement your own. ;-)

**Comment by yeguixin** [comment]
Thanks a lot.
