### ISSUE TITLE
why you use the reflect pad ? 

### ISSUE THREAD

**Issue by taki0112** [junyanz/pytorch-CycleGAN-and-pix2pix#211]
Hi 
why you use the `reflect pad` instead of `zero pad` ? 
Does this affect performance a lot?

**Comment by junyanz** [comment]
It helps reduce the boundary artifacts in the cyclegan training. See this twitter [discussion](https://twitter.com/karpathy/status/720642926070530049) for more details.

**Comment by John1231983** [comment]
Great. Why not add pad in the unet network? Thanks

**Comment by junyanz** [comment]
You are free to add them. We follow the U-net implementation in the original pix2pix paper.
