### ISSUE TITLE
UpsampleConvLayer instead of Conv_Transpose

### ISSUE THREAD

**Issue by beniroquai** [junyanz/pytorch-CycleGAN-and-pix2pix#217]
Hey, I'm facing the problem of high frequency artifacts also called "checkerboard" artifacts (distill.pub/2016/deconv-checkerboard/). 
I've successfully added this feature to the ResNET Generator and wanted to do the same for the UNET to check whether it works, but I'm not exactly certain how I should do this. 

I've added this layer: 
```
class UpsampleConvLayer(torch.nn.Module):
          def __init__(self, in_channels, out_channels, kernel_size, stride, upsample=None):
              super(UpsampleConvLayer, self).__init__()
              self.upsample = upsample
              if upsample:
                  self.upsample_layer = torch.nn.Upsample(scale_factor=upsample)
              reflection_padding = kernel_size // 2
              self.reflection_pad = torch.nn.ReflectionPad2d(reflection_padding)
              self.conv2d = torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride)

          def forward(self, x):
              x_in = x
              if self.upsample:
                  x_in = self.upsample_layer(x_in)
              out = self.reflection_pad(x_in)
              out = self.conv2d(out)
              return out
```

and try to call it in the Unet-Block like that:

```
# Defines the submodule with skip connection.
# X -------------------identity---------------------- X
#   |-- downsampling -- |submodule| -- upsampling --|
class UnetSkipConnectionBlock(nn.Module):
    def __init__(self, outer_nc, inner_nc, input_nc=None,
                 submodule=None, outermost=False, innermost=False, norm_layer=nn.BatchNorm2d, use_dropout=False):
        super(UnetSkipConnectionBlock, self).__init__()
        self.outermost = outermost
        self.innermost = innermost
        if type(norm_layer) == functools.partial:
            use_bias = norm_layer.func == nn.InstanceNorm2d
        else:
            use_bias = norm_layer == nn.InstanceNorm2d
        if input_nc is None:
            input_nc = outer_nc
        downconv = nn.Conv2d(input_nc, inner_nc, kernel_size=4,stride=2, padding=1, bias=use_bias)
        downrelu = nn.LeakyReLU(0.2, True)
        downnorm = norm_layer(inner_nc)
        uprelu = nn.ReLU(True)
        upnorm = norm_layer(outer_nc)

        if outermost:
            upconv = UpsampleConLayer(inner_nc * 2, outer_nc, kernel_size=2, stride=1, upsample=2)
            
            #upconv = nn.ConvTranspose2d(inner_nc * 2, outer_nc, kernel_size=4, stride=2,padding=1)
            down = [downconv]
            up = [uprelu, upconv, nn.Tanh()]
            model = down + [submodule] + up
        elif innermost:
            upconv = UpsampleConLayer(inner_nc, outer_nc, kernel_size=2, stride=1, upsample=2)
            #upconv = nn.ConvTranspose2d(inner_nc, outer_nc, kernel_size=4, stride=2,padding=1, bias=use_bias)
            down = [downrelu, downconv]
            up = [uprelu, upconv, upnorm]
            model = down + up
        else:
            upconv = UpsampleConLayer(inner_nc * 2, outer_nc, kernel_size=2, stride=1, upsample=2)
            #upconv = nn.ConvTranspose2d(inner_nc * 2, outer_nc,kernel_size=4, stride=2,padding=1, bias=use_bias)
            down = [downrelu, downconv, downnorm]
            up = [uprelu, upconv, upnorm]

            if use_dropout:
                model = down + [submodule] + up + [nn.Dropout(0.5)]
            else:
                model = down + [submodule] + up

        
        self.model = nn.Sequential(*model)
```

I'm getting dimensions errors:

`RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 3 and 2 in dimension 2 at /media/useradmin/Data/Benedict/PyTORCH_SRC/pytorch/aten/src/THC/generic/THCTensorMath.cu:111
`
. I'm pretty sure, that there is an easier fix for that, but I'm not that familiar with Pytorch unfortunately. Does anybody have a quick-fix for this? 

Thanks in advance!

**Comment by beniroquai** [comment]
Ok. Found my error. Had to change the filter dimensions:

```
class UnetSkipConnectionBlock(nn.Module):
    def __init__(self, outer_nc, inner_nc, input_nc=None,
                 submodule=None, outermost=False, innermost=False, norm_layer=nn.BatchNorm2d, use_dropout=False):
        super(UnetSkipConnectionBlock, self).__init__()
        self.outermost = outermost
        self.innermost = innermost
        if type(norm_layer) == functools.partial:
            use_bias = norm_layer.func == nn.InstanceNorm2d
        else:
            use_bias = norm_layer == nn.InstanceNorm2d
        if input_nc is None:
            input_nc = outer_nc
        downconv = nn.Conv2d(input_nc, inner_nc, kernel_size=4,
                             stride=2, padding=1, bias=use_bias)
        downrelu = nn.LeakyReLU(0.2, True)
        downnorm = norm_layer(inner_nc)
        uprelu = nn.ReLU(True)
        upnorm = norm_layer(outer_nc)

        if outermost:
            upconv = UpsampleConLayer(inner_nc * 2, outer_nc, kernel_size=3, stride=1, upsample=2)      
            #upconv = nn.ConvTranspose2d(inner_nc * 2, outer_nc, kernel_size=4, stride=2,padding=1, bias=use_bias)
            down = [downconv]
            up = [uprelu, upconv, nn.Tanh()]
            model = down + [submodule] + up
        elif innermost:
            upconv = UpsampleConLayer(inner_nc, outer_nc, kernel_size=3, stride=1, upsample=2)
            #upconv = nn.ConvTranspose2d(inner_nc, outer_nc,kernel_size=4, stride=2,padding=1, bias=use_bias)
            down = [downrelu, downconv]
            up = [uprelu, upconv, upnorm]
            model = down + up
        else:
            upconv = UpsampleConLayer(inner_nc * 2, outer_nc, kernel_size=3, stride=1, upsample=2)
            #upconv = nn.ConvTranspose2d(inner_nc * 2, outer_nc,kernel_size=4, stride=2,padding=1, bias=use_bias)
            down = [downrelu, downconv, downnorm]
            up = [uprelu, upconv, upnorm]

            if use_dropout:
                model = down + [submodule] + up + [nn.Dropout(0.5)]
            else:
                model = down + [submodule] + up

        self.model = nn.Sequential(*model)

    def forward(self, x):
        if self.outermost:
            return self.model(x)
        else:
            return torch.cat([x, self.model(x)], 1)
```

**Comment by nawashy** [comment]
Hi there,
Thanks for sharing the code, when I try to run it an error message is displayed as follows
AttributeError: 'UpsampleConvLayer' object has no attribute 'weight'

not sure how to resolve that

**Comment by beniroquai** [comment]
Hey, 

in networks.py you're initializing all the weights this way:
```
def weights_init_normal(m):
    classname = m.__class__.__name__
    # print(classname)
    if classname.find('Conv') != -1:
        init.normal(m.weight.data, 0.0, 0.02)
    elif classname.find('Linear') != -1:
        init.normal(m.weight.data, 0.0, 0.02)
    elif classname.find('BatchNorm2d') != -1:
        init.normal(m.weight.data, 1.0, 0.02)
        init.constant(m.bias.data, 0.0)
```

Thus you're looking for all entries with "conv" .. you could rename `UpsampleConvLayer` to `UpsampleConLayer`. Should work :) - Hope that helps!

**Comment by fantasy-fish** [comment]
> Ok. Found my error. Had to change the filter dimensions:
> 
> ```
> class UnetSkipConnectionBlock(nn.Module):
>     def __init__(self, outer_nc, inner_nc, input_nc=None,
>                  submodule=None, outermost=False, innermost=False, norm_layer=nn.BatchNorm2d, use_dropout=False):
>         super(UnetSkipConnectionBlock, self).__init__()
>         self.outermost = outermost
>         self.innermost = innermost
>         if type(norm_layer) == functools.partial:
>             use_bias = norm_layer.func == nn.InstanceNorm2d
>         else:
>             use_bias = norm_layer == nn.InstanceNorm2d
>         if input_nc is None:
>             input_nc = outer_nc
>         downconv = nn.Conv2d(input_nc, inner_nc, kernel_size=4,
>                              stride=2, padding=1, bias=use_bias)
>         downrelu = nn.LeakyReLU(0.2, True)
>         downnorm = norm_layer(inner_nc)
>         uprelu = nn.ReLU(True)
>         upnorm = norm_layer(outer_nc)
> 
>         if outermost:
>             upconv = UpsampleConLayer(inner_nc * 2, outer_nc, kernel_size=3, stride=1, upsample=2)      
>             #upconv = nn.ConvTranspose2d(inner_nc * 2, outer_nc, kernel_size=4, stride=2,padding=1, bias=use_bias)
>             down = [downconv]
>             up = [uprelu, upconv, nn.Tanh()]
>             model = down + [submodule] + up
>         elif innermost:
>             upconv = UpsampleConLayer(inner_nc, outer_nc, kernel_size=3, stride=1, upsample=2)
>             #upconv = nn.ConvTranspose2d(inner_nc, outer_nc,kernel_size=4, stride=2,padding=1, bias=use_bias)
>             down = [downrelu, downconv]
>             up = [uprelu, upconv, upnorm]
>             model = down + up
>         else:
>             upconv = UpsampleConLayer(inner_nc * 2, outer_nc, kernel_size=3, stride=1, upsample=2)
>             #upconv = nn.ConvTranspose2d(inner_nc * 2, outer_nc,kernel_size=4, stride=2,padding=1, bias=use_bias)
>             down = [downrelu, downconv, downnorm]
>             up = [uprelu, upconv, upnorm]
> 
>             if use_dropout:
>                 model = down + [submodule] + up + [nn.Dropout(0.5)]
>             else:
>                 model = down + [submodule] + up
> 
>         self.model = nn.Sequential(*model)
> 
>     def forward(self, x):
>         if self.outermost:
>             return self.model(x)
>         else:
>             return torch.cat([x, self.model(x)], 1)
> ```

I was wondering why you used kernel_size=3 instead of the original kernel_size(k=4) here.
