### ISSUE TITLE
 when  training,how many patches is cropped from every  input

### ISSUE THREAD

**Issue by IsDling** [junyanz/pytorch-CycleGAN-and-pix2pix#218]
when it's training, set loadSize to 286 and fineSize to 256, my question is that how many patches that is 256 * 256 is cropped from every  input

**Comment by junyanz** [comment]
One patch per image.

**Comment by IsDling** [comment]
thanks for help.And Can different loadSize and fineSIze change the number of patches from per image?It's that one patch from per image however the setting of loadSize and fineSize?

**Comment by junyanz** [comment]
Yes, we first load an image with loadSize and then crop a patch with fineSize. You can modify the data loader to support multiple patches cropping.

**Comment by IsDling** [comment]
thank you
