### ISSUE TITLE
Training CycleGAN on a full 12GB gpu is consuming only 3.5GB of the memory and training is very slow!

### ISSUE THREAD

**Issue by charan223** [junyanz/pytorch-CycleGAN-and-pix2pix#219]
Why is the memory consumption low? 
What is required GPU configuration to train?
What are the recommended number of iterations to train for datasets of size 10k images?
How much is the expected time to train?
Is there any way to increase the training speed?
Is there any way to regulate gpu memory?

**Comment by Matlmr** [comment]
I have the same problem of memory consumption. Did you figure anything out?

**Comment by junyanz** [comment]
We currently use `batchSize=1`. You can use a larger batchSize, which also depends on the size of your GPU memory.

**Comment by mrluker** [comment]
@charan223 @Matlmr 

As @junyanz said, you can increase the batch size to a higher number and find the limits of how high you can go to start a test.

Alternatively, I have typically trained at higher resolutions for a better result and more RAM utilization.

**Comment by junyanz** [comment]
What does "50-100 frames" mean? Is it a video or an image? Training a CycleGAN on 256x256 images requires about 8 GB memory.
