### ISSUE TITLE
potential bug

### ISSUE THREAD

**Issue by cddlyf** [junyanz/pytorch-CycleGAN-and-pix2pix#22]
In current release version, there is one potential bug when the gpu_ids is not 0,  because some tensor is initialized with "torch.cuda.Tensor(*shape)"(self.tensor(*shape)) like in the implementation of GANLoss. I guess it should be initialized in  gpu0 by default,  that is to say, when the model is not on gpu0,  below errors will happen.
`Some of weight/gradient/input tensors are located on different GPUs`

one simple fix solution might be to add "torch.cuda.device(self.opt.gpu_ids[0])" in parse function of base_options class.

**Comment by junyanz** [comment]
I am aware of the problem. I often just use `CUDA_VISIBLE_DEVICES=1,2` to avoid it. As you suggested, I tried to add `torch.cuda.device(self.opt.gpu_ids[0])` to the `base_options.py`. But I still got the same errors. Have you resolved it?

**Comment by viridyu** [comment]
Hi, have you solved this problem?

**Comment by junyanz** [comment]
It should be fixed in the latest version.
