### ISSUE TITLE
Bug in loading aligned training data

### ISSUE THREAD

**Issue by hazirbas** [junyanz/pytorch-CycleGAN-and-pix2pix#222]
The following line will cause artifacts in the input (left edge) /output (right edge) as aligned image is upsampled with Bicubic interpolation:

https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/079da5c02fd99ef35d7cad0e20c2924b7c2bcffd/data/aligned_dataset.py#L21

**Comment by junyanz** [comment]
Interesting. What is the size of your original image? What is the loadSize in your experiment? @SsnL might know the solution.

**Comment by SsnL** [comment]
Yeah, that’s possible. Maybe we can switch to first splitting and them
upsampling.

**Comment by junyanz** [comment]
That makes sense. Let's see if this [commit](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/6718e13d5ded5f630cba3a8eab7e29fc7a7455e2) will fix the issue. @hazirbas @SsnL
