### ISSUE TITLE
How to extract the intermediate layers' outputs in UnetGenerator?

### ISSUE THREAD

**Issue by jrenbme** [junyanz/pytorch-CycleGAN-and-pix2pix#227]
Hi, I'm doing an image to image transfer task(gray images) using Unet. The last several rows in my final outputs are always totally black(after Tanh() is -1) . Thus I would like to see the intermediate outputs to find out what causes this problem. But I don't know how to get them with register_forward_hook() or other methods. Since in this implementation layers don't have a specific name. Any ideas to deal with it?

**Comment by junyanz** [comment]
For grayscale images, you may want to set `--input_nc 1 --output_nc 1`. For the intermediate features, you probably need to implement register_forward_hook function and add names to each module in the Unet.
