### ISSUE TITLE
Some issue with the custom data loader

### ISSUE THREAD

**Issue by shirishr** [junyanz/pytorch-CycleGAN-and-pix2pix#228]
@junyanz,

When I run:    

**python train.py --dataroot ./datasets/horse2zebra --name my_cyclegan --model cycle_gan --loadSize 64 --nThreads 0 --gpu_ids 0 --dataset_mode unaligned** 

I get an error **Illegal instruction (core dumped)**

It seems that my cpu does not support dataset.getitem kind of instruction.

I am on Ubuntu 16.04, pytorch 3.1, cuda 9.0 cuDnn 7.1

Can you suggest a workaround?

**Comment by junyanz** [comment]
Not sure if this is related to our code. This [post](https://github.com/pytorch/pytorch/issues/2714) might be related. You may also want to try to run some PyTorch [examples](https://github.com/pytorch/examples/tree/master/dcgan).

**Comment by shirishr** [comment]
Will try...it could also be shared memory issue. I had made this work in my windows machine a few months ago.

**Comment by shirishr** [comment]
I think the issue occurred because of attempted installations of pytorch via conda as well as via via pip from a wheel. I cleaned everything up and got it working again. Thanks. 
I am now on I am on Ubuntu 16.04, pytorch 3.1, cuda 9.0 cuDnn 7.0.4

**Comment by MdAshrafulAlam** [comment]
@shirishr how to clean up? could you please tell me?

**Comment by shirishr** [comment]
@MdAshrafulAlam,
I uninstalled and reinstalled everything
