### ISSUE TITLE
RuntimeError: DataLoader worker (pid 2618) is killed by signal: Killed.

### ISSUE THREAD

**Issue by JuneLJQ** [junyanz/pytorch-CycleGAN-and-pix2pix#232]
I run the program with CPU (memory 2G) on the virtual machine and server, and I find every time I always have the same mistake. I don't know if it's because I use CPU instead of GPU to run the program. I want to know what parameters I need to modify if I run this program with CPU, or what configuration the server needs.（the following picture shows the mistake I met.）
![image](https://user-images.githubusercontent.com/37524234/38225225-7ec8a1f2-3726-11e8-8c57-67057142b1d3.png)

**Comment by junyanz** [comment]
I am not sure if our program can run on a CPU with 2G memory. I recommend a GPU with more than 6 GB memory.
