### ISSUE TITLE
How to use chekpoint files ?

### ISSUE THREAD

**Issue by omg777** [junyanz/pytorch-CycleGAN-and-pix2pix#233]
I trained CycleGAN with my own dataset.
and I have 
**latest_net_D_A.pth** , **latest_net_D_B.pth**
**latest_net_G_A.pth** and **latest_net_G_B.pth** files in checkpoints/AtoB/

How can I test with my different dataset ?
python test.py --dataroot  ...?
(I already read README file, but I don`t have latest_net_G.pth file)

**Comment by junyanz** [comment]
It depends. 
- case I (apply both G_A and G_B). See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#cyclegan-traintest).  Assume that you have training data under `./dataset/`, you can add your new dataset as a subdirectory (e.g.,  `../dataset/valA`  and `../dataset/valB`)  and set the phase as `--phase val`.
- case II (only apply one model G_A). See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-cyclegan) for more details about how to apply a single pretrained model.

**Comment by omg777** [comment]
@junyanz 
In case ll, I tried below command,
`python test.py --dataroot database/trainA --checkpoints_dir ./checkpoints/ --name AtoB --no_dropout --model test --dataset_mode single --loadSize 256
`
then, FileNotFoundError : './checkpoints/AtoB/latest_net_G.pth'
because I don`t have latest_net_G.pth file.
I have only **latest_net_D_A.pth , latest_net_D_B.pth
latest_net_G_A.pth and latest_net_G_B.pth** files.

**Comment by junyanz** [comment]
You need to rename it to `latest_net_G.pth` manually. I am thinking about adding a new flag `checkpoint_path` so that people can specify the path directly. I will add it once I have time.

**Comment by phyuphyuthaw** [comment]
Can I train and test at the same time? I have got the same error as omg777.  I am a little confused how to rename manually.

**Comment by paviddavid** [comment]
@junyanz I have `latest_net_{D/G}_{A/B}.pth
`
If I want to translate images in testB folder (to domain A), which` .pth` file should be renamed to `latest_net_G.pth` ? 

Does latest mean the last epoch? an furthermore every 5th epoch another model is output? 

maybe @phyuphyuthaw or @omg777 figured out which model must be renamed? 

Thanks in advance and kind regards

**Comment by junyanz** [comment]
1. use `_B` models.
2. Yes. The code will save intermediate checkpoints every 5 epoch.

**Comment by niraekjs** [comment]
Hey junyanz, any update on the checkpoint_path addition?

**Comment by FCgogogo** [comment]
how to reslove the question：No such file or directory: './checkpoints/horse2zebra_pretrained/latest_net_G.pth'？

**Comment by VaJavorek** [comment]
> You need to rename it to `latest_net_G.pth` manually. I am thinking about adding a new flag `checkpoint_path` so that people can specify the path directly. I will add it once I have time.

This is not implemented yet am I right? So for now just manual renaming? Then it works for me.
