### ISSUE TITLE
Test using "--model test" takes more VRAM compared with Testing using "--model cyclegan"

### ISSUE THREAD

**Issue by mrluker** [junyanz/pytorch-CycleGAN-and-pix2pix#236]
#### ```--model test --dataset_mode single``` VS. ```--model cycle_gan --dataset_mode unaligned```

@junyanz 
I am able to run images at **4800px*3,200px** with ```--model cycle_gan --dataset_mode unaligned``` but only able to run images at **1500px*1000px** with ```--model test --dataset_mode single``` Both use 22GB of VRAM on a NVIDIA Quadro P6000 that has 24gb of VRAM.

### **--model cycle_gan** _vs._ **--model test:**
**15.36**MegaPixels vs **1.5**MegaPixels

This confuses me and I would like to find out why ```--model cycle_gan --dataset_mode unaligned``` generates more outputs at a higher resolution using the same amount of VRAM when ```--model test --dataset_mode single``` generates fewer outputs and tops out VRAM at a much lower resolution.

### **Results using ```--model cycle_gan --dataset_mode unaligned```**
**_loadSize:_** 4800px
**_fineSize_** 4800px

**_Command Given:_** ```time python test.py --dataroot ./datasets/"lolLuke46" --name utahRaptor_64_256 --model cycle_gan --gpu_ids 0 --dataset_mode unaligned --loadSize 3000 --fineSize 3000 --resize_or_crop scale_width --which_epoch latest --no_dropout```

**_Ram Usage_** 21968MiB

**_Outputs Received:_**
- fake_A
- fake_B
- real_A
- real_B
- rec_A
- rec_B
**_Time:_** 9m25.4s

### **Results using ```--model test --dataset_mode single```**
**_loadSize:_** 1500px
**_fineSize_** 1500px
**_Command Given:_** ```time python test.py --dataroot datasets/"lolLuke46"/testA --checkpoints_dir ./checkpoints/ --name utahRaptor_64_256 --model test --dataset_mode single --loadSize 1500 --fineSize 1500 --which_epoch latest --resize_or_crop scale_width --no_dropout```
**_Ram Usage_** 21942 MiB
**_Outputs Received:_**
- fake_B
- real_A
**_Time:_** 0m23.9s

We had been using ```--model cycle_gan --dataset_mode unaligned``` and wanted to switch to ```--model test --dataset_mode single``` because of the obvious speed improvements and since we only need ```fake_B.png```

any suggestions?

**Comment by junyanz** [comment]
I just updated the `test_model.py`. It should fix the memory issue. Let me know if it works for you.
