### ISSUE TITLE
Generator modifies image size when not using already implemented cropping

### ISSUE THREAD

**Issue by Matlmr** [junyanz/pytorch-CycleGAN-and-pix2pix#237]
Hello !

For my project, I crop the images according to a ground truth mask, so I don't use the already implemented cropping functions. For some reason, the generator function now modifies the size of the images: for example, a 362x529 image becomes a 364x332 image after going through netG_A.

Anyone has an idea why?
Thanks

**Comment by junyanz** [comment]
I guess the padding/conv layers in the G will make height and width as multiples of 3. 
One thing you can do: 
- record the original image size 362x529
- resize your input to 364x332 by yourself. 
- feed it to the G 
- resize the output by 362x529.

**Comment by Matlmr** [comment]
Thanks for the reply!
I ended up modifying the get_transform function so that it doesn't do the cropping, and resizes the images to the nearest multiple of 4.
