### ISSUE TITLE
train one cycleGAN with multiple parallel datasets (ex trainA1->trainB1, trainA2-trainB2, trainA3-trainB3)

### ISSUE THREAD

**Issue by Hunterwolf88** [junyanz/pytorch-CycleGAN-and-pix2pix#244]
Sorry for the noob question, but I was wandering if it could be possible to train the same Cycle GAN with more than one correlation.
example: change all the zebras to horse AND all the oranges to apples in the same picture.
This could be interesting for more precise results (for example you can correlate tree photos to Monet trees, real flowers to Monet flowers, real houses to painted ones and so on), but I have absolutely no idea how it could be achieved and if it's actual necessary to have different train "subfolders" couples for that, or if you can simply put tree, flower and house photos in trainA and the painted ones in trainB.

Awesome project, anyway!

**Comment by junyanz** [comment]
It is possible. In the Monet's case, it should be fine. But I guess the performance might drop as you are using two completely different datasets (e.g. horse->zebra, and apple->orange) during one training session.
