### ISSUE TITLE
AttributeError: 'ResnetGenerator' object has no attribute 'module'

### ISSUE THREAD

**Issue by ForeverZyh** [junyanz/pytorch-CycleGAN-and-pix2pix#247]
I have downloaded a pretrained model and a dataset. Then when I tried to generate the results using the command line provided in the README, the following error occurred. 

I guess the recent code reformattings [843d68](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/843d68642bd15d5737e3eb39abd76c748d6b52e8#diff-51dac6ea9e67bde1fa278600286a93c6) [eb75f7](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/eb75f7d33830c06273cb5886b458e1a85fde041c#diff-51dac6ea9e67bde1fa278600286a93c6) [6fdc01](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/6fdc016dc651550c9f41dff186b15fa0051636bf#diff-51dac6ea9e67bde1fa278600286a93c6) caused the problem. Maybe the pretrained models did not get updated.

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    model = create_model(opt)
  File "/home/zyh/xxx/pytorch-cyclegan-and-pix2pix/models/__init__.py", line 17, in create_model
    model.initialize(opt)
  File "/home/zyh/xxx/pytorch-cyclegan-and-pix2pix/models/test_model.py", line 27, in initialize
    self.load_networks(opt.which_epoch)
  File "/home/zyh/xxx/pytorch-cyclegan-and-pix2pix/models/base_model.py", line 81, in load_networks
    net.module.load_state_dict(torch.load(save_path))
  File "/home/zyh/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 398, in __getattr__
    type(self).__name__, name))
AttributeError: 'ResnetGenerator' object has no attribute 'module'

**Comment by souringhosh** [comment]
I am getting the same issue

**Comment by junyanz** [comment]
It works with GPUs. I find it failed with CPU `--gpu_ids - 1`. I wonder if you are using GPUs or CPUs. If possible, could you paste the exact command line you are using?

**Comment by ForeverZyh** [comment]
@junyanz  Sorry, I forgot to mention it, I used CPU using `--gpu_ids -1`

**Comment by junyanz** [comment]
I just fixed the model save/load with CPU mode. Let me know if it works for you.

**Comment by ForeverZyh** [comment]
@junyanz Thanks, it works for me!
