### ISSUE TITLE
How to predict single image

### ISSUE THREAD

**Issue by jinfagang** [junyanz/pytorch-CycleGAN-and-pix2pix#25]
This network seems should feed into a pair of images which contains A and B, what if I want simply feed A image into net and help get a wonderful generation of B kind. How to do this exactly under the circumstance that I trained the network and got saved checkpoints? Any snippet ?

**Comment by visonpon** [comment]
i also want to know how to do , do you make any progress? @jinfagang @phillipi

**Comment by visonpon** [comment]
i also don't know how to do, did you make any progress? thks @jinfagang 
and if there is any advises you can provide? @phillipi

**Comment by visonpon** [comment]
i also don't know how to do, did you make any progress? thks @jinfagang 
and if there is any advises you can provide? @junyanz @phillipi

**Comment by junyanz** [comment]
We will provide a test code for single image after NIPS deadline (May 19). For now, you can create a placeholder image B (e.g. white image).

**Comment by hiepph** [comment]
Hi @junyanz, did you make any progress for this issue? Maybe a script, if I input an A image, it will produce a B generated image with trained model?

**Comment by jinfagang** [comment]
@hiepph You are just  waiting something as I am.

**Comment by hiepph** [comment]
I was tired of waiting so I decided writing my own. It takes `real_A.jpg` as input and generates `fake_B.png`. You can parse images location as arguments as you need:

```
    # Load model
    model = create_model(opt)

    # Load image
    real = Image.open('./real_A.jpg')
    preprocess = transforms.Compose([
        transforms.Scale(opt.loadSize),
        transforms.RandomCrop(opt.fineSize),
        transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5),
                             (0.5, 0.5, 0.5)),
    ])  

    # Load input
    input_A = preprocess(real).unsqueeze_(0)
    model.input_A.resize_(input_A.size()).copy_(input_A)
    # Forward (model.real_A) through G and produce output (model.fake_B)
    model.test()

    # Convert image to numpy array
    fake = util.tensor2im(model.fake_B.data)
    # Save image
    util.save_image(fake, './fake_B.png')
```

You can check full example here: https://gist.github.com/hiepph/125ebe0795ca9f5bfac3328b4d604928

And you run it with, for example:

```
python gen.py --dataroot datasets --name edges2shoes_pix2pix
```

`--dataroot` is a must option of base options so I just add a random value here. It matters at `--name` ---> the name of the trained model

**Comment by junyanz** [comment]
Thanks, @hiepph for sharing the helpful script. Sorry for the delay. I just uploaded a new [script](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/scripts/test_single.sh) for applying a pre-trained model to a collection of input images. Please use `--dataset_mode single` and `--model test` options.

**Comment by energy888666** [comment]
666
