### ISSUE TITLE
Paper question in pix2pix

### ISSUE THREAD

**Issue by JipengWuxmu** [junyanz/pytorch-CycleGAN-and-pix2pix#256]
When i read pix2pix, i meed a problem. 
It‘s −DA(GB(v,z0))−DB(GA(u,z))  in  formula 3,
can one task's discriminator used in another task's generator.

**Comment by junyanz** [comment]
Not sure if you are referring to the right equation. This is equation 3 in pix2pix paper. 
![image](https://user-images.githubusercontent.com/1924757/39288525-57f78e12-48f6-11e8-9963-bf5878199d28.png)
For your questions, I think it is an interesting idea and you are free to try it. It depends on your particular setup. If two tasks are similar to each other, it might help.

**Comment by JipengWuxmu** [comment]
sorry，it’s in dualgan，I'm wrong。
