### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:

### ISSUE THREAD

**Issue by rentonliu** [junyanz/pytorch-CycleGAN-and-pix2pix#262]
Hi , I just follow the instruction using the pretrained model to test horse2zebra
Here  are the errors I got:

dataset [SingleImageDataset] was created
/home/zhibo/pytorch-CycleGAN-and-pix2pix/models/networks.py:45: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, 0.0, 0.02)
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    model = create_model(opt)
  File "/home/zhibo/pytorch-CycleGAN-and-pix2pix/models/__init__.py", line 17, in create_model
    model.initialize(opt)
  File "/home/zhibo/pytorch-CycleGAN-and-pix2pix/models/test_model.py", line 27, in initialize
    self.load_networks(opt.which_epoch)
  File "/home/zhibo/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 85, in load_networks
    net.module.load_state_dict(torch.load(save_path))
  File "/home/zhibo/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
        Unexpected running stats buffer(s) "model.2.running_mean" and "model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.

Dose anyone know what's going on here?

**Comment by rentonliu** [comment]
I solved the problem.
pytorch version should be 0.3.1 as author mentioned

**Comment by HareshMiriyala** [comment]
installing torch 0.3.1 doesn't solve this issue !
