### ISSUE TITLE
2 images 256x256 pixels each on 2 gpus getting out of memory error?

### ISSUE THREAD

**Issue by inkplay** [junyanz/pytorch-CycleGAN-and-pix2pix#263]
Using 2 custom images in folder trainA and trainB under "style" folder and I am running Cuda out of memory error? Both images are 3 channel RGB 256x256 in size. I have 2 GTX 980 total of 6GB memory. Note I did not make valA valB folders.

I called:

`python train.py --dataroot ./datasets/style --model cycle_gan` everything else is on default. What do I need to change to make this work?

model stats:

> ------------ Options -------------
> batchSize: 1
> beta1: 0.5
> checkpoints_dir: ./checkpoints
> continue_train: False
> dataroot: ./datasets/style
> dataset_mode: unaligned
> display_freq: 400
> display_id: 1
> display_ncols: 4
> display_port: 8097
> display_server: http://localhost
> display_winsize: 256
> epoch_count: 1
> fineSize: 256
> gpu_ids: [0]
> init_type: normal
> input_nc: 3
> isTrain: True
> lambda_A: 10.0
> lambda_B: 10.0
> lambda_identity: 0.5
> loadSize: 286
> lr: 0.0002
> lr_decay_iters: 50
> lr_policy: lambda
> max_dataset_size: inf
> model: cycle_gan
> nThreads: 4
> n_layers_D: 3
> name: style_cyclegan
> ndf: 64
> ngf: 64
> niter: 10
> niter_decay: 100
> no_dropout: False
> no_flip: False
> no_html: False
> no_lsgan: False
> norm: instance
> output_nc: 3
> phase: train
> pool_size: 50
> print_freq: 100
> resize_or_crop: resize_and_crop
> save_epoch_freq: 5
> save_latest_freq: 5000
> serial_batches: False
> suffix:
> update_html_freq: 1000
> verbose: False
> which_direction: AtoB
> which_epoch: latest
> which_model_netD: basic
> which_model_netG: resnet_9blocks
> -------------- End ----------------
> CustomDatasetDataLoader
> dataset [UnalignedDataset] was created
> #training images = 1
> C:\Users\Luke Chen\Desktop\Painter\models\networks.py:45: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
>   init.normal(m.weight.data, 0.0, 0.02)
> ---------- Networks initialized -------------
> [Network G_A] Total number of parameters : 11.378 M
> [Network G_B] Total number of parameters : 11.378 M
> [Network D_A] Total number of parameters : 2.765 M
> [Network D_B] Total number of parameters : 2.765 M
> -----------------------------------------------

Actual Error:

> model [CycleGANModel] was created
> create web directory ./checkpoints\style_cyclegan\web...
> THCudaCheck FAIL file=c:\programdata\miniconda3\conda-bld\pytorch_1524549877902\work\aten\src\thc\generic/THCStorage.cu line=58 error=2 : out of memory
> Traceback (most recent call last):
>   File "train.py", line 31, in <module>
>     model.optimize_parameters()
>   File "C:\Users\Luke Chen\Desktop\Painter\models\cycle_gan_model.py", line 157, in optimize_parameters
>     self.backward_G()
>   File "C:\Users\Luke Chen\Desktop\Painter\models\cycle_gan_model.py", line 146, in backward_G
>     self.rec_B = self.netG_A(self.fake_A)
>   File "C:\Users\Luke Chen\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "C:\Users\Luke Chen\Anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 112, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "C:\Users\Luke Chen\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "C:\Users\Luke Chen\Desktop\Painter\models\networks.py", line 199, in forward
>     return self.model(input)
>   File "C:\Users\Luke Chen\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "C:\Users\Luke Chen\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
>     input = module(input)
>   File "C:\Users\Luke Chen\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "C:\Users\Luke Chen\Desktop\Painter\models\networks.py", line 241, in forward
>     out = x + self.conv_block(x)
> RuntimeError: cuda runtime error (2) : out of memory at c:\programdata\miniconda3\conda-bld\pytorch_1524549877902\work\aten\src\thc\generic/THCStorage.cu:58

**Comment by junyanz** [comment]
I recommend that you use batchSize=1 on 1 GPU.
