### ISSUE TITLE
No sigmoid in CycleGAN discriminator

### ISSUE THREAD

**Issue by wnls** [junyanz/pytorch-CycleGAN-and-pix2pix#269]
Hi,

In the process of reproducing cycle GAN and pix2pix, and have the following questions:

- Wondering why pix2pix uses sigmoid in the last layer of its discriminator but cycle GAN does not?
- Also is there a reason why cycle GAN updates generator first while pix2pix updates discriminator first?

Much appreciated!

**Comment by SsnL** [comment]
Because CycleGAN uses LSGAN, which applies a MSE loss.

**Comment by wnls** [comment]
Thank you!

On point 2 - is there a reason why cycle GAN updates generator first while pix2pix updates discriminator first? - Is this also answered by LSGAN? I skimmed through the paper and did not find the updating strategy mentioned.

**Comment by SsnL** [comment]
No. I don’t think there is particular reason as both approaches are
implemented in practice. Note that in both cases D is updated with same
gradients. Perhaps by updating G first it is less likely to be dominated by
D. But likely You can use either.

**Comment by junyanz** [comment]
I don't see a big difference regarding the order of G and D updates.

**Comment by wnls** [comment]
Thanks!

**Comment by manuelr417** [comment]
> Because CycleGAN uses [LSGAN](https://arxiv.org/abs/1611.04076), which applies a MSE loss.

Thanks a lot!! Wondering about the same for a couple of days!

**Comment by MarioProjects** [comment]
Hi, I don't understand why you don't need a sigmoid or something similar. Your discriminator final layer is a convolution that can output any value, and your range is [0,1]=(fake, real). Could you help me understand?

It would be the same for multilabel discriminator? (your discriminator distinguish between multiple classes instead of fake/real)
