### ISSUE TITLE
My computer halted everytime I input"python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --no_dropout"

### ISSUE THREAD

**Issue by marvellousxf** [junyanz/pytorch-CycleGAN-and-pix2pix#270]
My computer halted everytime I input"python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --no_dropout" and I just cannot figure out why it happens.
The reminder in the terminal stops at "create web directory ./chechpoints/maps_cyclesgan/web..."
I, a new learner beg for help....

**Comment by SsnL** [comment]
after that it enters the training loop. maybe it's just training too slow for you.

**Comment by SsnL** [comment]
Also might be a problem if you have old GPU, or GPU with suboptimal CUDA version.

**Comment by junyanz** [comment]
It would be useful if you can tell us the specs of your computer.

**Comment by SunHaozhe** [comment]
I have the same issue. Any suggestions ?

**Comment by junyanz** [comment]
Answered in a separate [post](#484 ).

**Comment by marvellousxf** [comment]
I have only one GPU, GeForce TITANX, Driver: 384.130 ,, Pytorch 0.4.0. CUDA 8.0.
