### ISSUE TITLE
Visdom server interface stays empty during training

### ISSUE THREAD

**Issue by benjamin9555** [junyanz/pytorch-CycleGAN-and-pix2pix#271]
I'm running cycleGAN with default options on a remote machine. I start the visdom server with the command python -m visdom.server and I see the visdom server header in my browser, but no data about the training process is getting displayed.

**Comment by SsnL** [comment]
did you start the visdom server on your remote machine, and ssh tunnel to it?

**Comment by benjamin9555** [comment]
I tried ssh tunnelling to avoid possible firewall problems, but still encounter the same problem:
<img width="1435" alt="screen shot 2018-05-24 at 14 18 38" src="https://user-images.githubusercontent.com/8866751/40484968-806fc63e-5f5d-11e8-8c3b-e76a7eec2ef6.png">

Here is the initial output I get when I start the visdom server with python -m visdom.server

`Downloading scripts. It might take a while.
It's Alive!
INFO:root:Application Started
You can navigate to http://localhost:8097
INFO:tornado.access:200 GET /vis_socket (127.0.0.1) 78.57ms`

**Comment by benjamin9555** [comment]
I have run some independent example for the visdom server, the problem comes from using a http proxy with visdom. Sorry for the noise.

**Comment by BlueSkyLT** [comment]
@bentaculum Hi I am running into a similar problem. I have visdom running on the remote server and ssh tunnel to it on my local machine. All I see is blank interface. I am not familiar with http proxy and not sure what is the issue here. Do you think it's possibly the same issue and know how to tackle it?

**Comment by junyanz** [comment]
If you have issues with visdom, could you use wandb instead?
