### ISSUE TITLE
70x70 PatchGAN

### ISSUE THREAD

**Issue by liuwei16** [junyanz/pytorch-CycleGAN-and-pix2pix#274]
where is the  implementation 70x70 PatchGAN loss in this code?
As stated in the paper, non-overlaping 70x70 patchs are utilized to computu the discriminator loss.

**Comment by zoucheng1991** [comment]
I also cannot find the implementation 70x70 PatchGAN loss in this code. @liuwei16 if u manage to locate the implementation of patchGAN in this code, please kindly tell me, thx.

**Comment by junyanz** [comment]
Here is the [code](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py#L314).
