### ISSUE TITLE
how to start train cycleGAN with checkpoints?

### ISSUE THREAD

**Issue by Wanger-SJTU** [junyanz/pytorch-CycleGAN-and-pix2pix#275]
I trained CycleGAN with my own dataset,  but got interupted. and I have `latest_net_D_A.pth` , `latest_net_D_B.pth` `latest_net_G_A.pth` and `latest_net_G_B.pth` files in `checkpoints/AtoB/` directory.
How could I restarted the training process, with the checkpoint files

**Comment by happsky** [comment]
Try --continue_train.

**Comment by junyanz** [comment]
Also, use `epoch_count`. See this [issue](#85) for more details.
