### ISSUE TITLE
Can the image-to-image translation by the models trained from cyclegan be real-time?

### ISSUE THREAD

**Issue by maliyong** [junyanz/pytorch-CycleGAN-and-pix2pix#278]
Dear professor，can the image-to-image translation by the models trained from cyclegan be real-time? I try some experiment, but found it is so slow with low fps.

**Comment by junyanz** [comment]
It can be real-time during the test time. It depends on the input image size and your GPUs.

**Comment by maliyong** [comment]
Thank you. I get it.
