### ISSUE TITLE
Some problems when I try to "bash" the datasets and pretrained models:

### ISSUE THREAD

**Issue by MachineryZ** [junyanz/pytorch-CycleGAN-and-pix2pix#282]
After I type the command"bash ./datasets/download_pix2pix_dataset.sh facades"
The terminal warns me:
WARNING: timetamping does nothing in combination with -0. See the manual for details.
And connection timed out

How to fix this problem?

**Comment by junyanz** [comment]
Have you fixed the issue? If not, you can also download it manually. The datasets are [here](https://people.eecs.berkeley.edu/~tinghuiz/projects/pix2pix/datasets/).

**Comment by IvanKush** [comment]
datasets are unavailable =(

**Comment by junyanz** [comment]
Hmm... I just clicked the [link](https://people.eecs.berkeley.edu/~tinghuiz/projects/pix2pix/datasets/) and it still works for me. 
![image](https://user-images.githubusercontent.com/1924757/42198563-b1a21fb4-7e56-11e8-9416-efbebd383f49.png)
