### ISSUE TITLE
Ask for help about the size of dataset and the num of epoches.

### ISSUE THREAD

**Issue by maliyong** [junyanz/pytorch-CycleGAN-and-pix2pix#283]
Hello, professor. Recently, I train the cyclegan with my own dataset. But my results are poor. Maybe it is because of  the size of my dataset and the num of epoches. How about your experiences about the size of my dataset and the num of epoches? if there are over-fitting occur when the number of dataset images is small and the num of epoches is large? Thank you very much.

**Comment by junyanz** [comment]
Overfitting will happen if the size of the dataset is small. We usually train 200K iterations for most of our experiments. You may want to apply more data [argumentation](https://github.com/mdbloice/Augmentor) (e.g., cropping, changing the color, etc.) if your training set is small.

**Comment by junyanz** [comment]
CycleGAN can get reasonable results on relatively small datasets (e.g., 1000, 2000 images). It also depends on your task (e.g., the complexity of your transformation, the diversity of your datasets). Also, we apply data augmentation during the training.
