### ISSUE TITLE
ConnectionError: HTTPConnectionPool(host='localhost', port=8097)

### ISSUE THREAD

**Issue by YANYANYEAH** [junyanz/pytorch-CycleGAN-and-pix2pix#284]
When I train the model ，some errors come：
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f06be427750>: Failed to establish a new connection: [Errno 111] Connection refused',))

and I run python -m visdom.server，but nothing happen. I wait for a long time but its still here.like this:
Downloading scripts. It might take a while.

Please help me and thanks a lot.

**Comment by junyanz** [comment]
See #230 for more details.
