### ISSUE TITLE
random cropping

### ISSUE THREAD

**Issue by mhusseinsh** [junyanz/pytorch-CycleGAN-and-pix2pix#289]
Hello,

I do understand that you do random cropping when loading the batch, as a type of data preprocessing.
The thing now, If I want to deploy the network and test it on a given pictures, the output (generated images), will be randomly cropped too. How can I feed a picture, and return a fully complete one ?

**Comment by charan223** [comment]
check out arguments in base_options file in options folder

**Comment by junyanz** [comment]
You can disable the cropping during the test time. Check out options such as `resize_or_crop`, `loadSize`, `fineSize`. See training/test [details](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#trainingtest-details).

**Comment by mhusseinsh** [comment]
@junyanz  so why do we resize images to a bigger size before cropping ? they are already 256x256, why are they resized to 286x286 ?

**Comment by mhusseinsh** [comment]
@junyanz so does this mean, that I can skip resizing and cropping for my dataset ? and just feed them as they are, and train them without any random cropping ?

And also, what is your opinion towards rectangle images ? I mean concerning resizing and cropping ? shall they be resized or not ? and if yes, to what extent or portion can they be resized too ? and accordingly, with the random cropping, shall I do rectangle crop patches or square ones ?
