### ISSUE TITLE
when load G net,there is a KeyError: 'unexpected key "module.model.model.0.weight" in state_dict',why?,i never changed the G net!

### ISSUE THREAD

**Issue by BlackDeal** [junyanz/pytorch-CycleGAN-and-pix2pix#290]

**Comment by junyanz** [comment]
It might be caused by instancenorm/batchnorm. Sometimes, you use a different normalization layer during test compared to the training.

**Comment by tigereatsheep** [comment]
@BlackDeal Check your training options in the dir ./checkpoints/expriment_name/opt.txt , follow the parameters in your testing options  --norm batch/instance
![image](https://user-images.githubusercontent.com/14801873/42038301-359d4f56-7b1d-11e8-8161-6910a0d931d5.png)
