### ISSUE TITLE
A little question about trainA dataset and trainB dataset.

### ISSUE THREAD

**Issue by zqdeepbluesky** [junyanz/pytorch-CycleGAN-and-pix2pix#291]
hi,I wonder If I try to set dataset trainA and trainB to the same picture,What would be the output result of my test dataset?Are their outputs unchanged?Have you tried to do this and will their results become high resolution images?

**Comment by taesung89** [comment]
I am not really sure what you mean, but if you train CycleGAN on two identical datasets, it will learn to not change anything. We observe this as long as the dataset size is reasonably big. This will hold true on the test dataset as well, so you are right that the outputs are unchanged. It's possible to run it on high res images as long as your GPU memory is enough.
