### ISSUE TITLE
How to use pre-trained .t7 file from Torch?

### ISSUE THREAD

**Issue by QROST** [junyanz/pytorch-CycleGAN-and-pix2pix#298]
I tried [https://github.com/clcarwin/convert_torch_to_pytorch](url) but it doesn't work for our CycleGAN model. I also tried use `load_filename = '%s_net_%s.t7' % (which_epoch, name)` `state_dict = load_lua(load_path, map_location=str(self.device))` in `def load_networks`. Neither works.. 

Really appreciate helps.

**Comment by junyanz** [comment]
I am not familiar with torch->pytorch conversion. You can also use the old Torch test code for your torch model, or retrain a new PyTorch model with the PyTorch code.
