### ISSUE TITLE
Does it support running on cpu? 

### ISSUE THREAD

**Issue by margaretmm** [junyanz/pytorch-CycleGAN-and-pix2pix#310]
I ran this command:  _python2 test.py --dataroot datasets/horse2zebra/testA --name horse2zebra_pretrained --model test_

and it return : 

THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=32 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    opt = TestOptions().parse()
  File "/home/AI/pytorch-CycleGAN-and-pix2pix/options/base_options.py", line 115, in parse
    torch.cuda.set_device(opt.gpu_ids[0])
  File "/usr/lib64/python2.7/site-packages/torch/cuda/__init__.py", line 262, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at torch/csrc/cuda/Module.cpp:32

**Comment by junyanz** [comment]
Set `--gpu_ids 0`. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#trainingtest-details) for more details.

**Comment by MrOCR** [comment]
@junyanz you mean `gpu_ids -1`?
also before training we should start the vserver? `python -m visdom.server`

**Comment by junyanz** [comment]
Yes, `-1`. If you want the visualization, you should start the visdom server. Otherwise, you can set `--display_id 0`.

**Comment by MrOCR** [comment]
@junyanz Thanks man for your hard work!
