### ISSUE TITLE
How about exposing 'gain' option?

### ISSUE THREAD

**Issue by Naruto-Sasuke** [junyanz/pytorch-CycleGAN-and-pix2pix#311]
You guys use 'gain=0.02' as a default value, maybe exposing it as an item of 'option/train_options.py'?

**Comment by junyanz** [comment]
This is a great catch. I just added it through this [commit](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/2ecf15f8a7f87fa56e784e0504136e9daf6b93d6). Let me know if it works for you.

**Comment by Naruto-Sasuke** [comment]
works fine!
