### ISSUE TITLE
output of fake_B and real_B

### ISSUE THREAD

**Issue by giorgiop2it** [junyanz/pytorch-CycleGAN-and-pix2pix#312]
Hello,
I'm using pytorch-CycleGAN-and-pix2pix with  the options to manage input and output with only one channel.
python train.py --nThreads 36 --display_id 0 --dataroot $CINECA_SCRATCH/fs --name pix2pix_unet --model pix2pix --which_model_netG unet_128 --which_direction AtoB   --data
set_mode aligned --no_lsgan --norm batch --pool_size 0 --input_nc 1 --output_nc 1  --gpu_ids 0,1,2,3

The dimension of fake_B and real_B are bigger than real_A (about two times).
-rw-r--r-- 1 gpedrazz interactive 118847 Jun 29 18:04 epoch043_fake_B.png
-rw-r--r-- 1 gpedrazz interactive  52765 Jun 29 18:04 epoch043_real_A.png
-rw-r--r-- 1 gpedrazz interactive 123111 Jun 29 18:04 epoch043_real_B.png
I remember that in an older version they were  about the same size.
Is this an error?
Thanks
Giorgio

**Comment by junyanz** [comment]
Could you print the shape of real_A, fake_B, and real_B? You can either get the information from the saved images or add a few lines in the code.

**Comment by giorgiop2it** [comment]
Hello,
thank you for replying
Here the shape of  resulting and training images
>>> im = Image.open('epoch143_real_B.png')
>>> import numpy
>>> numpy.array(im).shape
(256, 256, 3)
>>> im = Image.open('epoch143_real_A.png')
>>> numpy.array(im).shape
(256, 256, 3)
>>> im = Image.open('epoch143_fake_B.png')
>>> numpy.array(im).shape
(256, 256, 3)
Training image example
>>> im = Image.open('/gpfs/scratch/userinternal/gpedrazz/fs/train/1330.png')
>>> numpy.array(im).shape
(256, 514)

Giorgio

**Comment by junyanz** [comment]
It's possible that images in your output space are more complicated than images in your input space. This will cause the different sizes of images. The current code will save everything to a 3-channel image. You can change the behavior [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/util/visualizer.py#L20).
