### ISSUE TITLE
How Can I add attention mechanisms  for cyclegan?

### ISSUE THREAD

**Issue by c1a1o1** [junyanz/pytorch-CycleGAN-and-pix2pix#315]
I find it is difficult to add attention mechanisms in class ResnetGenerator.

How Can I add attention mechanisms  for cyclegan?

**Comment by junyanz** [comment]
Not sure what "attention mechanism" means.

**Comment by c1a1o1** [comment]
https://github.com/heykeetae/Self-Attention-GAN
Can you notice it??

**Comment by c1a1o1** [comment]
Thank you very much!

**Comment by Zico2017** [comment]
Similar question...
Do you think whether it's possible to add self-attention layer into pix2pix?
If possible, how to do it? add it to decoder part?

**Comment by junyanz** [comment]
It is possible. I think the self-attention layer should be added to the discriminator. You don't need to change the generator. You can just take the D from self-att GANs.

**Comment by c1a1o1** [comment]
@junyanz  Thank you very much!

**Comment by zhangdan8962** [comment]
> It is possible. I think the self-attention layer should be added to the discriminator. You don't need to change the generator. You can just take the D from self-att GANs.

Can you please explain that why we do not need attention layer in generator?

**Comment by junyanz** [comment]
You can add it to the generator. But for the paper "Selt-Attention GANs" (as mentioned by @c1a1o1), the authors only add it to the discriminator.

**Comment by dishamehra** [comment]
> It is possible. I think the self-attention layer should be added to the discriminator. You don't need to change the generator. You can just take the D from self-att GANs.

@junyanz We just need to take the self-attention layer from SAGAN and put it in the discriminator and not the entire discriminator architecture right?

**Comment by Gaussian01** [comment]
In the link above by @c1a1o1 they also add the self attention layers to the generator. 
![image](https://user-images.githubusercontent.com/60389356/182857471-eb55f671-b1e9-4fde-963d-e1c8921210a7.png)
