### ISSUE TITLE
Fail to use pre-trained model (CycleGAN)

### ISSUE THREAD

**Issue by liaoweiguo** [junyanz/pytorch-CycleGAN-and-pix2pix#318]
Seems the pre-trained model loading failed. but trainning with a K80 machine works fine

>>
bash pretrained_models/download_cyclegan_model.sh horse2zebra
<< OK
bash ./datasets/download_cyclegan_dataset.sh horse2zebra
<< OK
python test.py --dataroot datasets/horse2zebra/testA --name horse2zebra_pretrained --model test
<<

dataset [SingleImageDataset] was created
initialize network with normal
model [TestModel] was created
loading the model from ./checkpoints/horse2zebra_pretrained/latest_net_G.pth
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    model.setup(opt)
  File "/media/liao/User/ex/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 43, in setup
    self.load_networks(opt.which_epoch)
  File "/media/liao/User/ex/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 130, in load_networks
    net.load_state_dict(state_dict)
  File "/home/liao/anaconda3/lib/python3.6/site-packages/torch-0.4.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Unexpected key(s) in state_dict: "model.2.num_batches_tracked", "model.5.num_batches_tracked", "model.8.num_batches_tracked", "model.10.conv_block.2.num_batches_tracked", "model.10.conv_block.6.num_batches_tracked", "model.11.conv_block.2.num_batches_tracked", "model.11.conv_block.6.num_batches_tracked", "model.12.conv_block.2.num_batches_tracked", "model.12.conv_block.6.num_batches_tracked", "model.13.conv_block.2.num_batches_tracked", "model.13.conv_block.6.num_batches_tracked", "model.14.conv_block.2.num_batches_tracked", "model.14.conv_block.6.num_batches_tracked", "model.15.conv_block.2.num_batches_tracked", "model.15.conv_block.6.num_batches_tracked", "model.16.conv_block.2.num_batches_tracked", "model.16.conv_block.6.num_batches_tracked", "model.17.conv_block.2.num_batches_tracked", "model.17.conv_block.6.num_batches_tracked", "model.18.conv_block.2.num_batches_tracked", "model.18.conv_block.6.num_batches_tracked", "model.20.num_batches_tracked", "model.23.num_batches_tracked".

**Comment by junyanz** [comment]
@taesung89

**Comment by taesung89** [comment]
Please pull the latest commit of this repo and try again. I added some code to get around the issue. 

The problem was due to the following situation on PyTorch. 
The conda version uses version 0.4, which does not have num_batches_tracked field. 
The version built from source is 0.5, which introduced `num_batches_tracked`. 
For forward compatibility, I disabled `num_batches_tracked`.
