### ISSUE TITLE
issues about resize and crop when test 

### ISSUE THREAD

**Issue by liang233** [junyanz/pytorch-CycleGAN-and-pix2pix#319]
hello,I use pix2pix to dehaze now ,my datasets is 620*460,it is not a index of 2,when I train,I use the solution in  demo,resizing 286*286，crop 256*256,but when I test,what should I test data?thanks

**Comment by junyanz** [comment]
You can use `loadSize 286 fineSize 286` or `loadSize 286 fineSize 256`.
