### ISSUE TITLE
How to run the tiff image?

### ISSUE THREAD

**Issue by jianhaogao** [junyanz/pytorch-CycleGAN-and-pix2pix#320]
I want to apply the networks to the tiff image but it doesn't work. How can I change to code ? Plz help me!

**Comment by junyanz** [comment]
The current code does not support tiff images. You can change the data loader accordingly .
For aligned dataset, change this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/aligned_dataset.py#L24)
For unaligned dataset, change this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/unaligned_dataset.py#L36)

**Comment by jianhaogao** [comment]
Thank you, I'll try.
