### ISSUE TITLE
Pre-trained model confusion

### ISSUE THREAD

**Issue by gy201611124** [junyanz/pytorch-CycleGAN-and-pix2pix#323]
I think the pre-trained model ' style_ ukiyogh ' has been changed to ' style_vangogh '. Could you check it? Thank you.

**Comment by JungJungyeji** [comment]
I also think so. However, it seems that the style_ukiyoe_pretrained is stored in style_cezanne_pretrained. Therefore, style_cezanne_pretraind is missing. It takes me a long time to train. I would be very grateful if I could receive style_ukiyoe_pretrained data.

**Comment by junyanz** [comment]
@taesung89

**Comment by taesung89** [comment]
It was a mistake on me. Sorry about that. I fixed it. Could you check if it works now?
