### ISSUE TITLE
different outputs (images)

### ISSUE THREAD

**Issue by mhusseinsh** [junyanz/pytorch-CycleGAN-and-pix2pix#326]
Hello

Can someone explain for me please the rec_A/B and idt_A/B images ? the fake and the real are known for sure, I am asking about the two others

Thanks a lot

**Comment by calebescobedo** [comment]
I believe rec means reconstruction and idt means identity. 

Some sections of the [Cycle-GAN paper](https://arxiv.org/pdf/1703.10593.pdf) offer good examples. 
Figure 4 has a good example of reconstruction. 

Section 5.2 under the header **Photo generation from paintings** explains what identity mapping loss does. It helps preserve color. 
Figure 9 shows an example of using identity along with CycleGAN.

**Comment by taesung89** [comment]
Yes. @calebescobedo  is correct. 
If we call G the generator from A to B, and F from B to A, 

rec_A = F(G(A))
rec_B = G(F(B))
idt_A = G(B)
idt_B = F(A)

**Comment by shreyasbapat** [comment]
@taesungp  I am not getting idt images after testing. How can i get them?

**Comment by taesungp** [comment]
Do you want to generate idt images at test time? The code doesn't have an option to do that (we removed such functionality for simplicity), but it should be fairly easy to add it. Basically, use `--model cycle_gan` and modify lines like [this](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/cycle_gan_model.py#L59) and `def forward` to generate G(B).

**Comment by grbagwe** [comment]
Is there a way to add Spatial Pyramid Pooling layer to work with images of different size and so as to not resize them ? 
Thanks
Gaurav

**Comment by sumanthratna** [comment]
> Yes. @calebescobedo is correct.
> If we call G the generator from A to B, and F from B to A,
> 
> rec_A = F(G(A))
> rec_B = G(F(B))
> idt_A = G(B)
> idt_B = F(A)

Thanks for the explanation. Can you explain the difference between fake_B and idt_A?

**Comment by junyanz** [comment]
It is possible. Feel free to try it.
