### ISSUE TITLE
Does `continue_train` option work?

### ISSUE THREAD

**Issue by hiepph** [junyanz/pytorch-CycleGAN-and-pix2pix#33]
I trained `edges2shoes` dataset with following command:

```
python train.py --dataroot ./datasets/edges2shoes --name edges2shoes_pix2pix --model pix2pix --which_model_netG unet_256 --which_direction AtoB --lambda_A 100 --align_data --use_dropout --no_lsgan --batchSize 12 --niter 15 --niter_decay 15 
```

Then after 1 epoch (and it's already saved its own checkpoint), I interrupt with `Ctrl+C`. The day after, I want to continue training with following command:

````
python train.py --dataroot ./datasets/edges2shoes --name edges2shoes_pix2pix --model pix2pix --which_model_netG unet_256 --which_direction AtoB --lambda_A 100 --align_data --use_dropout --no_lsgan --batchSize 12 --niter 15 --niter_decay 15 --continue_train
````

You can notice I parse in `--continue_train` option (as I read in `options/train_options.py`).

I notice that generated fake image is kept, but epoch is reset back to 1, loss is also graphed from nothing.

I wonder if this continued training or not? If not, how can I keep training my model after interrupting it.

**Comment by tnako** [comment]
Work,
some options like epoch/iter count, image size or loss values can be reconfigured, that is why epoch start from 0. It mean "I won't more 100 epoch with lambda_A = 100" for example

And some options like model type or model settings can`t change, if you create pix2pix model, continue to train pix2pix model

**Comment by junyanz** [comment]
Yeah,  epoch/iter count will be initialized as 0. Otherwise, it should be fine. I used to save the old model somewhere else.
