### ISSUE TITLE
CUP Training Time

### ISSUE THREAD

**Issue by calebescobedo** [junyanz/pytorch-CycleGAN-and-pix2pix#331]
I am currently trying to train CycleGAN using only my computers CPU. 
Are there any flags that I should run with in order to decrease the training time? 

I have 36 CPU cores to work with. 

How long should I expect training to take when I use the CPU? 

Thanks!

**Comment by taesung89** [comment]
You can reduce the number of iterations of training. This can be done by changing `--niter` and `--niter_decay`. The total number of iterations is `niter + niter_decay`
