### ISSUE TITLE
visdom.ConnectionError: Error connecting to Visdom server

### ISSUE THREAD

**Issue by kangyang94** [junyanz/pytorch-CycleGAN-and-pix2pix#333]
I have install every necessary packets successfully.But when I train the pix2pix following the course, I get the error like following:
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    visualizer = Visualizer(opt)
  File "/home/ky/pytorch-CycleGAN-and-pix2pix/util/visualizer.py", line 47, in __init__
    self.vis = visdom.Visdom(server=opt.display_server, port=opt.display_port, raise_exceptions=True)
  File "/home/ky/miniconda2/lib/python2.7/site-packages/visdom/__init__.py", line 324, in __init__
    }, endpoint='env/' + env)
  File "/home/ky/miniconda2/lib/python2.7/site-packages/visdom/__init__.py", line 445, in _send
    raise ConnectionError("Error connecting to Visdom server")
visdom.ConnectionError: Error connecting to Visdom server

I firstly use visdom.Does anyone know how to fix this error?Thanks!

**Comment by junyanz** [comment]
See #230 for more details.

**Comment by Gordonqian2017** [comment]
Thanks a lot , it  works.

**Comment by aamirhr** [comment]
Hello guys my code works but i still get this in the beginning 
Could not connect to Visdom server. 
 Trying to start a server....
Command: /home/bvde103/anaconda3/envs/pytorch-CycleGAN-and-pix2pix/bin/python -m visdom.server -p 8097 &>/dev/null &

and while training i dont see any graph plots for loss, i only see print visualizer printing different losses but plot visualizer for loss graphs i dont see. The function def plot_current_losses(self, epoch, counter_ratio, losses): in visualizer.py is for creating loss graphs for the training right ? Pls help

**Comment by junyanz** [comment]
Your understanding is correct. ``plot_current_losses`` is for creating loss graphs. If visdom doesn't work well for you, you can also use wandb instead via ``--use_wandb`.
