### ISSUE TITLE
some images are rotated even with --no_flip

### ISSUE THREAD

**Issue by AllAwake** [junyanz/pytorch-CycleGAN-and-pix2pix#334]
i've been using CycleGAN for more than several months but  just recently started to observe this rotation, almost sure it happened after upgrading to PyTorch 0.4 
thank you!

**Comment by junyanz** [comment]
Which `resize_or_crop` and `dataset_mode` are you using? Are you using `no_flip`?

**Comment by AllAwake** [comment]
i don't set the first two so they are defaulted , and yes - no_flip

and it seems like only the rectangular images get rotated - i'm currently training with square ones, and there is no rotation as far as i can see

**Comment by SsnL** [comment]
Do you have a concrete example? From the code it shouldn't have such behavior...

**Comment by AllAwake** [comment]
and of course you're right  - double checked the training set - some of the images coming my  phone were rotated and i totally missed - so sorry :woman_facepalming:

**Comment by SsnL** [comment]
No worries. Have fun with CycleGAN. :)
