### ISSUE TITLE
Coloring problem

### ISSUE THREAD

**Issue by PhoenixFeifei** [junyanz/pytorch-CycleGAN-and-pix2pix#337]
Excuse me, how do I control the generated color or style when I use a generated model to test it. For example, I use a pixel2pixel to color a line drawing. How do I control the color that he generates, or it is uncontrollable?

**Comment by junyanz** [comment]
You need to also tell the network which color you would like to generate during training/test. 
See a relevant work on user-guided colorization: [paper](https://arxiv.org/abs/1705.02999), [code](https://github.com/junyanz/interactive-deep-colorization)

**Comment by Epiphqny** [comment]
@PhoenixFeifei @junyanz May i ask how to use the Imagenet data for training colorization task. Do I need to convert the data into gray images myself?

**Comment by junyanz** [comment]
Yes, people typically convert an RGB image to Lab. Many libraries that can do the job for you with one line of code.  Once you have a Lab image, you can train a network to predict ab from L.
