### ISSUE TITLE
using the trained model(fineSize=512) to produce the test image (640*480)result , i got an error

### ISSUE THREAD

**Issue by visonpon** [junyanz/pytorch-CycleGAN-and-pix2pix#34]
using the trained model(fineSize=512) to produce the test image (640*480)results , i got an error as follows:
`runtimeerror: sizes do not match at /b/wheel/pytorch-src/torch/lib/THC/generic/THCTensorCopy.c:48`

when i fineSize the test images, i also reveive the error, do you know why? thanks~ @junyanz

**Comment by MKFMIKU** [comment]
I have the same error!
Please tell me how to solve it.
