### ISSUE TITLE
Resnet based autoencoder

### ISSUE THREAD

**Issue by ahmed-fau** [junyanz/pytorch-CycleGAN-and-pix2pix#341]
Hi,

I am working on implementation of an auto-encoder network using resnet architecture following the your implementation introduced for the 'ResnetGenerator' module.

Just to verify my understanding: is the bottleneck implemented independently from the residual blocks ? i.e. apply one 'ResnetBlock' with same convolution (using padding) then apply traditional strided convolution until reaching the bottleneck ?

Best

**Comment by junyanz** [comment]
ResnetGenerator has (1) K convolutional layers (2) N ResnetBlock (3) K strided convolutional layers. 
The ResnetBlock will keep the spatial resolution. (2) can be treated as the bottleneck.

**Comment by ahmed-fau** [comment]
"The ResnetBlock will keep the spatial resolution"

This means that it is 'same convolution'  ?

 "(2) can be treated as the bottleneck"

Isn't it (3) ?? as the strided convolution should decrease the spatial dimension till reaching the bottleneck. 

Best

**Comment by junyanz** [comment]
Strided-convolution will increase the spatial dimension. Convolution will decrease the dimension. ResNet block will keep the dimension. See this [post](https://towardsdatascience.com/types-of-convolutions-in-deep-learning-717013397f4d) and ResNet paper for more details.
