### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by tangjilin** [junyanz/pytorch-CycleGAN-and-pix2pix#343]
I train my model(G:44M,  D:40M) with about 15k training data with size of 128. I use a single 1080 GPU to train and my batch size is 32. However, I feel the training is slow. It cost me about 2.5 hour for a epoch. Is it  normal?Or my model has some problem?

**Comment by junyanz** [comment]
It looks normal to me. The training often takes a few days. In your case, you may not need to train the model for 200 epochs. Sometimes, 50 will be enough if you have 15k images. You may want to check if your GPU usage is 100%. If not, you may want to improve the IO.

**Comment by junyanz** [comment]
You can increase the [num_threads](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L33). You can store your data on an SSD drive.
