### ISSUE TITLE
How to set larger iters to train the model longer?

### ISSUE THREAD

**Issue by ouyangkid** [junyanz/pytorch-CycleGAN-and-pix2pix#346]
I first try the default setting for both model training, and they stop at 200 epoch as the epochSize=1. If I want to train larger iters, which parameters should modify?
I read the base_options.py and train_options.py, but didn't find one.

Should I train them twice and set the --which_epoch last in the 2nd round training?

Which parameter controls the total training iters?

**Comment by junyanz** [comment]
You can set the `--niter` and `niter_decay `. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/train_options.py#L17) for more details.

**Comment by ouyangkid** [comment]
@junyanz thanks for your kind reply, I currently got to understand how the iter=200 is calculated, the total iter=niter+niter_decay.  Before that, I thought they work separately.

**Comment by junyanz** [comment]
Cool. Sorry for the confusion. You are correct!
