### ISSUE TITLE
Html visualizations interfere

### ISSUE THREAD

**Issue by tychovdo** [junyanz/pytorch-CycleGAN-and-pix2pix#349]
Hi,

Thank you for the clean and well documented PyTorch implementation.
I have one issue with the HTML visualizations when training multiple models on the same machine. Results from one model end up in the 'images' folder and 'index.html' file that corresponds to the other experiment. For example, running two different experiments the 'fake_B' image on epoch 0 in the html visualizations are the same although the parameters of the models are different. Somehow the visualizer of one experiment instance overwrites results of the other instance.

Both experiments are running with different 'opt.name' parameters and therefore different 'checkpoint' folders.

How can I solve this issue? 

Thanks in advance,
Tycho

**Comment by qihuaiyu** [comment]
Hi, I also want to visualize the results by index.html file, could you tell me how should I do to make it ?  I opened the file, but the pictures failed  to load.

**Comment by junyanz** [comment]
From this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/util/visualizer.py#L50), `self.web_dir = os.path.join(opt.checkpoints_dir, opt.name, 'web')`. If you set different names, the code should write HTML files to different directories. Could you do a test with different opt.name?
