### ISSUE TITLE
Multi GPUs not working

### ISSUE THREAD

**Issue by doantientai** [junyanz/pytorch-CycleGAN-and-pix2pix#35]
I'm trying to run pix2pix network with 2 GPU with option 
`--gpu_ids 0,1`
However only one GPU is running.
I have 2 GPUs both are Titan 6GB

**Comment by doantientai** [comment]
Oh, I realized that I used default batchSize which is 1. Now I increased it up to 100 and both GPUs are working very well.

**Comment by ZhuFengdaaa** [comment]
I use `--batchSize 32` and get "out of memory" and I use `--batchSize 16`. How can you increase it up to 100? I use the dataset monet2photo.
