### ISSUE TITLE
is there a way to continue training ?

### ISSUE THREAD

**Issue by dmaugis** [junyanz/pytorch-CycleGAN-and-pix2pix#350]
is there an argument to continue training after 200 epoch if I feel it's not enough ? else, how to do that ? thanks ! the --continue training option seems to do the job, but are the checkpoints retained ? with the correct numbering ?

**Comment by AllAwake** [comment]
checkpoints will be retained using epoch_count option - as you might see the default is 1 but you could set it to say 201 and then your checkpoints will be numbered accordingly

**Comment by junyanz** [comment]
See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/87) for how to resume your previous training.
