### ISSUE TITLE
cyclegan checkerboard redux

### ISSUE THREAD

**Issue by AllAwake** [junyanz/pytorch-CycleGAN-and-pix2pix#351]
it seems like with an older version the checkerboard goes away with training  but lately using the latest code (with pytorch 0.4)  i just can't get rid of it  - was there any change in the code related to that?...

thanks!

**Comment by junyanz** [comment]
Not sure about that. I think we only updated the PyTorch 0.4 syntax. 
Maybe @SsnL can have a look.

**Comment by SsnL** [comment]
The code should be equivalent. Can you share the settings and results you used/got for 0.4?

**Comment by AllAwake** [comment]
thank you guys, as long as there are no changes on your side, i'll continue to tweak my own code - basically i'm trying to use cycleGAN for super-resolution so upscaling result in the weird texture...

**Comment by SsnL** [comment]
@AllAwake It is not impossible that something in PyTorch changed that impacted. Please let me know if you found anything wrong in that regard.
