### ISSUE TITLE
pix2pix  questions in subtitle generate?

### ISSUE THREAD

**Issue by xieyufei1993** [junyanz/pytorch-CycleGAN-and-pix2pix#353]
![image](https://user-images.githubusercontent.com/19235054/44378376-91a19100-a533-11e8-9992-9f94eb7011fe.png)
I just want to use pix2pix  to generate the subtitle，but the result is not very good.what can i do to improve the result?Looks forward to hearing from you 
@junyanz

**Comment by junyanz** [comment]
It might be great to mention your (1) dataset size (2) training data details (e.g., image resolution (height x width), if input and output images are aligned). It is hard to give any advice without knowing more details. 

I think you should crop square patches and train with patches during training. During the test time, you can run the model in a fully convolutional fashion. You can also use different networks (such as ResNet Generator).

**Comment by xieyufei1993** [comment]
Thanks for your answer, my train dataset size is 20000 and my train script now is : python -u train.py --dataroot ./datasets/rgb2black/classAB/ --name rgb2black_pix2pix --model pix2pix --which_model_netG resnet_6blocks --display_id 0 --which_direction AtoB --continue_train --resize_or_crop none --no_flip. 
the size of 
![image](https://user-images.githubusercontent.com/19235054/44391215-d5ab8a80-a561-11e8-9902-6983c6742118.png)
is 32*280，how should I change the script?
@junyanz

**Comment by junyanz** [comment]
The aspect ratio for 32*280 is too extreme. Maybe you would like to train a model on 32x32 patches or 32x64 patches. You can try `--resize_or_crop crop --fineSize 32`. See more details in the training/test [practice](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md).

**Comment by xieyufei1993** [comment]
Thank you very much ,I will have a try
