### ISSUE TITLE
train.py and test.py run without error, but produce no results

### ISSUE THREAD

**Issue by Valafar** [junyanz/pytorch-CycleGAN-and-pix2pix#355]
Hi. I'm trying to use CycleGAN on an image translation task, where both my domain and my target sets have 200 images. I placed them into subdirectories as specified, and the programs run smoothly, but no visualization information ever shows up in my visdom tab and the index.html file produced at the end is almost completely blank. The images are slightly different sizes, but doesn't the resize_and_crop tag take care of that?

**Comment by taesung89** [comment]
Could you try running it with `--display_freq 1 --print_freq 1` and see what happens? This should display the result and print the error at every iteration.

**Comment by Valafar** [comment]
I feel like there must be some simple data formatting step that I have missed. Nothing changed with those tags. This is the typical output I get while the program is running: 

End of epoch 165 / 200 	 Time Taken: 0 sec
learning rate = 0.0000693
End of epoch 166 / 200 	 Time Taken: 0 sec
learning rate = 0.0000673
End of epoch 167 / 200 	 Time Taken: 0 sec
learning rate = 0.0000653
End of epoch 168 / 200 	 Time Taken: 0 sec
learning rate = 0.0000634
End of epoch 169 / 200 	 Time Taken: 0 sec
learning rate = 0.0000614

The learning rate starts at 0.02 and decreases as the number of epochs gets near 200.

**Comment by Valafar** [comment]
Wait. I got an error that time at epoch 195.

Traceback (most recent call last):
  File "train.py", line 55, in <module>
    model.save_networks(epoch)
  File "/home/ubuntu/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 99, in save_networks
    torch.save(net.module.cpu().state_dict(), save_path)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py", line 161, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py", line 118, in _with_file_like
    return body(f)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py", line 161, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py", line 238, in _save
    serialized_storages[key]._write_file(f, _is_real_file(f))
RuntimeError: Unknown error -1

**Comment by Valafar** [comment]
It seems as though it was an issue with pixel density and image scaling. The results are now printing to visdom.

**Comment by junyanz** [comment]
Cool. I am glad that you figured it out.
