### ISSUE TITLE
CycleGAN "retain_graph=True" RuntimeError 

### ISSUE THREAD

**Issue by happsky** [junyanz/pytorch-CycleGAN-and-pix2pix#356]
loss_D.backward()
  File "/home/csdept/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/csdept/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

Any suggestion?

**Comment by taesung89** [comment]
Hi,

could you post the entire call stack? This can be resolved by specifying `retain_graph=True` in the call to `backward` of autograd. (https://pytorch.org/docs/stable/autograd.html#torch.autograd.backward) However, I would like to know why this happened in your case. 

-Taesung

**Comment by Ha0Tang** [comment]
Hi, Taesug, 
I want to use one optimizer for four different discriminators in CycleGAN, and it occurs above error.
Why are you use one optimizer for two different discriminators rather than two different optimizers for two different discriminators?

**Comment by happsky** [comment]
Hi, Taesug,
I want to use one optimizer for four different discriminators in CycleGAN, and it occurs above error.
Why are you use one optimizer for two different discriminators rather than two different optimizers for two different discriminators?

**Comment by junyanz** [comment]
I think you can use both (either one optimizer for two Ds or two optimizers for two Ds). It is not a big difference. One optimizer for two Ds can save a few lines of code.
