### ISSUE TITLE
How do I fix this error? '_cuda_setDevice'

### ISSUE THREAD

**Issue by ArchitectTaeyoon** [junyanz/pytorch-CycleGAN-and-pix2pix#360]
Hello,

I have been following the instruction up to the training stage, where I got stuck.
```
#!./scripts/train_cyclegan.sh
python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan
```

And I get the following error;

```
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    opt = TrainOptions().parse()
  File "/Users/taeyoonkim/Documents/ML/pix2pix/pytorch-CycleGAN-and-pix2pix/options/base_options.py", line 116, in parse
    torch.cuda.set_device(opt.gpu_ids[0])
  File "/Users/taeyoonkim/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 262, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: 'module' object has no attribute '_cuda_setDevice'
```

Seems like this is a popular question, and after looking at the previous answers, I have been trying to install different versions of Pytorch, but didn't succeed. I couldn't figure out how to run it on the CPU like the other answer suggests. (`--gpu_ids 0`)

Running on Mac OS High Sierra 10.13.3 
Python 2.7 version.
Installed : pip, anaconda2, pytorch (python2.7, CUDA 9.2), visdom, dominate, brew, bash, wget, CUDA developer toolkit, cuDNN

I also installed python3 using brew, but switching the path became problematic, so I stuck to 2.7 versions. I have tried installing pytorch 0.4.0, although the terminal seems to be using 0.4.1
I tried downgrading to pytorch 0.3.1 and the same error appears. (#267)

**Comment by junyanz** [comment]
The current code only supports PyTorch 0.4+. See [Q & A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#typeerror-object-of-type-tensor-is-not-json-serializable-258) for answer details.

**Comment by ArchitectTaeyoon** [comment]
yup I tried the latest versions (0.4+) first. Same error.

**Comment by junyanz** [comment]
Hmm, do you have an NVIDIA GPU on your Mac? If not, you can set `--gpu_ids -1` to use CPU mode.

**Comment by ArchitectTaeyoon** [comment]
yes I have an NVIDIA GPU. 
I would like to use the GPU, since it is much faster..

I tried the CPU mode command anyways, and it won't work.
Am I meant to insert `--gpu_ids -1` line into  .profile ?

Thank you for answering my questions! :)

**Comment by junyanz** [comment]
add `--gpu_ids -1` to your python command. 
I am not sure if your issue is caused by this repo. You may want to run some PyTorch official [examples](https://github.com/pytorch/examples) and see if your PyTorch is installed correctly.

**Comment by ArchitectTaeyoon** [comment]
okay thanks! I will try the examples and come back :)

**Comment by SsnL** [comment]
The PyTorch binary for osx does not support CUDA. So if you run with gpu_ids not -1, you will see such error. You can build from pytorch github source to support CUDA.

**Comment by SsnL** [comment]
Both linux and windows binaries work with CUDA. Have fun!

**Comment by ArchitectTaeyoon** [comment]
Thank you ! :)

**Comment by dsy199610** [comment]
> --gpu_ids -1

where should I type this command?

**Comment by QasimWani** [comment]
i'm having the same issue as @ArchitectTaeyoon with python3.8. 
@ArchitectTaeyoon how were u able to solve/fix your error?

**Comment by RoyceDavison** [comment]
> i'm having the same issue as @ArchitectTaeyoon with python3.8.
> @ArchitectTaeyoon how were u able to solve/fix your error?

An example will be like (suppose I want to apply a pre-trained model):
python ./test.py --dataroot ./datasets/monet2photo/testA/ --name monet2photo_pretrained --model test --no_dropout --gpu_ids -1
Just add --gpu_ids -1 to your python command.

**Comment by aktaseren** [comment]
> Hmm, do you have an NVIDIA GPU on your Mac? If not, you can set `--gpu_ids -1` to use CPU mode.

That worked for me as well. Thank you.
