### ISSUE TITLE
Regarding 3D volume generator

### ISSUE THREAD

**Issue by snlee81** [junyanz/pytorch-CycleGAN-and-pix2pix#364]
Hello @junyanz , @taesung89 ,

Thank you for nice tutorial + nice codes. 

I ran several datasets with the CycleGAN but I eventually need 3D CycleGAN. Here, 3D is not video (x, y, t) input but some from medical image volume (x, y, z). I don't think CycleGAN support 3D input volume but just want to make sure that part. 

Thank you!

**Comment by junyanz** [comment]
The current code does not support 3D input. You probably need to write your own data loader (as well as generator and discriminator). See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#how-can-i-make-it-work-for-my-own-data-eg-16-bit-png-tiff-hyperspectral-images-309--320-202) for how to write the data loader.

**Comment by snlee81** [comment]
Okay. I did load 3D volumetric data and change some part of resnetGenerator() but need to modify entire network. Due to out of memory problem, larger volume cannot be trained though.

**Comment by junyanz** [comment]
Yes, 3D volumetric data is quite memory-intensive.

**Comment by snlee81** [comment]
Thank you very much for your answer. I will think about the way to overcome that.
