### ISSUE TITLE
How to only generate rec_A images?

### ISSUE THREAD

**Issue by cschar** [junyanz/pytorch-CycleGAN-and-pix2pix#366]
Hi, similar to this cyclegan-tensorflow project: https://github.com/xhujoy/CycleGAN-tensorflow
there is a functionality of only producing recreated images.

Currently, I'm using the following command: 

    python test.py --dataroot ./datasets/horse2zebra --name myhorse2zebracyclegan
     --model cycle_gan --which_direction=BtoA

The results however produce __6__ images per frame (fake_A, fake_B, real_A, real_B, rec_A, rec_B). I don't need all 6, I would just like to have the recreated image (in this case _rec_A)

Is this possible with the current options and config classes?

**Comment by junyanz** [comment]
We don't have this option. But you can remove `fake_A` and `fake_B` in these two [lines](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/cycle_gan_model.py#L30).
