### ISSUE TITLE
How to import a pre-trained discriminator model in cycle_gan_model?

### ISSUE THREAD

**Issue by yinqk** [junyanz/pytorch-CycleGAN-and-pix2pix#369]
when I done this like the title, I got the following error,Can someone help me? 

Traceback (most recent call last):
  File "train.py", line 14, in <module>
    model = create_model(opt)
  File "F:\ylp\pytorch-CycleGAN-and-pix2pix\models\__init__.py", line 37, in create_model
    instance.initialize(opt)
  File "F:\ylp\pytorch-CycleGAN-and-pix2pix\models\cycle_gan_model.py", line 60, in initialize
    self.netD_A.load_state_dict(torch.load(opt.pretrained))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.model.0.weight", "module.model.0.bias", "module.model.2.weight", "module.model.2.bias", "module.model.4.weight", "module.model.4.bias".
        Unexpected key(s) in state_dict: "model.0.weight", "model.0.bias", "model.2.weight", "model.2.bias", "model.3.running_mean", "model.3.running_var", "model.5.weight", "model.5.bias", "model.6.running_mean", "model.6.running_var", "model.8.weight", "model.8.bias", "model.9.running_mean", "model.9.running_var", "model.11.weight", "model.11.bias".

**Comment by junyanz** [comment]
Maybe you can use the `load_networks` [function](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/base_model.py#L118) to load the network. You can add `D_A` to `self.model_names`. You can change this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/cycle_gan_model.py#L38).

**Comment by yinqk** [comment]
Thanks for your reply. According to your instruction, I used the  load_networks function to load my network, but I got the following error:

#training images = 120
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
loading the model from ./checkpoints\try_cyclegan\100_net_D_A.pth
loading the model from ./checkpoints\try_cyclegan\100_net_D_B.pth
loading the model from ./checkpoints\try_cyclegan\100_net_D_A.pth
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    model = create_model(opt)
  File "F:\ylp\pytorch-CycleGAN-and-pix2pix\models\__init__.py", line 37, in create_model
    instance.initialize(opt)
  File "F:\ylp\pytorch-CycleGAN-and-pix2pix\models\cycle_gan_model.py", line 64, in initialize
    self.netD_B = BaseModel.load_disnetworks(self,opt.which_epoch)
  File "F:\ylp\pytorch-CycleGAN-and-pix2pix\models\base_model.py", line 158, in load_disnetworks
    self.__patch_instance_norm_state_dict(state_dict, net, key.split('.'))
  File "F:\ylp\pytorch-CycleGAN-and-pix2pix\models\base_model.py", line 115, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
AttributeError: 'NoneType' object has no attribute 'model'

**Comment by junyanz** [comment]
For the debugging information, it seems that the network `D_A` and `D_B` has been loaded. And the code failed when you tried to load them the second time. Maybe you want to check out which code produces the first two lines. 
```
loading the model from ./checkpoints\try_cyclegan\100_net_D_A.pth
loading the model from ./checkpoints\try_cyclegan\100_net_D_B.pth
```
