### ISSUE TITLE
Recovered images when training a new cyclegan model

### ISSUE THREAD

**Issue by mbillouin2015** [junyanz/pytorch-CycleGAN-and-pix2pix#370]
I am very interested in how cyclegan was able to recover the original images when after performing the image translations in both directions.  These recoveries were labeled as rec_A and rec_B.  How could you use a pretrained network to recover images from a test dataset?

**Comment by junyanz** [comment]
CycleGAN can recover images from the generated images as it is trained with this learning objective. See this [paper](https://arxiv.org/abs/1712.02950) for more details.
