### ISSUE TITLE
About load_network

### ISSUE THREAD

**Issue by yinqk** [junyanz/pytorch-CycleGAN-and-pix2pix#372]
When I wanted to load pretrained model by using load_network function, I got following error:

loading the model from ./checkpoints/try_cyclegan/50_net_D_A.pth
loading the model from ./checkpoints/try_cyclegan/50_net_D_B.pth
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    model = create_model(opt)
  File "F:\ylp\pytorch-CycleGAN-and-pix2pix\models\__init__.py", line 37, in create_model
    instance.initialize(opt)
  File "F:\ylp\pytorch-CycleGAN-and-pix2pix\models\cycle_gan_model.py", line 81, in initialize
    self.optimizer_D = torch.optim.Adam(itertools.chain(self.netD_A.parameters(), self.netD_B.parameters()),
AttributeError: 'NoneType' object has no attribute 'parameters'

I found that [there](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/base_model.py#L136) returned '**None**' ,So I got above error.

**Comment by junyanz** [comment]
You need to define the D before you load it from the disk. I am wondering if you have defined D. 
```python 
self.netD_A = networks.define_D(opt.output_nc, opt.ndf, opt.netD,
                                            opt.n_layers_D, opt.norm, use_sigmoid, opt.init_type, opt.init_gain, self.gpu_ids)
self.netD_B = networks.define_D(opt.input_nc, opt.ndf, opt.netD,
                                            opt.n_layers_D, opt.norm, use_sigmoid, opt.init_type, opt.init_gain, self.gpu_ids)
```

**Comment by yinqk** [comment]
yes, I have defined D .When I loaded the model from checkpoint, I got above error.

**Comment by yinqk** [comment]
I made a small mistake, and now I could load the model by using load_network function. And my pytorch version is 4.0. Thanks for your help.
