### ISSUE TITLE
Error while downloading day2night model 

### ISSUE THREAD

**Issue by shimiaoli** [junyanz/pytorch-CycleGAN-and-pix2pix#374]
Hi, I got error during downloading this model:

--2018-09-09 18:32:50-- https://people.eecs.berkeley.edu/~taesung_park/pytorch-CycleGAN-and-pix2pix/pix2pix_models/day2night.pth
Resolving people.eecs.berkeley.edu (people.eecs.berkeley.edu)... 128.32.189.73
Connecting to people.eecs.berkeley.edu (people.eecs.berkeley.edu)|128.32.189.73|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-09-09 18:32:51 ERROR 404: Not Found.

Thanks.

**Comment by junyanz** [comment]
Could you check out the latest commit? We moved the models to a new place.

**Comment by shimiaoli** [comment]
I got it. Thank you very much.

**Comment by des1red** [comment]
Why i can.t run the "test.py" or "train.py" after all the needed installnation had been installed?()

**Comment by des1red** [comment]
so ,like this...what should do to solve this trouble?




------------------ 原始邮件 ------------------
发件人: "Jun-Yan Zhu"<notifications@github.com>;
发送时间: 2018年9月12日(星期三) 上午6:20
收件人: "junyanz/pytorch-CycleGAN-and-pix2pix"<pytorch-CycleGAN-and-pix2pix@noreply.github.com>;
抄送: "向元吉"<739203572@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [junyanz/pytorch-CycleGAN-and-pix2pix] Error while downloadingday2night model  (#374)




What is your error?

**Comment by junyanz** [comment]
Could you include the debugging log?
