### ISSUE TITLE
Help! - AsserstionError - not a valid directory / randrange() (0,0, 0)

### ISSUE THREAD

**Issue by ArchitectTaeyoon** [junyanz/pytorch-CycleGAN-and-pix2pix#376]
I have manually downloaded the maps dataset,
and ran the train command in Anaconda3 prompt (Windows 10 64bit).
I get the following error - 

`Traceback (most recent call last):
  File "train.py", line 9, in <module>
    data_loader = CreateDataLoader(opt)
  File "C:\Users\tyk12\Documents\2_CODE\pix2pix\pytorch-CycleGAN-and-pix2pix\data\__init__.py", line 46, in CreateDataLoader
    data_loader.initialize(opt)
  File "C:\Users\tyk12\Documents\2_CODE\pix2pix\pytorch-CycleGAN-and-pix2pix\data\__init__.py", line 58, in initialize
    self.dataset = create_dataset(opt)
  File "C:\Users\tyk12\Documents\2_CODE\pix2pix\pytorch-CycleGAN-and-pix2pix\data\__init__.py", line 39, in create_dataset
    instance.initialize(opt)
  File "C:\Users\tyk12\Documents\2_CODE\pix2pix\pytorch-CycleGAN-and-pix2pix\data\unaligned_dataset.py", line 19, in initialize
    self.A_paths = make_dataset(self.dir_A)
  File "C:\Users\tyk12\Documents\2_CODE\pix2pix\pytorch-CycleGAN-and-pix2pix\data\image_folder.py", line 26, in make_dataset
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: ./datasets/maps/trainA is not a valid directory`

Thank you in advance!

**Comment by ArchitectTaeyoon** [comment]
Thank you for the quick feedback as always doctor Zhu!

Yes I will try (1).

I have tried (2) `replace the / by \ in the path.` and it still gave me the same error.

**Comment by ArchitectTaeyoon** [comment]
Thank you ! After sorting out the file directory like you mentioned, it moved on :)

The training process started, but then I ran into 4 exceptions and 1 connection error -

1. `ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it`

2. `urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001B7122DDDD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it`

3. `urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B7122DDDD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))`

4. ` File "C:\Users\tyk12\Anaconda3\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B7122DDDD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))`

5. `ConnectionError: Error connecting to Visdom server`

When I trigger `visdom` command, the Visdom browser window pops up fine.

**Comment by junyanz** [comment]
Please look at the [Q & A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#connection-errorhttpconnectionpool-230-24-38).

**Comment by ArchitectTaeyoon** [comment]
yup! thank you - saw these connection issues are listed there :)

**Comment by ArchitectTaeyoon** [comment]
Oooooh... I never thought about having 2 anaconda prompt windows open!
one for Visdom and one for training... Sorry and thanks!

Now I ran into a new error;
`ValueError: empty range for randrange() (0,0, 0)`

I am referring to issue #194

**Comment by ArchitectTaeyoon** [comment]
I tried adding `--loadSize 143 --fineSize 128`

and I still get  the same error;

```
    index_B = random.randint(0, self.B_size - 1)
  File "C:\Users\tyk12\Anaconda3\lib\random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "C:\Users\tyk12\Anaconda3\lib\random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)
```

Thank you for helping me along the way :)
I think I am almost there

**Comment by ArchitectTaeyoon** [comment]
Okay thanks for looking into it 👍 

Maybe I should try docker.

**Comment by ArchitectTaeyoon** [comment]
Got this to run in Windows properly now!

I changed the directories in image_folder.py, and downgraded the version of visdom.

Thanks again ! :)

**Comment by kumarballapavan** [comment]
> Got this to run in Windows properly now!
> 
> I changed the directories in image_folder.py, and downgraded the version of visdom.
> 
> Thanks again ! :)

How do you change the directories in image_folder.py! Can you kindly explain with code? Also could you kindly guide me how to downgrade the visdom's version using pip!

**Comment by junyanz** [comment]
You can change the data directories using `dataroot`. See this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L23). For pip usage, refer to this [webpage](https://www.shellhacks.com/python-how-to-use-pip-basic-commands/).

**Comment by kumarballapavan** [comment]
AssertionError: ./datasets/dehazing\train is not a valid directory

Can you kindly help me to fix this error!

**Comment by junyanz** [comment]
I think Windows has a different path format compared to Linux. Try something like `.\datasets\dehazing\train`.
