### ISSUE TITLE
 global name 'ConnectionError' is not defined in display_current_results

### ISSUE THREAD

**Issue by dmaugis** [junyanz/pytorch-CycleGAN-and-pix2pix#377]
I recently updated/rebuild my pytorch-CycleGAN-and-pix2pix docker image but now I have an error I did not get before:

End of epoch 5 / 200 	 Time Taken: 619 sec
learning rate = 0.0002000
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    visualizer.display_current_results(model.get_current_visuals(), epoch, save_result)
  **File "/cyclegan/util/visualizer.py", line 104, in display_current_results
    except ConnectionError:
NameError: global name 'ConnectionError' is not defined**

**Comment by SsnL** [comment]
Fixed in https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/fc1aca161e1896ed72b5ecafd9376bc59dcd32a2
