### ISSUE TITLE
FineTuning issues

### ISSUE THREAD

**Issue by parmidaatg** [junyanz/pytorch-CycleGAN-and-pix2pix#378]
I am trying to fine tune your winter2summer model. I downloaded the weights through the instruction.
I have couple of images that I put the winter ones in a trainA folder under  winter2summer_yosemite and the summer ones under trainB. The number of images in trainA and trainB are different from each other. 
Then inside my docker file , I am trying to run your train using the `--continue-train`flag.

`python train.py --dataroot datasets/winter2summer_yosemite --name winter2summer_yosemite --model cycle_gan --continue_train`

I get this error: 
`PermissionError: [Errno 13] Permission denied: './checkpoints/winter2summer_yosemite/opt.txt'`

How can I fix this?

I really appreciate your help. thanks

**Comment by Feywell** [comment]
How do you solve this question. I encounter the same question
