### ISSUE TITLE
ConnectionError[Errno 111], during run 'train.py' of maps

### ISSUE THREAD

**Issue by khryang** [junyanz/pytorch-CycleGAN-and-pix2pix#38]
when i run :
$ python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan

the error code :
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c1b19290>: Failed to establish a new connection: [Errno 111] Connection refused',))

how can I solve this??

==================
full script of error
---------------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/khryang/.local/lib/python2.7/site-packages/visdom/__init__.py", line 228, in _send
    data=json.dumps(msg),
  File "/home/khryang/.local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/khryang/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/khryang/.local/lib/python2.7/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/khryang/.local/lib/python2.7/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/home/khryang/.local/lib/python2.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c1b19290>: Failed to establish a new connection: [Errno 111] Connection refused',))
(epoch: 1, iters: 700, time: 0.456) D_A: 0.215 G_A: 0.561 Cyc_A: 2.316 D_B: 0.163 G_B: 0.450 Cyc_B: 0.794

**Comment by xuhuaren** [comment]
python -m visdom.server

**Comment by junyanz** [comment]
The `visdom` display functionality is turned on by default. To avoid the extra overhead of communicating with `visdom` set `--display_id 0`.

**Comment by khryang** [comment]
@xuhuaren, @junyanz  thanks for your answer!! I'll do that.

**Comment by eliethesaiyan** [comment]
@junyanz , did change the display_id to 0 but whenever i start the visdom server,it shows nothing,is there any specific folder i should run it into?should i do it after training?

**Comment by junyanz** [comment]
If you want to use the visdom server, you should change the display_id to a non-zero value. To view training results and loss plots, run `python -m visdom.server` and click the URL http://localhost:8097.

**Comment by Hunterwolf88** [comment]
added "--display_id 0" running train.py but I still get this error

**Comment by junyanz** [comment]
@Hunterwolf88  this seems to be strange. Could you post both your command line and the errors?

**Comment by junyanz** [comment]
See this [Q & A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#connection-errorhttpconnectionpool-230-24-38) for more details. You need to install `visdom` and type `python -m visdom.server`. 
@taesung89  Adding `--display_id 0` should be able to perform training without visualization function. We will have a look at that.

**Comment by snlee81** [comment]
@junyanz 

Yeah. I already install visdom and type "python -m visdom.server". It worked well but suddenly it doesn't work. I may need to install visdom again.
