### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'display_winsize'

### ISSUE THREAD

**Issue by qingshan412** [junyanz/pytorch-CycleGAN-and-pix2pix#384]
It reports 
```
AttributeError: 'Namespace' object has no attribute 'display_winsize'
```
when I just go with a pre-trained model (CycleGAN) as the guide: 
```bash
bash ./scripts/download_cyclegan_model.sh horse2zebra
bash ./datasets/download_cyclegan_dataset.sh horse2zebra
python test.py --dataroot datasets/horse2zebra/testA --name horse2zebra_pretrained --model test
```
It seems that ```opt.display_winsize``` is defined in ```train_options.py``` but not in ```test_options.py``` and ```base_options.py```, so if a pre-trained model is run directly, the error occurs. Since it will be used in both train and test, it would be better to add ```display_winsize``` in the ```base_options.py```.

**Comment by junyanz** [comment]
I just fixed it. Thanks.

**Comment by qingshan412** [comment]
Thanks for fixing it =)

> I just fixed it. Thanks.
