### ISSUE TITLE
How to take whole image as input at test time

### ISSUE THREAD

**Issue by universewill** [junyanz/pytorch-CycleGAN-and-pix2pix#386]
I read the FAQ here:
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#out-of-memory-174

I want to take whole image as input at test time. I run command like this:
```
python3 test.py --dataroot /data/images --name my_cyclegan  --model cycle_gan --resize_or_crop crop
```
However, i only get the result of a small crop of origin image.

Then i run command like this:
```
python3 test.py --dataroot /data/images --name my_cyclegan  --model cycle_gan
```

However, i find it resizes origin image, and output resized result (the results are saved in ./results/my_cyclegan folder ).

I want to get a result which has same width and height as origin image. How to achieve this goal?
Besides, my origin image width and height  is as large as (2000, 2000) or (1800, 2000)

**Comment by junyanz** [comment]
You can use the `--resize_or_crop none` or `--resize_or_crop scale_width --fineSize 2000`.
