### ISSUE TITLE
What are the idt images in visdom.server?

### ISSUE THREAD

**Issue by zwx8981** [junyanz/pytorch-CycleGAN-and-pix2pix#391]
Thank you for your great work. I have a question about the images shown in visdom.server during training. According to your paper, I understand that the first three columns refer to the process of A->G(A)->F(G(A)) and verse vice for B. I am just confused with the last column named idt_A and idt_B，which seems not mentioned in your paper. Can you explain the meaning of them a little bit? Thank you!

**Comment by zwx8981** [comment]
Well, I found them in sec 5.2 now, sorry for spam.

**Comment by junyanz** [comment]
Cool. See this [Q & A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#what-is-the-identity-loss-322-373-362) for more details.
