### ISSUE TITLE
SystemExit:2

### ISSUE THREAD

**Issue by luck-u** [junyanz/pytorch-CycleGAN-and-pix2pix#392]
When train.py is executed in jupyter notebook it shows :An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
why?

**Comment by junyanz** [comment]
`train.py` is a python script, not a jupyter notebook.  You probably have to modify the code. For example, removing `if __name__ == '__main__`.

**Comment by zahra74** [comment]
when i rum my main.py in google colab , i encounter with following error:
usage: ipykernel_launcher.py [-h] [--mode MODE]
ipykernel_launcher.py: error: unrecognized arguments: -f /root/.local/share/jupyter/runtime/kernel-72aff83b-728f-46c5-b21e-fbce72643810.json

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
 so
what can i do for solve it????

**Comment by ajay0103** [comment]
how to overcome this error
runfile('C:/Users/AJAY/Desktop/AV MATCHING/lib tracking.py', wdir='C:/Users/AJAY/Desktop/AV MATCHING')
usage: lib tracking.py [-h] -i INPUT -o OUTPUT [-f FPS] [-c CODEC]
lib tracking.py: error: the following arguments are required: -i/--input, -o/--output
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by junyanz** [comment]
Not sure if it is relevant to this repo.
