### ISSUE TITLE
day2night test results look off

### ISSUE THREAD

**Issue by neelsj** [junyanz/pytorch-CycleGAN-and-pix2pix#393]
I followed the process listed and the test results are not looking like what is the paper and overall look pretty off from what I’d expect.  I’m wondering if I’m doing something wrong.  I’ve included some images below.  Has anyone run into this?

![day2night](https://user-images.githubusercontent.com/25804011/45850017-42dd4780-bce9-11e8-83bf-063ae7ba16e9.jpg)

**Comment by junyanz** [comment]
The PyTorch model does not work well for this particular site as it looks quite different from training sites. It works reasonably well for other test sites. For example, this one. 
![example](https://user-images.githubusercontent.com/1924757/45853811-4d153b00-bd15-11e8-8d73-447c75b056e3.png)

The model is trained with only 90 sites. I think adding more sites might help improve the results. 

Also, the PyTorch was recently trained with the current PyTorch code. The results might be different from the Torch model. Please use the Torch model if you would like to reproduce the results in the paper.

**Comment by ArkaJU** [comment]
Where did you get the day2night dataset?

**Comment by junyanz** [comment]
See the [instruciton](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/datasets.md#pix2pix-datasets).
