### ISSUE TITLE
Maybe you should offer a guide on your code

### ISSUE THREAD

**Issue by Naruto-Sasuke** [junyanz/pytorch-CycleGAN-and-pix2pix#400]
In fact, your code is a little bit complex to understand for some people. Some of my friends shows their impatience when I recommend  them to read your code. Then I realize that some people prefer simplicity of code.  Therefore, I think it would be nice if you can add a guide on your code to help newbies understand your thoughts.

**Comment by junyanz** [comment]
Thanks for the great suggestions. We plan to add more detailed comments as well as toy model and dataset classes. Still working on it.  I also wonder which kinds of information will be helpful for you and your friends.

**Comment by Naruto-Sasuke** [comment]
The logic and structures of your code. How the code runs and what should us change if we want to process our own operations.
 For example, change 'data/aligned_dataset' to process your own preprocessing if you read aligned pairs of data, 'models/networks.py' aims at building networks and initialization of models. 'models/pix2pix_model.py' handles the main logical procedures.
It would be nice if it is detailedly illustrated by  a toy task.

**Comment by junyanz** [comment]
Thanks again for your valuable tips. Taesung and I spent some time on writing documentation and guide during winter break. Taesung provided a docker [file](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/docker.md).  I just wrote two templates: dataset [template](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/template_dataset.py) and model [template](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/template_model.py). We ar ewriting an overview of the code structure, and add more documentation to some key functions. Let me know if you have any questions or comments.

**Comment by junyanz** [comment]
Also added an [overview](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/overview.md) of our codebase. Feel free to edit or add stuff.

**Comment by Naruto-Sasuke** [comment]
It is quite detailed! I think this would help a lot of people  get deep into your codebase.
