### ISSUE TITLE
not enough memory: you tried to allocate 0GB

### ISSUE THREAD

**Issue by CodeMaterial** [junyanz/pytorch-CycleGAN-and-pix2pix#402]
Good afternoon,

I've been following your tutorial on CycleGAN and keep hitting the below error.

What would you recommend?

Thanks,

Sam.

(Running on 16.04 Ubuntu)
[log.txt](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/files/2473195/log.txt)

**Comment by junyanz** [comment]
It seems that you are using the CPU mode. But your RAM might be too small for the memory usage of CycleGAN.

**Comment by CodeMaterial** [comment]
I currently have 15gb installed. What is the best way to reduce ram consumption or how much do I need to increase my memory by for the maps dataset? Could I reduce the dataset size?
Thank you for the quick response

**Comment by junyanz** [comment]
Maybe try smaller image sizes `--loadSize 143 --fineSize 128`.

**Comment by CodeMaterial** [comment]
Smashing, that did the job. Thanks for the help!

**Comment by KnightOfTheMoonlight** [comment]
@CodeMaterial Excuse me, I have a similar problem, what do u mean by smashing?

**Comment by CodeMaterial** [comment]
It's informal Victorian English for wonderful or marvellous. 
For example 
"How's the tea?"
"Absolutely smashing thank you!"

And as for the 0GB error, just interpret it as an out of memory error and that should put you along the right path

**Comment by KnightOfTheMoonlight** [comment]
@CodeMaterial  Get it. Thanks!

**Comment by JiahongXue** [comment]
I run into the same issue. But I figured out a way by adding virtual memory to it. As long as you have an SSD on your computer. Free up some space if you don't have enough on your SSD (1.5* to 3* of actual RAM). According to this [virtual memory set up on Win10 tutorial](https://www.geeksinphoenix.com/blog/post/2016/05/10/how-to-manage-windows-10-virtual-memory.aspx)
