### ISSUE TITLE
shape inconsistency

### ISSUE THREAD

**Issue by YilinLiu97** [junyanz/pytorch-CycleGAN-and-pix2pix#408]
Hi @junyanz, thanks for the great work.  I have some MR images from two domains (first column), and the second column shows the corresponding translated images. The images in the bottom have cerebellum (highlighted in red) while the one on top don't. Interestingly, for the images in the bottom, the cerebellum is not preserved in the translated image but for the images on the top there appears cerebellum. It looks like that if data from domain A has some characteristics that do not belong to domain B, the discriminator can just judge based almost solely on that characteristic. Is there a way to solve this? I've tried increasing the lamba before the cycle consistency loss but it doesn't seem to help. I'm new with GANs. 

Thanks!

![gan](https://user-images.githubusercontent.com/26695815/47382167-489ec200-d6c7-11e8-868f-50263062a9f7.jpeg)

**Comment by u101022205** [comment]
@YilinLiu97  Hi,  i face a similar problem. Do you know why cyclegan will change shape? do you find way to avoid it? Thanks
