### ISSUE TITLE
Confuse in initial part of network.py

### ISSUE THREAD

**Issue by sunlightsgy** [junyanz/pytorch-CycleGAN-and-pix2pix#409]
Hello,

I find that in the `network.py`, the initial part has the following code:

```
if hasattr(m, 'bias') and m.bias is not None:
    init.constant_(m.bias.data, 0.0)
```
This code set all the bias to zero, is it a bug in this code?
Should it be `m.bias is None`?

Or, should all the bias in conv layer and linear layer be set to 0? I try with non-zero, but it seems to get worse results?

**Comment by junyanz** [comment]
@SsnL

**Comment by SsnL** [comment]
It only initializes them to zero, which is a common practice in training conv nets. In training, they will become nonzero.
