### ISSUE TITLE
Floydhub training :: ModuleNotFoundError: No module named 'dominate'

### ISSUE THREAD

**Issue by patalanov** [junyanz/pytorch-CycleGAN-and-pix2pix#413]
I need to use cloud services in order to train my data with `GPU`.

I picked FloydHub for that.

there I use a pytorch env `--env pytorch-0.4`.

but i'm getting `ModuleNotFoundError: No module named 'dominate'`.

as far as Im concerned, this module serves visualization.

how do I bypass that? IS it really necessary? can I visualize training using a cloud enviroment?

**Comment by junyanz** [comment]
You can install the `dominate` package. You can also modify the `visualizer.py` to remove dominate. I think visdom is using a remote environment.
