### ISSUE TITLE
about GPU 

### ISSUE THREAD

**Issue by yuanjiX** [junyanz/pytorch-CycleGAN-and-pix2pix#414]
here is my pytorch version in conda list :
pytorch     0.4.1       py37_cuda8.0.61_cudnn7.1.2_1  [cuda80]  pytorch
when i set gpu_ids,default = '0',result is RuntimeError: CUDA error: out of memory
when i set gpu_ids,default = '0,1,2' or default = '0,2',the result is AssertionError: Invalid device id
and I also run your code snippet to test my CUDA,the result is "..."
so, what should i do to solve this problem?

**Comment by junyanz** [comment]
how many GPUs do you have? How big is the GPU memory?

**Comment by yuanjiX** [comment]
1 GPU, memory 2 G.

**Comment by yuanjiX** [comment]
![qq 20181101154412](https://user-images.githubusercontent.com/23519004/47839244-04a96c80-dded-11e8-9b74-9b9c9dc29385.png)

**Comment by yuanjiX** [comment]
1 GPU， but i don't know which memory you point, so i upload a picture.
