### ISSUE TITLE
is cyclegan model proper for super resolution and denosing task?

### ISSUE THREAD

**Issue by universewill** [junyanz/pytorch-CycleGAN-and-pix2pix#415]
is cyclegan model proper for super resolution training? I want to train a model which can achieve both super resolution and denosing.

**Comment by junyanz** [comment]
I guess so. I can help if you don't have paired data. See these prior work [1](http://openaccess.thecvf.com/content_cvpr_2018_workshops/papers/w13/Yuan_Unsupervised_Image_Super-Resolution_CVPR_2018_paper.pdf), [2](https://arxiv.org/pdf/1806.09748.pdf).

**Comment by junyanz** [comment]
Sorry. It was a typo: I->it.
