### ISSUE TITLE
How to generate more random and different outputs?

### ISSUE THREAD

**Issue by yingzwang** [junyanz/pytorch-CycleGAN-and-pix2pix#419]
I trained pix2pix on only one or two image pairs. My application is to generate watercolor paintings from pencil sketches #416 . 
The GAN is supposed to learn a distribution conditioned on the input, not a deterministic mapping from input to output. But my output seems quite deterministic. Is it due to my limited training data? Or due to the limitation of pix2pix? 
How can I generate more random and different output samples?

**Comment by junyanz** [comment]
See this [post](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/152) for more details.

**Comment by yingzwang** [comment]
Thanks @junyanz . Found the answer there. BicycleGAN is exactly what I’m looking for. 
I want a pix2pix model which can produce different watercolor paintings from the same pencil sketch.
If I have some followup questions, should I ask in the BicycleGAN page?

**Comment by junyanz** [comment]
Yeah, please ask in the BicycleGAN page.
