### ISSUE TITLE
Error when using scale_width and grayscale images

### ISSUE THREAD

**Issue by prash-p** [junyanz/pytorch-CycleGAN-and-pix2pix#420]
I'm training on my own dataset and scaling the image widths to be 256 px, no cropping used, but in the 400th iteration of the 1st epoch I get the error:

`ValueError: could not broadcast input array from shape (3,164,256) into shape (3)`

I'm using this line to begin training:
`python train.py --dataroot ./datasets/my-images/ --name my_cyclegan --model cycle_gan --input_nc 1 --output_nc 1 --resize_or_crop scale_width --fineSize 256`

**Comment by prash-p** [comment]
It's to do with visdom's visualization expecting images of the same size. For now I'm using --display_id 0 to bypass the problem.

**Comment by junyanz** [comment]
@taesung89  Have you trained models with `scale_width`? Maybe you have the code to fix it.
