### ISSUE TITLE
Show multiple environments simultaneously

### ISSUE THREAD

**Issue by elimohl** [junyanz/pytorch-CycleGAN-and-pix2pix#425]
It will be very convenient to have an option to show multiple environments at one page simultaneously. It is much easy to compare experiment results when you can see them side by side.

**Comment by junyanz** [comment]
What does "multiple environments" mean? You mean the visdom environments? You can use the display port but different display ids.

**Comment by elimohl** [comment]
sorry, I make issue in wrong repository

**Comment by elimohl** [comment]
Probably because link to pix2pix is the second one when search for 'visdom multiple environment'.
