### ISSUE TITLE
How does a gpu with 6G memory set gpu_ids?

### ISSUE THREAD

**Issue by yuanjiX** [junyanz/pytorch-CycleGAN-and-pix2pix#429]
when i set gpu_ids,default = '0',result is RuntimeError: CUDA error: out of memory
when i set gpu_ids,default = '0,1,2' or default = '0,2',the result is AssertionError: Invalid device id

**Comment by junyanz** [comment]
If you only have one GPU, you should set `gpu_ids=0`. You may want to train a model with low-res images. (`loadSize=143 fineSize=128`).
See [Q & A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#out-of-memory-174) for `out of memory` error.

**Comment by yuanjiX** [comment]
well, thanks, it's working.
