### ISSUE TITLE
a small mistake?

### ISSUE THREAD

**Issue by xusuhui1989** [junyanz/pytorch-CycleGAN-and-pix2pix#43]
In data/unaligned_dataset.py, line 34, I find a small mistake: 

34. transform_list + = [transforms.ToTensor(),transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))]

I think "+ = " should be changed to "="?

**Comment by junyanz** [comment]
Nope. transform_list is a list that stores all the transformation. Here we appended more transformation operations to the list.
