### ISSUE TITLE
Feature Request: Testing models by 'iteration', not only by 'epoch'.

### ISSUE THREAD

**Issue by Naruto-Sasuke** [junyanz/pytorch-CycleGAN-and-pix2pix#432]
Hi, guys:
Testing models of different epochs is just an initial procedure of training models. Sometimes, having trained an initial model, we may continue train it and may frequently test it by a step of  hundreds of iterations to get a better one.

Thus, I propose an additionally testing scheme: adding an option 'save_by_iter' that changes `model.save_networks('latest')` to `model.save_networks('iter_'+str(total_steps))`. Of course, some other corresponding code should be also modified.

**Comment by junyanz** [comment]
Sounds good. Could you send a PR?

**Comment by Naruto-Sasuke** [comment]
Sure, will do in days.

**Comment by junyanz** [comment]
Thanks!

**Comment by Naruto-Sasuke** [comment]
#434
