### ISSUE TITLE
how to get output as horse2zebra.gif ?

### ISSUE THREAD

**Issue by techynew** [junyanz/pytorch-CycleGAN-and-pix2pix#433]
hi
I have executed the test.py file by downloading the pretrained model given by you  for horse2zebra dataset. And executed the command as follows:

python test.py --dataroot datasets/horse2zebra/testA --name horse2zebra_pretrained --model test --gpu_ids -1

after executing it shows the following:

processing (0000)-th image... ['datasets/horse2zebra/testA\\n02381460_1000.jpg']
processing (0005)-th image... ['datasets/horse2zebra/testA\\n02381460_1110.jpg']
processing (0010)-th image... ['datasets/horse2zebra/testA\\n02381460_1260.jpg']
processing (0015)-th image... ['datasets/horse2zebra/testA\\n02381460_1420.jpg']
processing (0020)-th image... ['datasets/horse2zebra/testA\\n02381460_1690.jpg']
processing (0025)-th image... ['datasets/horse2zebra/testA\\n02381460_1830.jpg']
processing (0030)-th image... ['datasets/horse2zebra/testA\\n02381460_2050.jpg']
processing (0035)-th image... ['datasets/horse2zebra/testA\\n02381460_2460.jpg']
processing (0040)-th image... ['datasets/horse2zebra/testA\\n02381460_2870.jpg']
processing (0045)-th image... ['datasets/horse2zebra/testA\\n02381460_3040.jpg']

the above code gives images as output in the result folder as fake and real.

i wish to get the horse2zebra.gif as the output. kindly suggest the procedure or which file to execute  to get the same.

i am running the code on windows 10 with CPU only

**Comment by junyanz** [comment]
You converted it into a GIF with Adobe products. If you want to a free option, you can search `images to GIF` on the web.
