### ISSUE TITLE
Wasserstein distance?

### ISSUE THREAD

**Issue by Arkkienkeli** [junyanz/pytorch-CycleGAN-and-pix2pix#439]
Hello,
Is it possible to build in the Wasserstein loss for pix2pix? 
Maybe someone already has the code? 
Thank you.

**Comment by junyanz** [comment]
I added a Wasserstein loss and gradient penalty loss in our codebase. Feel free to try it.

**Comment by lxy443626128** [comment]
hello,
where can i find the difined Wasserstein loss ?

**Comment by junyanz** [comment]
You need to specify `--gan_mode wgangp` and also call the function [cal_gradient_penalty](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py#L271) by yourself.

**Comment by moh3th1** [comment]
I did not understand, where should I call  **cal_gradient_penalty** or instead of what ?

**Comment by junyanz** [comment]
In wgan-gp, there are two loss functions: GAN loss (you can calculate it with GANLoss class with `--gan_mode wgangp`), and gradient penalty loss (you can use the function cal_gradient_panalty to calculate it). Please see the [wgan-gp](https://arxiv.org/pdf/1704.00028.pdf) paper for more details.

**Comment by lxy443626128** [comment]
How to call the  the function cal_gradient_penalty ?

def backward_D_basic(self, netD, real, fake):
        """Calculate GAN loss for the discriminator

        Parameters:
            netD (network)      -- the discriminator D
        """Calculate GAN loss for the discriminator

        Parameters:
            netD (network)      -- the discriminator D
            real (tensor array) -- real images
            fake (tensor array) -- images generated by a generator

        Return the discriminator loss.
        We also call loss_D.backward() to calculate the gradients.
        """
        # Real
        pred_real = netD(real)
        loss_D_real = self.criterionGAN(pred_real, True)
        # Fake
        pred_fake = netD(fake.detach())
        loss_D_fake = self.criterionGAN(pred_fake, False)
        #wgan-gp
        gradient_penalty, gradients = networks.cal_gradient_penalty(netD,real,fake,'cuda')
        # Combined loss and calculate gradients
        loss_D = (loss_D_real + loss_D_fake + gradient_penalty) * 0.5
        loss_D.backward()
        return loss_D

**Comment by junyanz** [comment]
It looks fine. Maybe you want to use `self.device`rather than `'cuda'`. You probably don't need to multiply gp loss by 0.5

**Comment by Arkkienkeli** [comment]
Hi, I try to make work with pix2pix, so I made changes in pix2pix_model.py
```
    def backward_D(self):
        """Calculate GAN loss for the discriminator"""
        # Fake; stop backprop to the generator by detaching fake_B
        fake_AB = torch.cat((self.real_A, self.fake_B), 1)  # we use conditional GANs; we need to feed both input and output to the discriminator
        pred_fake = self.netD(fake_AB.detach())
        self.loss_D_fake = self.criterionGAN(pred_fake, False)
        # Real
        real_AB = torch.cat((self.real_A, self.real_B), 1)
        pred_real = self.netD(real_AB)
        self.loss_D_real = self.criterionGAN(pred_real, True)
        #wgan-gp
        gradient_penalty, gradients = networks.cal_gradient_penalty(self.netD,real_AB,fake_AB,'cuda')
        # Combined loss and calculate gradients
        self.loss_D = (self.loss_D_real + self.loss_D_fake + gradient_penalty) * 0.5
        self.loss_D.backward()
```

And now I get error:

```
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
  File "/storage01/nikitam/pix2pix_wass/pytorch-CycleGAN-and-pix2pix/models/pix2pix_model.py", line 132, in optimize_parameters
    self.backward_G()                   # calculate graidents for G
  File "/storage01/nikitam/pix2pix_wass/pytorch-CycleGAN-and-pix2pix/models/pix2pix_model.py", line 120, in backward_G
    self.loss_G.backward()
  File "/storage01/nikitam/nikita3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/storage01/nikitam/nikita3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
```

**Comment by Arkkienkeli** [comment]
I changed the last line to:
`self.loss_D.backward(retain_graph=True)`
Now it starts, but the result is strange: I use it for mask-to-image translation and images are very blurry (like it is out of focus) in the background, but the objects look fine. These images are from training-time (from visdom server). Trained for 400 epochs so far.

The loss is: 
`G_GAN: -0.503 G_L1: 5.096 D_real: -0.501 D_fake:0.501`
Does it look correct? I was thinkinng that loss in this case should look like for usual training (decrease over time in correct case).
Thank you!

**Comment by junyanz** [comment]
I am not sure. You may want to monitor loss_gp as well. You can add `gp` to self.loss_names.
```python
self.loss_GP, gradients = cal_gradient_penalty()...
self.loss_GP.backward(retain_graph=True)
self.loss_D = (self.loss_D_fake + self.loss_D_real) * 0.5
self.loss_D.backward()
```

**Comment by Arkkienkeli** [comment]
How it looks after 30 epochs.

![image](https://user-images.githubusercontent.com/3052376/51612152-2bc19700-1f21-11e9-85ba-63208783bad2.png)

**Comment by beerboaa** [comment]
Question 1

According to WGAN-GP paper and [this](https://github.com/caogang/wgan-gp/blob/master/gan_cifar10.py#L219) implementation, loss should be ```D_fake - D_real + gradient_penalty```
Shouldn't it be `-` instead of `+` in         
`self.loss_D = (self.loss_D_real - self.loss_D_fake + gradient_penalty) `

Question 2

In your implementation of `backward_D_basic` function, you used `loss_D.backward()`, but I found this:
![image](https://user-images.githubusercontent.com/28640563/53292878-a18b7d80-37c1-11e9-9fbe-fadba2c22c6f.png)

Any suggestion?

**Comment by sitthinutk** [comment]
I guess we might need to update `backward_D_basic` function to 

```
def backward_D_basic(self, netD, real, fake):
    """Calculate GAN loss for the discriminator

    Parameters:
        netD (network)      -- the discriminator D
        real (tensor array) -- real images
        fake (tensor array) -- images generated by a generator

    Return the discriminator loss.
    We also call loss_D.backward() to calculate the gradients.
    """
    # Real
    pred_real = netD(real)
    loss_D_real = self.criterionGAN(pred_real, True)
    # Fake
    pred_fake = netD(fake.detach())
    loss_D_fake = self.criterionGAN(pred_fake, False)
    if self.opt.gan_mode  == 'wgangp':
        # wgan-gp
        gradient_penalty, gradients = networks.cal_gradient_penalty(netD, real, fake, self.device)
        loss_D = loss_D_fake + loss_D_real + gradient_penalty
    else:
        # Combined loss and calculate gradients
        loss_D = (loss_D_real + loss_D_fake) * 0.5
    loss_D.backward()
    return loss_D
```

because in `networks.py` already have `loss = -prediction.mean()`

```
if self.gan_mode in ['lsgan', 'vanilla']:
   target_tensor = self.get_target_tensor(prediction, target_is_real)
       loss = self.loss(prediction, target_tensor)
   elif self.gan_mode == 'wgangp':
       if target_is_real:
          loss = -prediction.mean()
       else:
          loss = prediction.mean()
```

correct me if I'm wrong.

**Comment by sitthinutk** [comment]
I've tried the following lines in `backward_D_basic`:
```python
self.loss_gp, gradients = cal_gradient_penalty()...
self.loss_gp.backward(retain_graph=True)
self.loss_D = (self.loss_D_fake + self.loss_D_real) * 0.5
self.loss_D.backward()
```
but, the losses exploded.

**Comment by beerboaa** [comment]
@Arkkienkeli Is your implementation correct?

**Comment by jclevesque** [comment]
`wgangp` loss also diverges for me. Model trains fine with `lsgan`. Bug in implementation or problem with my dataset?

**Comment by hellopipu** [comment]
> Hi, I try to make work with pix2pix, so I made changes in pix2pix_model.py
> 
> ```
>     def backward_D(self):
>         """Calculate GAN loss for the discriminator"""
>         # Fake; stop backprop to the generator by detaching fake_B
>         fake_AB = torch.cat((self.real_A, self.fake_B), 1)  # we use conditional GANs; we need to feed both input and output to the discriminator
>         pred_fake = self.netD(fake_AB.detach())
>         self.loss_D_fake = self.criterionGAN(pred_fake, False)
>         # Real
>         real_AB = torch.cat((self.real_A, self.real_B), 1)
>         pred_real = self.netD(real_AB)
>         self.loss_D_real = self.criterionGAN(pred_real, True)
>         #wgan-gp
>         gradient_penalty, gradients = networks.cal_gradient_penalty(self.netD,real_AB,fake_AB,'cuda')
>         # Combined loss and calculate gradients
>         self.loss_D = (self.loss_D_real + self.loss_D_fake + gradient_penalty) * 0.5
>         self.loss_D.backward()
> ```
> And now I get error:
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 51, in <module>
>     model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
>   File "/storage01/nikitam/pix2pix_wass/pytorch-CycleGAN-and-pix2pix/models/pix2pix_model.py", line 132, in optimize_parameters
>     self.backward_G()                   # calculate graidents for G
>   File "/storage01/nikitam/pix2pix_wass/pytorch-CycleGAN-and-pix2pix/models/pix2pix_model.py", line 120, in backward_G
>     self.loss_G.backward()
>   File "/storage01/nikitam/nikita3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/storage01/nikitam/nikita3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
>     allow_unreachable=True)  # allow_unreachable flag
> RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
> ```
I am confused why the error occurs while you only call the backward() once.

**Comment by junyanz** [comment]
You need to add `retain_graph=True` when you are calling `backward()` for gradient penalty loss. 
See [here](https://github.com/junyanz/VON/blob/master/models/shape_gan_model.py#L80) for an example (on generating 3D data with WGAN-GP)

**Comment by Miaowshroom** [comment]
Hey I am currently trying to implement the wgangp for pix2pix. I have read the previous comment in this thread, still have some parts that confuse me. I Also having the problem Trying to backward through the graph a second time, even I only call backward once.

My implementation: (I am updating D multiple times before updating G)
```python
def backward_D(self):
        """Calculate GAN loss for the discriminator"""
        # Fake; stop backprop to the generator by detaching fake_B
        fake_AB = torch.cat((self.real_A, self.fake_B), 1)  # we use conditional GANs; we need to feed both input and output to the discriminator
        pred_fake = self.netD(fake_AB.detach())
        self.loss_D_fake = self.criterionGAN(pred_fake, False)
        # Real
        real_AB = torch.cat((self.real_A, self.real_B), 1)
        pred_real = self.netD(real_AB)
        self.loss_D_real = self.criterionGAN(pred_real, True, soft_label=self.using_soft_label)
        # combine loss and calculate gradients
        # gradient penalty
        self.gradient_penalty, self.gradients = networks.cal_gradient_penalty(self.netD, real_AB, fake_AB, self.device, lambda_gp=self.L_GP)
        self.loss_D = self.loss_D_fake + self.loss_D_real + self.gradient_penalty
        self.loss_D.backward()
```

```
def optimize_parameters(self):
        self.forward()                   # compute fake images: G(A)
        
        for i in range(self.n_d): # updating D n times before updating G
            # update D
            self.set_requires_grad(self.netD, True)  # enable backprop for D
            self.optimizer_D.zero_grad()     # set D's gradients to zero
            self.backward_D()                # calculate gradients for D
            self.optimizer_D.step()          # update D's weights
        
        # update G
        self.set_requires_grad(self.netD, False)  # D requires no gradients when optimizing G
        self.optimizer_G.zero_grad()        # set G's gradients to zero
        self.backward_G()                   # calculate graidents for G
        self.optimizer_G.step()             # udpate G's weights

```
I have seen the suggested implementation:

```python
self.loss_gp, gradients = cal_gradient_penalty()...
self.loss_gp.backward(retain_graph=True)
self.loss_D = (self.loss_D_fake + self.loss_D_real) * 0.5
self.loss_D.backward()
```
I have 2 questions:
1. For the recommended code, why we could do the backward separately from gradient_penalty term. As we take the derivative, will the update be the same using these two approaches? 

2. When I am using `self.loss_D = self.loss_D_fake + self.loss_D_real + self.gradient_penalty`, I only call it once for every `self.backward_D() `. However, for the first update of D (i==0) the `self.backward_D()` went through. For the second update of D (i==0) I have the problem of `Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.`
I don't understand in this situation why it is counted as the second time. The second GP is actually wrt the second batch. The same story if I only do `self.loss_D = (self.loss_D_fake + self.loss_D_real)` it won't have the problem. What makes the difference between `self.loss_D_fake` and `self.gradient_penalty` that `self.loss_D_fake` does not need to retain the graph but `self.gradient_penalty` needs.

**Comment by junyanz** [comment]
@SsnL

**Comment by SsnL** [comment]
`networks.cal_gradient_penalty(self.netD, real_AB, fake_AB,` this `fake_AB` is not detached from the G graph.

**Comment by lkqnaruto** [comment]
> I added a Wasserstein loss and gradient penalty loss in our codebase. Feel free to try it.

Thank you for the great work! I noticed that D_real and D_fake are all negative throughout the training, is it normal?

**Comment by junyanz** [comment]
It could happen.

**Comment by lukebor** [comment]
wgangp works poorly on cycleGAN, however WGAN with gradient clipping works really good
