### ISSUE TITLE
Scale transform

### ISSUE THREAD

**Issue by jpmerc** [junyanz/pytorch-CycleGAN-and-pix2pix#44]
Just want to let people know that for me, the scale transform was making the program crash. I worked it out by replacing the list by a single value. I didn't put it in pull requests as I might be the only one who experienced this problem.

https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/unaligned_dataset.py

**Line 26**
Before: `transform_list.append(transforms.Scale(osize, Image.BICUBIC))`
After: `transform_list.append(transforms.Scale(opt.loadSize, Image.BICUBIC))`

**Comment by junyanz** [comment]
You need to upgrade your torch vision library for the current codebase: 
``` bash
git clone https://github.com/pytorch/vision
cd vision
python setup.py install
```
Scale(opt.loadSize) might not work if the input image is not square. 
From pytorch [doc](http://pytorch.org/docs/torchvision/transforms.html#torchvision.transforms.Scale): 
Rescales the input PIL.Image to the given ‘size’. If ‘size’ is a 2-element tuple or list in the order of (width, height), it will be the exactly size to scale. If ‘size’ is a number, it will indicate the size of the smaller edge. For example, if height > width, then image will be rescaled to (size * height / width, size) size: size of the exactly size or the smaller edge interpolation: Default: PIL.Image.BILINEAR
