### ISSUE TITLE
testing procedure

### ISSUE THREAD

**Issue by fishman2008** [junyanz/pytorch-CycleGAN-and-pix2pix#449]
For CycleGAN model, suppose there is only a testA folder, and the testB folder is empty, in this case, did you randomly fill the testB folder with some unrelated images? It has also been noticed that the transformation from B to A is better than the transformation from A to B. What will be the reasons for that? Thanks. @junyanz

**Comment by junyanz** [comment]
We provide a single direction test script. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-cyclegan) for more details.

**Comment by junyanz** [comment]
You can change your `fineSize` to match the `loadSize`. You can also crop the center part of the images and feed them to the model. You can write a new transform function [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/base_dataset.py#L26).
