### ISSUE TITLE
Kernel sizes

### ISSUE THREAD

**Issue by ChristianEschen** [junyanz/pytorch-CycleGAN-and-pix2pix#451]
Hi

I am wondering why you have choosen kernel size equal 4x4 for all your convolutional layers? Could you use any kernel size e.g. (3,3) like in the VGG paper?

best regards
Christian

**Comment by junyanz** [comment]
Yes, you can use 3x3. We follow the architecture from some early work such as [DCGAN](https://github.com/pytorch/examples/tree/master/dcgan), and [style-transfer.](https://github.com/jcjohnson/fast-neural-style)
