### ISSUE TITLE
Train on high-res images (1536x1536)

### ISSUE THREAD

**Issue by gvenkat21** [junyanz/pytorch-CycleGAN-and-pix2pix#452]
Hi,

I am trying to use pix2pix to clean my noisy documents. The documents have several different noises like faded texts, blotches, text warping, etc. My image size is 1536x1536. I know that pix2pix is designed to work on 256x256 images. 

Can anyone tell me what changes do I need to make to make it work on 1536x1536 images?

PS: I know that you can input the full res mage and then keep fineSize as 256 but then I am losing a lot of information.

**Comment by junyanz** [comment]
Maybe [pix2pixHD](https://github.com/NVIDIA/pix2pixHD) will help you.

**Comment by robertradar** [comment]
What will hapen, if one takes images (finesize) being larger than 256x256?

I noticed that pix2pix can run even for batchsize=16 on my GPU, but cycle_gan is not able to use batchsize>1 without CUDA error "out of memory". Is this normal?

**Comment by junyanz** [comment]
You can use a big fineSize which is larger than 256. CycleGAN uses 2-4 times more memory than pix2pix. I will expect a bigger batch size than 1.

**Comment by gvenkat21** [comment]
> Maybe [pix2pixHD](https://github.com/NVIDIA/pix2pixHD) will help you.

Ok cool...i'll check it out. Thanks

**Comment by robertradar** [comment]
> 
> 
> You can use a big fineSize which is larger than 256. CycleGAN uses 2-4 times more memory than pix2pix. I will expect a bigger batch size than 1.

I tried 501x501 for pix2pix. The following error occured in line 310 of networks.py:
'RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 2 and 3 in dimension 2 at c:\new-builder_3\win-wheel\pytorch\aten\src\thc\generic/THCTensorMath.cu:87'

**Comment by junyanz** [comment]
Could you try a size `512x512` instead?

**Comment by robertradar** [comment]
Yes, this works. I didn't know that the size has to be 2^k.
