### ISSUE TITLE
Help with reading label of generated results

### ISSUE THREAD

**Issue by nobodykid** [junyanz/pytorch-CycleGAN-and-pix2pix#456]
Hello, I'm trying to apply your code with CUHK Face-Sketch Dataset by setting the domain `A` as sketch images and domain `B` as photo images.

After generating the result using test sets, I have a bit difficulty in reading the label of generated result. For example here's one result

![image](https://user-images.githubusercontent.com/12664445/49370298-56178500-f726-11e8-9650-e76be92c4035.png)

So, when it says `fake_B`, does it means it's a translation result from `real_A` (meaning it's a fake version of domain B) or does it means a translation result of `real_B` (meaning its input is image from B)? 
And how do you suppose to read the HTML view generated to visualize the translation process of CycleGAN? Is it supposed to be
- `real_A` -> `fake_B` -> `rec_A` (following the position in template), or
- `real_A` -> `fake_A` -> `rec_A` (following the first domain data being input)

**Comment by taesung89** [comment]
By the way, looking at your results, it looks like the dataset A and B were flipped. Shouldn't real_A be sketch images according to your description?

**Comment by nobodykid** [comment]
Replying @taesung89, no, the dataset setting is exactly like what I mentioned. The A domain is the sketch domain, while the B domain is photo domain

Here's the proof for domain A set
![image](https://user-images.githubusercontent.com/12664445/49422223-9548e300-f7c5-11e8-93a0-124164445a93.png)

And here's for domain B set
![image](https://user-images.githubusercontent.com/12664445/49422236-a691ef80-f7c5-11e8-870f-4044197190d3.png)

I suppose, judging from the header of each table in the HTML, it reads data in domain B as input, thus making it `real_A`. I'll try experimenting it on switched sets (A being photo and B being sketched)

**Comment by nobodykid** [comment]
I have experimented with switching the side of dataset. And indeed it helps breaking the confusion. Thank you very much for the help

**Comment by kritin2** [comment]
> I have experimented with switching the side of dataset. And indeed it helps breaking the confusion. Thank you very much for the help

Can you explain how does the naming works? 
Also how does the naming works in the images stored for each epoch.
Thanks

**Comment by nobodykid** [comment]
Let me illustrate with my case, a sketch-to-photo process

There are two image domains that this model works upon, `A` which usually is the source image domain (in my case, it's the sketches collection), and `B` which usually is the target image domain we want to generate (in my case, it's the photos collection).

When we process the image, the model saves 3 types of image to help visualize the process happening inside the model
- `real_` images refer to the real images taken from each domain eg. `real_A` refers to image I take from the sketches collection
- `fake_` images are the one generated by the model when it tried to convert your input image to its adjacent domain eg. `fake_B` is a generated photo image as a result of processing `real_A` sketch image
- `rec_` images are the reconstructed images when the model tried to replicate back the original `real_` with the `fake_` images from adjacent domain it has created eg. `rec_A` is a reconstructed sketches of `real_A` sketch image given the output `fake_B` photo it made before

This also applies vice versa. When the model processes a `real_B` photo image, it creates a `fake_A` sketch out of it and `rec_B` as its attempt to reconstruct `real_B`

I hope that helps
