### ISSUE TITLE
What is an adequate training set size for CycleGAN?

### ISSUE THREAD

**Issue by talwarabhimanyu** [junyanz/pytorch-CycleGAN-and-pix2pix#459]
Hello, apologies if this is an elementary question. I'm trying to train a CycleGAN on a dataset of ~600 images of buildings and ~600 sketches of buildings. I trained for 200 epochs (using the default settings) and it seems my trained model did not generalize that well. May I ask if this is too small a dataset? If so, how may I regularize the network? Thank you. 

(I am a bit hesitant to use data augmentation as I want the GAN to learn to generate realistic looking building images, and if I augment my training set then it may no longer look realistic).

(Apologies if this is not the right forum to ask this kind of a question).

**Comment by junyanz** [comment]
The training set size depends on your tasks and domains. The more complicated task/domain is, the more images you meed. In your case, applying some cropping as data argumentation should not decrease the quality of images.
