### ISSUE TITLE
Why we should have two test datasets?

### ISSUE THREAD

**Issue by zychen2016** [junyanz/pytorch-CycleGAN-and-pix2pix#460]
After trained with my datasets,trainA and trainB.
Why we should have two domain datasets？
could I Only use testA to inference testB？

**Comment by junyanz** [comment]
Yes, you can test your model only in one direction. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-cyclegan) for more details.

**Comment by zychen2016** [comment]
Thanks
