### ISSUE TITLE
Error(s) in loading state_dict for ResnetGenerator:

### ISSUE THREAD

**Issue by zychen2016** [junyanz/pytorch-CycleGAN-and-pix2pix#461]
When I test pretrained model apple2orange,This error occurred.

`RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Missing key(s) in state_dict: "model.10.conv_block.6.weight", "model.10.conv_block.6.bias", "model.11.conv_block.6.weight", "model.11.conv_block.6.bias", "model.12.conv_block.6.weight", "model.12.conv_block.6.bias", "model.13.conv_block.6.weight", "model.13.conv_block.6.bias", "model.14.conv_block.6.weight", "model.14.conv_block.6.bias", "model.15.conv_block.6.weight", "model.15.conv_block.6.bias", "model.16.conv_block.6.weight", "model.16.conv_block.6.bias", "model.17.conv_block.6.weight", "model.17.conv_block.6.bias", "model.18.conv_block.6.weight", "model.18.conv_block.6.bias". 
	Unexpected key(s) in state_dict: "model.10.conv_block.5.weight", "model.10.conv_block.5.bias", "model.10.conv_block.6.running_mean", "model.10.conv_block.6.running_var", "model.10.conv_block.6.num_batches_tracked", "model.11.conv_block.5.weight", "model.11.conv_block.5.bias", "model.11.conv_block.6.running_mean", "model.11.conv_block.6.running_var", "model.11.conv_block.6.num_batches_tracked", "model.12.conv_block.5.weight", "model.12.conv_block.5.bias", "model.12.conv_block.6.running_mean", "model.12.conv_block.6.running_var", "model.12.conv_block.6.num_batches_tracked", "model.13.conv_block.5.weight", "model.13.conv_block.5.bias", "model.13.conv_block.6.running_mean", "model.13.conv_block.6.running_var", "model.13.conv_block.6.num_batches_tracked", "model.14.conv_block.5.weight", "model.14.conv_block.5.bias", "model.14.conv_block.6.running_mean", "model.14.conv_block.6.running_var", "model.14.conv_block.6.num_batches_tracked", "model.15.conv_block.5.weight", "model.15.conv_block.5.bias", "model.15.conv_block.6.running_mean", "model.15.conv_block.6.running_var", "model.15.conv_block.6.num_batches_tracked", "model.16.conv_block.5.weight", "model.16.conv_block.5.bias", "model.16.conv_block.6.running_mean", "model.16.conv_block.6.running_var", "model.16.conv_block.6.num_batches_tracked", "model.17.conv_block.5.weight", "model.17.conv_block.5.bias", "model.17.conv_block.6.running_mean", "model.17.conv_block.6.running_var", "model.17.conv_block.6.num_batches_tracked", "model.18.conv_block.5.weight", "model.18.conv_block.5.bias", "model.18.conv_block.6.running_mean", "model.18.conv_block.6.running_var", "model.18.conv_block.6.num_batches_tracked". 

`
pytorch version is 0.4.1.
python version is 3.5

python3 ./test.py --dataroot /data2/CZY/data/cyclegan/cyclegan_pytorch/data/apple2orange/testA --name apple2orange_pretrained --model test

**Comment by ArunPidugu** [comment]
Having the same problem (using a model generated after 5 epochs)

**Comment by junyanz** [comment]
Could you try to use `--no_dropout`? Make sure that you use the same `--netG` and `--norm` option during training and test.

**Comment by cy-xu** [comment]
> Could you add `--no_dropout`? Make sure that you use the same `--netG` and `--norm` option during training and test.

Hello Jun-Yan,

A follow up question probably related to `--no_dropout` option during testing.

I adopted your code into a simplified cycle-gan only version. To verify my implementaiton, I tried to test with your pre-trained model __horse2zebra__. The printed network is exactly the same, the training works, but I got the following error from testing (with exact same opts from testing, same `use_dropout = False`).
```
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Unexpected key(s) in state_dict: "model.2.running_mean", "model.2.running_var", "model.2.num_batches_tracked", "model.5.running_mean", "model.5.running_var", "model.5.num_batches_tracked", "model.8.running_mean", "model.8.running_var", "model.8.num_batches_tracked", "model.10.conv_block.2.running_mean", "model.10.conv_block.2.running_var", "model.10.conv_block.2.num_batches_tracked", "model.10.conv_block.6.running_mean", "model.10.conv_block.6.running_var", "model.10.conv_block.6.num_batches_tracked", "model.11.conv_block.2.running_mean", "model.11.conv_block.2.running_var", "model.11.conv_block.2.num_batches_tracked", "model.11.conv_block.6.running_mean", "model.11.conv_block.6.running_var", "model.11.conv_block.6.num_batches_tracked", "model.12.conv_block.2.running_mean", "model.12.conv_block.2.running_var", "model.12.conv_block.2.num_batches_tracked", "model.12.conv_block.6.running_mean", "model.12.conv_block.6.running_var", "model.12.conv_block.6.num_batches_tracked", "model.13.conv_block.2.running_mean", "model.13.conv_block.2.running_var", "model.13.conv_block.2.num_batches_tracked", "model.13.conv_block.6.running_mean", "model.13.conv_block.6.running_var", "model.13.conv_block.6.num_batches_tracked", "model.14.conv_block.2.running_mean", "model.14.conv_block.2.running_var", "model.14.conv_block.2.num_batches_tracked", "model.14.conv_block.6.running_mean", "model.14.conv_block.6.running_var", "model.14.conv_block.6.num_batches_tracked", "model.15.conv_block.2.running_mean", "model.15.conv_block.2.running_var", "model.15.conv_block.2.num_batches_tracked", "model.15.conv_block.6.running_mean", "model.15.conv_block.6.running_var", "model.15.conv_block.6.num_batches_tracked", "model.16.conv_block.2.running_mean", "model.16.conv_block.2.running_var", "model.16.conv_block.2.num_batches_tracked", "model.16.conv_block.6.running_mean", "model.16.conv_block.6.running_var", "model.16.conv_block.6.num_batches_tracked", "model.17.conv_block.2.running_mean", "model.17.conv_block.2.running_var", "model.17.conv_block.2.num_batches_tracked", "model.17.conv_block.6.running_mean", "model.17.conv_block.6.running_var", "model.17.conv_block.6.num_batches_tracked", "model.18.conv_block.2.running_mean", "model.18.conv_block.2.running_var", "model.18.conv_block.2.num_batches_tracked", "model.18.conv_block.6.running_mean", "model.18.conv_block.6.running_var", "model.18.conv_block.6.num_batches_tracked", "model.20.running_mean", "model.20.running_var", "model.20.num_batches_tracked", "model.23.running_mean", "model.23.running_var", "model.23.num_batches_tracked". 
```
__Question 1:__
I found that `__patch_instance_norm_state_dict` is the way you fixed this. But my pytorch=0.4.1 so it shouldn't make a difference, any ideas? Is it because your pre-trained model was trained on a pytorch < 0.4?

__Question 2:__
Running your code, I got the same error as the original post, but it can be solved with '--no_dropout` option. The problem is, I went through your all your code and I couldn't find out what difference does '--no_dropout' makes for `test.py` or `test_model.py`. For cycle-gan, dropout is always false, right?

Appreciate your time.
CY
