### ISSUE TITLE
Two queston:1.Your website is 404. 2.could you transfer professional DSLR photographs to smartphone snaps? 

### ISSUE THREAD

**Issue by zychen2016** [junyanz/pytorch-CycleGAN-and-pix2pix#468]
1.https://taesung89.github.io/cyclegan/2017/03/25/monet-to-photo-trainset.html
2. In your pre_trained model, you only offered the model that transfer smartphone photos to DSLR photo,
do you  try to transfer DSLR to smartphone photos?
if you have do that,could you share your model？
Thanks.

**Comment by taesungp** [comment]
Sorry, we don't have that model... Please train a new model. Thanks!
