### ISSUE TITLE
How do I apply identity loss --identity 1.0

### ISSUE THREAD

**Issue by kaltu** [junyanz/pytorch-CycleGAN-and-pix2pix#469]
In the FAQ [The color gets inverted from the beginning of training](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#the-color-gets-inverted-from-the-beginning-of-training-249)
It says

>  try using identity loss `--identity 1.0` or `--identity 0.1`.

However, if I add `--identity 1.0` to the arguments list.
The code simply not expecting this argument.
`train.py: error: unrecognized arguments: --identity 1.0`

Do I need to manually modify the code itself to add identity?
If so, which line in which file should I modify?

**Comment by junyanz** [comment]
Please use ``-lambda_identity``. I will update the Q & A.
