### ISSUE TITLE
"empy range for randrange()" when training with "--resize_or_crop crop"

### ISSUE THREAD

**Issue by Hunterwolf88** [junyanz/pytorch-CycleGAN-and-pix2pix#471]
Hello there,

I run into this error while training:

`File "/home/hunterwolf/anaconda3/envs/pic/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-23, -23)
`

I noticed that this happens when I add the "--resize_or_crop crop" to my script.

This is the script I use to start the training:

`python train.py --dataroot ./datasets/pic --name pic_cyclegan --model cycle_gan --no_dropout --display_id 0 --continue_train --loadSize 1500 --fineSize 300 --resize_or_crop crop --save_latest_freq 500`

In my dataset I have various sized squared/rectangle images with the minimum resolution of 300x300 px.

**Comment by junyanz** [comment]
[This](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#valueerror-empty-range-for-randrange-390-376-194) might be related.

**Comment by Hunterwolf88** [comment]
thank you, it was :)
