### ISSUE TITLE
Training problems

### ISSUE THREAD

**Issue by Nikocchen** [junyanz/pytorch-CycleGAN-and-pix2pix#472]
I was using my datasets in the format required.But when i was runing train.py.The program just runs to Networks initialized.No error,no warning.Could you help me about my problem.Thanks a lot!

My training datasets about 226  128*128 images.I was using a remote server.

**Comment by junyanz** [comment]
Could you try to run our code on the default datasets first?

**Comment by Nikocchen** [comment]
Thanks a lot.I solved my problems.
