### ISSUE TITLE
Are transformations syncronized?

### ISSUE THREAD

**Issue by ChristianEschen** [junyanz/pytorch-CycleGAN-and-pix2pix#473]
Hi

I am working on an application where I need to use cycle gans for unpaired image-to-image translatations.
Are the transformation used on the data syncronized? Do I apply the same random crop to both image A and image B?

**Comment by junyanz** [comment]
It's synchronized in pix2pix. It's not synchronized in CycleGAN.  For unpaired case, we can assume that data are not aligned.

**Comment by ChristianEschen** [comment]
thank you.
