### ISSUE TITLE
reducing number of epochs

### ISSUE THREAD

**Issue by Praddmobile** [junyanz/pytorch-CycleGAN-and-pix2pix#475]
Hi! i can't find an option to reduce number of epochs? can i set it or I can just stop training after certain epoch?

**Comment by junyanz** [comment]
See this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/train_options.py#L21). You can use `--iter` and `--iter_decay`.

**Comment by Praddmobile** [comment]
thank you!
