### ISSUE TITLE
test.py -- object has no attribute 'lambda_identity'

### ISSUE THREAD

**Issue by joanneschan** [junyanz/pytorch-CycleGAN-and-pix2pix#477]
See my comment here:

https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/cf116ecf4d8fb2d8d8225853f8c1c338e7973ed0

**Comment by junyanz** [comment]
I just fixed it in the latest commit.

**Comment by joanneschan** [comment]
Thanks. 👍
