### ISSUE TITLE
error in attempting to train - no such file 'checkpoints/[directory]/latest_net_G_A.pth'

### ISSUE THREAD

**Issue by heaversm** [junyanz/pytorch-CycleGAN-and-pix2pix#485]
Hi - I'm attempting to follow the directions to train a model. I've set up a data directory with images in folders trainA and trainB. I now run:

```python test.py --dataroot ./datasets/instrument_wikiportraits --name instrument_wikiportraits --model cycle_gan --phase train```

and get the error

```No such file or directory: './checkpoints/instrument_wikiportraits/latest_net_G_A.pth'```

Am I forgetting a step in attempting to train a model? Shouldn't that file/directory be generated in the process of training?

**Comment by junyanz** [comment]
You should use `train.py` to train your models. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#cyclegan-traintest) for more details.

**Comment by heaversm** [comment]
Just saw that. Added a small PR that might clarify the steps for others. Thanks!

**Comment by junyanz** [comment]
Cool. Thanks. I merged your PR.
