### ISSUE TITLE
Invalid argument "reflesh" + problem of visdom visualization

### ISSUE THREAD

**Issue by SunHaozhe** [junyanz/pytorch-CycleGAN-and-pix2pix#488]
I run 
`bash ./datasets/download_cyclegan_dataset.sh monet2photo`
`python -m visdom.server`
`python train.py --dataroot ./datasets/monet2photo --name monet2photo_cyclegan --model cycle_gan`

I got an error after some iterations of training with invalid argument "reflesh" in __init__().

I think this error is a typo in the line 163 of ./util/visualizer.py :
`webpage = html.HTML(self.web_dir, 'Experiment name = %s' % self.name, reflesh=1)`

I think it should be "refresh" instead of "reflesh".

Furthermore, there is a problem of visualization of visdom while training on monet2photo, as shown here:
<img width="1107" alt="capture d ecran 2019-01-04 a 15 52 50" src="https://user-images.githubusercontent.com/26926814/50694026-0e439080-1039-11e9-9a8a-acf9e23f83a8.png">
The labels are not made properly.

**Comment by junyanz** [comment]
Thanks for pointing out the issues. It should be fixed with the latest commit.
