### ISSUE TITLE
is it possible to make it work on rectangular (i.e. height<>width) images?

### ISSUE THREAD

**Issue by ianni67** [junyanz/pytorch-CycleGAN-and-pix2pix#49]
I need to work on rectangular (height != width) images. What would it take to adapt this software to my needs? Any hints avoiding me to go through the whole code would be welcome.
Thank you.

**Comment by yeguixin** [comment]
I try to modify the aligned_dataset.py as follows:
---------------------------------------------------------------
        AB = AB.resize((160 * 2, 70), Image.BICUBIC)
        AB = self.transform(AB)

        self.opt.loadSize = 160
        self.opt.fineSize = 160
----------------------------------------------------------------
Here the size of my image is 160*70pix，but error occurs when runing train.py. The erroe messagge is:
RuntimeError: CUDNN_STATUS_BAD_PARAM
I don't know where is wrong. Did you solved it? @ianni67 
In addition, can the program only to train square images? @junyanz 
Thank you.

**Comment by junyanz** [comment]
The current code assumes `width==height`.  However, it is possible to modify the code to work on the rectangular cases.  You need to modify the dataset class under `/data` subdirectory.

**Comment by ianni67** [comment]
Thank you very much for your kind response. I made a fork of the project, where I'm playing with the code. I hope you don't mind. If I find anything useful, I'll let you know.
Currently my main change actually implements the change in the size of the slices, as described in the changelog.

**Comment by yeguixin** [comment]
Can the forking project  train the rectangle images? If it can, how to set the options? @junyanz

**Comment by ianni67** [comment]
you have to set the desired width and height in config.py and songToData.py

**Comment by yeguixin** [comment]
Thanks. But I didn't find the config.py and songToData.py in the project. Could you give me a link? Thanks again.

**Comment by ianni67** [comment]
I'm very sorry. I got confused in my previous post, as I have two related projects with similar issues.
The height has to be passed as a parameter in your command line, see the file base_options.py in the options folder.
Also make sure that --resize_or_crop is set to no-resize
and the no-flip switch is set in your command line.

**Comment by yeguixin** [comment]
Got it. Thanks for your timely replay Suppose the size of the image is 160*70pix. I can set in the command line as "--loadSize 160 --loadHeight 70 --resize_or_crop no-resize no_flip". Isn't is?

**Comment by ianni67** [comment]
yeah you get this error because you're using the "aligned" mode, but the code in my fork is only modified to work on rectangular images with the "unaligned" mode.

**Comment by yeguixin** [comment]
When I use the unaligned dataset. I encounter the error as follows:
------------ Options -------------
batchSize: 1
beta1: 0.5
checkpoints_dir: ./checkpoints
continue_train: False
dataroot: ./datasets/captcha/
dataset_mode: unaligned
display_freq: 100
display_id: 1
display_port: 8097
display_single_pane_ncols: 0
display_winsize: 256
fineSize: 100
gpu_ids: [0]
identity: 0.0
input_nc: 3
isTrain: True
lambda_A: 100.0
lambda_B: 10.0
loadSize: 100
lr: 0.0002
max_dataset_size: inf
model: pix2pix
nThreads: 2
n_layers_D: 3
name: captcha_model
ndf: 64
ngf: 64
niter: 100
niter_decay: 100
no_flip: False
no_html: False
no_lsgan: True
norm: batch
output_nc: 3
phase: train
pool_size: 50
print_freq: 100
resize_or_crop: scale_width
save_epoch_freq: 5
save_latest_freq: 5000
serial_batches: False
use_dropout: False
which_direction: AtoB
which_epoch: latest
which_model_netD: basic
which_model_netG: unet_256
-------------- End ----------------
CustomDatasetDataLoader
dataset [UnalignedDataset] was created
#training images = 20000
pix2pix
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    model = create_model(opt)
  File "/home/nisl/gxye/program/pytorch-CycleGAN-and-pix2pix_rectangle/models/models.py", line 10, in create_model
    assert(opt.dataset_mode == 'aligned')
AssertionError

Where the command line as follows:
python train.py --dataroot ./datasets/captcha/ --name captcha_model --model pix2pix --which_model_netG unet_256 --which_direction AtoB --lambda_A 100 --dataset_mode unaligned --no_lsgan --norm batch --loadSize 100 --fineSize 100 --resize_or_crop scale_width

I read the code in details to analyze the reason and found that the pix2pix model has to use the aligned dataset. That is the training images must to be square using pix2pix model. Isn't it?  Sorry for do not clear which model that I used before. Nevertheless, Thank you very much.

**Comment by ianni67** [comment]
@yeguixin yes you are right. At the time being, the code for pix2pix still requires square image.

**Comment by junyanz** [comment]
It only depends on the generator. You are free to use 'resnet_6blocks' or 'resnet_9blocks' which should support some rectangular inputs. I think 'unet_128' and 'unet_256' only support square input images. There are other workaround solutions. (1) You can load the image as rectangular images, and crop square patches for example. Or (2) resize the image to a square image, run the training/test,  and resize the result back to the original rectangular image during the test time.
