### ISSUE TITLE
Is it possible to specify which model to test ?

### ISSUE THREAD

**Issue by SunHaozhe** [junyanz/pytorch-CycleGAN-and-pix2pix#493]
Let's say I have multiple checkpoints under the `./checkpoints/.../` folder, 

30_net_G_A.pth
30_net_G_B.pth
120_net_G_A.pth
120_net_G_B.pth
200_net_G_A.pth
200_net_G_B.pth
latest_net_G_A.pth
latest_net_G_B.pth
etc.

It seems that the script `test.py` only test with `latest_net_G_... .pth`. Is it possible to choose to test with `120_net_G_... .pth` without renaming the file or modifying the code provided ? Renaming checkpoints can be a problem if there are 200 checkpoints to test.

I didn't find the answer by reading README or existing issues.

**Comment by junyanz** [comment]
Please use '--epoch'. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L53) for more details.

**Comment by SunHaozhe** [comment]
Thank you for the help.
