### ISSUE TITLE
How to change schedule of number of D iterations vs G iterations

### ISSUE THREAD

**Issue by gvenkat21** [junyanz/pytorch-CycleGAN-and-pix2pix#496]
Hi,

Just want to know how to tweak pix2pix code if i want to stop generator from training for a few iterations and if I want to train discriminator more or vise-versa.

Thanks

**Comment by junyanz** [comment]
It is not implemented in this repo.  You can separate the D and G optimization into two functions, and add a for loop in the training code. 

People find that using different learning rates for G and D might be more effective than using a different number of iterations.  See this [paper](https://arxiv.org/abs/1805.08318) for more details.
