### ISSUE TITLE
Generating large images

### ISSUE THREAD

**Issue by aabramovrepo** [junyanz/pytorch-CycleGAN-and-pix2pix#497]
Hello everyone, 

  first of all, some great work here! I have the following question. I would like to translate [GTA 10K images](https://fcav.engin.umich.edu/sim-dataset) of 1914 x 1052 px to Cityscapes style (2048 x 1024 px). My goal is to train Faster RCNN on the modified images, which requires the shorter side of the image to be 600. Would this be possible with Pytorch CycleGAN architecture on GTX Titan X? I have been playing with load_size and crop_size value a bit, but the desired size does not seem to fit into the memory.

Thanks a lot in advance for any help!

Best,
Alexey

**Comment by junyanz** [comment]
You can crop patches during training and run the model on full images during test time. We have precomputed Cityscape->GTA results. See our [webpage](https://junyanz.github.io/CycleGAN/) "Driving Applications" for more details.  Also, see our recent work [CycADA](https://arxiv.org/abs/1711.03213).

**Comment by JamesChenChina** [comment]
@junyanz  hello, do you have pre-trained model that can transfer GTA to Cityscape? 
Many thanks

**Comment by junyanz** [comment]
@taesungp
