### ISSUE TITLE
A confusion on these two lines of code

### ISSUE THREAD

**Issue by Naruto-Sasuke** [junyanz/pytorch-CycleGAN-and-pix2pix#502]
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/4cd98a5ddd6c7444edc26423e2894ce83b74a73a/models/pix2pix_model.py#L65-L66

Why does the internal `L1Loss()` need no `.to(self.device)` ?

**Comment by SsnL** [comment]
Because this particular module doesn’t own any buffer/weights. So doing .to or not doesn’t matter.
