### ISSUE TITLE
How can we use this code if i want to test a model for image at a time

### ISSUE THREAD

**Issue by vikasgandham** [junyanz/pytorch-CycleGAN-and-pix2pix#507]
We have an etl pipeline which splits the pdf into page images (bytes) as spark dataframe. Now i want to run/test pix2pix model one row at a time, can we do this with custom dataset or any other way?

I tried creating custom dataset to construct openCV image from bytes.I see this works for smaller data but as the data increases i see memory spike, so not sure if i made the changes right.

And since i want to run one row at a time i don't really need a dataset(since i don't iterate on), but based on my understanding code works off of dataset objects so instead of __get_item function i am defining a new function get_data which takes bytes as input.This function would be called for each row
within spark dataframe

I am setting all the initialization part like creating model, creating datasets only once not for each row but still i see memory issues.

Note:
1) I am a Software Engineer, so not familiar with data science concepts, working on using this 
into our etl pipeline to determine segments

2) The code that i wrote for custom dataset is little older it not as per your new template for dataset,
but want to know if the usecase is feasible and can be implemented using this code

3) I tried testing it on 60 gb cpu with 16 cores.

[custom_dataset.txt](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/files/2794634/custom_dataset.txt)

**Comment by junyanz** [comment]
You don't have to use any dataset class. You can replace this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/test.py#L56) with your own data pipeline. You can modify the `test` function and feed your data as input.

**Comment by vikasgandham** [comment]
If you check the custom_dataset.txt attached in previous comment its just a plain object with a new function called get_data.This function has the code from unaligned_dataset's _get_item which reads 
image from bytes and has code to convert into tensors.And when i test it i am actually using something like this

`custom_dataset = CustomAlignedDataset(opt)
 img_map= custom_dataset.get_data(resized_b)
  model.set_input(img_map)
  model.test()
`

this is because test function of pix2pix model expects a map with {'A','B','A_paths','B_paths'}. When you mean modify the test function i hope that is models test() method, what i need to modify i don't think it takes raw bytes it has to be converted in some form.

And the bigger question is, i somehow got it working for smaller data like if i have 5 to 6 pdfs which would have around 150 pages, so i am trying too debug if the pix2pix code is memory intensive or 
i am screwing something integrating this into spark etl code which is making memory intensive.

**Comment by junyanz** [comment]
There might be a memory leak in your code. You should be able to load one image, apply pix2pix, clear both CPU and GPU memory, and process the next image.

**Comment by vikasgandham** [comment]
Another question when i copied the code from aligned dataset __getitem__(self, index) method to my method, and passed that result to model.set_input() and model.test() it failed with this error message

 ****Expected 4-dimensional input for 4-dimensional weight [64, 3, 4, 4], but got input of size [4, 2048, 2048]****

When i digged though the dataset and dataloader  code i found somewhere **default_collate()** function is being called on the result from dataset's _getitem.

So i am calling that function at the end once i get the dictionary with {'A','B','A_paths','B_paths'}.

Do you know if **default_collate** function is needed at the end to convert it , i am suspecting if this is causing memory issue.I dont know what it does but that resolved the "channels error above" so i added that.If that is not needed how could i resolved the above error.

If my comments does not make any sense please check the code that is attached in my first comment, you might understand what i am talking about.

**Comment by junyanz** [comment]
I am not sure if `default_collate` is related. Maybe you want to make sure that your tensor size is correct. It should be a 4D tensor (batchsize x channels x height x width).

**Comment by vikasgandham** [comment]
Is the pix2pix model memory intensive while testing?

I have logged some info before calling test method and after calling test
This is what i am observing for the first image which is 6.5 gig

Memory for process 99648 before test is 531.2109375
Memory for process 99648 after test is 6935.40234375

And for the subsequent images its little less but first one is taking up a lot of memory.

Is this expected?

**Comment by junyanz** [comment]
It depends on your input image size. U-Net is a relatively big model.

**Comment by tjusxh** [comment]
I also encounter the same question. Anyone resolve the question?

**Comment by taesungp** [comment]
@tjusxh which part of this thread are you referring to?

**Comment by tjusxh** [comment]
when I  run the test part  of the pix2pix.

**Comment by tjusxh** [comment]
> @tjusxh which part of this thread are you referring to?

Expected 4-dimensional input for 4-dimensional weight [64, 3, 4, 4], but got input of size [4, 2048, 2048], I make sure my input is not [64,3,4,4]

**Comment by taesungp** [comment]
What kind of data are you using? 

The input to the deep neural generator network (`netG`) should be a 4-dimensional tensor, arranged in the order of (batch size, num channels, height, width). It looks like your input to the layer is not a 4 dimensional tensor, although it should be a 4 dimensional tensor with 64 channels

**Comment by tjusxh** [comment]
Thanks very much. I resolve the question by unsqueeze(0) adding the channel.

**Comment by taesungp** [comment]
Awesome!
