### ISSUE TITLE
Is modify_commandline_options ever called?

### ISSUE THREAD

**Issue by Roulbac** [junyanz/pytorch-CycleGAN-and-pix2pix#514]
I get the idea of letting models setting the defaults that are specific to them; like the cyclegan using lsgan by default or the pix2pix using vanilla gan by default; but is the modify_commandline_options ever called?
I did a quick search through the repo for 'modify_commandline_options' and didn't find a single call.
Is this a bug?

**Comment by junyanz** [comment]
It is called [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/a0f535fa5998c254b171cc67d85529aec3b0fef9/options/base_options.py#L75). [get_option_setter](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/a0f535fa5998c254b171cc67d85529aec3b0fef9/models/__init__.py#L48) will return a function object `modify_commandline_options`.
