### ISSUE TITLE
Generated Images have noise in them

### ISSUE THREAD

**Issue by shreyasbapat** [junyanz/pytorch-CycleGAN-and-pix2pix#518]
I am getting a lot of a patterned noise in the generated dataset. Any known reason?
![die](https://user-images.githubusercontent.com/24257914/52461725-4b4df600-2b96-11e9-9edf-dab81f90f027.png)

**Comment by 3DTOPO** [comment]
It usually improves after a number of epochs. How many epochs was that trained for?

**Comment by shreyasbapat** [comment]
It's 200 epochs!

**Comment by 3DTOPO** [comment]
How many images are in your training set?

**Comment by shreyasbapat** [comment]
1500. Every image size is around 390x190

**Comment by shreyasbapat** [comment]
@junyanz Can you help?

**Comment by junyanz** [comment]
I am not sure what caused it.

**Comment by shreyasbapat** [comment]
Can more epochs fix it?

**Comment by prash-p** [comment]
I get the same noise patterns in my checkpoint images when using 128x350 images, more epochs don't seem to fix the problem.

**Comment by junyanz** [comment]
If you keep getting the checkboard artifacts, you can try different upsampling layers. See this [post] for more [details](https://distill.pub/2016/deconv-checkerboard/).  There is a [PR](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/pull/382) related to this.

**Comment by shreyasbapat** [comment]
Right! My solution also lead to similar direction. Meanwhile that PR has some merge conflicts!

**Comment by CaelynCheung1996** [comment]
I have the same patterns when training the CycleGAN. However, it only happens in one direction (translating StyleA to StyleB). Any idea what might cause this? My Style A images are in higher resolution and B is lower resolution. Thx!
