### ISSUE TITLE
[CycleGAN] Training one generator and one discriminator only

### ISSUE THREAD

**Issue by LilNader** [junyanz/pytorch-CycleGAN-and-pix2pix#520]
Hello, is it possible to train two neural networks only (1 generator and 1 discriminator) instead of four Networks? 
I'd like to decrease the GPU load and train on many batches. I'm concerned about training CycleGAN Image translation model to one domain only, I don't care about the other domain.
Where can I apply this modification in the code?
Thanks in advance!

**Comment by junyanz** [comment]
To use CycleGAN, you have to train 4 networks simultaneously. Removing one or two networks will hurt the performance of the training. If you have paired input-output data, you can consider using pix2pix which only needs two networks.

**Comment by John1231983** [comment]
Thanks. So if we have pair data, which one is better: CycleGan or pix2pix?

**Comment by LilNader** [comment]
CycleGANs are for unpaired data while pix2pix are used for paired data

**Comment by John1231983** [comment]
Yes. If they are applying to paired data, is cycleGAN better than pix2pix? I think cycleGAN also can apply for paired data, as the paper mentioned

**Comment by junyanz** [comment]
I will recommend that you use pix2pix or pix2pixHD for paired cases. In the paper, we used some pix2pix datasets, but we didn't use the paired information.
