### ISSUE TITLE
Using pix2pix to generate only one label while keeping other portion as-is.

### ISSUE THREAD

**Issue by michaelhsieh42** [junyanz/pytorch-CycleGAN-and-pix2pix#523]
Hi,
I would like to try out the pix2pix model for an application where I would only need the model to generate just one label while keeping all other part of the image from the source. Muck like photo inpainting illustrated in the original paper but for a semantic label. Take cityscape dataset as an example, I just want to have the model create "cars" for me while the road, trees, signs, buildings should all come from the original source image. 

My question is, how should I prepare the dataset? My thought is to have the source RGB image as "A", while in "B" image to replace the cars in the source image with a fix RGB value such as

<img width="500" alt="cityscape_b" src="https://user-images.githubusercontent.com/17433802/52576688-995d3680-2dee-11e9-83b5-ecf3806f57da.png"> 

Is this the proper way to setup the dataset? Is the model going learn "only" from the cars and generate only cars in testing?

Thanks a lot.

**Comment by junyanz** [comment]
You can also just predict a car segmentation `car_segment`. During the test time, you can compute original_image * (1-car_segment) + yellow_color * car_segment.

**Comment by michaelhsieh42** [comment]
Thanks for your input. Are you suggesting training with the full set of labels and taking only the cars in test time? Is what I am doing (learning just from cars) going to produce anything different from learning from everything?

**Comment by junyanz** [comment]
You need surrounding pixels (context) to detect cars. I recommend using the original image as input.

**Comment by michaelhsieh42** [comment]
@junyanz could you please elaborate a bit more? Why does it need to "detect" cars when there's already labels on the cars in the image B? By the way, I meant to do label-to-image (BtoA) translation.

**Comment by junyanz** [comment]
I see. You are translating images from B to A. I was confused before. You can just use the entire image as input.
