### ISSUE TITLE
Parameter selection for gray image?

### ISSUE THREAD

**Issue by John1231983** [junyanz/pytorch-CycleGAN-and-pix2pix#524]
I am using cycle GAN with UNet generator to translation from T1 to T2 in the medical image. Both are gray images with size of `1x256x256` (CxHxW). 

![t1_t2](https://user-images.githubusercontent.com/24875971/52603038-00044380-2e33-11e9-9101-d66db62b35a9.png)

I am wondering about the parameters `opt.input_nc, opt.output_nc, opt.ngf` in the

https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/690470c80bb7021d96c9d3f82e416e633dbb2da3/models/cycle_gan_model.py#L73

What should I choose? In my opinion, it should be 1 for  `opt.input_nc=1, opt.output_nc=1, ` and `opt.ngf=8`. Thanks

**Comment by junyanz** [comment]
You can set `--input_nc 1` and `--output_nc ` and leave opt.ngf as default. You may want to try Resnet architecture as well.

**Comment by John1231983** [comment]
Thanks. It worked now. Just for your suggestion, unet has more parameters and larger checkpoints MB. What is the benefit of using resnet comparison with unet? When should I use resnet?

**Comment by taesungp** [comment]
We do not have a definite answer for that. Resnet tends to make less changes and work better when two domains are similar.
