### ISSUE TITLE
`--no_dropout` during testing

### ISSUE THREAD

**Issue by cy-xu** [junyanz/pytorch-CycleGAN-and-pix2pix#529]
> Could you add `--no_dropout`? Make sure that you use the same `--netG` and `--norm` option during training and test.

_Originally posted by @junyanz in https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/461#issuecomment-446005658_

Hello Jun-Yan,

A follow up question probably related to `--no_dropout` option during testing.

I adapted your code into a simplified cycle-gan only version. To verify my implementaiton, I tried to test with your pre-trained model __horse2zebra__. My model looks exactly same as yours when printed out, the training works, but I got the following error from testing (with exact same opts from testing, same `use_dropout = False`).
```
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Unexpected key(s) in state_dict: "model.2.running_mean", "model.2.running_var", "model.2.num_batches_tracked", "model.5.running_mean", "model.5.running_var", "model.5.num_batches_tracked", "model.8.running_mean", "model.8.running_var", "model.8.num_batches_tracked", "model.10.conv_block.2.running_mean", "model.10.conv_block.2.running_var", "model.10.conv_block.2.num_batches_tracked", "model.10.conv_block.6.running_mean", "model.10.conv_block.6.running_var", "model.10.conv_block.6.num_batches_tracked", "model.11.conv_block.2.running_mean", "model.11.conv_block.2.running_var", "model.11.conv_block.2.num_batches_tracked", "model.11.conv_block.6.running_mean", "model.11.conv_block.6.running_var", "model.11.conv_block.6.num_batches_tracked", "model.12.conv_block.2.running_mean", "model.12.conv_block.2.running_var", "model.12.conv_block.2.num_batches_tracked", "model.12.conv_block.6.running_mean", "model.12.conv_block.6.running_var", "model.12.conv_block.6.num_batches_tracked", "model.13.conv_block.2.running_mean", "model.13.conv_block.2.running_var", "model.13.conv_block.2.num_batches_tracked", "model.13.conv_block.6.running_mean", "model.13.conv_block.6.running_var", "model.13.conv_block.6.num_batches_tracked", "model.14.conv_block.2.running_mean", "model.14.conv_block.2.running_var", "model.14.conv_block.2.num_batches_tracked", "model.14.conv_block.6.running_mean", "model.14.conv_block.6.running_var", "model.14.conv_block.6.num_batches_tracked", "model.15.conv_block.2.running_mean", "model.15.conv_block.2.running_var", "model.15.conv_block.2.num_batches_tracked", "model.15.conv_block.6.running_mean", "model.15.conv_block.6.running_var", "model.15.conv_block.6.num_batches_tracked", "model.16.conv_block.2.running_mean", "model.16.conv_block.2.running_var", "model.16.conv_block.2.num_batches_tracked", "model.16.conv_block.6.running_mean", "model.16.conv_block.6.running_var", "model.16.conv_block.6.num_batches_tracked", "model.17.conv_block.2.running_mean", "model.17.conv_block.2.running_var", "model.17.conv_block.2.num_batches_tracked", "model.17.conv_block.6.running_mean", "model.17.conv_block.6.running_var", "model.17.conv_block.6.num_batches_tracked", "model.18.conv_block.2.running_mean", "model.18.conv_block.2.running_var", "model.18.conv_block.2.num_batches_tracked", "model.18.conv_block.6.running_mean", "model.18.conv_block.6.running_var", "model.18.conv_block.6.num_batches_tracked", "model.20.running_mean", "model.20.running_var", "model.20.num_batches_tracked", "model.23.running_mean", "model.23.running_var", "model.23.num_batches_tracked". 
```
__Question 1:__
I found that `__patch_instance_norm_state_dict` is the way you fixed this. But my pytorch=0.4.1 so it shouldn't make a difference, any ideas? Is it because your pre-trained model was trained on a pytorch < 0.4?

__Question 2:__
Running your code, I got the same error as the original post, but it can be solved with `--no_dropout` option. The problem is, I went through your all your code and I couldn't find out what difference does '--no_dropout' makes for `test.py` or `test_model.py`. For cycle-gan, dropout is always false, right?

Appreciate your time.
CY

**Comment by cy-xu** [comment]
@junyanz I think I have answered my first question. I copied your `__patch_instance_norm_state_dict` function and your pre-trained model now works with my implementation. However, the results look different... All output images from `my test.py` + `your pre-traied model` looks darker than your results... interesting... 

One thing I have not implement yet is the image pool, but my understanding is that it is not involved during testing process. Any suggestions? Could it caused by the `__patch_instance_norm_state_dict`?

![n02381460_1010_fake_b](https://user-images.githubusercontent.com/24612082/52766727-f1f22680-2fdc-11e9-8b65-ec47fc653180.png)
![horse2zebra_fake_1](https://user-images.githubusercontent.com/24612082/52766747-03d3c980-2fdd-11e9-8cf9-4a789e7749f9.png)

I'm training a new horse2zebra model tonight with my `train.py` and will keep you posted for results.

**Comment by cy-xu** [comment]
![horse2zebra_fake_1](https://user-images.githubusercontent.com/24612082/52906369-38bf6680-31ff-11e9-9829-f479a80e9383.png)
Epoch 60 of a retrained model from my implementation. 

Hi @junyanz, I fixed the dark output issue simply by normalize. I simply used `tv.utils.save_image`. My second question remain unsolved, if you can help. Thank you!

**Comment by junyanz** [comment]
Image pool is not related to `__patch_instance_norm_state_dict` and not being used during test time. It can improve training stability but it is optional.

**Comment by cy-xu** [comment]
Thanks. But what changes does '--no_dropout' option make for test.py or test_model.py ?

From the code it seems dropout is always false for cycle gan but we do get the error from original post if not including that option. 

Thanks!

**Comment by junyanz** [comment]
CycleGAN uses `--no_dropout` by default. (test.py will a CycleGAN class). `test_model.py` does not use `--no_dropout` by default. Therefore, you need to add `--no_dropout`.

**Comment by cy-xu** [comment]
I see. I must have missed something. Thank you :)

**Comment by junyanz** [comment]
Cool. You are welcome.
