### ISSUE TITLE
A question regarding dropout and latent vector x

### ISSUE THREAD

**Issue by TheIllusion** [junyanz/pytorch-CycleGAN-and-pix2pix#53]
Dear authors of pytorch-CycleGAN-and-pix2pix,

I have a question regarding latent vector x for CycleGAN. 

A while ago, I read a paper related to pix2pix. According to the paper, the random noise is applied to GANs by using dropout. 

I can also see that there's a dropout option for CycleGAN.
However, it seems that dropout is off by default(if it is not specified). 

So I have a question.
Is the dropout option is the way to provide randomness for CycleGAN?
And if the option is off, does the generator produce the same output every time? 

Thanks for your great work.

**Comment by junyanz** [comment]
We haven't tried the dropout for CycleGAN. I guess it might make it more difficult to reconstruct the original input image. Currently, the option is off and will produce the same output.

**Comment by TheIllusion** [comment]
Dear junyanz,

Thanks for your quick reply.
