### ISSUE TITLE
strange error when restarting training

### ISSUE THREAD

**Issue by javismiles** [junyanz/pytorch-CycleGAN-and-pix2pix#530]
hi friends

having a problem here restarting a training

- trained 53 epochs
- stopped training, got and saved my 
latest_net_G_A.pth
latest_net_G_A.pth
latest_net_D_A.pth
latest_net_D_B.pth
files

then run this command to restart training

!python CYC/train.py --dataroot fd --name hz --update_html_freq 100 --print_freq 50 --save_epoch_freq 1 --checkpoints_dir hztemp --display_id -1 --model cycle_gan --continue_train --epoch_count 54

but I get this strange error that you see below, any help?
"RuntimeError: storage has wrong size: expected -4874980492039885429 got 9408"

strange because the pth files occupy 44 megabytes the G ones and 10 megabytes the D ones, what's that error referring to? thank you

output of running the command:

----------------- Options ---------------
               batch_size: 1                             
                    beta1: 0.5                           
          checkpoints_dir: hztemp                        	[default: ./checkpoints]
           continue_train: True                          	[default: False]
                crop_size: 256                           
                 dataroot: fd                            	[default: None]
             dataset_mode: unaligned                     
                direction: AtoB                          
              display_env: main                          
             display_freq: 400                           
               display_id: -1                            	[default: 1]
            display_ncols: 4                             
             display_port: 8097                          
           display_server: http://localhost              
          display_winsize: 256                           
                    epoch: latest                        
              epoch_count: 54                            	[default: 1]
                 gan_mode: lsgan                         
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: True                          	[default: None]
                 lambda_A: 10.0                          
                 lambda_B: 10.0                          
          lambda_identity: 0.5                           
                load_iter: 0                             	[default: 0]
                load_size: 286                           
                       lr: 0.0002                        
           lr_decay_iters: 50                            
                lr_policy: linear                        
         max_dataset_size: inf                           
                    model: cycle_gan                     
               n_layers_D: 3                             
                     name: hz                            	[default: experiment_name]
                      ndf: 64                            
                     netD: basic                         
                     netG: resnet_9blocks                
                      ngf: 64                            
                    niter: 100                           
              niter_decay: 100                           
               no_dropout: True                          
                  no_flip: False                         
                  no_html: False                         
                     norm: instance                      
              num_threads: 4                             
                output_nc: 3                             
                    phase: train                         
                pool_size: 50                            
               preprocess: resize_and_crop               
               print_freq: 50                            	[default: 100]
             save_by_iter: False                         
          save_epoch_freq: 1                             	[default: 5]
         save_latest_freq: 5000                          
           serial_batches: False                         
                   suffix:                               
         update_html_freq: 100                           	[default: 1000]
                  verbose: False                         
----------------- End -------------------
dataset [UnalignedDataset] was created
The number of training images = 451
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
model [CycleGANModel] was created
loading the model from hztemp/hz/latest_net_G_A.pth
Traceback (most recent call last):
  File "CYC/train.py", line 34, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/content/CYC/models/base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "/content/CYC/models/base_model.py", line 187, in load_networks
    state_dict = torch.load(load_path, map_location=str(self.device))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 549, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected -4874980492039885429 got 9408

**Comment by junyanz** [comment]
I haven't seen this error before. According to this [post](https://github.com/roytseng-tw/Detectron.pytorch/issues/107), maybe your file is corrupted. You can try to download the models again. (delete the old ones first)
