### ISSUE TITLE
Poor results after 80 hours of training

### ISSUE THREAD

**Issue by HKH515** [junyanz/pytorch-CycleGAN-and-pix2pix#534]
I'm running train.py on a ~600 image training set, randomly choosing 20 images per run (running on Google Colab has it's limitiations) and the results are quite poor, not sure if the parameters that I'm using are incorrect, but would appreciate any help.

The problem I'm trying to solve is image to image translation on images on brownbears to polar bears.
### Results
Input (Brownbear)
![brown-bear-pictures_216_real_a](https://user-images.githubusercontent.com/5413669/52904269-8947bb80-3221-11e9-8ac8-a71334074b65.png)
Output (Polarbear)
![brown-bear-pictures_216_fake_b](https://user-images.githubusercontent.com/5413669/52904270-89e05200-3221-11e9-9840-1553826d6a12.png)
Input (Brownbear)
![brown_bear_us_fish_real_a](https://user-images.githubusercontent.com/5413669/52904271-89e05200-3221-11e9-9e1f-edb1fb7cff61.png)
Output (Polarbear)
![brown_bear_us_fish_fake_b](https://user-images.githubusercontent.com/5413669/52904272-8a78e880-3221-11e9-9f01-a9f6a0a96a02.png)

The notebook I'm running this on is available ![here](https://github.com/HKH515/brownbear2polarbear/blob/master/brownbear2polarbear_cyclegan.ipynb)

The training command is
```
python pytorch-CycleGAN-and-pix2pix/train.py --dataroot /content/brownbear2polarbear --name brownbear2polarbear_cyclegan --model cycle_gan --continue_train --max_dataset_size 20 --save_epoch_freq 50
```
and the test command is
```
python pytorch-CycleGAN-and-pix2pix/test.py --dataroot /content/brownbear2polarbear --name brownbear2polarbear_cyclegan --model cycle_gan --num_test 155
```

Note that in the notebook link I provided, the training seems to halt a quarter of the way through, this was  due to erreneous stopping and should not be the cause of the problem, as I train for 200 epochs per run when I don't stop it.

**Comment by junyanz** [comment]
What do you mean by randomly choosing 20 images per run? What is your `batch_size`? CycleGAN should not be expected to work for any X, Y combinations. I will see if you can first reproduce horse<->zebra results.

**Comment by HKH515** [comment]
Since I'm running this on a google colab instance, I only have 90 minutes of computation time.
Since running the train script on all of the  ~600 images in trainA and ~600 images in trainB, I randomly choose 20 images from each set to train on, but I was under the impression that this won't be a problem since I'm using the unaligned_dataset option, which is for unpaired images.

My `batch_size` is 1.

I'll try training on the horse2zebra dataset and see if that works.
