### ISSUE TITLE
Looking for pytorch project template

### ISSUE THREAD

**Issue by LightGal** [junyanz/pytorch-CycleGAN-and-pix2pix#536]
I love your code which is structured and clear. I was wondering whether it is based on an existing "pytorch project template for deep learning". I have searched that in your repos but found nothing.

Also, I have noticed that your code contains many base_*.py files. Are these files general and capable enough for a totally different task?

Looking forward to your suggestions. Thanks in advance~

**Comment by junyanz** [comment]
We wrote our own project template from scratch. It should be general enough for other deep learning projects. We used it for other research projects as well.

**Comment by LightGal** [comment]
Thanks for your clarification and suggestions.  Closed.
