### ISSUE TITLE
Inputs with different size

### ISSUE THREAD

**Issue by LilNader** [junyanz/pytorch-CycleGAN-and-pix2pix#537]
Hello, Is it possible to feed both generators images with different sizes without resizing and preprocessing?

In my case, Domain A images are of size 50x100 while Domain B images are of size 50x500 and I want to generate fake Domain B images with size 50x500 from Domain A images (50x100).

What is the simplest approach for my case and where exactly to apply the changes in the code?
Thanks

**Comment by taesungp** [comment]
That will require tweaking the generator architecture a bit. 

The simplest way would be creating the generator to work at the higher resolution, and use `torch.nn.funtional.interpolate` to the generated output to downsample the image to match the lower resolution.

**Comment by patrick-han** [comment]
> That will require tweaking the generator architecture a bit.
> 
> The simplest way would be creating the generator to work at the higher resolution, and use `torch.nn.funtional.interpolate` to the generated output to downsample the image to match the lower resolution.

What if resizing/downsampling is not an option? (in my case it is important to retain the exact values at the same size/resolution for the respective domain) Does the Generator inherently rely on the fact that the inputs/outputs are the same size?

**Comment by junyanz** [comment]
The generator in the current codebase assumes that the input and output have the same size. You can modify the generator's code for your own purpose/sizes (e.g., adding or removing one downsampling/upsampling layer)
