### ISSUE TITLE
B to A training?

### ISSUE THREAD

**Issue by alexiskattan** [junyanz/pytorch-CycleGAN-and-pix2pix#54]
I'm really enjoying the library.  Maybe consider having a flag for training from B->A so the dataset doesn't have to be redone.

**Comment by junyanz** [comment]
Thanks. We do have a flag called `which_direction`. See [base_options](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L28) for more details

**Comment by alexiskattan** [comment]
A thank you!
