### ISSUE TITLE
Pre-trained discriminator model source

### ISSUE THREAD

**Issue by LILeilei66** [junyanz/pytorch-CycleGAN-and-pix2pix#543]
Hi,
If I wasn't mistaken, the pre-trained models published online only contain the generators, but no discriminators? Actually, I am now working on the horse|zebra model,  I would really appreciate it if the pre-trained discriminators are also available.

Thanks in advance.

**Comment by taesungp** [comment]
Sorry but we don't have the discriminators anymore. The only way is to retrain from scratch. Note that the pretrained models do not exactly replicate the results in the paper anyway, because the paper result was produced using the Torch repo.

**Comment by LILeilei66** [comment]
I see. Thanks for the quick response.
