### ISSUE TITLE
Training is good but testing has a problem.

### ISSUE THREAD

**Issue by happsky** [junyanz/pytorch-CycleGAN-and-pix2pix#548]
processing (0000)-th image... []
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f0045c20400>>
Traceback (most recent call last):
  File "/home/Special/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/Special/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/Special/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/Special/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/Special/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/Special/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/Special/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 153, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_SPACE(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "test.py", line 39, in <module>
    save_images(webpage, visuals, img_path, aspect_ratio=opt.aspect_ratio, width=opt.display_winsize)
  File "/home/Special/pytorch-CycleGAN-and-pix2pix/util/visualizer.py", line 13, in save_images
    short_path = ntpath.basename(image_path[0])

**Comment by taesungp** [comment]
the loaded images don't seem to have paths. Are you using your own dataset class?

By default, the name of the result image is used from `A_paths` field of the dict returned in `__getitem__` of `BaseDataset` class. It looks like `A_paths` returned an empty string. As reference, take a look at `__getitem__` function of `data/unaligned_dataset.py` and how it returns `A_paths`.

**Comment by Ha0Tang** [comment]
I am using the default aligned dataset --dataset_mode aligned

**Comment by taesungp** [comment]
@Ha0Tang are you the same person who started this thread? 

That is strange. What batch size are you using? What's the output of `AB_path` of `__getitem__` of `AlignedDataset`? Could you check this and share with me?

**Comment by Ha0Tang** [comment]
Yes, the batch size is 8.
The output of `AB_path` is,

> /data/TH/dataset/test/Case10_1_00000_1_00126.png
> /data/TH/dataset/test/Case10_1_00000__1_01469.png
> /data/TH/dataset/test/Case10_1_00000_1_01683.png
> /home/Special/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:1890: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
>   warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
> processing (0000)-th image... []
> Traceback (most recent call last):
>   File "test.py", line 39, in <module>
>     save_images(webpage, visuals, img_path, aspect_ratio=opt.aspect_ratio, width=opt.display_winsize)
>   File "/home/Special/pytorch-CycleGAN-and-pix2pix_sg2_3_rmadv_changeGs_4_atte_feature10_rml1_attentionboth_12_tv_disloss4_pooling_feature_ego2top_uncertainty4/util/visualizer.py", line 13, in save_images
>     short_path = ntpath.basename(image_path[0])
> IndexError: list index out of range

**Comment by Ha0Tang** [comment]
I have solved it, my bad, misspelling in the file. Thanks for your help.
I will close this thread.

**Comment by taesungp** [comment]
Awesome!

**Comment by wds2wd2** [comment]
> I have solved it, my bad, misspelling in the file. Thanks for your help. I will close this thread.

hi,

I have the same problem as you. How did you solve it?
