### ISSUE TITLE
overwritten option file

### ISSUE THREAD

**Issue by k-fujimt** [junyanz/pytorch-CycleGAN-and-pix2pix#551]
Hi.
When training and testing models, the file 'opt.txt' to store information about the option setting seems to be overwritten if there is an existing opt.txt.
I don't want to overwrite existing opt.txt because sometimes I want to check train options after looking test results.
(Then opt.txt only records test options.)
Do I have to edit base_options.py or some other codes?
Do you have any plans to update this project to avoid overwriting option files?

**Comment by taesungp** [comment]
It is overwritten [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L110). You can change this part to avoid overwriting. We intentionally made it overwritten so that the opt.txt file is always representing the newest options.
