### ISSUE TITLE
It is hard to generate cars?

### ISSUE THREAD

**Issue by happsky** [junyanz/pytorch-CycleGAN-and-pix2pix#552]
When I am using pix2pix to generate scene images, I find everything is ok except cars, as shown in the following figures:
![image](https://user-images.githubusercontent.com/5948971/53503803-6bc2ef00-3a76-11e9-83a7-4048e9d01f22.png)
![image](https://user-images.githubusercontent.com/5948971/53503834-7b423800-3a76-11e9-93c8-ebc5d182373d.png)
![image](https://user-images.githubusercontent.com/5948971/53503860-87c69080-3a76-11e9-910a-14b20dacfdba.png)
![image](https://user-images.githubusercontent.com/5948971/53503895-9614ac80-3a76-11e9-8315-13ae4437b3a6.png)

Any suggestions?

**Comment by SsnL** [comment]
What's your input A?

**Comment by happsky** [comment]
I am doing the cross-view image translation, the input, fake_B, and real_B as follows:

![image](https://user-images.githubusercontent.com/5948971/53504504-b3964600-3a77-11e9-90df-4a8d3ccd0ffd.png) ![image](https://user-images.githubusercontent.com/5948971/53504540-c4df5280-3a77-11e9-9322-062e14a4d2a2.png)

//
![image](https://user-images.githubusercontent.com/5948971/53504674-fce69580-3a77-11e9-8f1d-d1d9c5e3d29f.png)
![image](https://user-images.githubusercontent.com/5948971/53504705-096aee00-3a78-11e9-80a7-0e4158f7d700.png)


//
![image](https://user-images.githubusercontent.com/5948971/53504736-1687dd00-3a78-11e9-9509-b2b9e68645f2.png)
![image](https://user-images.githubusercontent.com/5948971/53504753-21db0880-3a78-11e9-98ee-5ce6ac59680d.png)


//
![image](https://user-images.githubusercontent.com/5948971/53504785-30292480-3a78-11e9-8dc9-e5e2b9dd0b34.png)
![image](https://user-images.githubusercontent.com/5948971/53504806-3d461380-3a78-11e9-8f57-5a8f91c6aa7e.png)

**Comment by SsnL** [comment]
I think your dataset probably has too much geometrical ambiguity (view point), which can be hard for gan to force a reasonable explanation. Maybe try using a larger network?
