### ISSUE TITLE
Realistic image generation

### ISSUE THREAD

**Issue by sudharavali** [junyanz/pytorch-CycleGAN-and-pix2pix#553]
I have a bunch of synthetic images of particular type of drone with sky as background, and another set of images of that drone in flight, In both the datasets the background is sky. Can cyclegan help in adding realism(different lighting conditions, etc) to the synthetic mages I have ? 

What I mean by synthetic is that, a 3d drone model has been rendered and sky is added as the background to it.  Please let me know.

**Comment by taesungp** [comment]
No one knows until you try and see how it looks. It will depend on many factors such as size of the dataset, resolution, diversity within dataset, and the quality and end task you'd like to achieve.
