### ISSUE TITLE
More artifacts with l1 loss than l2 loss

### ISSUE THREAD

**Issue by ligua** [junyanz/pytorch-CycleGAN-and-pix2pix#558]
Hi, I am using cyclegan for image enhancement task. However, I discovered that L1 Loss seems to be have more artifacts than L2 loss. I understand that l1 loss for image is mostly better than L2 loss, it is discussed in pix2pix and ESRGAN and many other papers. However, the artifacts here is still severe, is there any tricks or tips for this?Or did I miss something?

Thank you so much and Best Regards

**Comment by taesungp** [comment]
The quality of CycleGAN translation depends on many factors. If you found that L2 loss worked better for your task, feel free to use L2. Our motivation of using L1 is for sharper images as you pointed out.
