### ISSUE TITLE
Does PatchGAN support images of different input sizes?

### ISSUE THREAD

**Issue by duanyinong** [junyanz/pytorch-CycleGAN-and-pix2pix#561]
Hello:
Thank you very much for your work.  As a newcomer to pytorch.I want to use PatchGAN (NLayerDiscriminator) in the pix2pix model with my own defined generation network. 
My problem is described as follows: 
The important thing is that my dataset image size is different. (if cutting to a uniform size will lose important information)
My build generating network can meet the above conditions, and my generated image is the same size as the original image, but due to the difference in the original image size, the size of the image combined into A_B form is different. I don't know if PatchGAN can accept such different input ? Do you have any suggestions?
Thank you very much for your reply。

**Comment by taesungp** [comment]
As long as you use batch size 1, it should be able to do that with minor code revision. PatchGAN discriminator can work with arbitrary image sizes. The generator, on the other hand, may not directly work because the output size may not be the same as input size.
