### ISSUE TITLE
what is the difference between cyclegan and pix2pix

### ISSUE THREAD

**Issue by andeyeluguo** [junyanz/pytorch-CycleGAN-and-pix2pix#563]
I want to know the difference between cyclegan and pix2pix。
why you put it together。

**Comment by hariv** [comment]
Pix2pix and CycleGAN are both networks for image to image translation between domains. Pix2pix works in a pairwise fashion in that it needs corresponding images from two different domains to learn to translate from one to the other. CycleGAN on the other hand, does not need corresponding images from both domains to learn. It learns a two way mapping between the domains simultaneously.

**Comment by dpmcgonigle** [comment]
Here is a good article explaining the differences:
https://towardsdatascience.com/cyclegans-and-pix2pix-5e6a5f0159c4
