### ISSUE TITLE
Tiff end-to-end using CycleGan

### ISSUE THREAD

**Issue by albusdemens** [junyanz/pytorch-CycleGAN-and-pix2pix#565]
Hi, first of all congratulations for your paper and for the code. It was a pleasure reading what you did and how you did it.

I am running CycleGAN with different types of tiffs in trainA and trainB. The tiffs are 256x256 pixels in size and have 1 channel per pixel. I am using tiffs to have a wide range of values.

I changed the code as you suggest (https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/320 and similar), but what I got out during the training in `./checkpoints` are three-channels PNGs. Do you think it would be possible to change the code so that it goes from 1 channel tiff to 1 channel tiff with no information loss? As far as I understand, at present you are converting the imported files to PNGs along the way. In other words: I would like my tensors to be `[256*256*int_range,1]`. Thanks for the help!

**Comment by taesungp** [comment]
It should be possible, but you will need to change the codes that save the images into .png file, along with using the options `--input_nc 1 --output_nc 1`.

**Comment by albusdemens** [comment]
Thanks for the tip! Have a great week

**Comment by CaelynCheung1996** [comment]
> Hi, first of all congratulations for your paper and for the code. It was a pleasure reading what you did and how you did it.
> 
> I am running CycleGAN with different types of tiffs in trainA and trainB. The tiffs are 256x256 pixels in size and have 1 channel per pixel. I am using tiffs to have a wide range of values.
> 
> I changed the code as you suggest (#320 and similar), but what I got out during the training in `./checkpoints` are three-channels PNGs. Do you think it would be possible to change the code so that it goes from 1 channel tiff to 1 channel tiff with no information loss? As far as I understand, at present you are converting the imported files to PNGs along the way. In other words: I would like my tensors to be `[256*256*int_range,1]`. Thanks for the help!

Hi, I am using the tiff data too. I was wondering what image loader you are using in open the tiff images to load 1-channel grayscale tiff images. Also, did you change the IMG_EXTENSION variable in the file "image_folder.py"? Thx.

**Comment by albusdemens** [comment]
I tried using imageio but that was a while ago... I lost track of how
things went. However, I am sure I changed the IMG_EXTENSION variable.
