### ISSUE TITLE
Number of layers in NLayerDiscriminator

### ISSUE THREAD

**Issue by masontchen** [junyanz/pytorch-CycleGAN-and-pix2pix#567]
Hi, I noticed that the three-layer discriminator actually has 6 convolutional layers ("sequence" has 6 conv2d commands). However, I do not understand how this can result in a receptive field of 70x70, as there seems to be an extra layer compared to what @emilwallner mentioned in https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/39

Thank you!

**Comment by taesungp** [comment]
it should have 5 convolutional layers (note that [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py#L555) the range starts from 1, not 0. ) , and the last two layers don't have `stride=2`. In our code, `NLayerDiscriminator` with `n_layers_D==3` actually means the number of downsampling layers is 3. Sorry it's a bit misleading.
