### ISSUE TITLE
Aspect ratio flag in test.py

### ISSUE THREAD

**Issue by alexiskattan** [junyanz/pytorch-CycleGAN-and-pix2pix#57]
I am trying to use the `--aspect_ratio` flag in `test.py`

`python test.py --dataroot ./datasets/text/testA/  --name text  --model test  --which_model_netG unet_256  --which_direction AtoB  --dataset_mode single --aspect_ratio 2.0`

In the `results` folder though, the images are still 1:1.

**Comment by taesung89** [comment]
I am sorry but --aspect_ratio was not implemented. I will add the code asap.

**Comment by alexiskattan** [comment]
Thank you!  I make the samples square but thought to tell you.  Thanks again for the great library.

**Comment by junyanz** [comment]
We just implemented `aspect_ratio` in the test code. Let us know if it works for you.
