### ISSUE TITLE
load size & crop size lower than 32, it causes error.

### ISSUE THREAD

**Issue by joeljoeljo** [junyanz/pytorch-CycleGAN-and-pix2pix#570]
I want to train a dataset of 16x16, but i faces this error when i set the base options to the following below. I believe is a conv layer issue. When i set it back to 32x32, it is able to run perfectly.
        parser.add_argument('--load_size', type=int, default=16, help='scale images to this size')
        parser.add_argument('--crop_size', type=int, default=16, help='then crop to this size')

Thank you!
----------------- Options ---------------
               batch_size: 1                             
                    beta1: 0.5                           
          checkpoints_dir: /media/sit-np/New Volume/hdd/cyclegan/checkpoints
           continue_train: False                         
                crop_size: 16                            
                 dataroot: /media/sit-np/New Volume/hdd/cyclegan/datasets/cyclefeb_8/16
             dataset_mode: unaligned                     
                direction: AtoB                          
              display_env: main                          
             display_freq: 400                           
               display_id: 1                             
            display_ncols: 4                             
             display_port: 8097                          
           display_server: http://localhost              
          display_winsize: 256                           
                    epoch: latest                        
              epoch_count: 1                             
                 gan_mode: lsgan                         
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: True                                 [default: None]
                 lambda_A: 10.0                          
                 lambda_B: 10.0                          
          lambda_identity: 0.5                           
                load_iter: 0                                    [default: 0]
                load_size: 16                            
                       lr: 0.0002                        
           lr_decay_iters: 50                            
                lr_policy: linear                        
         max_dataset_size: inf                           
                    model: cycle_gan                     
               n_layers_D: 3                             
                     name: experiment_cyclegan                  [default: experiment_name]
                      ndf: 64                            
                     netD: basic                         
                     netG: resnet_9blocks                
                      ngf: 64                            
                    niter: 100                           
              niter_decay: 100                           
               no_dropout: True                          
                  no_flip: False                         
                  no_html: False                         
                     norm: instance                      
              num_threads: 4                             
                output_nc: 3                             
                    phase: train                         
                pool_size: 50                            
               preprocess: resize_and_crop               
               print_freq: 100                           
             save_by_iter: False                         
          save_epoch_freq: 5                             
         save_latest_freq: 5000                          
           serial_batches: False                         
                   suffix:                               
         update_html_freq: 1000                          
                  verbose: False                         
----------------- End -------------------
dataset [UnalignedDataset] was created
The number of training images = 699
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
model [CycleGANModel] was created
---------- Networks initialized -------------
[Network G_A] Total number of parameters : 11.378 M
[Network G_B] Total number of parameters : 11.378 M
[Network D_A] Total number of parameters : 2.765 M
[Network D_B] Total number of parameters : 2.765 M
-----------------------------------------------
WARNING:root:Setting up a new session...
create web directory /media/sit-np/New Volume/hdd/cyclegan/checkpoints/experiment_cyclegan/web...
Traceback (most recent call last):
  File "train_experiment.py", line 51, in <module>
    model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
  File "/home/sit-np/ssd/cyclegan/models/cycle_gan_model.py", line 187, in optimize_parameters
    self.backward_G()             # calculate gradients for G_A and G_B
  File "/home/sit-np/ssd/cyclegan/models/cycle_gan_model.py", line 169, in backward_G
    self.loss_G_A = self.criterionGAN(self.netD_A(self.fake_B), True)
  File "/home/sit-np/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sit-np/ssd/cyclegan/models/networks.py", line 577, in forward
    return self.model(input)
  File "/home/sit-np/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sit-np/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/sit-np/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sit-np/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: std::exception

**Comment by taesungp** [comment]
It's probably because G and D downsample more than 16x16 images. You should reduce the number of downsamplings in G and D.
