### ISSUE TITLE
pix2pix model acc becomes lower after hundeds  epochs

### ISSUE THREAD

**Issue by universewill** [junyanz/pytorch-CycleGAN-and-pix2pix#571]
I find a confusing problem: the pix2pix model acc goes high within several epochs (for example, 150 epochs), and after that , the acc goes down and down... And from the faked imaged i can see the model already get lost.

I can understand why the acc does't go up anymore after many epochs, but i really can not figure out why it goes down and down.

Any hints here?

**Comment by grbagwe** [comment]
is it due to over fitting? ? how many images do you have in your train dataset ?

**Comment by universewill** [comment]
If it is over fitting, i think it will achieve more accurate result on train data. but it is not. The result on train dataset goes bad, and the faked image on train data get total lost.
So i am confused.

I have 1500 image pairs in my train dataset.
And i do some (flip, resize, rotate) to expand it to about 10000 image pairs
@grbagwe

**Comment by universewill** [comment]
Besides, i used pix2pix to train a segment task. Should i use origin unet model other than pix2pix model for my task?
