### ISSUE TITLE
CityScapes of Data preprocessing

### ISSUE THREAD

**Issue by Ricelll** [junyanz/pytorch-CycleGAN-and-pix2pix#575]
@junyanz When Training the model on CityScapes(photo->label), I have a question the how to prepare the pair of data(input,target):
{RGB photo，the ont-hot label map},size is {(3,2048,1024),(30,2048,1024)}
or
{RGB photo，the ont-hot label map},size id {(3,2048,1024),(1,2048,1024)}
or
any else?

**Comment by junyanz** [comment]
We treat the label map as an RGB image in pix2pix and CycleGAN. This encoding will not work if you have too many categories. In more recent work pix2pixHD and [SPADE](https://github.com/NVlabs/SPADE), we treat it as a one-hot label map 30x2048x1024.

**Comment by Ricelll** [comment]
@junyanz  Thanks very much.
