### ISSUE TITLE
Getting a type error while Training

### ISSUE THREAD

**Issue by getamu** [junyanz/pytorch-CycleGAN-and-pix2pix#580]
I am trying to train the model but getting the following error.
` self.dataset = dataset_class(opt)
TypeError: __new__() missing 2 required positional arguments: 'bases' and 'namespace'`

**Comment by Hewenly** [comment]
I first use python2 and find the problem with ABC, later I change ABC to ABCMeta and it comes the similar problems
Later, I use the python3 with ABCMeta, and get the same problem as you, after I change ABCMeta back to ABC, it works

**Comment by getamu** [comment]
Thanks

**Comment by junyanz** [comment]
The current code works with Python 3.
