### ISSUE TITLE
continue_train

### ISSUE THREAD

**Issue by biexiangduo** [junyanz/pytorch-CycleGAN-and-pix2pix#582]

**Comment by biexiangduo** [comment]
when i break train (i.e epoch=3),and I add "--continue_train" in command.But it failed with "no such file named lateset ..."So I just add "--epoch_count 3" 。It seems work,start from epoch 3 but the curve has break relationship of previous curve that epoch1 and 2 show .continue seem isolated and no relation with previous work.

**Comment by k-fujimt** [comment]
You should set `--continue_train --epoch 3 --epoch_count 4` (3 is the current final epoch).
`--epoch` option means which weights is loaded for initialization of networks.
Default value of this option is `latest`, so I think in this case if you don't specify `--epoch` option, initial weights are loaded.
`--epoch_count` option means the start number of epoch count.

In your case, when only `--continue_train` was set, latest weights were supposed to be loaded because you didn't specify `--epoch` option. 
Then "no such file" error occurred because latest weights were not saved yet. 

And when only '--epoch_count 3' was set,  the program started training from scratch with start epoch number 3, because you didn't specify `--continue_train` option.
That's why your curve after epoch 3 had no relationship with epoch 1 and 2.

**Comment by biexiangduo** [comment]
Thanks for update.
I wish to express my appreciation for your help.

**Comment by biexiangduo** [comment]
my last train in epoch 3 ,but not finished. Then I continue"python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --gpu_ids -1 --epoch_count 3"

I try"python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --gpu_ids -1 --continue_train --epoch_count 3" .But show"FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/maps_cyclegan/latest_net_G_A.pth'" 

should I restart from epoch 1?

**Comment by biexiangduo** [comment]
I break down train by "ctrL+c".Would this operation save training?

thanks

**Comment by biexiangduo** [comment]
I think  i forget add "--save_latest_freq" and "--save_epoch_freq" so that I can continue to the latest training

**Comment by junyanz** [comment]
I am glad that you figured it out.

**Comment by Mercury-ML** [comment]
I'm using Colab with gDrive.  I would like to resume training from the last written epoch, in this case 95.  So I've tried adding "--continue_train --epoch 95 --epoch_count 96" to the end of my training command and I get the error: FileNotFoundError: [Errno 2] No such file or directory: ''/content/drive/My Drive/art/training-checkpoints/color_pix2pix/95_net_G.pth'    I've written my checkpoints to gDrive (google drive).  **Weirdly** google drive allows to folders to have the same name (I've never encountered this in any other OS before and when I execute the training command another "train-checkpoints/color_pix2pix" folder gets created with a train_opt.txt file inside.  Any thoughts / ideas on what I should do would be greatly appreciated
Here's the full training command:  
!python train.py --dataroot ./datasets --name color_pix2pix --model pix2pix --direction AtoB --crop_size 1024 --load_size 1144 --display_id 0 --checkpoints_dir '/content/drive/My Drive/art/training-checkpoints' --continue_train --epoch 95 --epoch_count 96

**Comment by ranch-hands** [comment]
> You should set `--continue_train --epoch 3 --epoch_count 4` (3 is the current final epoch).
> `--epoch` option means which weights is loaded for initialization of networks.
> (Default value of this option is `latest`.)
> `--epoch_count` option means the start number of epoch count.
> 
> In your case, when only `--continue_train` was set, latest weights were supposed to be loaded because you didn't specify `--epoch` option.
> Then "no such file" error occurred because latest weights were not saved yet.
> 
> And when only `--epoch_count 3` was set, the program started training from scratch with start epoch number 3, because you didn't set `--continue_train` option.
> That's why your curve after epoch 3 had no relationship with epoch 1 and 2.

Hi There
Do you know how we can test the network on other datasets? please help.
Thanks in advance

**Comment by ranch-hands** [comment]
> I am glad that you figured it out.

Hi There
Do you know how we can test the network on other datasets? please help and describe throughly.
Thanks in advance

**Comment by Mercury-ML** [comment]
Are you using Pix2Pix or Cyclegan?  If pix2pix, this video is helpful:  https://www.youtube.com/watch?v=vrvwfFej_r4&t=1352s

**Comment by ranch-hands** [comment]
> Are you using Pix2Pix or Cyclegan? If pix2pix, this video is helpful: https://www.youtube.com/watch?v=vrvwfFej_r4&t=1352s

I want to use both of them(test my own data on them to see which one is better) but my problem is that I don't know how to give it my own data. can anyone help?

**Comment by Mercury-ML** [comment]
If you like, you can email me at stephena3b3c3 at gmail dot com and I can give you some guidance

**Comment by ranch-hands** [comment]
Hi there

Thanks for your email.
I don't know why github doesn't inform me when people answer me in the
posts.
By the way I'm trying to find a network that is supervised and changes the
pictures to some other pictures.

Best
