### ISSUE TITLE
the problem of runing python -m visdom.server

### ISSUE THREAD

**Issue by qianxiao111** [junyanz/pytorch-CycleGAN-and-pix2pix#583]
![2](https://user-images.githubusercontent.com/32053722/54575734-36d00980-4a30-11e9-87c2-a984740b16dc.png)
When I run this code, the error is appeared.How to solve this problem?

**Comment by junyanz** [comment]
The error is not relevant to this repo. Maybe you want to post it on visdom [repo](https://github.com/facebookresearch/visdom).

**Comment by qianxiao111** [comment]
Thanks. I have a question. I found taht when the number of training sets in X and Y domains is approximately equal, the effect of training is better than that of three or four times the number of images in one domain. Why is that?

**Comment by junyanz** [comment]
I don't know. There are three settings. 
Setting 1. Images A: 1000, Images B: 1000
Setting 2. Images A: 3000, Images B: 1000
Setting 3. Images A: 3000, Images B: 3000

Have you observed that Setting 2 works better than Setting 3? I  understand that Setting 2 works better than Setting 1 as there are more training data.
