### ISSUE TITLE
Are the state of the optimizers being saved?

### ISSUE THREAD

**Issue by saihemanthKGP** [junyanz/pytorch-CycleGAN-and-pix2pix#592]
Are the optimizers state being saved during training so that it can be continued after stopping, with exact same state? It seems only model weights are being saved

**Comment by junyanz** [comment]
I believe only the network weights are being saved in the current codebase. You can easily extend the code to save the state_dict of optimizers. See this [post](https://pytorch.org/tutorials/beginner/saving_loading_models.html) for more details.
