### ISSUE TITLE
How do you use AMT perceptual studies in this project ?

### ISSUE THREAD

**Issue by shuyuandeqipa** [junyanz/pytorch-CycleGAN-and-pix2pix#593]
When I am reading this paper, I find it is amazing to use AMT  to test whether the output image is good or not. But I do not know how to write the HTML files to show our images to the workers so that they can judge our study results correctly, so can you show me the code you use to evaluation your work in the CycleGAN paper !  Thank you !

**Comment by junyanz** [comment]
We follow the [protocol](https://github.com/phillipi/AMT_Real_vs_Fake) written by Phillip Isola.
