### ISSUE TITLE
No ReLU layer at the output of residual block

### ISSUE THREAD

**Issue by deNsuh** [junyanz/pytorch-CycleGAN-and-pix2pix#595]
Thanks for the paper and code, they're very helpful in my learning and research.
While reading [your implementation of residual blocks](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py#L426), I've noticed that there is no ReLU layer at the output of residual blocks. Is there a reason for that? (better performance, etc.?)

**Comment by junyanz** [comment]
There is a ReLU layer in the [middle](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py#L407). We mostly follow the network implementation of [fast-neural-style-transfer](https://github.com/jcjohnson/fast-neural-style/blob/master/fast_neural_style/models.lua#L10). I haven't tested different implementations of resnet blocks.

**Comment by deNsuh** [comment]
Thanks for the reply! I've also seen, from [this blog post on Residual Net](http://torch.ch/blog/2016/02/04/resnets.html), that removing the ReLU layer at the end of residual block slightly improves performance.
