### ISSUE TITLE
How to select number of block in generator network?

### ISSUE THREAD

**Issue by John1231983** [junyanz/pytorch-CycleGAN-and-pix2pix#597]
I am using the Unet generator network. It is clear that the number of blocks related to the image size.  
>For example, # if |num_downs| == 7,      image of size 128x128 will become of size 1x1 # at the bottleneck

https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/fb1b4f1c16191e067a09798444144c3a96707230/models/networks.py#L146

My question is that why we need the 1x1 at the bottleneck for the generator? If I use  num_downs=5 for an image size of 128x128, then I have 4x4 at the bottleneck. What is benefit using 4x4 at the bottleneck in comparison with 1x1? I think 1x1 lost a lost of spatial information. Thanks

**Comment by junyanz** [comment]
Feel free to try `1x1` or `4x4` bottlenecks. I don't think that `1x1` will lose spatial information as U-Net has other skip connections.

**Comment by John1231983** [comment]
Thanks. I tried it and confirm that 4x4 bottleneck reduces the artifact boundary due to the conv2dtransposed operator. I also replace the conv2d transposed with upsampling -pad - conv3x3 but the artifact does not resolve. So, I guess the 4x4 bottleneck may good when we consider detail in the boundary.

**Comment by junyanz** [comment]
Great. Thanks for sharing your tips.
