### ISSUE TITLE
blurred images with my dataset

### ISSUE THREAD

**Issue by giladdiv** [junyanz/pytorch-CycleGAN-and-pix2pix#6]
Hi
first of all you did a very god job!
I am trying to get  realistic airplane images from images of CAD models
when i tried to do it with 2000 images of CAD models and 2000 images of real airplanes those are the result
CAD model:
![02691156_1a32f10b20170883663e90eaf6b4ca52_a035_e014_t001_d003](https://cloud.githubusercontent.com/assets/23100778/25220101/6afac17a-25b9-11e7-8060-4f55cb16a0cd.png)
real image:
![aeroplane_2009_002531_1_1](https://cloud.githubusercontent.com/assets/23100778/25220260/ea7947aa-25b9-11e7-89f4-248a639ae6ec.jpg)

results:
![02691156_1d663e36e305fa8e2178120752ee7a07_a013_e005_t002_d003](https://cloud.githubusercontent.com/assets/23100778/25220142/892d69ae-25b9-11e7-87ef-de88ed5b0db2.png)

Do you think I need more data? more iterations? or that this the best results i should expect regarding the blur effect

**Comment by phillipi** [comment]
Cool! I guess this is CycleGAN, not pix2pix? 2000 images is often enough (e.g., horses2zebras is ~1000 images), and more data does not always help. The distribution of data definitely matters though. Ideally you want the two domains to be as similar as possible -- same kinds of planes, same number of each kind, etc.

I'd definitely let it run a bit longer just to see if it keeps getting better. But this level of blur is pretty common in our results.

**Comment by giladdiv** [comment]
thank you very much!

**Comment by sudharavali** [comment]
Hi @giladdiv , I am currently doing something very similar to what you have done . Can you tell me how many iterations if you have tried this on, any other changes to have made to your code to get the best possible results ?
