### ISSUE TITLE
Forgot to add norm layer in innermost of UnetSkipConnectionBlock?

### ISSUE THREAD

**Issue by zizhaozhang** [junyanz/pytorch-CycleGAN-and-pix2pix#60]
Hi
It seems at [UnetSkipConnectionBlock line 281]( https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py#L281). There needs an extra norm layer after convolution.
Isn't it?

**Comment by taesung89** [comment]
At the innermost layer of UNet, the tensor is of size 1x1. If you normalize it, the value becomes 0, so we did not add normalization layer at the innermost bottleneck.
