### ISSUE TITLE
Requirements.txt problem 

### ISSUE THREAD

**Issue by syenn2896** [junyanz/pytorch-CycleGAN-and-pix2pix#600]
![image](https://user-images.githubusercontent.com/23692343/55422117-df947200-55b5-11e9-8a12-f726d65bb337.png)

![image](https://user-images.githubusercontent.com/23692343/55422143-f0dd7e80-55b5-11e9-8def-ea0c19ba83be.png)

hello I have a problem when I tried to run the requirements. any solution? I am using ubuntu now

**Comment by SsnL** [comment]
You don't have enough memory. See the error.
