### ISSUE TITLE
Something wrong in Unet architecture

### ISSUE THREAD

**Issue by John1231983** [junyanz/pytorch-CycleGAN-and-pix2pix#601]
Hello, I have visualize the Unet architecture and found that it has a different with original unet. In the first layer, it should be concate to the last layer via skip connection. However, you have ignored it to the code

Namely, 
Your network is
```
input (3)-> input /2 --> input/4 -->input/8 ....[input/8*2, input/4] --> [input/4*2, input /2] --> input/2*2 (3)
```
But I think it should be
```
input (3)-> input /2 --> input/4 -->input/8 ....[input/8*2, input/4] --> [input/4*2, input /2] --> [input/2*2, input]-->classification --1x1x1 conv (3)
```

**Comment by junyanz** [comment]
Details are slightly different. But the overall structure is similar.
