### ISSUE TITLE
The training script gets stuck at this.

### ISSUE THREAD

**Issue by AdarshMJ** [junyanz/pytorch-CycleGAN-and-pix2pix#602]
I have succesfully installed the requirements. Im training it on horse2zebra dataset. The training script seems to get stuck at this. Any idea why this is happening?
Im using MacBook Pro with no GPU support. The script I'm running is this  - 

python train.py --dataroot ./datasets/horse2zebra --name horse2zebra_cyclegan --gpu_ids -1

<img width="473" alt="Screenshot 2019-04-03 at 12 21 46 PM" src="https://user-images.githubusercontent.com/24205200/55459103-5bb9a480-560c-11e9-9b6f-26313f61cb60.png">

**Comment by junyanz** [comment]
It might be caused by visdom. Could you activate the visdom server before starting the program?
```bash
python -m visdom.server
``` 
See this [post](https://github.com/facebookresearch/visdom/issues/549) for more details.

**Comment by jxingm** [comment]
Hi,I have met the same problem,have you figured it out? THX.

**Comment by junyanz** [comment]
You can also add `--display_id 0` to disable visdom.

**Comment by jxingm** [comment]
> You can also add `--display_id 0` to disable visdom.

Thans for your reply! but when I add --displat_id 0,I got error like this:
`RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 10 and 11 in dimension 2 at /opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/generic/THCTensorMath.cu:111`

Do you know why?

**Comment by junyanz** [comment]
Did you use `--display_id` or `--displat_id`? Your error seems not to be relevant to the visdom. Are you able to train models with provided datasets? I recommend that you first train a model on provided datasets before using it for your own datasets.

**Comment by jxingm** [comment]
> Did you use `--display_id` or `--displat_id`? Your error seems not to be relevant to the visdom. Are you able to train models with provided datasets? I recommend that you first train a model on provided datasets before using it for your own datasets.

Thanks for your reply.I have solved it by using "scale_width_and_crop" not "scale_and_width". because my datasets have different sizes .
Thanks for your work again!
