### ISSUE TITLE
Reverse order in GAN loss

### ISSUE THREAD

**Issue by njellinas** [junyanz/pytorch-CycleGAN-and-pix2pix#603]
Hi,

Wouldn't it make more sense to put `fake_A` in the equation below, as D_A is responsible for discriminating between real/fake images in the A domain. And also reverse accordingly in backward_D_A and backward_D_B.

https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/95f3a190bfa5e63b269ba331551f9257727d28d4/models/cycle_gan_model.py#L169

**Comment by SsnL** [comment]
No, `D_A` is responsible for discriminating in `B` domain. You can think of it as the paired discriminator for `G_A`.
