### ISSUE TITLE
[Citycapes FCN evaluation] label module not found 

### ISSUE THREAD

**Issue by OliverHe18** [junyanz/pytorch-CycleGAN-and-pix2pix#606]
Hi Junyan,
Thanks for the great work!
I am running the cityscapes evaluation script and got the following error:

Traceback (most recent call last):
  File "./scripts/eval_cityscapes/evaluate.py", line 69, in <module>
    main()
  File "./scripts/eval_cityscapes/evaluate.py", line 28, in main
    CS = cityscapes(args.cityscapes_dir)
  File "/home/yipenghe/pytorch-CycleGAN-and-pix2pix/scripts/eval_cityscapes/cityscapes.py", line 20, in __init__
    labels = __import__('labels')
ModuleNotFoundError: No module named 'labels'

I looked at the source code of cityscapes.py and found your comment at line 18, saying "import cityscapes label helper and set up label mapping". However, I could not find the helper scripts and am really not sure what's wrong with the module "labels". 

Could you please kindly advise how to get over this issue? I look forward to your thoughts.

**Comment by junyanz** [comment]
@tinghuiz

**Comment by junyanz** [comment]
Have you followed the instructions [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#evaluating-labels2photos-on-cityscapes)?

**Comment by OliverHe18** [comment]
> Have you followed the instructions [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#evaluating-labels2photos-on-cityscapes)?

Thank you for your prompt reply Junyan! 
Yes, I have installed Caffe and downloaded the model(in Ubuntu, using CPU). I also ran the command to add to the python path. Then executed the following command to run the script:

python ./scripts/eval_cityscapes/evaluate.py --cityscapes_dir ./datasets/cityscapes/ --result_dir ./results/cityscapes_label2photo_pretrained/test_latest/images --output_dir ./eval/

**Comment by pleaseconnectwifi** [comment]
My situation was similar to yours! That's how I solved it:
Clone this repo [evaluation of the Cityscapes dataset](https://github.com/mcordts/cityscapesScripts/tree/master/cityscapesscripts) and put the **cityscapesscripts** folder into your **cityscapes_dir** and rename it as **scripts**.

**Comment by junyanz** [comment]
Yes, please follow this [instruction](https://github.com/phillipi/pix2pix#evaluating-labels2photos-on-cityscapes).
