### ISSUE TITLE
couldn't communicate with the NVIDIA driver in WSL

### ISSUE THREAD

**Issue by zyzhang1130** [junyanz/pytorch-CycleGAN-and-pix2pix#610]
Hi guys, I tried to use WSL (windows 10 subsystem for linux) as my environment. I have already installed driver, CUDA and Cudnn for both windows and Linux separately but when I use nvidia-smi to check it says "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."  Anyone knows what is going on?

**Comment by junyanz** [comment]
Not sure if it is related to this repo. Could you post it on PyTorch repo or NVIDIA repo?

**Comment by zyzhang1130** [comment]
okay then.
