### ISSUE TITLE
How about adding a flag to decide whether to add SN to D and G ?

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [junyanz/pytorch-CycleGAN-and-pix2pix#611]
SN has been applied to D to stabilize the training of adversarial models. And PatchGAN_SN has been verified its effectiveness in many works (e.g., gated conv, EdgeConnect, also in SPADE) Maybe we can add a flag to define whether to add this stuff to D/G.

**Comment by junyanz** [comment]
@taesungp could you help add one?

**Comment by Zhaoyi-Yan** [comment]
I can help add this in a few days when I am free, if you don't mind.

**Comment by junyanz** [comment]
Yeah, that would be great.
