### ISSUE TITLE
error with "--crop_size" with pix2pix model

### ISSUE THREAD

**Issue by Hunterwolf88** [junyanz/pytorch-CycleGAN-and-pix2pix#612]
Hello there,
I have a paired dataset with just 400 images, many of them with a very high resolution (6000x6000 or more).

Training with cyclegan and "--crop_size 300" works fine, and gives me decent results testing on high resolution images without cropping.

Since my dataset is paired, I want to try it with pix2pix model, but if I add the parameters
`--preprocess crop --crop_size 300`
I get this:
`# crop_size should be smaller than the size of loaded image
AssertionError`
Without this parameter my images are resized.

My smallest image is 320x320px.
what do you think it could be?

**Comment by Hunterwolf88** [comment]
obviously that was caused by the model unet256, that supports images sized 256x256px (and multiples.).
fixed using --crop_size 256.
Probably an alternative model (different than '--netG unet256') can be used to avoid the problem.

**Comment by junyanz** [comment]
`resnet_block6` and `resnet_block9` support more input image sizes.
