### ISSUE TITLE
Why do not use LeakReLU instead of ReLU in upsampling side?

### ISSUE THREAD

**Issue by John1231983** [junyanz/pytorch-CycleGAN-and-pix2pix#613]
In the Unet network, you used LeakReLU at encoding to maintain the weight less than zero. I am wondering what is happen if we use LeakReLU in the up-sampling side (after concatenate and before convtranspose2d)? Do you think we got some improve although training time will be slow?

https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/3a9943cbe22a821a0129b8ae26f2ebb1343bcc16/models/networks.py#L509

Second question I want to ask is that what if I add a VAE block in the bottleneck of Unet? Thanks

**Comment by junyanz** [comment]
We follow the common GAN practice. For example,  the [DCGAN](https://arxiv.org/pdf/1511.06434.pdf) paper states that
```
• Use ReLU activation in generator for all layers except for the output, which uses Tanh.
• Use LeakyReLU activation in the discriminator for all layers.
```
We have explored this idea in follow-up work. It helps to produce different results given the same input.

**Comment by John1231983** [comment]
@junyanz : Cool. I expected VAE can reduce the blur in result but it does not. Could you suggest any paper/method to reduce the blur in the result of cycleGAN. I tried to reduce lamda to 5 but the result is still blurred.

**Comment by junyanz** [comment]
I don't have a method in my mind. VAE probably cannot reduce the blurness of the results. Maybe you can try different network architectures and upsampling [layers](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/217).

**Comment by John1231983** [comment]
Thanks. But I think checkbox artifact and the blur may different one. I meet the checkbox artifact and I just train longer and it is disappear :).

**Comment by yanhuanhuanyy** [comment]
#231
