### ISSUE TITLE
Generators learn permutations of images

### ISSUE THREAD

**Issue by tangbinh** [junyanz/pytorch-CycleGAN-and-pix2pix#617]
My implementation of CycleGAN is very much similar to this implementation, and I'm able to get pretty good images with it using the `vangogh2photo` dataset. The weird thing is that during training both generators often map images to those that are totally different in content, even though this problem never happens during testing. I imagine that powerful generators can totally learn a valid permutation between images, and since we don't have paired data, this is okay with the cycle loss. Does this problem happen to you as well and should we worry about it?

**Comment by junyanz** [comment]
This is possible for some applications, as many permutations could satisfy cycleGAN loss, and it is an ill-posed problem. Two potential improvements could be (1): use a smaller generator (2) add an identity [loss](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#what-is-the-identity-loss-322-373-362) to further regularize the capacity of the network.

**Comment by tangbinh** [comment]
Thank you for your response. Although the problem is theoretically possible, I just realize that it's actually due to a bug in my code, where I plot images coming out of the image buffers.
