### ISSUE TITLE
What is the training time for a K80

### ISSUE THREAD

**Issue by wahlforss** [junyanz/pytorch-CycleGAN-and-pix2pix#621]
Hey,

I'm thinking of implementing CycleGAN from scratch for a school project. 

What is the training time for getting okay results with say the horse2zebra  dataset using a K80?

**Comment by junyanz** [comment]
It is possible. K80 is 2.5 times slower than GTX 1080. Therefore, it might take 2-3 days.

**Comment by anovik** [comment]
I just trained CycleGAN on K80 with summer2winter_yosemite dataset, it took about 3 days. Hope it helps.
