### ISSUE TITLE
how to get idt_A & idt_B images when I test the model?

### ISSUE THREAD

**Issue by Lo0uis** [junyanz/pytorch-CycleGAN-and-pix2pix#627]
Hi there,

I made my own datasets for CycleGAN and trained the model.
When I create testA and testB folders and test, only fake_A, fake_B, real_A, real_B, rec_A, rec_B are generated as output.

I want to get images idt_A and idt_B, but what should I do?

**Comment by junyanz** [comment]
You need to make two changes. 
1. add `idt_A` and `idt_B` to visual_names. See this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/cycle_gan_model.py#L60).
2. generate idt_A and idt_B in the forward [function](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/cycle_gan_model.py#L117).
```python
self.idt_A = self.netG_A(self.real_B)
self.idt_B = self.netG_B(self.real_A)
```
