### ISSUE TITLE
TypeError: 'NoneType' object is not callable, if we set the --norm to 'none'.

### ISSUE THREAD

**Issue by WANG-Chaoyue** [junyanz/pytorch-CycleGAN-and-pix2pix#630]
As described in the title, the kinds of networks' norm are defined through the parameter --norm. Yet, if I set it to None, raise below error:
File "pytorch-CycleGAN-and-pix2pix/models/networks.py", line 493, in __init__
    downnorm = norm_layer(inner_nc)
TypeError: 'NoneType' object is not callable

Very great coding! If this small issue can be fixed, it could be better. Thanks!

**Comment by junyanz** [comment]
Should be fixed by the latest [commit](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/7cdcd5341a53c1d7d01f98ab5cdf0590815792e9).
