### ISSUE TITLE
Style of Other Artists

### ISSUE THREAD

**Issue by galoisgroupcn** [junyanz/pytorch-CycleGAN-and-pix2pix#633]
Hi everyone!

Are there styles of other famous artists available – e.g. Edvard Munch, Pierre-Auguste Renoir, etc. If not, how can I get style_munch, style_renoir, etc? Is there any open-source code to train the style of a particular artist?

As an example, Dr. Fouhey transfered the style of Cloude Monet to Thomas Kinkade.

http://web.eecs.umich.edu/~fouhey//fun/monet/index.html

Could you please tell me how I can do it?

Thank you!

Amber Ji

@junyanz

**Comment by junyanz** [comment]
You need to collect the artwork by yourself using some online [tools](https://github.com/lucasdavid/wikiart) and train a model using our codebase.
For Cloude Monet to Tomas Kinkade, you could contact Dr. Fouhey.
