### ISSUE TITLE
Number of conv layer in U-net wrt. image size

### ISSUE THREAD

**Issue by nobodykid** [junyanz/pytorch-CycleGAN-and-pix2pix#635]
Hello, I'm currently experimenting with GAN and using pix2pix architecture as my base.

Based from your implementation, I see that you use 8-level-depth U-Net for 256\*256 image and 7-level-depth for 128\*128 images. And I noticed that the number of layer corresponds to the power of 2 of the image size.

May I know the reason behind this choice of network architecture? And have you tried with different depth (eg. 256*256 with, say, 10 level of depth)?

**Comment by junyanz** [comment]
In pix2pix work, we followed the architecture of U-Net [paper](https://arxiv.org/abs/1505.04597). For more recent architecture, maybe you would like to try [pix2pixHD](https://github.com/NVIDIA/pix2pixHD) and [SPADE](https://github.com/NVlabs/SPADE).

**Comment by nobodykid** [comment]
What about the number of layers within it? Is there a reason behind it?
I've read the U-net paper, but I didn't see any explicit mention of the reason behind choice of network depth

**Comment by junyanz** [comment]
If you downsample or upsample by 2 every layer, you will get 7=log2(128) and 8=log2(256)

**Comment by nobodykid** [comment]
Thank you. I think this will be my last question for now :

What's the reason behind another loss option, LS-GAN and WGAN?

**Comment by junyanz** [comment]
Ls-gan works better for cyclegan. Ls-GAN and vanilla gan loss work similarly for pix2pix.

**Comment by nobodykid** [comment]
I see, thank you very much for your advice
