### ISSUE TITLE
Can I use AtoB model to BtoA generation？

### ISSUE THREAD

**Issue by kinredon** [junyanz/pytorch-CycleGAN-and-pix2pix#639]
I have trained a model which translate images from data set A to data set B. Then I could use images from A to generate B. How can I use images from B to generate A just use the AtoB model? At test phase, I use the argument `--direction BtoA`, but the generated results seem to be wrong. 

the AtoB test command as follows:

`python test.py --name city2foggy --dataroot datasets/city2foggy/ --model test --dataset_mode city2foggy --preprocess none --num_test 2975`

add `--direction BtoA` for BtoA translation.

**Comment by junyanz** [comment]
I don't think that you can. If you are using pix2pix, you need to train a new model from B->A. If you are using cyclegan, it will come up with models with both directions.
