### ISSUE TITLE
How to add a parameter in Unet?

### ISSUE THREAD

**Issue by xml94** [junyanz/pytorch-CycleGAN-and-pix2pix#640]
I want to add a parameters in Unet.
like this, 
![Screenshot from 2019-05-14 17-54-34](https://user-images.githubusercontent.com/30434881/57684759-63d81b80-7671-11e9-981d-c855f76fed58.png)
But an error appeared: `RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 512, 2, 2]], which is output 0 of ViewBackward, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).`

I tried to find the result but failed, even though I found some informatin at #398 .

By the way, the error are different.

@junyanz 

Thanks a lot.

**Comment by xml94** [comment]
I add the parameter in Networks.py and in module called UnetSkipConnectionBlock.

I suspected there is an imcompatility in loss function or update process.

**Comment by lizhihao6** [comment]
Sorry for bother you, have you solve this error?

**Comment by lizhihao6** [comment]
> Sorry for bother you, have you solved this error?

Alright I have fixed my error.... Pytorch does not support in-place operation...
