### ISSUE TITLE
the problem of python -m visdom.server

### ISSUE THREAD

**Issue by qianxiao111** [junyanz/pytorch-CycleGAN-and-pix2pix#641]
When I input this code, the error is appeared. How to solve this problem?
![11111](https://user-images.githubusercontent.com/32053722/57741270-ac81ea00-76ee-11e9-911a-9d8baddc1873.png)

**Comment by junyanz** [comment]
I am not sure. Maybe you can post the question at the visdom [repo](https://github.com/facebookresearch/visdom).
