### ISSUE TITLE
Problem with visdom.server

### ISSUE THREAD

**Issue by beardoll** [junyanz/pytorch-CycleGAN-and-pix2pix#642]
When I run "python -m visdom.server", there happens:
"OSError: [Errno 98] Address already in use"
How can I solve this problem? The port stays unchanged as 8097 and I don't have any other sessions occupying this port...

**Comment by junyanz** [comment]
You or other people may have started a session. You can try (1) killing the existing visdom jobs, (2)restarting the machine, or (3) using a different display port `--display_port`

**Comment by qianxiao111** [comment]
> You or other people may have started a session. You can try (1) killing the existing visdom jobs, (2)restarting the machine, or (3) using a different display port `--display_port`

I meet the same problem. I use different display port, python -m visdom.server -port=15024, but the display screen shows no images, just blue.
![12345](https://user-images.githubusercontent.com/32053722/58180011-e7ca7d00-7cdb-11e9-9423-1227c296276b.png)

**Comment by junyanz** [comment]
You need to specify the display port when running train.py. See this [argument](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/train_options.py#L18) for more details.

**Comment by qianxiao111** [comment]
> You need to specify the display port when running train.py. See this [argument](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/train_options.py#L18) for more details.

Thank you very much.

**Comment by dorry1996** [comment]
I think maybe it's because you have run "python -m visdom.server" before. All I do is just type localhost:8097 in web browser. And we can see the training results there.
![360截图16240201103544](https://user-images.githubusercontent.com/46192647/58312905-dfd71e00-7e3e-11e9-9a38-b84ffa91be32.png)

**Comment by qianxiao111** [comment]
![5等级](https://user-images.githubusercontent.com/32053722/58444151-5c147e80-8129-11e9-8093-ec6a8b0ad6ea.png)
> You need to specify the display port when running train.py. See this [argument](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/train_options.py#L18) for more details.
I want to generate two different levels' distortion images, the source domain consists of 4744 non-distortion images, when the 400 small gaussian blur images are included in target domain, the generation images is shown in the left. When the 400 severe gaussian blur images are included in target domain, the generation images is shown in the right.  In theory the quality of the slight distortion image should be better than that of severe distoriton, but I failed by using cyclegan. Do you know what could lead to this and what would be a good way to improve?
![1等级](https://user-images.githubusercontent.com/32053722/58444143-5159e980-8129-11e9-84a9-af1cfac29a43.png)

**Comment by junyanz** [comment]
If you just deal with gaussian blur, you can use a much smaller network.

**Comment by qianxiao111** [comment]
> If you just deal with gaussian blur, you can use a much smaller network.

Thanks，but I need  to  generate some multiple distortion (such as jpeg and gaussian blur) or gaussian noise. Is it feasible to reduce network structure?

**Comment by junyanz** [comment]
I think so. Both jpeg and gaussian blur are local effects.

**Comment by qianxiao111** [comment]
> I think so. Both jpeg and gaussian blur are local effects.

Thanks, when I reduce the number of Resnet blocks in generator network and use the code of remove the checkerboard artificats, the effect is better. How to explain it? Is it because there are few samles in target domain?

**Comment by junyanz** [comment]
Reducing the number of Resnet blocks can make the network's capacity smaller. This might be helpful when your task only involved small and local changes. You don't need a big network for modeling small changes.

**Comment by qianxiao111** [comment]
> Reducing the number of Resnet blocks can make the network's capacity smaller. This might be helpful when your task only involved small and local changes. You don't need a big network for modeling small changes.

Thanks，when debuging the code, I  find the input of D network is 256*256.  Is this correct?

**Comment by junyanz** [comment]
It depends on the `crop_size`. If your `crop_size` is 128, the input to D is 128*128.

**Comment by qianxiao111** [comment]
> It depends on the `crop_size`. If your `crop_size` is 128, the input to D is 128*128.

Thanks, I want to added the perceptual loss of the VGG network. When i change the code, i found a error. Could you help me?

**Comment by qianxiao111** [comment]
> It depends on the `crop_size`. If your `crop_size` is 128, the input to D is 128*128.

Thanks, could you help me? I want to add the perceptual loss of VGG to cyclegan method. However, I find this error is presented. I change the codes of network.py and cycle_gan.py.



 
![A](https://user-images.githubusercontent.com/32053722/60382252-1124b880-9a93-11e9-9f9b-f592dd56d2d0.png)

**Comment by junyanz** [comment]
It seems that you haven't calculated loss_G_A. You can either remove 'G_A' from visual_names or calculate the loss_G_A.

**Comment by qianxiao111** [comment]
> It seems that you haven't calculated loss_G_A. You can either remove 'G_A' from visual_names or calculate the loss_G_A.

Thans very much. I have a problem, the number of images under certain distortion type is relatively small. Can I mix images with some different distortion types to generate distortion images?  Do these distortion types need to be similar? such as global distortion or local distortion.

**Comment by junyanz** [comment]
Similar distortion will be ideal.

**Comment by lbq779660843** [comment]
Based what u discussed above, I run the commands as the following and it works to me:
         (1)run the python script in a new terminal:
` python -m visdom.server -port=15024`
             plues:if it prints error,you can look through all ports by run the command 'netstat -antu' and then make sure whether the port '15024' has been taken)
         (2)if u run the first command successfully , u can get the imformation just like this 
![Capture](https://user-images.githubusercontent.com/27773249/61097878-78793a00-a48f-11e9-8b72-205cc0ce0513.JPG)
              then I can see the result after copying the website in the broswer :
              http://30-0001-21910:8097/
![333](https://user-images.githubusercontent.com/27773249/61098117-6cda4300-a490-11e9-9113-475370d3e509.JPG)

**Comment by qianxiao111** [comment]
> Similar distortion will be ideal.

Thanks, I have one problem, if I want to generate the real distortion(the distortion types is not known), I don't easily judge the real distortios are transfered to the undistorted images.How to judge whether the generated images is right? Could you give me some advice?

**Comment by junyanz** [comment]
If you can determine whether the generated image is correct, you could use it to evaluate the algorithm. See some recent denoising [work](http://openaccess.thecvf.com/content_cvpr_2018/papers/Chen_Image_Blind_Denoising_CVPR_2018_paper.pdf) for more details.

P.S: I closed the issue as the original visdom issue has been resolved.
