### ISSUE TITLE
How to know if parameters and architecture are good despite the training time

### ISSUE THREAD

**Issue by davicorreiajr** [junyanz/pytorch-CycleGAN-and-pix2pix#648]
Hi, first of all, I got amazed with the project! I started learning deep learning recently and this project (well documented, by the way) helped me to better understand GANs. Congratulations!

So, I'd like to play around with the parameters, maybe change, remove or add a layer/function in the architecture to see how they impact the results. But I'm a bit lost about the best way to do it; I mean, I've seen that a good training would take a couple of days. Is there a faster way to train the net to have an idea if the results might be good or should I really wait all this time (couple of days)? What's the fastest way to analyse if some change is gonna produce results similar to the paper?

Thanks in advance!

**Comment by junyanz** [comment]
I recommend that you try the new parameters/architectures on low-resolution images or small image datasets.
