### ISSUE TITLE
Continuing training always start from epoch 1 again

### ISSUE THREAD

**Issue by tyathalae** [junyanz/pytorch-CycleGAN-and-pix2pix#65]
Hi, when I halt my training at some point (i.e. epoch 40) and want to continue it later, I give
 `--continue_train --which_epoch 40` 
arguments to the train.py but when it starts training, it begins from epoch 1 again. Because of that, output HTML files are being overwritten.
You can check the attached `loss_log.txt` file.
[loss_log.txt](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/files/1164832/loss_log.txt)

**Comment by junyanz** [comment]
Yes, it will restart the epoch count, and rewrite the results webpage. Maybe one can add a  '--epoch_count' flag to address this issue. Feel free to send a pull request if you can fix it.  Otherwise, we will look at it later.

**Comment by junyanz** [comment]
I just added the `--epoch_count` flag. By default, the program will initialize the epoch count as 1. Set `--epoch_count` to specify a different starting epoch count.

**Comment by tyathalae** [comment]
Great news, thank you for the update!
