### ISSUE TITLE
How about re-ordering gpu_ids ?

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [junyanz/pytorch-CycleGAN-and-pix2pix#653]
How about changing this snippet:
```python
        os.environ["CUDA_VISIBLE_DEVICES"]=opt.gpu_ids # new added
        str_ids = opt.gpu_ids.split(',')
        opt.gpu_ids = []
        for str_id in str_ids:
            id = int(str_id)
            if id >= 0:
                opt.gpu_ids.append(id)
        # re-order gpu ids
        opt.gpu_ids = [i.item() for i in torch.arange(len(opt.gpu_ids))] # new added
```

Original code:
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/7cdcd5341a53c1d7d01f98ab5cdf0590815792e9/options/base_options.py#L125-L131

In this case, when we want to get the relative gpu_id in running models, we doesn't get something like '3,6,7', instead we obtain re-ordering relative indexes: '0,1,2'.  Usually, When absoulte gpu_ids is useless in running the code, yet relative gpu_ids are useful in debuging multi-gpu models as we need to get the relative gpu_ids by `torch.cuda.current_device()`

**Comment by junyanz** [comment]
It's up to individual's preference. Some folks like to use CUDA_VISIBLE_DEVICE while others are not. Feel free to modify the code as you like.
