### ISSUE TITLE
ways to predict semantic label

### ISSUE THREAD

**Issue by lzhbrian** [junyanz/pytorch-CycleGAN-and-pix2pix#657]
Hi, thanks for the code.
I have a question about the way to predict semantic label when doing *-to-semanticLabel experiments.

Say we have C kinds of semantic labels.
Did the network outputs HxWxC (i.e. each semantic label is a channel and is one hot)
or it just outputs HxWx3, where each color represents some semantic label?

**Comment by junyanz** [comment]
I recommend that you output HXWXC.

**Comment by lzhbrian** [comment]
Thanks!
