### ISSUE TITLE
the problem of test path

### ISSUE THREAD

**Issue by qianxiao111** [junyanz/pytorch-CycleGAN-and-pix2pix#658]
I have a problem, when I test the test sets. Then I test the current path as shown in fig.2. How can i modify the first path.
![QQ图片20190529110205](https://user-images.githubusercontent.com/32053722/58526320-3195f480-8201-11e9-96b9-c9ef8453b1d4.png)
![21122](https://user-images.githubusercontent.com/32053722/58526366-5722fe00-8201-11e9-81ee-fa01950f1809.png)

**Comment by junyanz** [comment]
You can modify [dataroot](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L23).
