### ISSUE TITLE
Bug in combine_A_and_B.py?

### ISSUE THREAD

**Issue by SimpleXP** [junyanz/pytorch-CycleGAN-and-pix2pix#66]
In line 18: splits = os.listdir(args.fold_A)
splits store all the image files in fold_A

line 20: for sp in splits:
sp is each image name in splits

line 21: img_fold_A = os.path.join(args.fold_A, sp)
this line make img_fold_A the actual path of each image in fold_A, so img_fold_A is a image path, not a folder anymore

line 23: img_list = os.listdir(img_fold_A)
this line try to list all the image in img_fold_A, but img_fold_A is a image path, not a folder, so this line will return an error

An I correct? Or did I misunderstand the script?

**Comment by SimpleXP** [comment]
After I check again, seems I put the images into wrong folder, so it's not a bug after all. 
Issue closed.

**Comment by parseb** [comment]
I think the folder structure is unclear, "dataset" and "datasets". I'm trying to figure this out. @SimpleXP  can you mention the issue you encountered?

**Comment by parseb** [comment]
I think the my problem was different filetypes. Hope I'm wrong.
