### ISSUE TITLE
i am observing issue with snli model with pytorch examples

### ISSUE THREAD

**Issue by streamhsa** [junyanz/pytorch-CycleGAN-and-pix2pix#660]
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    torch.cuda.set_device(args.gpu)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 264, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: 'module' object has no attribute '_cuda_setDevice'

Note : i am running snli model on AMD GPU(Vega20) on ROCm driver .

**Comment by junyanz** [comment]
We haven't tested our code on AMD GPU. @SsnL

**Comment by SsnL** [comment]
You can’t (yet) use AMD GPUs with pytorch.
