### ISSUE TITLE
Testing pix2pix unpaired photo

### ISSUE THREAD

**Issue by TiburonEl** [junyanz/pytorch-CycleGAN-and-pix2pix#661]
Hi,
Could someone help me with testing the pix2pix model on unpaired images?
The script test.py requires paired data, but I would like to provide only input image and see what the model will generate.

**Comment by junyanz** [comment]
Check out instruction [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-pix2pix).

**Comment by TiburonEl** [comment]
Thanks, I will try. I had some error but I guess it is sth wrong in my code

**Comment by kalai2033** [comment]
@TiburonEl , Hi , Iam also trying to test the pix2pix model for unpaired image. Please let me know how did you run the test.
