### ISSUE TITLE
-- model test not working?

### ISSUE THREAD

**Issue by hpwarren** [junyanz/pytorch-CycleGAN-and-pix2pix#662]
When I use the "--model test" option to run a trained model on new input I get an error:

> No such file or directory: './checkpoints/my_project_cyclegan/latest_net_G.pth

The checkpoint directory has these files
  latest_net_G_A.pth
  latest_net_G_B.pth

but no "latest_net_G.pth".

is "latest_net_G.pth" file generated differently than the files generated during training or is this a bug?

Note that I am able to train and test models just fine. It is only when I use the "test" model on a single input image that I run into problems.

**Comment by patrick-han** [comment]
I believe this is related to issue #233 ?

**Comment by junyanz** [comment]
You need to rename it to `latest_net_G.pth` manually.

**Comment by hpwarren** [comment]
That was actually the first thing I tried, but I got an error when reading the dictionary. Partial output is given below.

Also, I have to confess that I wasn't sure which of these files should be copied to latest_net_G.pth, so I tried both of them and got the same error

latest_net_G_A.pth
latest_net_G_B.pth

----------------- End -------------------
dataset [SingleDataset] was created
initialize network with normal
model [TestModel] was created
loading the model from ./checkpoints/my_project_cyclegan/latest_net_G.pth
Traceback (most recent call last):
  File "test.py", line 47, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
 
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Missing key(s) in state_dict: "model.10.conv_block.6.weight", "model.10.conv_block.6.bias", . . .

**Comment by junyanz** [comment]
Could you also make sure that you use the same `--netG` during training and test?

**Comment by hpwarren** [comment]
For both training and test modes I see this in the options output:
  netD: basic
  netG: resnet_9blocks

**Comment by ninashp** [comment]
Hi, I got the same error as @hpwarren in loading state_dict while using 9blocks ResNet, any suggestions?

**Comment by BenUsesGit** [comment]
Hello,
same problem, same question... any development?

**Comment by junyanz** [comment]
Could you also make sure that you use the same normalization `--norm` during training and test?

**Comment by BenUsesGit** [comment]
> Could you also make sure that you use the same normalization `--norm` during training and test?

I did not change this parameter. Should it be something in particular?

**Comment by BenUsesGit** [comment]
I changed line 199 of base_model.py to:

`net.load_state_dict(state_dict, strict=False)`

Then it worked. But I am not sure whether this can lead to problems with other types of nets.

**Comment by BenUsesGit** [comment]
> I changed line 199 of base_model.py to:
> 
> `net.load_state_dict(state_dict, strict=False)`
> 
> Then it worked. But I am not sure whether this can lead to problems with other types of nets.

Ok, this was not the way to go. It works, but the generated images look nothing like the ones created during the training.

As it turns out, when the cycleGAN is created [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/08af6e49389fe35a0d1c97f8e3b0b68df3535d58/models/test_model.py#L45)  as testmodel object in testmodel.py, that there is a dropout layer generated because the opt.no_dropout flag is negated.
So even if you use the same switches for dropout in training and test, during loading one of the nets there will be errors.

I took away the negation. Then testing or "applying" the generator worked and the images looked like the ones during training.

[G_A_test.txt](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/files/3563452/G_A_test.txt)
[G_A_train.txt](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/files/3563453/G_A_train.txt)

**Comment by junyanz** [comment]
Yes. I forgot to mention that you need to add `--no_drouput` in your test script. It is added automatically in the CycleGAN training code [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/08af6e49389fe35a0d1c97f8e3b0b68df3535d58/models/cycle_gan_model.py#L39).

**Comment by pynsigrid** [comment]
I had met the same problem, and here is a checklist that may help you.

1. Refer to issue #233, the test script should be like [one-direction](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-cyclegan) or [bi-direction](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#cyclegan-traintest). 
2. Check your 'test_opt.txt' for checkpoint file details. Even you use default argparse, it's better to check one more time. ('./scripts/test_single.sh' use different model and params with default).
3. Remember to change the 'latest_net_G_A/B.pth' to 'latest_net_G.pth'. It depends on your input '--direction BtoA/AtoB'.

**Comment by wgansir** [comment]
Even if the default parameter for -- model is cycle_ gan, but when we execute the test command, we still need to add the parameter -- model cycle_ gan, this problem will be solved. As for the specific reasons, I am not clear
