### ISSUE TITLE
docker container not compatible with master branch

### ISSUE THREAD

**Issue by Peetee06** [junyanz/pytorch-CycleGAN-and-pix2pix#666]
Hi there,

I'm trying to train a CycleGAN model on my universities machine learning cluster.
To run your code I'm using the docker container you provided. When running I get an error stating module "abc" was not found. I guess the docker container is running python 2.7?

I tried using the torch0.3.1 branch with which I was able to successfully train the model but then ran into problems while testing (No module named torch) as I want to do that on my local machine. 

I have no experience with docker so I don't know how to create a container that is able to run the master branch. Can you help me with that?
If possible I would like to avoid using the torch0.3.1 branch as I would have to change the environment on my local machine for testing..

**Comment by Peetee06** [comment]
I got it to work.
Used the predefined Dockerfile to build a Docker container.
Then converted that container to a singularity sandbox directory (as the cluster I'm training the CycleGAN on uses singularity containers).
Then I ran the training code inside that container and whenever a module was missing or an error occured I installed/fixed that by shelling into the sandbox.
When the training started successfully I built an immutable image from the sandbox and uploaded it to the cluster filesystem.

**Comment by junyanz** [comment]
@taesungp  Could you have a look?

**Comment by GzuPark** [comment]
When I also try to train using the docker image, I have the same problem as @Peetee06 .
He is right and I solved this problem to install python3(with requirements.txt) in the container.

**Comment by GzuPark** [comment]
I'm not sure, but I found something missing in the [Dockerfile](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/39e6060451c56f56578fd1fb2c3711435fe738a9/docs/Dockerfile).

First of all, [`Miniconda-latest-Linux-x86_64.sh`](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/656b9322f3db490149e9261b3742d6dbb8166c30/docs/Dockerfile#L4) should be replace to `Miniconda3-latest-Linux-x86_64.sh` based on the [Miniconda installer archive](https://repo.continuum.io/miniconda/)

Second, missed a `RUN conda env create -f environment.yml` in the Dockerfile and do more things, or just do it if you download `Miniconda3`.

**Comment by arbrog** [comment]
I was having issues with your Dockerfile which seems to specify [minconda 2 (ie python 2) ](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/8cda06f7c36b012769efac63adc1a68586b8fb85/docs/Dockerfile#L4)while the rest of your code uses [python 3](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/8cda06f7c36b012769efac63adc1a68586b8fb85/environment.yml#L6). I was having issues so I made a Dockerfile using miniconda3 (and CUDA 10.1). Seems like this issue was never fixed but the ticket was closed?

```
FROM nvidia/cuda:10.1-base

RUN apt update && apt install -y wget unzip curl bzip2 git
RUN curl -LO http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -p /miniconda -b
RUN rm Miniconda3-latest-Linux-x86_64.sh
ENV PATH=/miniconda/bin:${PATH}
RUN conda update -y conda

RUN conda install -y pytorch torchvision -c pytorch
RUN mkdir /workspace/ && cd /workspace/ && git clone https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix.git && cd pytorch-CycleGAN-and-pix2pix && pip install -r requirements.txt

WORKDIR /workspace
```

**Comment by taesungp** [comment]
Thank you for the suggestion! I updated the Dockerfile following @arbrog 's suggestion.
