### ISSUE TITLE
CycleGAN: Is there a way to get the score map of patchGAN?

### ISSUE THREAD

**Issue by guomukun** [junyanz/pytorch-CycleGAN-and-pix2pix#667]
Hi there,
Thanks for the great work. Just wondering is there a way that i can get the score map produced by patchGAN in cycleGAN?

**Comment by junyanz** [comment]
You can add some visualization code to visualize `pred_fake` [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/cycle_gan_model.py#L134). It should be a 30x30x1 tensor.
