### ISSUE TITLE
Confusion with CycleGAN testing regarding domains

### ISSUE THREAD

**Issue by patrick-han** [junyanz/pytorch-CycleGAN-and-pix2pix#668]
Hi I am trying to train a CycleGAN such that I can translate images from domain B to domain A. After training the initial model I wanted to test it on some out-of-training-set images from domain B. So I used:

`python test.py --dataroot datasets/my_proj/testB --name my_cyclegan_proj --model test --no_dropout`

However when I open the index.html the view the results I am confused. As I understand it real_A refers to a real image from domain A, however the pictures with this label in the html file are my pictures from the folder testB, which are real images from domain B. 

I've double checked that my trainA, testA and trainB, testB folder contain only the images from their respective domains. Additionally, like some previous issues mentioned I renamed `latest_net_G_B.pth -> latest_net_G.pth`

Does this have something to do with the --direction flag? Or am I still confused about the labeling of the results?

**Comment by junyanz** [comment]
`real_A` means the input images (in your case, test images from domain B). The test code under `--model test` mode will always name the input images as `real_A`.

**Comment by junyanz** [comment]
I got rid of `A` and `B` in test_model.py in the latest commit.

**Comment by Rjaat** [comment]
> ike some previous issues mentioned I renamed `latest_net_G_B.pth -> latest_net_G.pth`

hi @patrick-han can you higjhlight the link for that perticular issue? actually i am stuck at same since i cant find the `latest_net_G.pth`

or shall i rename the `latest_net_G_A.pth` and `latest_net_G_A.pth` for domain A and domain B respectively???
