### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by spladder** [junyanz/pytorch-CycleGAN-and-pix2pix#67]
I am running this on a Mid 2011 IMac OSX 10.10, and so far everything has run smoothly. I am at this step in the instructions:
python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --no_dropout

And I get this as a result:
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    opt = TrainOptions().parse()
  File "/Users/samuellevin/vision/pytorch-CycleGAN-and-pix2pix/options/base_options.py", line 60, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/Users/samuellevin/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 161, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

How do I fix this?

**Comment by junyanz** [comment]
I wonder if you have installed the Pytorch with CUDA support. What's the GPU in your iMac?

**Comment by codytodonnell** [comment]
Try running on CPU by adding the following option: `--gpu_ids -1`

**Comment by rchavezj** [comment]
"--gpu_ids -1" doesn't work on mac sadly...

**Comment by vin-ni** [comment]
any news on this?

**Comment by ZangChaoyu** [comment]
请问在windows中怎样解决AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

**Comment by teevino123** [comment]
![cuda error](https://user-images.githubusercontent.com/58145952/95647380-57672500-0ae8-11eb-834a-bca2fae00318.png)
Hey guys!
I am using windows 10 with only CPU and getting the error mentioned in the screenshot.
How to fix it?
Thank you.

**Comment by junyanz** [comment]
Not sure. It seems to be related to PyTorch. You could post/find the issue on the PyTorch repo.

**Comment by teevino1** [comment]
Thank you so much for your suggestion let me go through on pytorch repo.

**Comment by QasimWani** [comment]
> ![cuda error](https://user-images.githubusercontent.com/58145952/95647380-57672500-0ae8-11eb-834a-bca2fae00318.png)
> Hey guys!
> I am using windows 10 with only CPU and getting the error mentioned in the screenshot.
> How to fix it?
> Thank you.

hey!
were u able to figure out what the problem you had was?
