### ISSUE TITLE
Regarding the Network Architecture of CycleGAN

### ISSUE THREAD

**Issue by sudharavali** [junyanz/pytorch-CycleGAN-and-pix2pix#670]
Hello, 

First of all, thank you for your amazing work. 
I am just having a hard time visualizing the network architecture as to how it is going to take the 256x256 input image and use the downsampling, transformation and upsampling functions on it and with what size of filters and layers. I am looking forward to an architecture that uses 9 resnet blocks. 

Can you please explain that in a better way or point me to a good source with that explanation. Thank you !!

**Comment by sudharavali** [comment]
To be more precise, what would be the number of filters used in the first layer and their size when 256x256 image is given as input.

**Comment by junyanz** [comment]
We implemented the network of Johnson et el.  You can find more details about the network in their [paper](https://cs.stanford.edu/people/jcjohns/papers/fast-style/fast-style-supp.pdf). You can also print the network.

**Comment by sudharavali** [comment]
Thank you so much !
