### ISSUE TITLE
Discrepancy in the input image and the generated image

### ISSUE THREAD

**Issue by sudharavali** [junyanz/pytorch-CycleGAN-and-pix2pix#672]
Hello, 

Thank you for your great work. I trained CycleGAN to generated realistic images from synthetic ones. After training I observed a disturbance : 

This is my input synthetic image : 

![Drone_scene_1025_real_A](https://user-images.githubusercontent.com/33206551/59238804-5c9f2180-8bcd-11e9-9481-360a30dec151.png)

and this is my generated image : 

![Drone_scene_1025_fake_B](https://user-images.githubusercontent.com/33206551/59238806-61fc6c00-8bcd-11e9-8cf5-9d8290b5844a.png)

You can notice how the position of the drone in the generated image with respect to the input image has changed. 

Why do you think that is and what can I do to make sure that the drone remains in the same position.

Please let me know. Thank you !

**Comment by junyanz** [comment]
It seems that drones have different sizes and locations in your source and target domains. One thing you can do is to (1) apply an object (drone) detection method that can predict the bounding box of the drone, (2) crop the drone based on its bounding box and resize it to 256x256.  (3) only apply Cyclegan on cropped images.

**Comment by sudharavali** [comment]
Ohh that seems to be a good solution, when you asked me to collect only "cropped images", did you mean to that for real images ? The real images indeed are very far from the camera and not zoomed in. 

Please let me know, which type of images you were referring to. Thanks alot !

**Comment by junyanz** [comment]
For "cropped images", I mean the output image from step (2). You crop the object and resize it to the same size.

**Comment by junyanz** [comment]
Another thing that you can do is for your simulation environment, you adjust the camera parameters so that your CG drone has the same size as the real drone.

**Comment by sudharavali** [comment]
Alright, correct me if I am wrong. From what I understood, in the first solution given, we need to crop images from the real dataset from its bounding box so that the images are cropped up or (ii) as mentioned in the second solution, the size of the drones in the simulated environment must match the size of the real drone. 
Let me know if this is what you meant, thanks alot for your advice.

**Comment by junyanz** [comment]
Yes.

**Comment by sudharavali** [comment]
Thanks alot !!!
