### ISSUE TITLE
In train.py there is problem.kindly give me the solution

### ISSUE THREAD

**Issue by nehaleosharma** [junyanz/pytorch-CycleGAN-and-pix2pix#673]
import time
from options.train_options import TrainOptions
from data import create_dataset
from models import create_model
from util.visualizer import Visualizer
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-7aa52d21683f> in <module>()
      1 import time
----> 2 from options.train_options import TrainOptions
      3 from data import create_dataset
      4 from models import create_model
      5 from util.visualizer import Visualizer

ModuleNotFoundError: No module named 'options'

**Comment by junyanz** [comment]
Did you run the code inside the main directory? See more information about this error [here](https://stackoverflow.com/questions/43728431/relative-imports-modulenotfounderror-no-module-named-x).

**Comment by nehaleosharma** [comment]
Hello 
Thank you so much for the reply .earlier was doing program on anaconda commnad prompt and facing lot of problems but now have tried it on googlecolab it stop after 2nd epoch and ask to reconnect  .PFA in the last.
1. After reconnecting  the uploaded data disappear what is the solution to get results on googlecolab? 
2. Im using utkface right now with 128*128  image size how long will it take to complete execution .
3. Any further tips to complete the program 

Kindly guide me .As this is my first ever program that im trying to run for my work.
Please reply as soon as possible.
Thanks in advance  for ur guidance 
Regards Neha





Sent from Yahoo Mail on Android 
 
  On Thu, 13 Jun 2019 at 2:50 am, Jun-Yan Zhu<notifications@github.com> wrote:   
Did you run the code inside the main directory? See more information about this error here.

**Comment by junyanz** [comment]
I haven't used the googlecolab so that I cannot give you too many suggestions. The program should tell you the training time per epoch, and you can calculate the total training time from that.

**Comment by nehaleosharma** [comment]
Thanku so much 

Sent from Yahoo Mail on Android 
 
  On Thu, 13 Jun 2019 at 9:46 pm, Jun-Yan Zhu<notifications@github.com> wrote:   
I haven't used the googlecolab so that I cannot give you too many suggestions. The program should tell you the training time per epoch, and you can calculate the total training time from that.
