### ISSUE TITLE
Loading .npy with 4 channels/layers

### ISSUE THREAD

**Issue by patrick-han** [junyanz/pytorch-CycleGAN-and-pix2pix#674]
I believe this is related to #500, but I can't seem to figure out how to pass my 4-channel .npy arrays. After I apply the transforms I get this:

`UserWarning: Using a target size (torch.Size([2, 4, 43, 43])) that is different to the input size (torch.Size([2, 4, 44, 44])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.`

My input arrays are (4,33,33) and (4,43,43). I don't understand where the size 44 is coming from.

**Comment by junyanz** [comment]
I am not sure. Maybe due to this [function](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/base_dataset.py#L115). The program, in general, assumes that the height and width can be divided by 4.

**Comment by patrick-han** [comment]
> I am not sure. Maybe due to this [function](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/base_dataset.py#L115). The program, in general, assumes that the height and width can be divided by 4. (I am trying to directly load the arrays rather than generate an image)

I believe that was the issue, my numpy arrays needed to be divisible by 4. I had commented out [this](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/base_dataset.py#L98) line and needed to manually resize the array.

**Comment by junyanz** [comment]
As a side note, we did this because the network only takes the input that is divisible by 4.

**Comment by patrick-han** [comment]
> As a side note, we did this because the network only takes the input that is divisible by 4.

I see, is there a particular the inputs must be divisible by 4? Would I easily be able to change this for arbitrary dimensions? For my project I can't afford to resize the arrays
