### ISSUE TITLE
ImportError: cannot import name ABC

### ISSUE THREAD

**Issue by gm039** [junyanz/pytorch-CycleGAN-and-pix2pix#678]
Hi,

I am pulling the docker file (_docker pull taesungp/pytorch-cyclegan-and-pix2pix_) and trying to run the following command after running _nvidia-docker run -it taesungp/pytorch-cyclegan-and-pix2pix_.

python train.py --dataroot ./datasets/<Datasertt_Name>--name GAN_cyclegan --model cycle_gan

Error:
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    from options.train_options import TrainOptions
  File "/Container_Folder/options/train_options.py", line 1, in <module>
    from .base_options import BaseOptions
  File "/Container_Folder/options/base_options.py", line 5, in <module>
    import models
  File "/Container_Folder/models/__init__.py", line 22, in <module>
    from models.base_model import BaseModel
  File "/Container_Folder/models/base_model.py", line 4, in <module>
    from abc import ABC, abstractmethod
**ImportError: cannot import name ABC**

Can you please help? Any lead will be appreciated.
Thank you

**Comment by jialiang19** [comment]
Hey @gm039. Could you please check the version of the python you are using? I had similar problem before, since I was using the python2. After the updating to python3, the problem was fixed.

**Comment by SStauden** [comment]
When downloading from [http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh](http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh), how it is specified in the [Dockerfile](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/Dockerfile), Miniconda with python2 automatically gets installed, which does not work with the needed dependencies.

I could solve this issue by replacing `Miniconda-latest-Linux-x86_64.sh` with `Miniconda3-latest-Linux-x86_64.sh` everywhere in the [Dockerfile](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/Dockerfile) and then building the image again. This downloads the latest Miniconda version with python3.

**Comment by gm039** [comment]
@SStauden @jialiang19 Thank you! It worked.

**Comment by suno24** [comment]
@SStauden @jialiang19 Hi,I am having same problem.
I tried your approach,and tried CycleGAN train.
`Traceback (most recent call last):
  File "train.py", line 25, in <module>
    from util.visualizer import Visualizer
  File "/workspace/pytorch-CycleGAN-and-pix2pix/util/visualizer.py", line 8, in <module>
    from scipy.misc import imresize
ImportError: cannot import name 'imresize' from 'scipy.misc' (/miniconda/lib/python3.7/site-packages/scipy/misc/__init__.py)
`
I checked version of python , python3.7.3 .
Could you help.

**Comment by suno24** [comment]
@gm039 @jialiang19 
Hi,I am having same problem.
I tried your approach,and tried CycleGAN train.

Traceback (most recent call last): 
File "train.py", line 25, in <module>
 from util.visualizer import Visualizer 
File "/workspace/pytorch-CycleGAN-and-pix2pix/util/visualizer.py", line 8, in <module>
 from scipy.misc import imresize 
ImportError: cannot import name 'imresize' from 'scipy.misc' (/miniconda/lib/python3.7/site-packages/scipy/misc/__init__.py)

I checked version of python , python3.7.3 .
Could you help.

**Comment by junyanz** [comment]
Could you install the library scipy? See the [instruction](https://www.scipy.org/install.html) here.

**Comment by suno24** [comment]
@junyanz Thanks you. resolved!
