### ISSUE TITLE
how to do an inference using one image at every time?

### ISSUE THREAD

**Issue by lxy443626128** [junyanz/pytorch-CycleGAN-and-pix2pix#679]

**Comment by lxy443626128** [comment]
just like this:
python test.py --model ### \
                     --input input_sample.jpg \
                     --output output_sample.jpg \
                     --image_size 256

**Comment by junyanz** [comment]
It is not supported in the current codebase. You can modify the `test.py` accordingly. You can write code to read and save images using `--input` and `--output`.
