### ISSUE TITLE
What does the --save_by_iter do? 

### ISSUE THREAD

**Issue by shreyasbapat** [junyanz/pytorch-CycleGAN-and-pix2pix#683]
Does it save the checkpoints on every iteration or is it something else?

**Comment by patrick-han** [comment]
Looks like it just changes the suffix of the latest cached model filename to indicate which iteration it was saved on [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/656b9322f3db490149e9261b3742d6dbb8166c30/train.py#L67) (as opposed to just saying 'latest')
