### ISSUE TITLE
Any reason can cause color blocks?

### ISSUE THREAD

**Issue by wadesunyang** [junyanz/pytorch-CycleGAN-and-pix2pix#686]
![image](https://user-images.githubusercontent.com/15172283/60316045-a47ac280-999b-11e9-8e44-789cea49e970.png)
when i use pix2pix train the model,   it can generate the picture with color blocks,   anyone can help me   what reason may cause this problem,  thanks.

**Comment by SerinaWei** [comment]
What is your solution to this problem? I encountered the same issue. Thanks! @wadesunyang
