### ISSUE TITLE
CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 1.96 GiB total capacity; 1.07 GiB already allocated; 12.50 MiB free; 135.23 MiB cached)

### ISSUE THREAD

**Issue by rachitagrwl** [junyanz/pytorch-CycleGAN-and-pix2pix#689]
Hi,

Please guide me solve this issue. I am just following your Github steps to run it successfully.

**Comment by junyanz** [comment]
The program requires more than 2 GB GPU. It seems that your GPU has 2 GB, which is not sufficient to run the program.

**Comment by rachitagrwl** [comment]
I ran it with load_size 128 - I know this will very less frame size. But a quick question is it worth to do that efforts.?

**Comment by junyanz** [comment]
If you use CycleGAN, it will require more than 2GB even with load_size 128.

**Comment by rachitagrwl** [comment]
Okay, any way to compute/hack around to computer over it.?

**Comment by junyanz** [comment]
I am not aware. You can also use GPU cloud computing if you don't buy a new GPU.

**Comment by TavRotenberg** [comment]
Hi, I have a similar error.
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.76 GiB total capacity; 2.42 GiB already allocated; 26.12 MiB free; 2.75 GiB reserved in total by PyTorch).
Is that GPU also too small?

**Comment by kalai2033** [comment]
@TavRotenberg It depends on the input image size. There are chances that other processes are utilizing the gpu memory as well. Please clear it and just use the preprocess flag as --preprocess resize and crop and try to run now. Hope it helps

**Comment by ccfarah** [comment]
For anyone that finds themselves contending with this issue, --crop_size is the specific parameter that allowed me to train the CycleGAN model without bumping into a memory issue. Modified from the default 256 to 128. Training and testing results look reasonable.

**Comment by junyanz** [comment]
+1. please refer to [training & test tips](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#trainingtesting-with-high-res-images) for high-res model training.
