### ISSUE TITLE
Specifying Checkpoint at Test Time

### ISSUE THREAD

**Issue by shreyasbapat** [junyanz/pytorch-CycleGAN-and-pix2pix#691]
How to specify which set of weights to use while testing?

**Comment by junyanz** [comment]
Please use `--epoch`. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L53) for more details.

**Comment by shreyasbapat** [comment]
Oh! I missed that parameter when looking through the fie. Thanks a lot @junyanz
