### ISSUE TITLE
Network Choice for Paired data

### ISSUE THREAD

**Issue by swz30** [junyanz/pytorch-CycleGAN-and-pix2pix#697]
Hi, 

Which network style do think works better in the case of paired data (pix2pix): UNet, ResNet, or any other network architecture that you can recommend?

Thank you.

**Comment by junyanz** [comment]
Both UNet and ResNet should work. See some recent work such as [pix2pixHD](https://github.com/NVIDIA/pix2pixHD) and [SPADE](https://github.com/NVlabs/SPADE) for recent development in network architecture.

**Comment by swz30** [comment]
Thank you.
