### ISSUE TITLE
Do not support python2

### ISSUE THREAD

**Issue by TYLVY** [junyanz/pytorch-CycleGAN-and-pix2pix#7]
```python
from builtins import object
```
`ImportError: No module named builtins`

**Comment by hubertlee915** [comment]
Please try this:
`pip install future --upgrade`

**Comment by TYLVY** [comment]
It has been sovled accroding to your reply, thank you.

**Comment by niranjanshr13** [comment]
@TYLVY close this issue.

**Comment by junyanz** [comment]
Thanks @hubertlee915! I just add the comment "pip install future --upgrade" before the "from builtins import object".
