### ISSUE TITLE
How can i change total epoch count? epoch_count param did not work

### ISSUE THREAD

**Issue by DilaraAlb** [junyanz/pytorch-CycleGAN-and-pix2pix#704]

**Comment by junyanz** [comment]
Please use `--niter` and `--niter_decay`. See the [code](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/train_options.py#L30) for more details. `--epoch_count` is for a different purpose (i.e., continue training).

**Comment by DilaraAlb** [comment]
Thanks
