### ISSUE TITLE
how dataset is created and how model is created in train.py and test.py

### ISSUE THREAD

**Issue by wl082013** [junyanz/pytorch-CycleGAN-and-pix2pix#705]
Sorry for bothering you. The code is very nice and helpful.
I could not understand several definitions in train.py and test.py. 
For instance, dataset = create_dataset(opt), I know this is aimed to create dataset using dataloader, however, there is no create_dataset class defined in dataset folder and same as create_model(opt). 
Since I created my own dataloader reading four directories, and I want to assign each folder to four target domains, so could you give some help on how you created dataset with the class create_dataset? Generally, we use  torch.utilis.data.DataLoader to load image dataset (such as unaligned_dataset.py)
Also create_model, since I also modifed the network structure, but I am kind of confused about the mode_create, how does it function for the model (such as cycle_gan_model).
Thanks for your help.

**Comment by azinonos** [comment]
The create functions are defined in the __init__.py file for every directory, it's good to have a look in there.

**Comment by wl082013** [comment]
thanks  a lot. I found it.  Is there any direct way to load data and set model? Since in my case, I need to load four directories and distribute them to generator and discriminators. 
Thanks a lot

**Comment by junyanz** [comment]
You can implement a custom loading function in your custom class and call the function during training.

**Comment by wl082013** [comment]
Thanks for your help.  I will try
