### ISSUE TITLE
I reduced the image size . but result is poor

### ISSUE THREAD

**Issue by Realdr4g0n** [junyanz/pytorch-CycleGAN-and-pix2pix#707]
Hello, I appreciate to your great research and implementations.
I would like to thank you for doing such a great job.

Anyway, I have a Question.

When I learned with 3x256x256 images , it was fine
but I learn with 1x50x50 image, it is poor

I want to learn with 1(channel) x 50 x 50 image from this model.
So I modify some options

images = A 4000 : B 4000

input_nc = 1
output_nc = 1
load size = 50
crop size = 50 (or preprocessing = none)
batch size = 64 ( when I learn with 3x256x256 image , it was 3) 
epoch = 200 

(Discriminator loss is very poor. this is got 0.00xx when 10~20 epoch.)

I want know that what I modified options is influence to poor generate
and if it is influenced my learn, I want to know how tune the options

Thank you.

**Comment by junyanz** [comment]
You may want to use a smaller generator and a smaller discriminator for low-resolution images. You can remove a few layers from each model.

**Comment by Realdr4g0n** [comment]
Thanks to reply.

As you advised ,I remove some layers and result is greater than I expected 
So, what caused the problem of my experiment is resolution : layers issue

Thanks you very much
