### ISSUE TITLE
Unpaired training noobie question

### ISSUE THREAD

**Issue by gelinger777** [junyanz/pytorch-CycleGAN-and-pix2pix#708]
I apologize for such a  simple question. I am very new to pix2pix, and still discovering it's power.
My initial target is following. 
There is specific style of photos turned to paintings that a CoinTelegraph.com is using 

![image](https://user-images.githubusercontent.com/184276/61377092-d0a2a880-a8a2-11e9-96a8-34abb559be57.png)

or 

![image](https://user-images.githubusercontent.com/184276/61377197-05aefb00-a8a3-11e9-9fee-56e363341f87.png)

I want to  train pix2pix with 1000s of such paintings to turn into a painting like that ones from up. 
Because literally I am not able to create a-b pictures and then train, as I understood I would need unpaired training. 

Could somebody from you  hint me to the script example or doc where I can find ready examples of such a training? 

As I understood I should have like 1000 images in a specific folder, then via command line train the model on them , and then whenever I will put in a photo it will be translated into painting similar to this one. Am I right?

**Comment by junyanz** [comment]
As you don't have pairs, you need to use CycleGAN. Follow the [instruction](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#cyclegan-traintest). You need to prepare two folders. One contains real images. The other contains paintings. Real images need to share similar content with paintings.

**Comment by gelinger777** [comment]
> Real images need to share similar content with paintings.

This is what I cannot digest and understand. What does it mean similar content?  

Should I put in one folder 1000 images from Cointelegraph, and in second one like 1000 random images of people and objects?

**Comment by junyanz** [comment]
Random images of people and objects will not work. Real images should have similar objects. For example, if paintings are about flowers. Your real images should also be about flowers. If your real images have different content such as animals, CycleGAN will not work.

**Comment by gelinger777** [comment]
I see, thank you very much ..
