### ISSUE TITLE
test results are blurred and seem worse than the training results

### ISSUE THREAD

**Issue by hyang23333** [junyanz/pytorch-CycleGAN-and-pix2pix#709]
Thanks for sharing such a wonderful project! When I trained the model with facades, the training results were good seen with carnal eyes, but when I tested the model ,the results are vaguer, also with some noises. Is that normal?

**Comment by junyanz** [comment]
Test results are usually slightly worse than training results. Did you use the default setting?

**Comment by hyang23333** [comment]
I used the default setting in both training and testing process. If so,the results are normal, right?

**Comment by junyanz** [comment]
Being slightly worse is normal.

**Comment by hyang23333** [comment]
![18_fake_B](https://user-images.githubusercontent.com/52700830/61709726-6e561600-ad82-11e9-83ea-d0565ec0d3f3.png) Sorry to trouble you but i'm really new here. By using the default setting, the results I got are very blurry.

Here is the command line:python3 train.py --dataroot ./datasets/facades --name facades-o1 --model pix2pix --direction BtoA --gpu_ids 6

Should I add something more or adjust some parameters? Thanks a lot!

**Comment by junyanz** [comment]
You are expected to get the last column of the results on this [webpage](https://phillipi.github.io/pix2pix/images/index_facades2_loss_variations.html).  Could you also try to [download](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#pix2pix-traintest) pre-trained models and test the model and compare with your model?

**Comment by hyang23333** [comment]
Thank  you very much! Pretrained models work very well. By the way, I still have one more question.  When I use cityscapes dataset to train without any change of default setting, the output results are in dark gray , in other words , with no color. Could you tell me what's wrong with it ?

![13_fake_B](https://user-images.githubusercontent.com/52700830/61853597-e3465e80-aeee-11e9-9fa9-9ff7a719e9b6.png)
Thank you again!

**Comment by junyanz** [comment]
The model was trained for 200 epochs in the paper. Not sure about the D_loss. If you want to have even sharper results, you can use [pix2pixHD](https://github.com/NVIDIA/pix2pixHD).

**Comment by hyang23333** [comment]
Thanks for your patience. I did train it for 200 epochs and that blurry picture is the final result. What should I set if I hope to reproduce the results in the paper. I don't think default setting also works well.

Thank you so much!

**Comment by junyanz** [comment]
Could you share with us your training script?

**Comment by junyanz** [comment]
I just tried it. It seems to work for me. Here is my training script. Are you using the latest code?
```
set -ex
GPU_ID=0
CLASS=cityscapes
SAVE_EPOCH=25

DISPLAY_ID=$((GPU_ID*10+1))
CUDA_VISIBLE_DEVICES=${GPU_ID} python train.py \
	--dataroot ./datasets/${CLASS} \
	--name ${CLASS}_pix2pix \
	--save_epoch_freq ${SAVE_EPOCH} \
	--model pix2pix \
	--display_id ${DISPLAY_ID} \
	--direction BtoA \
	--display_freq 4000 \
```

**Comment by hyang23333** [comment]
Sorry for the noise. It works now and thank you so much!
