### ISSUE TITLE
286x286 PatchGAN

### ISSUE THREAD

**Issue by kampelmuehler** [junyanz/pytorch-CycleGAN-and-pix2pix#712]
Hi,
what is the correct config for using the whole imageGAN in pix2pix
I suppose it has to be --netD n_layers but I'm uncertain about the value of --n_layers_D.
Any hint would be appreciated. Thanks!

**Comment by junyanz** [comment]
A standalone ImageGAN has not been included in this repo. You can increase --n_layers_D so that the final output is 1x1.  I guess it's 5 or 6.

**Comment by kampelmuehler** [comment]
Thanks for your comment. In the standard pix2pix model the inputs to the Discriminator are 256x256, `--n_layers_D 6` then results in the size being 2x2, 1x1 is impossible, since it breaks at `--n_layers_D 7`

**Comment by junyanz** [comment]
In the original pix2pix paper, 286 × 286 discriminator:
C64-C128-C256-C512-C512-C512
Maybe you can change crop_size to 286.

**Comment by kampelmuehler** [comment]
I tried that, but it's causing problems with dimensions at the skip connections in Unet:

```
File "/media/ssd1/moritz/workspace/GAN/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 535, in forward
    return torch.cat([x, self.model(x)], 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 16 and 17 in dimension 2
```

**Comment by junyanz** [comment]
Yeah, U-Net only supports 256. Could you try to change the padding to 0 in this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py#L578)? ALso check out the original 64x64 [imageGAN](https://github.com/pytorch/examples/blob/master/dcgan/main.py#L161) implemented in DCGAN.

**Comment by kampelmuehler** [comment]
Ok, thanks for the help!

**Comment by John1231983** [comment]
Hi. Should I use patchgan for pix2pix? I have image size of 128x128, so it is clear that cyclegan will use nlayer as 5 (output is 4x4 patch). But for pix2pix, is nlayer 5 or 7?

**Comment by Chenziyang7799** [comment]
Hi. If I set the nlayer to 6, the output size is 2×2, does it mean that the image is divided into 2×2 patches for discrimination? If I set nlayer to 3, how many patches are separated?

**Comment by Chenziyang7799** [comment]
Now, I know the calculation formula of patch quantity. But what I don't understand is that the discriminator outputs a map, how do you compute the cross entropy?

**Comment by Chenziyang7799** [comment]
Sorry, i have known that. But ,i have a new problem, when training D, why is loss_D_fake additive and loss_D_real average?

**Comment by Chenziyang7799** [comment]
In other words, I want to know the meaning  of False : self.criterionGAN(pred_fake, False)

**Comment by Chenziyang7799** [comment]
I know that, sorry to ask so many silly questions

**Comment by VishalP1975** [comment]
Hi, Is it possible to use ResNet50 or other classifiers instead of PatchGAN classifier in discriminator? 
I am trying to segment only the fully visible objects in an image which contain a more number of objects but my model not able to detect all the completely visible objects. Do you have any suggestions on how to proceed for this task?

Thank you & Any suggestions would be appreciated.!!

**Comment by junyanz** [comment]
@Chenziyang7799  Sorry I missed your questions.  here are some answers: (1) We calculate the cross-entropy loss for each element in the map and average them. (2) We use a smaller learning rate for D. (3) You can see this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/f13aab8148bd5f15b9eb47b690496df8dadbab0c/models/networks.py#L240) for the False flag.

**Comment by junyanz** [comment]
@VishalP1975 You can use a pre-trained network as a discriminator. For segmentation, I recommend that you use a segmentation network, rather than pix2pix/cyclegan.
