### ISSUE TITLE
Order of training networks in CycleGANModel

### ISSUE THREAD

**Issue by adishegde** [junyanz/pytorch-CycleGAN-and-pix2pix#718]
Hey! I'm slightly confused about the way the parameters of the network are updated in `CycleGANModel`.

1. The [original GAN paper's](https://arxiv.org/pdf/1406.2661.pdf) `Algorithm 1` suggests optimizing over `D` first followed by `G`. However, in the current implementation `G` seems to be optimized before `D`.

2. The more important question is that shouldn't `G` be optimized over the latest `D`'s predictions? I believe we'll be solving the mini-max game only then.

In summary, what I believe should happen in `CycleGANModel.optimize_parameters` is:
```
self.forward()

# optimize D
self.set_requires_grad([self.netD_A, self.netD_B], True)
self.optimizer_D.zero_grad()
self.backward_D_A()
self.backward_D_B()
self.optimizer_D.step()

# forward pass once again to get predictions using latest discriminator D*
self.forward()

# optimize G
self.set_requires_grad([self.netD_A, self.netD_B], False)
self.optimizer_G.zero_grad()
self.backward_G()
self.optimizer_G.step()
```

Would appreciate any inputs on this.

**Comment by junyanz** [comment]
1. I think the order is not that important. Either order should work in practice.
2. The current optimization sequence (forward -> update G -> update D -> forward -> update G -> update D ...) is consistently with the order you proposed. There is one step offset. (You start from update D- > forward -> update G ->update D...). But both are fine in practice.

**Comment by adishegde** [comment]
Appreciate the quick response! I initially thought that the only difference is a one-step offset too but not performing a forward pass between `update G -> update D` would lead to optimizing the discriminator on a non-optimal generator.

I realize that these points might not be of practical consequence but wanted to know any reason/intuition for the current implementation.

**Comment by junyanz** [comment]
When D is trained, we use an image [buffer](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/util/image_pool.py) that stores 50 previously generated samples from previous Gs. The idea of using non-optimal previously generated samples can slightly stabilize the training as discussed in this [paper](https://arxiv.org/pdf/1612.07828v1.pdf). I think computing all the intermediate images (fake_A/B and rec_A/B) is expensive in CycleGAN. So we only computed once in our implementation.
