### ISSUE TITLE
understanding optimization 

### ISSUE THREAD

**Issue by nehaleosharma** [junyanz/pytorch-CycleGAN-and-pix2pix#720]
appendix 7 in 7.1 training detail(paper)
in practice,objective is divided by 2 while optimizing D,which slows down the rate at which D learns relative to the rate of G. I am not getting point in terms of code.

**Comment by junyanz** [comment]
We multiply the D loss by 0.5 [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/pix2pix_model.py#L101).

**Comment by nehaleosharma** [comment]
Thanku so much

**Comment by 13462877152** [comment]
Thank you very much for your excellent project. I am puzzled about this point. Usually , we always want the D learn faster than the G,   why slow down the rate here ?  if there art three items in the D_loss ,such as fake_loss item 1, false_item 2 and the true item,  what should we do for the D in this situation ?   * 0.3  or 0.5 ?  Looking forward  your help.
