### ISSUE TITLE
Stuck on "WARNING:root:Setting up a new session"

### ISSUE THREAD

**Issue by za13** [junyanz/pytorch-CycleGAN-and-pix2pix#724]
I downloaded the `facades` dataset. I then run `python train.py --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --direction BtoA`, but I'm stuck at `WARNING:root:Setting up a new session`

Even after a few hours, it says there and doesn't seem to progress. Why is this?

**Comment by junyanz** [comment]
You need to start the visdom server first. Type `python -m visdom.server` in a different console. You can also disable visdom server with `--display_id 0`.
