### ISSUE TITLE
How To upload input image at webpage demo?

### ISSUE THREAD

**Issue by RuikangSun** [junyanz/pytorch-CycleGAN-and-pix2pix#726]
Output image could be saved, however, input image can't be uploaded.
My model requires complex input. Using line tool is really difficult.
So is it possible to upload image file as input?
I understand a little of Python, but nothing of JavaScript.
Maybe I shouldn't put this issue here, but I can't find a better place.
Thanks!
![afdasf](https://user-images.githubusercontent.com/20597187/62614698-84e19d00-b93e-11e9-8f75-e84cc417eb8f.png)

**Comment by junyanz** [comment]
Please post your question in the TensorFlow-pix2pix [repo](https://github.com/affinelayer/pix2pix-tensorflow). The web demo is not implemented by this repo. As far as I know, it is not supported by the TensorFlow-pix2pix.

**Comment by RuikangSun** [comment]
Close old issues.
