### ISSUE TITLE
Train  640x480 images

### ISSUE THREAD

**Issue by pablin992** [junyanz/pytorch-CycleGAN-and-pix2pix#728]
I am trying to train 640x480 images, which combined result in 1280x480. I use the following parameters:

`python3 train.py --dataroot ./datasets/sim2real --name sim2real_pix2pix --model pix2pix --direction AtoB --preprocess none`

but I am getting the following error:

`RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 2 and 3 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71`

Does anyone know how to solve it?

**Comment by junyanz** [comment]
The default network for pix2pix is `unet256` which only works for `256x256` or `512x512`. There are a few options: (1) you can resize your image to `512x512`. See the option for `--preprocess`. (2) you can use a different network such as `resnet_9blocks` or your own network.
