### ISSUE TITLE
Loading multiple models when training a network

### ISSUE THREAD

**Issue by azinonos** [junyanz/pytorch-CycleGAN-and-pix2pix#729]
Hello,

I'm working on an implementation where I am extending an architecture to use a third pre-trained network. I've been looking at the code and I can't think of a non-messy way to load a model in-code without copying the options from the original model and changing properties to then create the third model again. Is there a more straightforward way to do this?

Just as an example, let's say we have our Network A, and our other Network B. B is trained on some data and then the model is saved. Then while training A, I want to load the pre-trained B and do something with it. How would I go about loading B in-code?

**Comment by junyanz** [comment]
We use the function [load_networks](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/base_model.py#L175) to load all the pre-trained models. The variable [model_names](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/pix2pix_model.py#L50) controls which model will be loaded.  If you want to write your custom function to load a model, I recommend that you write a separate script to  test the function before adding it to the training pipeline.

**Comment by azinonos** [comment]
Thanks for the reply junyanz, I've had a look at the code but this seems to be a case where the models you would have in the model_names variable have to be of the same class, eg.  Pix2Pix. What if the Network B (like in the example) was another architecture, eg. a fully connected network, of another class FCN. Would you load it the same way?

Also I see that load_networks is only called in test mode, while I'd like to load the pre-trained model  B during the training of A as well, without saving it every time.

**Comment by junyanz** [comment]
1. You need to define your network architecture, such as we have done for [G](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/pix2pix_model.py#L56) and for [D](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/pix2pix_model.py#L60). You need to write your own function for creating a network object.  
2. It is called during [training](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/pix2pix_model.py#L51) as well. See this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/base_model.py#L78).

**Comment by azinonos** [comment]
Regading (1), I've defined my own architecture in a separate class file, I was wondering of how to load it during the training of another class/architecture. Could you elaborate on writing my own function for creating the object? We could talk via PM if this is easier so I can explain what I'm doing in my code.

Regarding (2), I've look throught that function before, it looks like the networks are being loaded only if the network is in test mode or if training continues from a previous point, unless I misunderstand something?

Thanks again for the response.

**Comment by junyanz** [comment]
(1) Here is a PyTorch [tutorial](https://pytorch.org/tutorials/beginner/saving_loading_models.html) on how to load a model. 
(2) You can modify the code by removing the `isTrain` flag for your network.
Sorry that I don't have time to read your code. I will recommend that you follow some PyTorch tutorials.

**Comment by azinonos** [comment]
I'll have a look into this, thanks.
