### ISSUE TITLE
what‘s wrong cant run,cuda problem

### ISSUE THREAD

**Issue by liangwei191** [junyanz/pytorch-CycleGAN-and-pix2pix#73]
I got stuck for this step,I am ubutun on windows,win10 x64 gtx970 with the lastest driver and cuda installed,anybody can help,thanks.!!!

root@SC-201705310804:/mnt/e/github/pytorch-CycleGAN-and-pix2pix# python test.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --phase test --no_dropoutet_256 --which_dire
THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=87 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    opt = TestOptions().parse()
  File "/mnt/e/github/pytorch-CycleGAN-and-pix2pix/options/base_options.py", line 60, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 162, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at torch/csrc/cuda/Module.cpp:87

software have:
root@SC-201705310804:/mnt/e/github/pytorch-CycleGAN-and-pix2pix# pip freeze

dominate==2.3.1
numpy==1.13.1
olefile==0.44
Pillow==4.2.1
PyYAML==3.12
six==1.10.0
torch==0.2.0.post1
torchvision==0.1.9

**Comment by junyanz** [comment]
You probably didn't install the cuda, gpu driver and/or pytorch correctly. Are you able to run some basic pytorch [examples](https://github.com/jcjohnson/pytorch-examples)?

**Comment by AliceMa-thss15** [comment]
@liangwei191 My error is the same as yours.TAT

**Comment by AliceMa-thss15** [comment]
@junyanz I got stuck in exactly the same step. My pytorch has been installed correctly but I cannot use gpu  on my own laptop. Can I run this project without gpu?

**Comment by junyanz** [comment]
@AliceMa-thss15  you can use cpu by setting `--gpu_ids -1`. See [training details](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#trainingtest-details) for more information.

**Comment by brando90** [comment]
someone know how to solve this for pytorch?
