### ISSUE TITLE
Running with CPU?

### ISSUE THREAD

**Issue by yugo-harago** [junyanz/pytorch-CycleGAN-and-pix2pix#734]
In the prerequisites is saying CPU or NVIDIA GPU + CUDA CuDNN, is that means I can run without NVIDIA and CUDA but in CPU? I'm having the error: Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
I need to install NVIDIA driver even if I only use CPU?

**Comment by hujinda** [comment]
> In the prerequisites is saying CPU or NVIDIA GPU + CUDA CuDNN, is that means I can run without NVIDIA and CUDA but in CPU? I'm having the error: Found no NVIDIA driver on your system. Please check that you
> have an NVIDIA GPU and installed a driver from
> http://www.nvidia.com/Download/index.aspx
> I need to install NVIDIA driver even if I only use CPU?

base_options.py
('--gpu_ids', type=str, default='-1', help='gpu ids: e.g. 0  0,1,2, 0,2. use -1 for CPU')

**Comment by yugo-harago** [comment]
Thanks a lot! solved!
