### ISSUE TITLE
modifications required to go from colored to grayscale images in Pix2Pix

### ISSUE THREAD

**Issue by harjatinsingh** [junyanz/pytorch-CycleGAN-and-pix2pix#74]
What are the modifications required to go from colored to grayscale images and use `NLLLoss2d()` loss for generator instead of L1 loss. I tried a hacky way by making `self.criterionL1 = torch.nn.NLLLoss2d()` in network initialization and using 
`self.loss_G_L1 = self.criterionL1(self.fake_B, self.real_B.long()[:,1,:,:]) * self.opt.lambda_A #I was intending to see if I can get away with just passing first channel of RGB image to start with` 

in backward pass of Generator. I get the following  runtime error 

> RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

**Comment by junyanz** [comment]
It is hard to tell unless you send more information regarding your code and error messages.
