### ISSUE TITLE
scipy.misc.imresize has been removed in scipy 1.3

### ISSUE THREAD

**Issue by odinsbane** [junyanz/pytorch-CycleGAN-and-pix2pix#740]
I went through the installation instructions and training failed for the cycle gan because imresize was missing. I resolved the issue by installing scipy 1.2 in my virtual environment, now it appears to train fine.

Possibly add scipy==1.2 to the requirements file?

**Comment by junyanz** [comment]
`imresize` has been replaced in the latest [commit](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/dca9002f598fada785b92d496fcdc7b04528b393). Could you download the latest code and try it again?

**Comment by odinsbane** [comment]
Works great, I re-installed scipy 1.3 and started another training and everything seemed to work. Thanks!

**Comment by junyanz** [comment]
Great!
