### ISSUE TITLE
Different results when padding test image with different size

### ISSUE THREAD

**Issue by Leo196** [junyanz/pytorch-CycleGAN-and-pix2pix#746]
Hi, 

I used pix2pix to train my dataset, and there are many images with different size. To solve this problem, I crop images into 256*256 during train process and pad testing images to 512*512 instead of crop them into 256*256.

However, I found that the result is different when I used the input1 (256*256, crop) and input2(512*512, padding) when test. I did a little experiment, and that's the result. 

![image](https://user-images.githubusercontent.com/54628212/63855333-c4495980-c9d1-11e9-8f35-e342b017ee58.png)

![image](https://user-images.githubusercontent.com/54628212/63855373-df1bce00-c9d1-11e9-9982-c0eb0e50d92e.png)

**Comment by Leo196** [comment]
Thanks for your prompt response and cycleGAN is an excellent work. Hmm, in my work, I want to preserve the realness of test images (with different size) as soon as possible, so I pad them to 512*512 and then crop the results according to real size instead of scaling or cropping before testing. Here are 4 simulation experiments during test. 

![result](https://user-images.githubusercontent.com/54628212/63942195-cb3e9d80-ca9f-11e9-8580-24e5ab64cf38.png)

In my opinion, EXP1,EXP3,EXP4 should have similar results because they have the same area.  I want to know your suggestions on this issue. I just saw in the comment that you said _it will not work_. Can you tell me the reason? 

Thanks a lot and look forward to your reply.

**Comment by Leo196** [comment]
I have changed _nn.InstanceNorm2d(..., track_running_stats=False) tonn.InstanceNorm2d(..., track_running_stats=True)  _ during train

**Comment by junyanz** [comment]
See this [post](https://twitter.com/karpathy/status/720622989289644033?lang=en) on zero-padding for more details. Again, I think the network can be directly deployed on your test images without resizing and cropping. Please experiment with the flag `--preprocess none` or `--preprocess scale_width`.

**Comment by Leo196** [comment]
Thanks a lot for your fast responses. I'll try it.
