### ISSUE TITLE
screen freezes when trained with multiple GPUs

### ISSUE THREAD

**Issue by daofeng2007** [junyanz/pytorch-CycleGAN-and-pix2pix#747]
![multi_gpu](https://user-images.githubusercontent.com/11918249/63896505-2ef19980-c9c0-11e9-8d4f-77260e6824fb.PNG)
The training did not make any progress, as shown in the left image of the screenshot, when I used two GPU for training. However, the right image of the screenshot shows GPU 0 and 1 were fully used.

Training with single GPU did not have any issue.

**Comment by daofeng2007** [comment]
Somehow this issue disappears by itself the second day I tried it.

**Comment by jiashu-zhu** [comment]
Hi daofeng, I met this question recently, have you handled this issue? @daofeng2007 @
