### ISSUE TITLE
How to train for 3D volumes

### ISSUE THREAD

**Issue by GiannakopoulosIlias** [junyanz/pytorch-CycleGAN-and-pix2pix#752]
Hello,

Thanks for this excellent repository. I want to use pix2pix as 3D volume to 3D volume translation.
In addition, each data-point consist of fifteen 3D tensors as inputs and two 3D tensors as outputs. 

Is it possible to configure pix2pix and apply it for such an application? 

Thanks

**Comment by junyanz** [comment]
The current repo doesn't support 3D input/output. You need to implement your own 3D generator and discriminator.

**Comment by GiannakopoulosIlias** [comment]
Thanks for the quick response!
