### ISSUE TITLE
Questions for training 

### ISSUE THREAD

**Issue by wl082013** [junyanz/pytorch-CycleGAN-and-pix2pix#753]
Hi, junyan, 
so hornored to get your help.
Is it possible to use your code as basic code for triaining SR dataset? Namely, trainA is LR image, and trainB is HR image. Your code is fixed with image resize and crop functions, however, what I need is various input size (either LR or HR) pair. I may resize LR to 256, however, HR should be 2565x4. The reason I ask you for help is your code style (concise and clear) matches mine, and I like using your code as basic for my problem.
Thank you for help.

**Comment by junyanz** [comment]
It's possible. You can replace the current generator with an SR generator (e.g., this [one](https://github.com/pytorch/examples/blob/master/super_resolution/model.py#L6)).

**Comment by wl082013** [comment]
Okay, how about the image size? since cyclegan fixed all image size, but  my SR dataset is with various image size, so can I just change the image size ? besides, is it possible to load trainA(LR) and trainB(HR) in a paired format using your unaligned dataloader? e.g. trainA: 1.png <-> trainB 1.png like this. 
Thanks for your kind help.

**Comment by junyanz** [comment]
It depends on the SR generator. Some SR generators support images with different sizes. Regarding data loader, you probably need to write your own data loader. You can modify the aligned data [loader](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/aligned_dataset.py).

**Comment by wl082013** [comment]
okay  thanks for your help
