### ISSUE TITLE
Numpy as training input

### ISSUE THREAD

**Issue by Zohiet** [junyanz/pytorch-CycleGAN-and-pix2pix#755]
New to python and deep learning. I am wondering how can we directly use numpy as training input? I think that is definitely possible, right?

**Comment by momenator** [comment]
I did it for my project, where my input data are npz files. You just have to change the data loader to use `np.load(PATH_TO_FILE)` instead of `Image.open(...)`.

**Comment by Zohiet** [comment]
Thanks for your reply. My input is 512*512 in npy and what if I want to save output in npy file too? Which file shall I change?

**Comment by momenator** [comment]
It depends on the type of your dataset. For example in my experiment I used `--dataset_mode unaligned`, so I've changed the next few lines from [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/unaligned_dataset.py#L57) to something like:

```
        # A_img = Image.open(A_path).convert('RGB')
        # B_img = Image.open(B_path).convert('RGB')
        # apply image transformation
        # A = self.transform_A(A_img)
        # B = self.transform_B(B_img)
        A = np.array([np.load(A_path)['data']]).astype(np.float32)
        B = np.array([np.load(B_path)['data']]).astype(np.float32)	

        return {'A': A, 'B': B, 'A_paths': A_path, 'B_paths': B_path}
```

**Comment by Zohiet** [comment]
Thanks a lot!

**Comment by prabathbr** [comment]
> It depends on the type of your dataset. For example in my experiment I used `--dataset_mode unaligned`, so I've changed the next few lines from [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/unaligned_dataset.py#L57) to something like:
> 
> ```
>         # A_img = Image.open(A_path).convert('RGB')
>         # B_img = Image.open(B_path).convert('RGB')
>         # apply image transformation
>         # A = self.transform_A(A_img)
>         # B = self.transform_B(B_img)
>         A = np.array([np.load(A_path)['data']]).astype(np.float32)
>         B = np.array([np.load(B_path)['data']]).astype(np.float32)	
> 
>         return {'A': A, 'B': B, 'A_paths': A_path, 'B_paths': B_path}
> ```

Hello, I am trying to use the same code with "unaligned" dataset and I have NPZ files in trainA,testA trainB,testB folders in dataset. But when I am trying to run the code, I am getting below error and it looks like dataloader can't see the NPZ files. Do you have any idea on how to solve this ? Thanks in advance.

```
    self.dataloader = torch.utils.data.DataLoader(
  File "k:\Miniconda3\envs\pyt\lib\site-packages\torch\utils\data\dataloader.py", line 277, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "k:\Miniconda3\envs\pyt\lib\site-packages\torch\utils\data\sampler.py", line 97, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```
