### ISSUE TITLE
Issue with Colab

### ISSUE THREAD

**Issue by muxgt** [junyanz/pytorch-CycleGAN-and-pix2pix#757]
Hi! I'm using CycleGAN in Google Colab. In some reason when training it doesn't show anything in Checkpoints folder - no folders and no files. I tried with different browsers and different accounts. The files themselves are there and model continues to train after stop with no problem. Anybody knows why that is?
And also any chance to visualize the progress in Colab? Visdom server seems not to work there and html file not displayed.

**Comment by muxgt** [comment]
I found a way to visualize the process but got another question. Is there a way to visualize more than one picture in each epoch? Where can I find this in the code?

**Comment by junyanz** [comment]
The code is [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/util/visualizer.py#L156). Feel free to modify it.

**Comment by muxgt** [comment]
Thanks!

**Comment by kalai2033** [comment]
@muxgt I was also not getting any files in the default checkpoint directory. But the files were created when i created a different checkpoint directory. Also, Could you please let me know how did you stop and resume training as colab workspace gets reset in 12 hours. And also how did you visualize the progress with visdom server.

**Comment by muxgt** [comment]
@kalai2033 to resume training you just need to copy checkpoint files to your google drive for example. And then upload them in the new Colab runtime in the same folder where they were. And regarding visualization I don't know how to do it with visdom, instead I just downloaded html file and the pictures from time to time and opened it on local disk.

**Comment by kalai2033** [comment]
@muxgt Thanks for a quick reply. Should i include --epoch_count flag during resuming the training. or shoud i just run the same train script. And one more doubt when i open the index.html file in my browser the page is always refreshing and it doesnt show any pics. Should i wait till the training is stopped and then open?

**Comment by kalai2033** [comment]
@muxgt Thanks dude. You saved me a lot of time.
