### ISSUE TITLE
For correcting distortion using pix2pix

### ISSUE THREAD

**Issue by riktimmondal** [junyanz/pytorch-CycleGAN-and-pix2pix#762]
I am trying to correct distortion in am image using pix2pix where my total training set consist of only 90 images.Even after training for long hours and trying out various hyperparameters it is not able to learn even the basis stuffs.Can you suggest something?

Thanks in advance.

**Comment by junyanz** [comment]
I am not sure about your application and data. 90 images might be not enough. Consider applying some data augmentation and be cautious about overfitting.

**Comment by riktimmondal** [comment]
![087_SC_BIN](https://user-images.githubusercontent.com/24415468/64951435-84bcb180-d89b-11e9-9dd8-f9465fd698d0.png)
![090_SC_BIN](https://user-images.githubusercontent.com/24415468/64951465-93a36400-d89b-11e9-895f-9b6b222b203b.png)
![086_SC_BIN](https://user-images.githubusercontent.com/24415468/64951478-9aca7200-d89b-11e9-9ab3-4de787e87eca.png)

I am trying to address perspective distortion correction.I have augmented data and created a dataset of 1000 images.But I think its getting overfiited since it performs very well on training images and very bad at test images.I even the eval flag(kept training and testing parameter same).Any suggestion on this?

**Comment by EdenMelaku** [comment]
can u show us your training dataset sample?

**Comment by junyanz** [comment]
I am not sure if pix2pix is the best option for you, as we assume that input images and output images are spatially aligned, which is not the case of your application. I recommend that you use other models such as [STN](https://arxiv.org/abs/1506.02025).

**Comment by riktimmondal** [comment]
Thanks for your information I will check STN.
