### ISSUE TITLE
using different discriminator

### ISSUE THREAD

**Issue by wl082013** [junyanz/pytorch-CycleGAN-and-pix2pix#763]
Hi Dr.Zhu
Sorry to bother you again.
Is it possible to use Relativistic Discriminators for CycleGAN training?
![1568168298(1)](https://user-images.githubusercontent.com/16892862/64663175-e937d500-d485-11e9-951c-49a8f516bbb9.jpg)
My concern is that for cycleGAN real and fake are different images, but RaD seems to be only used for the paired case. Are you familiar with this case ?
Thanks

**Comment by junyanz** [comment]
It's possible. You can try different GAN objective functions. It can be used for the unpaired case as the original unconditional GANs are trained without pairs.

**Comment by junyanz** [comment]
We haven't observed significant improvement. But you are free to try it by yourself.

**Comment by wl082013** [comment]
> @wl082013: any improvement do you achieve using the new gan? My performance down when using it.

yeah the performance drops!
