### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by jsaisagar** [junyanz/pytorch-CycleGAN-and-pix2pix#764]
Hi,

I have been training pix2pix with unet256 as generator. My training data is 10000 images of 256*256 resolution.
Each epoch is taking around 25000 seconds (7.25 hrs) 
I am running experiments on two 1080 Ti cards with batch size 32 

May I know if it is usually the case?

Thanks for any help,

**Comment by junyanz** [comment]
It is a little bit slow. What is your GPU usage percentage? Is it 100%?

**Comment by jsaisagar** [comment]
Never mind. I have increased the number of workers. Now it is taking around 1 hour for epoch. Closing the issue. Thanks for the reply junyanz.

**Comment by isrishtisingh** [comment]
@jsaisagar How did you increase the number of workers? 
There is a "num_threads" parameter for training options, but that is for data loading, are you referring to this? 
How can I set num_workers to increase training speed?
