### ISSUE TITLE
How to run test in the aligned mode?

### ISSUE THREAD

**Issue by Makhaon** [junyanz/pytorch-CycleGAN-and-pix2pix#768]
I try to train and test the CycleGAN in the aligned mode. All works fine except of finding resuts of test. A put test images to the dataset\test folder, run test.py, it wrote processing (0000)-th image..., processing (0005)-th image... and exit. And nothing was happend, no any error or exception, and no result images anywhere.

**Comment by EdenMelaku** [comment]
please check   `project folder/results/"name of your experiment"/test_latest/ `, in this folder u will find images folder and index.html, u can find all the generated images and the real images in the images folder or open index.html for better visualization.

**Comment by Makhaon** [comment]
Found. Thank you.
