### ISSUE TITLE
Load input to RAM

### ISSUE THREAD

**Issue by KyriakosZantis** [junyanz/pytorch-CycleGAN-and-pix2pix#769]
Hello i am training a CycleGan with a huge number of images(70 000) for each collection, A and B. All images are panoramas 256*512 and i was wondering if it possible to load all images to RAM and not loading for each epoch all the images again.I have  enough RAM capacity as all images are around 10GB. Is it possible from me to alter it through parameters or coding? I believe this solution will make my training a much more faster
Thank you in advance

**Comment by junyanz** [comment]
It's possible. You can modify the initialization code of the data loader [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/unaligned_dataset.py#L29). You can load all the images in the beginning. I am not sure if it is necessary, as the data loading is already quite efficient. You can increase the `--num_threads`. You can see the time of data loading from the logging information.

**Comment by KyriakosZantis** [comment]
Thanks i will try it.you see i am thinking of a way instead of each epoch reload all 10GB if there is a way to have it loaded from the start and just accessing it.I believe after the first slow one epoch later on will be loading faster

**Comment by KyriakosZantis** [comment]
in the code there is a use of opt.max_dataset_size that is set to Inf. So any number i use won't do any change i think

**Comment by junyanz** [comment]
The default of `max_dataset_size` is inf. But you can set a smaller number as you like.
