### ISSUE TITLE
General strategy for training continuation when data becomes gradually available

### ISSUE THREAD

**Issue by vgrabovets** [junyanz/pytorch-CycleGAN-and-pix2pix#774]
Hi! Thank you for great work!
I have a question regarding training pix2pix when new data becomes gradually available and training from scratch every time is not really feasible.
Let's say now I have 1000 images, I trained `model_1` using only them from scratch.
After some time I get another 1000 images.

How should I continue training in this case?
1) use `model_1` and train on 2000 images
2) use `model_1` and train on new 1000 images
3) use `model_1` and train on new 1000 images + random sample from previous batch

Images between batches will always depict the same general scene with variations.

Do you have some hints? Or just trial and error? Thank you

**Comment by junyanz** [comment]
Both 1 and 3 might work better. Also, you don't need to train the model for 200 epochs. Maybe 10 or 50 epochs will be enough.
