### ISSUE TITLE
Grid-like image after training cycle GAN

### ISSUE THREAD

**Issue by MaureenZOU** [junyanz/pytorch-CycleGAN-and-pix2pix#78]
When training the cycle-gan, I got some grid like images like the following, I think that is due to the up sampling problem, is anyone met this problem and have solutions? 
Similar issue https://github.com/fchollet/keras/issues/3940.
<img width="257" alt="screen shot 2017-08-16 at 9 02 21 am" src="https://user-images.githubusercontent.com/11957155/29377224-242d86a6-8289-11e7-9761-ce6a48da7bdd.png">

Thanks a lot!

**Comment by phillipi** [comment]
Could be related to this issue: https://distill.pub/2016/deconv-checkerboard/

The solution proposed there is to replace deconvolution with upsampling followed by stride 1 convolution. The cost is a naive implementation will be ~4 times as slow (but you could make it almost as fast with a smarter implementation, see the matrices in the distill post). 

Another partial solution is to use a combination of kernel sizes and strides that minimize the unequal sampling problem (e.g., use kernel size 4 and stride 2; you can see the effect in the interactive widget on the distill post).

In my experience, the artifacts usually go away with enough training, as the adversary can notice these artifacts and eventually the generator will adjust its weights to avoid them, even with a naive architecture. The architecture tricks above could help get to good solutions faster, but in general we found them to be unnecessary if you just train long enough.

**Comment by MaureenZOU** [comment]
thanks a lot~ got it

**Comment by mrluker** [comment]
I've run into problems changing the sampling to kernel size 4 for the sampling. @phillipi 

How did you go about changing that setting in the networks.py file?

**Comment by junyanz** [comment]
@mrluker  It depends on which generator you are using, for the resnet generator, you can change the network architectures [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py#L207); for the u-net generator, you can edit [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py#L333). You can change the kernel_size in each function.

**Comment by vis-opt** [comment]
Can someone share how long it took for the generators to stop producing the grid-like artifacts? For example, did it occur early on in training (let's say before 100 epochs were completed) or did it occur after the LR decay?

**Comment by TheGeorgData** [comment]
Hi! i have the same problem. My Cycle-GAN generates images with big grid like this. Is this the same problem or not?
![generated7027](https://user-images.githubusercontent.com/79103055/121785709-94d70180-cbe5-11eb-8a46-b0f275b9c719.jpg)
