### ISSUE TITLE
using CycleGAN for Chinese characters style transfer

### ISSUE THREAD

**Issue by dandanli814** [junyanz/pytorch-CycleGAN-and-pix2pix#780]
Hi, thank you for sharing the code and this is a very good work. Now, I want to  know if the CycleGAN can be used for Chinese characters style transfer. As I  know, zi2zi used the pix2pix for this task. I need some suggestions. Thank you~^_^

**Comment by junyanz** [comment]
Sure. You might check out this recent [work](https://arxiv.org/pdf/1801.08624.pdf).

**Comment by dandanli814** [comment]
> Sure. You might check out this recent [work](https://arxiv.org/pdf/1801.08624.pdf).

Thank you~^_^
