### ISSUE TITLE
Turn off Visdom

### ISSUE THREAD

**Issue by QaziSajid** [junyanz/pytorch-CycleGAN-and-pix2pix#781]
I am running this code on a remote GPU, and can only access via terminal. Due to this my output is filled with Visdom error message like no display, etc. I just want to directly print the results after each iteration, and store the log files. Is there any way to turn off the Visdom stuff? Below is a snippet of the error.

``raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f143e55c550>: Failed to establish a new connection: [Errno 111] Connection refused',))``

**Comment by junyanz** [comment]
Please refer to this [Q & A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#connection-errorhttpconnectionpool-230-24-38).
