### ISSUE TITLE
[Question] Which is faster CPU or GPU? 

### ISSUE THREAD

**Issue by dcangulo** [junyanz/pytorch-CycleGAN-and-pix2pix#784]
I am using an i7-3770k @ 4.0GHz and GTX 1060 6GB on a Windows 10 machine with WSL (Windows Subsystem for Linux), but currently WSL is not able to access Nvidia graphics card so I am using a CPU only to train the model.

Now the question is, does training the model on CPU only reduce the speed of the training? Or will I feel an improved speed on using the GPU given the same amount of dataset?

Or will I have reduced quality when using CPU only?

I am thinking of buying another SSD so I can install Ubuntu on it, that's why I am asking this question.

Thanks.

**Comment by junyanz** [comment]
GPUs will be much faster. The quality is not affected by the choice of GPU or CPU.
