### ISSUE TITLE
How to save checkpoints while training ?

### ISSUE THREAD

**Issue by coditive** [junyanz/pytorch-CycleGAN-and-pix2pix#791]
Hi! I am newbie to Deep Learning and just found out how to train the model. Please help me with
Whenever I train the model with dataset and then i interrupt it. After restarting training procedure, it starts with new session and previous training is lost, i think so.

Thank you in Advance..!!
![erro1](https://user-images.githubusercontent.com/41199211/66670779-2efbdf00-ec78-11e9-8bac-3266abaeed83.png)
![erro2](https://user-images.githubusercontent.com/41199211/66670780-2f947580-ec78-11e9-83f2-378c9979be07.png)

**Comment by coditive** [comment]
i want to know how to save or create latest_net_G_A.pth file while training....?

**Comment by junyanz** [comment]
Please see this [Q & A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#can-i-continueresume-my-training-350-275-234-87).
