### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/data/A',Using my own data set

### ISSUE THREAD

**Issue by kexijia** [junyanz/pytorch-CycleGAN-and-pix2pix#794]

**Comment by junyanz** [comment]
You need to point the `--dataroot` to your own directory.

**Comment by kexijia** [comment]
thank you！！！

**Comment by Marion2** [comment]
I have the same problem and when I had `python3 datasets/combine_A_and_B.py --fold_A /path/to/data/A --fold_B /path/to/data/B --fold_AB /path/to/data --dataroot ./datasets`

I have this error : `create image pairs: error: unrecognized arguments: --dataroot ./datasets`

Sorry for the silly question but I don't get if I have to create a folder named `/path/to/data` into the `datasets` folder with A and B folder into it

**Comment by junyanz** [comment]
Please follow the valid flags. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/datasets/combine_A_and_B.py#L6). `--dataroot` does not exist for `combine_A_and_B.py`.
