### ISSUE TITLE
About data set configuration

### ISSUE THREAD

**Issue by Migita6** [junyanz/pytorch-CycleGAN-and-pix2pix#795]
Hi!
I have a question about the composition of a dataset.
If there are similar questions in the past, I'm sorry.

I want to perform segmentation with images cut out from videos with Pix2pix.
In that case, is it possible to test with only the cut outed image without combining the correct image?
Best regars.

**Comment by junyanz** [comment]
Yes, please use `--model test`. See this [section](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-pix2pix) for more details.  Also, add the pix2pix generator flags `--netG unet --norm batch` or whatever you used.

**Comment by Migita6** [comment]
Thank you
