### ISSUE TITLE
Question about line 156 in utils.visualizer.

### ISSUE THREAD

**Issue by EricKani** [junyanz/pytorch-CycleGAN-and-pix2pix#798]
Hi,

Firstly, I must express my admire for this project's producers. This project is really awsome and useful for writing a new project for reference.

I have a question about line 156 in code of 'util.visualizer'. Should there be '(`save_result **and** not self.saved`)'? Because every iteration the 'visualizer instance' will be reseted in train.py(line 47). Whether interation meet the condition of `save_result = total_iters % opt.update_html_freq == 0`, `not self.saved` is `**True**`. `Fasle or True` and `True or True` are all `True`. The meaning of save_result is missing.

I don't know whether I said right. Hope to get reply~. Thanks.

Best regards,

Eric Kani

**Comment by junyanz** [comment]
Good catch. I think we should probably move `visualizer.reset()` out of the inner loop. We just need to reset it once every epoch. The purpose of this condition (L156) is to make sure that we save results to HTML at least once for each epoch, when `display_current_results` is called, and even when `update_html_freq` is much larger than `display_freq`.

**Comment by junyanz** [comment]
Just updated the code. Thanks again for reporting the issue.
