### ISSUE TITLE
Running remotely causes errors due to Visdom

### ISSUE THREAD

**Issue by rogertrullo** [junyanz/pytorch-CycleGAN-and-pix2pix#8]
Hi, after merging #3 , If I try to use a remote server through ssh, it is showing these errors

![image](https://cloud.githubusercontent.com/assets/8496304/25285377/fe93a446-2687-11e7-9b12-3833fbb2949b.png)

How can I run it without it trying to use use visdom?
Thanks!

**Comment by ruotianluo** [comment]
Did you do `python -m visdom.server`.
You can also set display_id to 0

**Comment by rogertrullo** [comment]
Thanks @ruotianluo , I hadn't done that. Currently I am opening an additional connection and opening the visdom server. Is there a way I can do that using only one connection?

**Comment by ruotianluo** [comment]
Open another screen? or run the server in background?

**Comment by rogertrullo** [comment]
Yes that's what I do right now open another screen, if  run it in the background is there a way to close the visdom server?

**Comment by rogertrullo** [comment]
I can close the server killing it with the pid (not sure if the cleanest way) when running in bg.
Thanks!
