### ISSUE TITLE
Question about the code.

### ISSUE THREAD

**Issue by EricKani** [junyanz/pytorch-CycleGAN-and-pix2pix#800]
Hi, Junyan:

I have two new question about the code.

First is `web_dir = os.path.join(opt.results_dir, opt.name, '%s_%s' % (opt.phase, opt.epoch))` in test.py(L49). There is `opt.epoch` consistently. But when you load model with `opt.load_iter`. This web_dir is probably not very precise.

Secondly, I see a Pull request about 'spectral normalization' in history. But no implementation in master code. I just want to know are there some wrong in the Pull code?

Thanks!

Best regards,

Eric Kani

**Comment by junyanz** [comment]
Yes. `opt.load_iter` is not used in the test code as it is an optional flag, which is not used very often. For completeness, I will add it to the test code. If `opt.load_iter > 0`, the test code will create a web directory using iteration for naming. `Spectral normalization` PR still needs some code review and clean up. But you are free to use this branch.

**Comment by EricKani** [comment]
Thank you, I will try this branch with `Spectral normalization`.
