### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by qianxiao111** [junyanz/pytorch-CycleGAN-and-pix2pix#801]
Hello, the document of testA is 17125 images, when I run the test code, the generation images in the results document are only 4744. Please tell me how to deal with this problem?

**Comment by junyanz** [comment]
The CycleGAN data loader takes the max(|testA_images|, |testB_images|). See this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/unaligned_dataset.py#L71). You can use the flag `--model test` to only test the model in one direction. See the instruction [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-cyclegan).

**Comment by qianxiao111** [comment]
Thank you very much!
