### ISSUE TITLE
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'

### ISSUE THREAD

**Issue by lucid0921** [junyanz/pytorch-CycleGAN-and-pix2pix#811]
When I run the code **"python train.py --dataroot ./datasets/monet2photo/ --name monet2photo_cyclegan --model cycle_gan"**, I got AttributeError like the tile **"AttributeError: module 'html5lib.treebuilders' has no attribute '_base'"**.

How can I solve this problem?

![image](https://user-images.githubusercontent.com/34934336/67347877-560eb680-f57e-11e9-9233-27cbe9792557.png)

![image](https://user-images.githubusercontent.com/34934336/67347917-72aaee80-f57e-11e9-9bca-beb22d84e39f.png)

![image](https://user-images.githubusercontent.com/34934336/67347933-7dfe1a00-f57e-11e9-834a-b0e376b3676d.png)

**Comment by junyanz** [comment]
Have you installed visdom? Does visdom work for you? It seems to be related to visdom rather than our codebase. Maybe you can post the question in the visdom repo.

**Comment by lucid0921** [comment]
Ok, thanks! I downgraded visdom and the code has been running. I'll see.
