### ISSUE TITLE
test.py RuntimeError: Error(s) in loading state_dict for UnetGenerator

### ISSUE THREAD

**Issue by Pavm96** [junyanz/pytorch-CycleGAN-and-pix2pix#812]
I have a saved model, and when i run this command: 

sudo python3 test.py --dataroot ./datasets/mydataset--model pix2pix --direction BtoA  --name test10

I get this error:

dataset [AlignedDataset] was created
initialize network with normal
model [Pix2PixModel] was created
loading the model from ./checkpoints/test10/latest_net_G.pth
Traceback (most recent call last):
  File "test.py", line 47, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/usr/myec2/pix2pix/models/base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "/usr/myec2/pix2pix/models/base_model.py", line 198, in load_networks
    net.load_state_dict(state_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for UnetGenerator:
        Missing key(s) in state_dict: "model.model.1.model.2.weight", "model.model.1.model.2.bias", "model.model.1.model.2.running_mean", "model.model.1.model.2.running_var", "model.model.1.model.3.model.2.weight", "model.model.1.model.3.model.2.bias", "model.model.1.model.3.......

**Comment by Pavm96** [comment]
Here are some of the options I used; may be relevant.

--model pix2pix --direction BtoA --batch_size 1 --norm instance --gpu_ids 0 --lr_policy linear --beta1 0.9 --lr 0.000001 --name test10 --gan_mode lsgan --init_type xavier

**Comment by junyanz** [comment]
Please also add `--norm instance` in your test code. The default one for pix2pix is `--norm batch`.

**Comment by Pavm96** [comment]
Worked. Thank you.
