### ISSUE TITLE
Dataset image size

### ISSUE THREAD

**Issue by Migita6** [junyanz/pytorch-CycleGAN-and-pix2pix#813]
Hi!
I have a question about a dataset.
Does the data set have to be square?
Is it possible to study and test without resizing?

**Comment by junyanz** [comment]
They don't have to be square images. During training time, you can crop square patches using the flag `--preprocess crop`. During test time, you can apply the model to images with arbitrary sizes (rectangle or not) using the flag `--preprocess none`.

**Comment by Migita6** [comment]
thank you!

**Comment by sybil12** [comment]
> They don't have to be square images. During training time, you can crop square patches using the flag `--preprocess crop`. During test time, you can apply the model to images with arbitrary sizes (rectangle or not) using the flag `--preprocess none`.

but out of memory

**Comment by carpemonf** [comment]
> They don't have to be square images. During training time, you can crop square patches using the flag `--preprocess crop`. During test time, you can apply the model to images with arbitrary sizes (rectangle or not) using the flag `--preprocess none`.

Hi @junyanz. I'm following these steps for my tests with pix2pix. I'm using `--preprocess crop` during training with 256x256 crops, and `--preprocess none` for testing 432x1072 images. However, I'm getting the following error for the tests:

`RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 2 and 3 in dimension 3 at`

Do you have any idea where the problem might be?
Thank you.
