### ISSUE TITLE
With net_G: unet_256, how to keep the size of the input?

### ISSUE THREAD

**Issue by jzchenriver** [junyanz/pytorch-CycleGAN-and-pix2pix#815]
Thank you for your wonderful project. It helps me a lot.

Recently, I have a pre-trained pix2pix model, in which net_G is unet_256. When I tried to translate a 1920x1088 picture with this option, the output was resized to 256x256. 

> python test.py --dataroot ./datasets/rgb2ir/ --name rgb2ir_pretrained --model test --netG unet_256 --direction AtoB --dataset_mode single --norm batch --output_nc 1

Is there a method to keep the size of the input picture? Must I retrain the model with net_G: resnet_9blocks?

**Comment by junyanz** [comment]
You probably need to retrain your models with `resnet_9blocks`. It depends on both `--netG` and `--preprocess`. See the [Q & A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#trainingtesting-with-rectangular-images) for more details.
