### ISSUE TITLE
Prepare dataset for CycleGAN

### ISSUE THREAD

**Issue by kpagels** [junyanz/pytorch-CycleGAN-and-pix2pix#816]
First of all thank you for this great implementation.

I have a question about whether you have some tips for preparing dataset for CycleGAN. I havent been able to find anything talking about this specific thing online. Do you have some links for this?  

I have two datasets that has the following distribution of data:

**Dataset A:**
_Class 1: 1280
Class 2: 420
Class 3: 1270_

**Dataset B:**
_Class 1: 3000
Class 2: 3000
Class 3: 3000_

As you can see **dataset A** has less images in class 2. And **dataset B** has the same numbers of images pr class. But there are more data in **dataset B** then in **dataset A.** 

1) Does it make sense to split my datasets into training / testing parts? And if so, should it be 70 / 30? I want to use my generated images for training a network for classification.

2) Should I either remove some images from class 1 and class 3, or do data augmentation on class 2? Or is it fine to keep it as is? 

3) Should I have the same number of images in **dataset A** as in **dataset B** to do proper training?

**Comment by junyanz** [comment]
1. You probably need some training/test split, as you need to evaluate your classifier's performance. You can also just follow the training/test split for your classification task. 
2. I think it's fine to keep it as it.
3. They don't have to be the same.

**Comment by kpagels** [comment]
Thanks!
