### ISSUE TITLE
There is something wrong when training with gpu

### ISSUE THREAD

**Issue by cjb752815359** [junyanz/pytorch-CycleGAN-and-pix2pix#817]
When I was training with gpu, there is a error :
---------- Networks initialized -------------
[Network G_A] Total number of parameters : 11.378 M
[Network G_B] Total number of parameters : 11.378 M
[Network D_A] Total number of parameters : 2.765 M
[Network D_B] Total number of parameters : 2.765 M
-----------------------------------------------
Setting up a new session...
create web directory E:\ChenJiabing\pytorch-CycleGAN-and-pix2pix-master\weights\mini\web...

Process finished with exit code -1073741819 (0xC0000005)

I debug it and find the problem is at backward. The last function is Variable._execution_engine.run_backward(
        tensors, grad_tensors, retain_graph, create_graph,
        allow_unreachable=True)  # allow_unreachable flag
But when with cpu ,everything is fine.

**Comment by cjb752815359** [comment]
Before the project stops, the gpu is 100%, but the memory of gpu is 11GB.

**Comment by junyanz** [comment]
Does it work with default datasets and training script? Could you run the demo code of PyTorch?

**Comment by cjb752815359** [comment]
> Does it work with default datasets and training script? Could you run the demo code of PyTorch?

I find that problem is also in ssd which is implemented in Pytorch. Maybe the key point is Pytorch?

**Comment by cjb752815359** [comment]
> Does it work with default datasets and training script? Could you run the demo code of PyTorch?

I test some project.
Project1(Simple):
import torch
from torch.autograd import Variable

w1 = torch.Tensor([2]) #认为w1 与 w2 是函数f1 与 f2的参数
w1 = Variable(w1,requires_grad=True)
w2 = torch.Tensor([2])
w2 = Variable(w2,requires_grad=True)
x2 = torch.rand(1)
x2 = Variable(x2,requires_grad=True)
y2 = x2**w1            # f1 运算
z2 = w2*y2+1           # f2 运算
z2.backward()
print(x2.grad)
print(y2.grad)
print(w1.grad)
print(w2.grad)
I can get the result.
Project2:
A CNN experiment.
The address is https://github.com/MorvanZhou/PyTorch-Tutorial/blob/master/tutorial-contents/502_GPU.py.
The same problem occurs again.

**Comment by avichapman** [comment]
Hi. Did you ever solve this problem?

**Comment by kolessios** [comment]
@avichapman In my case this problem occurred because I did not have CUDA 9.2 installed. Since I have CUDA 10.2 what I did was update PyTorch in `requirements.txt` for a version that was compatible with that and the problem disappeared.
