### ISSUE TITLE
Generate infrared images from visual images

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [junyanz/pytorch-CycleGAN-and-pix2pix#827]
Hi sir,   I have Infrared and visual images with same information I want to train the GAN on these images and then generate new infrared images by using some other visual images.    Which project do you recommend and Can i work with my own dataset? 

Training = both infrared and visual images with same information.

Generate = infrared images from given new visual images.

**Comment by junyanz** [comment]
If you have paired visual-infrared images, you can try pix2pix. (Otherwise, you can try cyclegan) You may want to write your custom data loader for processing your images. See a template [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/template_dataset.py).

**Comment by MuhammadAsadJaved** [comment]
yes sir I have enough paired visual-infrared images.  I will try pix2pix. Bundle of thanks.

**Comment by YangBo0411** [comment]
> Hi sir, I have Infrared and visual images with same information I want to train the GAN on these images and then generate new infrared images by using some other visual images. Which project do you recommend and Can i work with my own dataset?
> 
> Training = both infrared and visual images with same information.
> 
> Generate = infrared images from given new visual images.

Hello, I want to achieve the same goal as you, but I have used both pix2pix and cyclegan networks which have not been very effective. Have you solved your problem? Can you share your experience?
