### ISSUE TITLE
A mistake occurred while training cyclegan

### ISSUE THREAD

**Issue by infororange** [junyanz/pytorch-CycleGAN-and-pix2pix#829]
when i use 
python train.py --dataroot ./datasets/horse2zebra --name horse2zebra --model cycle_gan
There will be errors :
NotSupportedError: slicing multiple dimensions at the same time isn't supported yet
        proposals (Tensor): boxes to be encoded
    """
    # perform some unpacking to make it JIT-fusion friendly
    wx = weights[0]
    wy = weights[1]
    ww = weights[2]
    wh = weights[3]

    proposals_x1 = proposals[:, 0].unsqueeze(1)
                   ~~~~~~~~~ <--- HERE
    proposals_y1 = proposals[:, 1].unsqueeze(1)
    proposals_x2 = proposals[:, 2].unsqueeze(1)
    proposals_y2 = proposals[:, 3].unsqueeze(1)

    reference_boxes_x1 = reference_boxes[:, 0].unsqueeze(1)
    reference_boxes_y1 = reference_boxes[:, 1].unsqueeze(1)
    reference_boxes_x2 = reference_boxes[:, 2].unsqueeze(1)
    reference_boxes_y2 = reference_boxes[:, 3].unsqueeze(1)

How should this be solved?thank you so much!

**Comment by junyanz** [comment]
Not sure if it is relevant to our repo. We didn't use `reference_boxes` in this codebase.

**Comment by zhihaoWang1994** [comment]
你好 我们也遇到了这个问题   请问您解决了么

**Comment by mojoee** [comment]
Same Problem right here

**Comment by junyanz** [comment]
It might be caused by the incompatibility between your PyTorch version and torchvision version.

**Comment by mojoee** [comment]
@junyanz that's right. I fixed it by uninstalling the pytorch libraries and reinstalling it with another version. Now the code is running.
