### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by liuhh02** [junyanz/pytorch-CycleGAN-and-pix2pix#833]
Hello everyone, I've created my own custom dataset for pix2pix and also ran `python datasets/combine_A_and_B.py --fold_A /path/to/data/A --fold_B /path/to/data/B --fold_AB /path/to/data`. The command executed nicely and generated the paired {A, B} images as promised. However, when I try to run the train command `python train.py --dataroot path/to/ABdata --name pet_pix2pix --model pix2pix --input_nc 1 --output_nc 1` I get an error saying 

> ValueError: num_samples should be a positive integer value, but got num_samples=0

My image type is tiff so I changed the line `AB = Image.open(AB_path).convert('RGB')` in data/aligned_dataset.py to `AB = Image.open(AB_path)`. Could that be contributing to the problem?
This is the full error message:

> dataset [AlignedDataset] was created
> Traceback (most recent call last):
>   File "train.py", line 29, in <module>
>     dataset = create_dataset(opt)  # create a dataset given opt.dataset_mode and other options
>   File "/content/pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 57, in create_dataset
>     data_loader = CustomDatasetDataLoader(opt)
>   File "/content/pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 79, in __init__
>     num_workers=int(opt.num_threads))
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 213, in __init__
>     sampler = RandomSampler(dataset)
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/sampler.py", line 94, in __init__
>     "value, but got num_samples={}".format(self.num_samples))
> ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by liuhh02** [comment]
After doing some tinkering around, I finally found the reason why I was getting the error! Turns out under data/image_folder.py there's a line
`IMG_EXTENSIONS = [
    '.jpg', '.JPG', '.jpeg', '.JPEG',
    '.png', '.PNG', '.ppm', '.PPM', '.bmp', '.BMP',
]`
and it doesn't contain '.tiff' and '.TIFF', so it wasn't reading the image files. So just add in the two lines to get
`IMG_EXTENSIONS = [
    '.jpg', '.JPG', '.jpeg', '.JPEG', 
    '.png', '.PNG', '.ppm', '.PPM', '.bmp', '.BMP', '.tif', '.TIF', '.tiff', '.TIFF',
]`
and the error should go away!

**Comment by junyanz** [comment]
Great. I will add the format to the latest commit.
