### ISSUE TITLE
Generating images of same file type as input

### ISSUE THREAD

**Issue by liuhh02** [junyanz/pytorch-CycleGAN-and-pix2pix#837]
Hello, I am using tiff images in the training of my pix2pix model. However, during the training and testing, the images generated are in the png format instead of tiff. As a result, the generated png image is completely black. Is there any way I can modify the code to generate images in a tiff format? Thank you!

**Comment by junyanz** [comment]
You can modify the `save_image` function [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/util/util.py#L49)

**Comment by liuhh02** [comment]
@junyanz Thank you very much! I modified the line to say `image_pil = Image.fromarray(image_numpy, mode='F')`. However, I am now getting an error saying 

> ValueError: Too many dimensions: 3 > 2.

that the Image dimensions is 3 instead of 2. Was the image converted to 3D in during the testing phase?

**Comment by junyanz** [comment]
I am not sure. You can print the shape of the image_numpy.

**Comment by liuhh02** [comment]
@junyanz Ok, I have printed out the shape of the image array and it says (256, 256, 3). Is there any reason why there is a 3 in the 3rd dimension? I have set the input and output channels to 1, so I am not sure why there is a 3 at the end. Are there perhaps any other areas in the code which might be creating this extra dimension? Thank you for your help!

**Comment by liuhh02** [comment]
Another problem is the `image_path` parameter in the `save_image` function – I can't save the image as tiff as the default is .png. When I tried to print `image_path`, I got the directory /results/model_name/test_latest/images/image1_real_A.png, meaning it is already appending the .png file format to the file and hence I cannot save the image as a tiff. Where can I change this? I've tried tracing back the code from `img_path = model.get_image_paths()` in the test.py file to the [create_model](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/1c733f5bd7a3aff886403a46baada1db62e2eca8/models/__init__.py#L54) function in models/__init__.py to the `get_image_paths(self)` function at [models/base_model.py](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/1c733f5bd7a3aff886403a46baada1db62e2eca8/models/base_model.py#L112) but so far no luck as the get_image_paths(self) function says:

> def get_image_paths(self):
        """ Return image paths that are used to load current data"""
        return self.image_paths

and I am loading the data in as tiff, so I'm not sure where to go on from there. Any ideas how I can change the .png to .tiff? Thank you for your help!

**Comment by junyanz** [comment]
You can use `str.replace`. See this [tutorial](https://www.tutorialspoint.com/python/string_replace.htm).

**Comment by liuhh02** [comment]
@junyanz Ok I got that, thank you! I would like to clarify Is there any reason why there is a 3 in the 3rd dimension for image_numpy? I have set the input and output channels to 1, so I am not sure why there is a 3 at the end. Are there perhaps any other areas in the code which might be resulting in a 3? Thank you for your help!

**Comment by junyanz** [comment]
We assume it is often an RGB image. But feel free to change it for your application.

**Comment by liuhh02** [comment]
@junyanz Alright got it, thanks a lot for your help!
