### ISSUE TITLE
How to retrain model using saved weights?

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [junyanz/pytorch-CycleGAN-and-pix2pix#840]
Hi , 
      I have trained a pix2pix model on custom dataset for 200 epochs and tested it but the generated images are not very good.   can you give me some suggestion to increase the performance? 
1-I have trained model on 512 x 512 visual images to generate infrared images using paired images.
2- How can I continue the training from last stored weights? Do you think the performance will increase if i train this model more ? i.e for 1000 epoch.
3-Please see few attached input and output examples generated with trained model. 
3- Any other suggestions to increase the quality of output? 
![1](https://user-images.githubusercontent.com/28862708/68822661-7daff500-06cc-11ea-8e16-009d8e6b8571.png)
![1output](https://user-images.githubusercontent.com/28862708/68822664-7daff500-06cc-11ea-85fe-1f93bb101e16.png)
![2](https://user-images.githubusercontent.com/28862708/68822665-7e488b80-06cc-11ea-941e-1e8a7304540e.png)
![2output](https://user-images.githubusercontent.com/28862708/68822667-7e488b80-06cc-11ea-9c46-ccd8cda760ee.png)
![3](https://user-images.githubusercontent.com/28862708/68822668-7e488b80-06cc-11ea-9790-2364a64f73e0.png)
![3output](https://user-images.githubusercontent.com/28862708/68822669-7ee12200-06cc-11ea-8064-8f84a5ffebe9.png)
![4](https://user-images.githubusercontent.com/28862708/68822670-7ee12200-06cc-11ea-8cde-4fe5670577d7.png)
![4output](https://user-images.githubusercontent.com/28862708/68822673-7f79b880-06cc-11ea-906d-27f0b6d740e9.png)

**Comment by junyanz** [comment]
See this [Q & A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#can-i-continueresume-my-training-350-275-234-87) regarding continue training. For better results, you can try our recent work such as [pix2pixHD](https://github.com/NVIDIA/pix2pixHD) and [SPADE](https://github.com/NVlabs/SPADE).

**Comment by MuhammadAsadJaved** [comment]
Thank you very much.
