### ISSUE TITLE
This also work in windows10

### ISSUE THREAD

**Issue by vicdxxx** [junyanz/pytorch-CycleGAN-and-pix2pix#845]
It can work in windows10, I test cycleGAN part, should add this platform in introduction list?

**Comment by junyanz** [comment]
This is good to know. Maybe not in the introduction list, as we cannot provide full support now and we haven't fully tested the code.  (as we don't have a windows machine).

**Comment by stefenmax** [comment]
how to receive data in windows, because the bash cant use

**Comment by ApoorvaSuresh** [comment]
@stefenmax did you find a way to do it? Please let me know :)

**Comment by junyanz** [comment]
You can download the data from our [website](http://efrosgans.eecs.berkeley.edu/cyclegan/datasets/) directly.
