### ISSUE TITLE
Cycle gan is symmetry,why the performance of  B to A is wrose than  A to B?

### ISSUE THREAD

**Issue by zjuxiaobaiq** [junyanz/pytorch-CycleGAN-and-pix2pix#849]
Cycle gan is symmetry,why the performance of  B to A is wrose than  A to B?

**Comment by junyanz** [comment]
The model is symmetric. But datasets and tasks might be not. Sometimes, translating A to B is harder than the other direction.

**Comment by zjuxiaobaiq** [comment]
thanks! 

> The model is symmetric. But datasets and tasks might be not. Sometimes, translating A to B is harder than the other direction.



> The model is symmetric. But datasets and tasks might be not. Sometimes, translating A to B is harder than the other direction.

**Comment by zjuxiaobaiq** [comment]
> The model is symmetric. But datasets and tasks might be not. Sometimes, translating A to B is harder than the other direction.

Thanks! May i ask  another questions ?
1.In my task,Loss_D_B goes to zero after several epoch while loss_D_A looks good.Does the failure of discriminate D will have bad effect on the G_A and D_A？
2.I supervise the train process by watching the pictures generated by the G_A. And it seems look good.However,  when i try to test the G_A with 200 test pictures ,the result is so bad that i can not recognise what is . What problem may happen,could you give me some advices?

**Comment by junyanz** [comment]
1. It may potentially hurt the performance of G_A.
2. Not sure what happened. For sanity check, you can run your test script and your model on your training images, and see if it looks as good as before. Make sure you use similar or compatible training and test parameters (e.g., `--preprocess`, `--load_size`, `--crop_size`, etc.)

**Comment by zjuxiaobaiq** [comment]
> It may potentially hurt the performance of G_A.
> Not sure what happened. For sanity check, you can run your test script and your model on your training images, and see if it looks as good as before. Make sure you use similar or compatible training and test parameters (e.g., --preprocess, --load_size, --crop_size, etc.)

Perhaps something wrong with my own data,now the model works.Thanks a lot!
