### ISSUE TITLE
Transfer Learning with pix2pix

### ISSUE THREAD

**Issue by liuhh02** [junyanz/pytorch-CycleGAN-and-pix2pix#857]
Hello, thank you for your great work! I would like to ask about the possibility of applying transfer learning to the discriminator in pix2pix. The source and target images are concatenated together at the channel level, hence the resulting channels is 6 instead of 3. However, most if not all transfer learning models are trained with and expect images in 3 channels, so how can I use these pre-trained models in the discriminator?

**Comment by junyanz** [comment]
You can use 6 channel discriminator as long as you do it for both source and target domains.

**Comment by liuhh02** [comment]
Do you mean that I can apply the transfer learning models to the source and target images separately as 3 channel images before concatenating them together?

**Comment by junyanz** [comment]
That might work. You can also modify the first layer of your model (from 3 channel input to 6 channel input) and use the pre-trained weights for the rest of the network.

**Comment by liuhh02** [comment]
Thanks a lot for your help!

**Comment by chinery** [comment]
Hi @liuhh02, I wondered if you ever found any interesting results with transfer learning on pix2pix? Either on the discriminator or the generator?

**Comment by liuhh02** [comment]
> Hi @liuhh02, I wondered if you ever found any interesting results with transfer learning on pix2pix? Either on the discriminator or the generator?

Yes I did! I applied pix2pix to the medical domain, specifically to translate between MRI and PET scans. I have published my findings [here](https://ieeexplore.ieee.org/abstract/document/9182970) and [here](https://link.springer.com/article/10.1007/s00259-020-05131-z).
