### ISSUE TITLE
Resume Training from the last saved checkpoint

### ISSUE THREAD

**Issue by Maria-Siddiqua** [junyanz/pytorch-CycleGAN-and-pix2pix#859]
I want to know that **"What modification in the code is required to resume the training from the last saved checkpoint, if one wants to do training in parts"** ?

**Comment by junyanz** [comment]
See this [FAQ](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#fine-tuningresume-training).
