### ISSUE TITLE
Enhancing the continuity between 2D frames in videos or 3D data?

### ISSUE THREAD

**Issue by WeisiX** [junyanz/pytorch-CycleGAN-and-pix2pix#869]
Great work! The famous horse-to-zebra video displays an amazing result in stability and continuity between adjacent time frames. I am wondering is the network just simply trained with individual 2D images or is there anything special during training phase to enhance the continuity between frames? Thanks in advance!

**Comment by junyanz** [comment]
The network is trained with 2D images only. You can still see flickering artifacts if you look at the results carefully. In a follow-up work [vid2vid](https://github.com/NVIDIA/vid2vid), we trained models on videos and enforced continuity during training.

**Comment by WeisiX** [comment]
Thank you! @junyanz
