### ISSUE TITLE
Can a self supervised technique be used for generating paired image?

### ISSUE THREAD

**Issue by kalai2033** [junyanz/pytorch-CycleGAN-and-pix2pix#878]
Hi,
  I have used your pix2pix GAN model with my custom dataset. But the process of generating image pairs takes a lot of time. I have very less data around 100 image pairs. Even when I tried cycle GAN the results were not great. I came across the term self-supervised learning. My question is whether can I use self-supervision to image translation tasks since I have very little data.

**Comment by junyanz** [comment]
In some sense, CycleGAN is using the idea of self-supervised learning for image-to-image translation. If you have some paired data and still want to use unlabelled data, you can train models in a semi-supervised learning setting by mixing the objective of pix2pix and CycleGAN.  Here is a recent [work](https://arxiv.org/pdf/1901.08212.pdf) on this topic.
