### ISSUE TITLE
How can i save model more frequently?

### ISSUE THREAD

**Issue by GiovanniPasq** [junyanz/pytorch-CycleGAN-and-pix2pix#879]
i need to save model after a predefined number of iterations, is there a way to do this? Or should I wait for the end of an epoch? Can I set the maximum number of iterations?

**Comment by junyanz** [comment]
Two flags `----save_by_iter` and `--save_latest_freq` can do the job for you. See this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/train_options.py#L23) and #683 for more details
