### ISSUE TITLE
'aligned_data mode' means the data is paired?

### ISSUE THREAD

**Issue by khryang** [junyanz/pytorch-CycleGAN-and-pix2pix#88]
if the dataset_mode == aligned
then, does the data have to be paired?

I don't know exectly what it means, 'aligned', 'unaligned', and 'single'

**Comment by junyanz** [comment]
Yes, `aligned` means that the input and output images are aligned/paired (e.g. in pix2pix). `Unaligned` means that the input/output images are unpaired (in cyclegan), and `single` means that only input images are needed/used.  I will probably change the naming to paired/unpaired later.

**Comment by khryang** [comment]
@junyanz  ah.. but in the previous version of cycle-gan code, it used the default setting of dataset as 'aligned data' ----> (at here, in base_option) https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/e6858e35f0a08c6139c133122d222d0d85e8005d

that time I trained the network(cycle-gan), but during training the data was not imported with paired.
Anyway, it showed good result.

**Comment by SsnL** [comment]
@khryang That is probably because that the datasets you used aren't paired.
