### ISSUE TITLE
Question about sets size ratio

### ISSUE THREAD

**Issue by domef** [junyanz/pytorch-CycleGAN-and-pix2pix#880]
I'm sorry if this is a trivial quesiton. I want to train a CycleGAN using my dataset A (about 5000 images) and a public synthetic dataset B (about 5 milions images). How many images should I choose from dataset B? In other words, must the two sets have approximately the same size or one can be much bigger then the other? Does it depends on whether I want to train AtoB or BtoA?

Edit: another question, does the images from the two sets need to have the same size?

**Comment by junyanz** [comment]
The number of images in the two datasets can be different. For example, if we transform a Monet's painting to a landscape photo, we only have a few hundreds of paintings, but we can use lots of natural photos. I recommend that you use the same or similar image sizes.
