### ISSUE TITLE
Can this repo be used on windows10?

### ISSUE THREAD

**Issue by wallcuber** [junyanz/pytorch-CycleGAN-and-pix2pix#885]

**Comment by wallcuber** [comment]
pytorch 1.3

**Comment by junyanz** [comment]
We haven't tested it by ourselves. But several users have reported that they managed to use it on Windows (e.g. #845)

**Comment by wallcuber** [comment]
> We haven't tested it by ourselves. But several users have reported that they managed to use it on Windows (e.g. #845)

thanks for your reply : )
