### ISSUE TITLE
Training and test images size

### ISSUE THREAD

**Issue by domef** [junyanz/pytorch-CycleGAN-and-pix2pix#886]
I want to translate dataset A to dataset B. Images in A are 1280x1024 and images in B are 128x128. During training i just resize and crop the first dataset but I'm wondering if then I can generate new images using full size (1024x1080) or if it can be a problem as the network has been trained on much smaller images.

**Comment by junyanz** [comment]
It is possible. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#trainingtesting-with-high-res-images) for more details.
