### ISSUE TITLE
Testing single images with the "test" model doesn't work per the ReadMe

### ISSUE THREAD

**Issue by macrael** [junyanz/pytorch-CycleGAN-and-pix2pix#89]
Following the readme instructions for training a model with pix2pix and then trying to test the model on a collection of single images gave me the following error. The only thing I did different from the readme instructions was I ran it on my CPU (both in training and in testing) with `--gpu_ids -1`. 

Here's my training command: 
`python train.py --dataroot ./datasets/little_numbers --name little_numbers --model pix2pix --which_model_netG unet_256 --which_direction BtoA --lambda_A 100 --dataset_mode aligned --no_lsgan --norm batch --gpu_ids -1`

And my testing command: 
`python test.py --dataroot ./datasets/little_numbers/single_test/ --name little_numbers --model test --which_model_netG unet_256 --which_direction BtoA --dataset_mode single --gpu_ids -1`

And the error: 
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    model = create_model(opt)
  File "/Users/macrael/code/pytorch-CycleGAN-and-pix2pix/models/models.py", line 19, in create_model
    model.initialize(opt)
  File "/Users/macrael/code/pytorch-CycleGAN-and-pix2pix/models/test_model.py", line 22, in initialize
    self.load_network(self.netG, 'G', which_epoch)
  File "/Users/macrael/code/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 56, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/Users/macrael/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 383, in load_state_dict
    .format(name))
KeyError: 'unexpected key "model.model.1.model.2.weight" in state_dict'
```

This reproduced as well with the facades dataset that is used in the Readme.

**Comment by junyanz** [comment]
I guess you need to add `--norm batch` to the test script. By default, it will use `--norm instance`.

**Comment by macrael** [comment]
Thanks! That fixed it.
