### ISSUE TITLE
No models saved in Colab

### ISSUE THREAD

**Issue by domef** [junyanz/pytorch-CycleGAN-and-pix2pix#890]
I was using the PyTorch Colab notebook of CycleGAN. I trained the network using `!python train.py --dataroot ./datasets/horse2zebra --name horse2zebra --model cycle_gan --display_id -1 --n_epochs 5 --n_epochs_decay 5` but it didn't saved any model (I'm using default settings to save every 5000 iterations, in fact it printed several times that something was saved to `checkpoint` folder, but the folder was empty).

**Comment by junyanz** [comment]
Not sure if you have the write permission to the directory that saves models. You can specify it using `'--checkpoints_dir`.

**Comment by domef** [comment]
The default folder `checkpoints` had the right permissions, but even applying `chmod 777` didn't solve the problem. Changing directoty with `--checkpoints_dir` solved instead the problem. Thanks.

**Comment by YXD123450** [comment]
> 不知道您是否具有对保存模型的目录的写许可权。您可以使用指定它`--checkpoints_dir`。



> Not sure if you have the write permission to the directory that saves models. You can specify it using `--checkpoints_dir`.

Where should I put the '--checkpoints_dir‘

**Comment by YXD123450** [comment]
> The default folder `checkpoints` had the right permissions, but even applying `chmod 777` didn't solve the problem. Changing directoty with `--checkpoints_dir` solved instead the problem. Thanks.

Where should I put the '--checkpoints_dir‘

**Comment by junyanz** [comment]
add it to the arguments of `python train.py ...`.

**Comment by MariaSun** [comment]
> > The default folder `checkpoints` had the right permissions, but even applying `chmod 777` didn't solve the problem. Changing directoty with `--checkpoints_dir` solved instead the problem. Thanks.
> 
> Where should I put the '--checkpoints_dir‘

I have the same question.
