### ISSUE TITLE
Not getting saved checkpoints on Google Colab

### ISSUE THREAD

**Issue by himansh1314** [junyanz/pytorch-CycleGAN-and-pix2pix#891]
When I am trying to train on my dataset, I'm not getting checkpoints saved after every 5 epochs. I know the problem with google colab, that it has issues with visdom. I'm okay with visdom not working, but even the checkpoints aren't saved in the checkpoints directory. Please help.

**Comment by domef** [comment]
I had the same problem (https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/890). Just create another folder and use it to save models with `--checkpoints_dir your_folder`.

**Comment by junyanz** [comment]
It seems to be solved with #890. So I close this issue.

**Comment by himansh1314** [comment]
> I had the same problem (#890). Just create another folder and use it to save models with `--checkpoints_dir your_folder`.

Thanks for your help, it worked.
