### ISSUE TITLE
Question about max_dataset_size

### ISSUE THREAD

**Issue by domef** [junyanz/pytorch-CycleGAN-and-pix2pix#896]
The parameter `max_dataset_size ` limits the maximum number of images used. But I'm wondering, if I have `n` images in my dataset and max_dataset_size is `m`, does the network use the same `m` images at each epoch or are they chosen randomly each time? I'm using `unalignes_dataset`.

**Comment by junyanz** [comment]
It will use the set of m images, as it was used to create the dataset during initialization. See this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/unaligned_dataset.py#L29).

**Comment by domef** [comment]
Do you think that it would be useful give the network a different subset each epoch? I think it can be good because it allows to have a bigger dataset without increasing the training time.

**Comment by junyanz** [comment]
then you can just use the original dataset, and reduce the number of epoches?

**Comment by domef** [comment]
Yes, I think it can work. Thank you very much.
