### ISSUE TITLE
Question about resize and crop

### ISSUE THREAD

**Issue by domef** [junyanz/pytorch-CycleGAN-and-pix2pix#897]
I have 256x256 images in dataset A and 128x128 images in dataset B. If I use `--preprocess resize_and_crop --load_size 256 --crop_size 128`, the images in dataset B are loaded at 128x128 or upscaled to 256x256 and the  cropped at 128x128?

**Comment by junyanz** [comment]
For dataset B. 
(1) your 128x128 input image will be resized to 256x256
(2) the program will crop a 128x128 patch from your 256x256 upscaled image.
