### ISSUE TITLE
Generator samples from other dataset

### ISSUE THREAD

**Issue by domef** [junyanz/pytorch-CycleGAN-and-pix2pix#898]
I trained a CycleGAN with default parameters (but images loaded at 128x128 without cropping) for 200 epochs. The images generated are bad, but that's not the point. The strange thing is that sometimes the generator samples modified images from destination dataset. Have you ever seen this problem? Do you have any idea what can cause this problem?

**Comment by junyanz** [comment]
Not sure if I fully understand your question. What does it mean by "sometimes the generator samples modified images from destination dataset."? what is a modified image?

**Comment by domef** [comment]
I mean that, if I translate from A to B, the result it's just an image from B. Anyway, it seems I almost solved the problem cropping the images (I didn't used crop before).

**Comment by junyanz** [comment]
Glad that you figured it out. Cropping can prevent from memorizing training images from domain B.
