### ISSUE TITLE
help! valueError:signal number 32 out of range

### ISSUE THREAD

**Issue by fdgyhbn** [junyanz/pytorch-CycleGAN-and-pix2pix#901]
I run command like this:
  python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan

And get error below.I don't know why.

Setting up a new session...
create web directory ./checkpoints/maps_cyclegan/web...
Exception in thread Thread-1:
Traceback (most recent call last):
File"/mnt/dailongquan/10819_hongchen/anaconda3/envs/cyclegan1/lib/python3.5/threading.py",
line 914, in _bootstrap_inner
    self.run()
File "/mnt/dailongquan/10819_hongchen/anaconda3/envs/cyclegan1/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
File"/mnt/dailongquan/10819_hongchen/anaconda3/envs/cyclegan1/lib/python3.5/multiprocessing/resource_sharer.py", line 139, in _serve
    signal.pthread_sigmask(signal.SIG_BLOCK, range(1, signal.NSIG))
File "/mnt/dailongquan/10819_hongchen/anaconda3/envs/cyclegan1/lib/python3.5/signal.py", line 60, in pthread_sigmask
    sigs_set = _signal.pthread_sigmask(how, mask)
ValueError: signal number 32 out of range

**Comment by junyanz** [comment]
I think the error is related to your PyTorch version. This [issue](https://github.com/NVIDIA/flownet2-pytorch/issues/119) might be related.

**Comment by junyanz** [comment]
Cool. We will update the xml accordingly.
