### ISSUE TITLE
Notes on Colorization

### ISSUE THREAD

**Issue by Rubiel1** [junyanz/pytorch-CycleGAN-and-pix2pix#905]
> . Also set --input_nc 1 and --output_nc 2.

From [notes-on-colorization](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#notes-on-colorization).

Why 2? I assume colorization returns an rgb image? If this is not a typo, I am curious about why 2 is advised.

**Comment by junyanz** [comment]
It is correct. It works in Lab space. It takes the L channel as input, and predict ab channel. Chromatic information has 2 channels. Intensity has been given by the grayscale input.

**Comment by Rubiel1** [comment]
I see, thanks!
