### ISSUE TITLE
Could u help me?

### ISSUE THREAD

**Issue by YINDAIYING** [junyanz/pytorch-CycleGAN-and-pix2pix#908]

**Comment by YINDAIYING** [comment]
Hi there, my program is always killed with a single message "Killed" at one particular epoch, which is epoch 29. I really cannot figure out why without the exact error message. By the way, I am using 8G GPU, shouldn't be the memory issue.

**Comment by YINDAIYING** [comment]
Sorry it doesn't always end at one particular epoch. just around 25. Thank you!

**Comment by junyanz** [comment]
Hard to know what has happened without further information. Are you using a cluster? It might be killed by other users.

**Comment by YINDAIYING** [comment]
Ya i am using company cluster.....maybe killed by others I guess:(
