### ISSUE TITLE
can i run this repository using cpu only?

### ISSUE THREAD

**Issue by manvirvirk** [junyanz/pytorch-CycleGAN-and-pix2pix#912]
can i do training with gpu and cuda as i dont have these resources right now? i have only cpu. thanks

**Comment by diaosiji** [comment]
> can i do training with gpu and cuda as i dont have these resources right now? i have only cpu. thanks

Yes you can, I do it all day.

**Comment by manvirvirk** [comment]
using cpu only???

**Comment by manvirvirk** [comment]
I m getting this error as i dont have gpu and cuda.
please help, thanks.
![SharedScreenshot](https://user-images.githubusercontent.com/54542400/73914060-6ef96880-48de-11ea-94e5-f70f602dbbf2.jpg)

**Comment by diaosiji** [comment]
You can read [Training/test Tips](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md), it helped.

**Comment by manvirvirk** [comment]
how to set --gpu_ids -1 ? i mean where to add this ?

**Comment by diaosiji** [comment]
Just add it after your training command. For example: python test.py --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --direction BtoA --gpu_ids -1

**Comment by manvirvirk** [comment]
it worked, thanks!
