### ISSUE TITLE
Test pix2pix single dataset mode

### ISSUE THREAD

**Issue by sand47** [junyanz/pytorch-CycleGAN-and-pix2pix#913]
I was trying to test the pix2pix trained model on single dataset mode that is there is only domain A images in the test set folder and I want it to be translated into domain B. I see that we have an option for one side only for CycleGAN in the test.py header but is it possible to do the same for pix2pix if so it would be great if someone can tell me the test command, please?  and thanks a lot @junyanz for open sourcing this wonderful architecture.

Thanks

**Comment by junyanz** [comment]
The `--model test` also works for the pix2pix model. You need to modify the model name using ` --name`. Also, you need to make sure the dropout and normalization flags are the same as those used during training.

**Comment by sand47** [comment]
Thanks! I get the following error saying (RuntimeError: Error(s) in loading state_dict for ResnetGenerator ) and during my training, I used Resnet9block as my generator network and below are my training and test command. It would be great if you can tell me where I went wrong. Thank you so much @junyanz 

**Training command:** 

python train.py --dataroot ./thousandimages/dataset --name pix2pix1000Res --model pix2pix  --direction AtoB --no_flip --checkpoints_dir trained_model  --netG resnet_9blocks --display_freq 1 --num_threads 1 --save_epoch_freq 2 --save_latest_freq 1

**Test command:** 

python test.py --dataroot ./thousandimages/dataset/testA --model test --name pix2pix1000Res  --direction AtoB  --checkpoints_dir trained_model --netG resnet_9blocks 

**Error:** 

----------------- Options ---------------
             aspect_ratio: 1.0                           
             batch_size: 1                             
            checkpoints_dir: trained_model                 	[default: ./checkpoints]
            crop_size: 256                           
            dataroot: ./thousandimages/starcraft/testA	[default: None]
           dataset_mode: single                        
           direction: AtoB                          
          display_winsize: 256                           
                    epoch: latest                        
                     eval: False                         
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                isTrain: False                         	[default: None]
                load_iter: 0                             	[default: 0]
                load_size: 256                           
         max_dataset_size: inf                           
                    model: test                          
             model_suffix:                               
               n_layers_D: 3                             
                     name: pix2pix1000Restrans           	[default: experiment_name]
                      ndf: 64                            
                     netD: basic                         
                     netG: resnet_9blocks                
                      ngf: 64                            
               no_dropout: False                         
                  no_flip: True                          	[default: False]
                     norm: instance                      
                    ntest: inf                           
                 num_test: 50                            
              num_threads: 1                             	[default: 4]
                output_nc: 3                             
                    phase: test                          
               preprocess: resize_and_crop               
              results_dir: ./results/                    
           serial_batches: False                         
                   suffix:                               
                  verbose: False                         
----------------- End -------------------
dataset [SingleDataset] was created
initialize network with normal
model [TestModel] was created
loading the model from trained_model/expname/latest_net_G.pth
Traceback (most recent call last):
  File "test.py", line 47, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/content/gdrive/My Drive/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "/content/gdrive/My Drive/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 198, in load_networks
    net.load_state_dict(state_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Missing key(s) in state_dict: "model.1.bias", "model.4.bias", "model.7.bias", "model.10.conv_block.1.bias", "model.10.conv_block.6.bias", "model.11.conv_block.1.bias", "model.11.conv_block.6.bias", "model.12.conv_block.1.bias", "model.12.conv_block.6.bias", "model.13.conv_block.1.bias", "model.13.conv_block.6.bias", "model.14.conv_block.1.bias", "model.14.conv_block.6.bias", "model.15.conv_block.1.bias", "model.15.conv_block.6.bias", "model.16.conv_block.1.bias", "model.16.conv_block.6.bias", "model.17.conv_block.1.bias", "model.17.conv_block.6.bias", "model.18.conv_block.1.bias", "model.18.conv_block.6.bias", "model.19.bias", "model.22.bias". 
	Unexpected key(s) in state_dict: "model.2.weight", "model.2.bias", "model.5.weight", "model.5.bias", "model.8.weight", "model.8.bias", "model.10.conv_block.2.weight", "model.10.conv_block.2.bias", "model.10.conv_block.7.weight", "model.10.conv_block.7.bias", "model.11.conv_block.2.weight", "model.11.conv_block.2.bias", "model.11.conv_block.7.weight", "model.11.conv_block.7.bias", "model.12.conv_block.2.weight", "model.12.conv_block.2.bias", "model.12.conv_block.7.weight", "model.12.conv_block.7.bias", "model.13.conv_block.2.weight", "model.13.conv_block.2.bias", "model.13.conv_block.7.weight", "model.13.conv_block.7.bias", "model.14.conv_block.2.weight", "model.14.conv_block.2.bias", "model.14.conv_block.7.weight", "model.14.conv_block.7.bias", "model.15.conv_block.2.weight", "model.15.conv_block.2.bias", "model.15.conv_block.7.weight", "model.15.conv_block.7.bias", "model.16.conv_block.2.weight", "model.16.conv_block.2.bias", "model.16.conv_block.7.weight", "model.16.conv_block.7.bias", "model.17.conv_block.2.weight", "model.17.conv_block.2.bias", "model.17.conv_block.7.weight", "model.17.conv_block.7.bias", "model.18.conv_block.2.weight", "model.18.conv_block.2.bias", "model.18.conv_block.7.weight", "model.18.conv_block.7.bias", "model.20.weight", "model.20.bias", "model.23.weight", "model.23.bias".

**Comment by junyanz** [comment]
You need to add `--norm batch`.

**Comment by sand47** [comment]
Thank you so much for your time, it worked!
