### ISSUE TITLE
CPU training time

### ISSUE THREAD

**Issue by manvirvirk** [junyanz/pytorch-CycleGAN-and-pix2pix#914]
it is taking alot of training time on CPU. Is it possible to reduce CPU training time?How long it takes to train using CPU?

**Comment by diaosiji** [comment]
Very very long time. I advice you that only use pretrained model to predict on CPU, or training on a tiny dataset.

**Comment by junyanz** [comment]
It could be 10x slower, and take 1-2 weeks for a small dataset.

**Comment by manvirvirk** [comment]
thanks for the help
