### ISSUE TITLE
Approx Training time

### ISSUE THREAD

**Issue by arunasank** [junyanz/pytorch-CycleGAN-and-pix2pix#917]
What is the approximate training time for a sample of 118165 images? Each image is 178 * 218? Each of my GPUs is 10GB. I am using your docker image to train.

```
python3 train.py --dataroot ./datasets/male2female/ --name male2female_cyclegan --model cycle_gan --resize_or_crop crop --fineSize 100 --loadSize 178 --batch_siize 10 --gpu_ids 1,3,4,5,6,7 --continue_train --norm instance
```

cc @junyanz

**Comment by junyanz** [comment]
It can vary based on your GPU and hard drive The program will print timing per iteration on the console. You can calculate the training time.
