### ISSUE TITLE
the tiny question about 'store_true option'

### ISSUE THREAD

**Issue by khryang** [junyanz/pytorch-CycleGAN-and-pix2pix#92]
in your base and train option, does the 'store_true' mean the default value of the original function?

1. for example, in 'base_options.py'
        self.parser.add_argument('--serial_batches', action='store_true', help='if true, takes images in order to make batches, otherwise takes them randomly')

2. and that flag use in data_loader.py
        shuffle=not self.opt.serial_batches

what does mean that 'store_true'?
and 'shuffle' is true if opt.serial_batches is not mentioned?

could you explain the function of code (1 and 2) ?

**Comment by khryang** [comment]
I searched on the internet, it told that if

**Comment by junyanz** [comment]
See the argparse [document](https://docs.python.org/2/library/argparse.html) for more details.
By default, `opt.serial_batches=False`. If you added the flag `--serial_batches` in the command line, it will make `opt.serial_batches=True`, and it will not shuffle the input data. This is helpful if you want to fix the order of your test images.
