### ISSUE TITLE
Still get this error--module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by jmq19950824** [junyanz/pytorch-CycleGAN-and-pix2pix#927]
I tried to reproduce the code from [https://github.com/samet-akcay/ganomaly](url) and run the commands in the git bash software. But I meet the following problems and it seems difficult for me to fix it by myself:

![image](https://user-images.githubusercontent.com/39890732/75091679-2367df80-55ab-11ea-8097-5617abd1910a.png)

**the main error is "AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'"**

1.
I tried to fix this problems by refering #360 and #67——
that is, I change the code **torch.cuda.set_device(self.opt.gpu_ids[0])** to  **torch.cuda.set_device(self.opt.gpu_ids[-1])** and **torch._C._cuda_setDevice(device)** to **torch._C._cuda_setDevice(-1)**，but it still not works.

2.
I tried to reinstall the pytorch and update to the newest version (1.4.0), still exists error.

3.
I read the PyTorch Q&A and there may be some problems about my CUDA, I tried to add **--gpu_ids -1** to my code (that is, sh experiments/run_mnist.sh --gpu_ids -1, see the following picture), still exit error.
![image](https://user-images.githubusercontent.com/39890732/75091866-f9afb800-55ac-11ea-90bc-7f45dced0c60.png)

I was stucked by this problem by few days and I hope someone could help me. Thanks a lot!

**Comment by junyanz** [comment]
Not sure if it is related to our repo. Could you post the questions at PyTorch repo or ganomaly repo?
