### ISSUE TITLE
train error ： ImportError: cannot import name 'Optional'

### ISSUE THREAD

**Issue by TryingZ** [junyanz/pytorch-CycleGAN-and-pix2pix#933]
File "/home/zhang/anaconda3/envs/py3pt/lib/python3.6/site-packages/torchvision/models/inception.py", line 8, in <module>
    from torch.jit.annotations import Optional
ImportError: cannot import name 'Optional'

after pip install use requirement.txt

**Comment by liushuangliuliu** [comment]
i have the same problem ,have you fix it?? bro

**Comment by liushuangliuliu** [comment]
I have the same problem,have you fixed it ? bro

**Comment by TryingZ** [comment]
> I have the same problem,have you fixed it ? bro
check the version of pytorch and torchvision ,the versions of pytorch and torchvision should correspond to each other.

**Comment by liushuangliuliu** [comment]
it work ，thank you！

**Comment by Yinhance** [comment]
> > I have the same problem,have you fixed it ? bro
> > check the version of pytorch and torchvision ,the versions of pytorch and torchvision should correspond to each other.

thx！

**Comment by jokisa** [comment]
i have the same problem. Please can you tell me how you fix it,

thanks

**Comment by junyanz** [comment]
According to this [post](https://github.com/open-mmlab/mmdetection/issues/2138), it might be caused by version incompatibility between PyTorch and torchvision.
