### ISSUE TITLE
Newer versions of CycleGAN?

### ISSUE THREAD

**Issue by kpagels** [junyanz/pytorch-CycleGAN-and-pix2pix#948]
Hi. I have worked with CycleGAN the last year and I really like it!. But since cyclegan is from 2017 it is almost 3 years old now. Do you know if there are some "better" versions of CycleGAN in 2020? Or some other extensions of GANs that does the image to image translation just as CycleGAN but just more optimal?

**Comment by junyanz** [comment]
You may want to try [StarGAN](https://github.com/clovaai/stargan-v2)(-v2), [MUNIT](https://github.com/NVlabs/MUNIT) and [DRIT](https://github.com/HsinYingLee/DRIT)(++). The performance of each model highly depends on your application. No single model works better than others in all the datasets.

**Comment by kpagels** [comment]
Thanks @junyanz. What about Domain Adaptation? I noticed you guys did an extension called CyCADA. Did you do any updates on this one? Or do you know of newer methods in domain adaptations with GAN?

**Comment by junyanz** [comment]
There are probably new methods. You can check which paper cites CycADA in google scholar.

**Comment by kpagels** [comment]
Thanks @junyanz . Have a nice day.
