### ISSUE TITLE
why the color was change! when load image and show it

### ISSUE THREAD

**Issue by donghaoye** [junyanz/pytorch-CycleGAN-and-pix2pix#95]
why the color was change! when load image and show it

**Comment by junyanz** [comment]
What will happen if you save the image again, and open it? Could you show a side-by-side example?

**Comment by donghaoye** [comment]
I have solved this problem.
Since I use opencv2 to handle image, the color was change.
Your project  processes image by PIL. I get it. THKS!

**Comment by junyanz** [comment]
I am glad that you fixed it.
