### ISSUE TITLE
Call for more edges-object datasets

### ISSUE THREAD

**Issue by diaosiji** [junyanz/pytorch-CycleGAN-and-pix2pix#951]
Thank @junyanz and his fellows, pix2pix project provide two large dataset: edges2shoes and edges2handbags for edges to object image generation training, and also, there is a instruction for how to build our own datasets, I go through that, it works.

However, the single object images, which are white background and res is bigger than 256*256, are hard to Spider on the net(like Amazon and JD)，I worked for weeks, the pictures spider down are different and most of them are complex backgrounded.

So, May I ask for help that, **Anyone can give me some existing object image dataset names, in which, the images are white background, the object is single in the center of the pic, and the res is >= 256*256pix**. So I can go on with HED edges getting and edges-object datasets construction. When it done, I will share it.

Thanks!

**Comment by junyanz** [comment]
I think you can detect if the image has a white background, by counting the number of white pixels or using a color histogram.

**Comment by diaosiji** [comment]
> You can potentially detect if the image has a white background, by counting the number of white pixels or using a color histogram.

Thanks for your advice! I will take it!
