### ISSUE TITLE
ValueError: empty range for randrange() (0,0, 0)

### ISSUE THREAD

**Issue by manvirvirk** [junyanz/pytorch-CycleGAN-and-pix2pix#960]
i m getting this error?
can anyone help?

 File "C:\Users\virkt\Anaconda3\envs\pix2pix\lib\random.py", line 200, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)

**Comment by manvirvirk** [comment]
how to solve this?

**Comment by junyanz** [comment]
See this [Q&A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#valueerror-empty-range-for-randrange-390-376-194).

**Comment by manvirvirk** [comment]
i got it. Can you tell me where in the code (lines numbers) we have to make changes. Thanks

**Comment by manvirvirk** [comment]
my image size is greater than crop size.

**Comment by junyanz** [comment]
Your image size might be smaller than crop size.

**Comment by manvirvirk** [comment]
How to change crop size in code?

**Comment by junyanz** [comment]
Add the flag `--crop_size`.

**Comment by manvirvirk** [comment]
i could not solve . please tell where to add this flag?

**Comment by manvirvirk** [comment]
my load size is 286 and crop size is 256

**Comment by manvirvirk** [comment]
thanks for helping long way . got it :) training started.
