### ISSUE TITLE
Loss plots from a model that has finished running

### ISSUE THREAD

**Issue by arunasank** [junyanz/pytorch-CycleGAN-and-pix2pix#967]
I finished running my CycleGAN model for the full 200 epochs, and terminated the visdom server as well. Are the final loss plots stored somewhere or can they be regenerated somehow?

**Comment by arunasank** [comment]
Duplicate of https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/28. 

I presume the way is to extract it from the `loss_log.txt`?

**Comment by junyanz** [comment]
Yes. You probably need to write some visualization code to plot the data stored in this text file.
