### ISSUE TITLE
Training on larger image size, but still generates in 256x256

### ISSUE THREAD

**Issue by Rachnog** [junyanz/pytorch-CycleGAN-and-pix2pix#97]
Hi to all,
First of all, thanks to authors for amazing software!

I successfully trained couple of models with default parameters, but when I changed` --loadSize 550 --fineSize 512 --display_winsize 512` parameters from default to 512 (I want to generate images of this size), train process was totally alright, but when I tried to generate images, all they were of size 256x256 and it happened couple of times. Here is the command I've used to train:

`python train.py --dataroot ./xxx --name xxx_cyclegan_512 --model cycle_gan --no_dropout --loadSize 550 --fineSize 512 --display_winsize 512`

What should I do to generate larger images?
Thanks for help!

**Comment by mrluker** [comment]
Open base_options.py, and change loadSize and fineSize.

Save and then run test. You can test at higher resolutions than you can train.
