### ISSUE TITLE
when offline is set to True in visualizer function

### ISSUE THREAD

**Issue by kpagels** [junyanz/pytorch-CycleGAN-and-pix2pix#976]
Hi,

When I set offline = True and log_to_filename="test.json". 

https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/fb5f30e2f590d1a50d1b2be6c3a7ae2f0ed48376/util/visualizer.py#L72

Do you have an suggestion on how I visualize it in python? Did you create any code for this?

**Comment by junyanz** [comment]
Not sure if I understand your question. We used Visdom to visualize results. Please see visdom [repo](https://github.com/facebookresearch/visdom) for more details.

**Comment by kpagels** [comment]
Okay @junyanz I found out how it worked. But when my program is done running. How can I visualize it? I can read that argument is replay_log and the filename. But how exactly does I run this? Do you have any guidelines?

**Comment by junyanz** [comment]
You should be able to still the plot after your training is finished, as long as you don't kill your visdom server. I haven't used `replay_log`. I am not sure if the format in `loss_log` will work for the function.

**Comment by kpagels** [comment]
Okay. Thanks @junyanz :)
