### ISSUE TITLE
Error while using cyclegan for images with size of channel = 1 (grayscale images)

### ISSUE THREAD

**Issue by isalirezag** [junyanz/pytorch-CycleGAN-and-pix2pix#98]
I was trying to use cyclegan for gray scale images, i chose` --input_nc 1 --output_nc 1` , but I still receive an error.

>  RuntimeError: Need input.size[1] == 1 but got 3 instead.

Does anyone try to see 1 channel thing works?
I use this to run the code for grayscale images:
`python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --no_dropout --input_nc 1 --output_nc 1 --pool_size 50 --loadSize 64 --fineSize 32 --batchSize 1
`
I do have gray scale images in the Train A and B and Val A and B folders, but for some reasons that I dont know it still consider 3 channels....
Anyone have any idea why?

![image](https://user-images.githubusercontent.com/12434910/30236429-f3e46f94-94cd-11e7-9683-a74ca6bd281a.png)

**Comment by junyanz** [comment]
1 channel images are supported now.

**Comment by isalirezag** [comment]
I dont think it is supporting grayscale images correctly yet.
It did train based on grayscale but when I tried to test it on gray scale images it gave me an error:
```
While copying the parameter named model.1.weight, whose dimensions in the model are torch.Size([100, 1, 7, 7]) and whose dimensions in the checkpoint are torch.Size([1, 3, 7, 7]), ...
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    model = create_model(opt)
  File "/home/sgolest1/Desktop/AAA/JPEG/vision/pytorch-CycleGAN-and-pix2pix/models/models.py", line 19, in create_model
    model.initialize(opt)
  File "/home/sgolest1/Desktop/AAA/JPEG/vision/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 46, in initialize
    self.load_network(self.netG_A, 'G_A', which_epoch)
  File "/home/sgolest1/Desktop/AAA/JPEG/vision/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 360, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:48

```

**Comment by junyanz** [comment]
Did you add `--input_nc 1` flag in your test script

**Comment by isalirezag** [comment]
yeap (python test.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --phase test  --no_dropout --input_nc 1 --output_nc 1
)
, it didnot help

**Comment by junyanz** [comment]
Did you get good results during training? Your input and output images are both grayscale images?
From the error information, It seems that you can load G_A but not G_B.
Could you try to print the network architecture with the following command during both training and test. 
You can add this command before loading the models. 
```python
networks.print_network(self.netG_A)
networks.print_network(self.netG_B)
```

**Comment by isalirezag** [comment]
The training did finished successfully, the problem appears for testing.
if I put 
```
networks.print_network(self.netG_A)
networks.print_network(self.netG_B) 
```
before 
`model = create_model(opt)`
that wont work because it says 

> NameError: name 'networks' is not defined

**Comment by junyanz** [comment]
You need to add it [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/cycle_gan_model.py#L34)

**Comment by isalirezag** [comment]
Here is the output:

`cycle_gan
initialization method [xavier]
initialization method [xavier]
ResnetGenerator (
  (model): Sequential (
    (0): ReflectionPad2d (3, 3, 3, 3)
    (1): Conv2d(1, 100, kernel_size=(7, 7), stride=(1, 1))
    (2): InstanceNorm2d(100, eps=1e-05, momentum=0.1, affine=False)
    (3): ReLU (inplace)
    (4): Conv2d(100, 200, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (5): InstanceNorm2d(200, eps=1e-05, momentum=0.1, affine=False)
    (6): ReLU (inplace)
    (7): Conv2d(200, 400, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (8): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
    (9): ReLU (inplace)
    (10): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (11): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (12): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (13): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (14): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (15): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (16): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (17): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (18): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (19): ConvTranspose2d(400, 200, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
    (20): InstanceNorm2d(200, eps=1e-05, momentum=0.1, affine=False)
    (21): ReLU (inplace)
    (22): ConvTranspose2d(200, 100, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
    (23): InstanceNorm2d(100, eps=1e-05, momentum=0.1, affine=False)
    (24): ReLU (inplace)
    (25): ReflectionPad2d (3, 3, 3, 3)
    (26): Conv2d(100, 1, kernel_size=(7, 7), stride=(1, 1))
    (27): Tanh ()
  )
)
Total number of parameters: 27738001
ResnetGenerator (
  (model): Sequential (
    (0): ReflectionPad2d (3, 3, 3, 3)
    (1): Conv2d(1, 100, kernel_size=(7, 7), stride=(1, 1))
    (2): InstanceNorm2d(100, eps=1e-05, momentum=0.1, affine=False)
    (3): ReLU (inplace)
    (4): Conv2d(100, 200, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (5): InstanceNorm2d(200, eps=1e-05, momentum=0.1, affine=False)
    (6): ReLU (inplace)
    (7): Conv2d(200, 400, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (8): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
    (9): ReLU (inplace)
    (10): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (11): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (12): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (13): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (14): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (15): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (16): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (17): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (18): ResnetBlock (
      (conv_block): Sequential (
        (0): ReflectionPad2d (1, 1, 1, 1)
        (1): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
        (3): ReLU (inplace)
        (4): ReflectionPad2d (1, 1, 1, 1)
        (5): Conv2d(400, 400, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(400, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (19): ConvTranspose2d(400, 200, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
    (20): InstanceNorm2d(200, eps=1e-05, momentum=0.1, affine=False)
    (21): ReLU (inplace)
    (22): ConvTranspose2d(200, 100, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
    (23): InstanceNorm2d(100, eps=1e-05, momentum=0.1, affine=False)
    (24): ReLU (inplace)
    (25): ReflectionPad2d (3, 3, 3, 3)
    (26): Conv2d(100, 1, kernel_size=(7, 7), stride=(1, 1))
    (27): Tanh ()
  )
)
Total number of parameters: 27738001
initialization method [xavier]
initialization method [xavier]
While copying the parameter named model.1.weight, whose dimensions in the model are torch.Size([100, 1, 7, 7]) and whose dimensions in the checkpoint are torch.Size([1, 3, 7, 7]), ...
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    model = create_model(opt)
  File "/home/sgolest1/Desktop/AAA/JPEG/vision/pytorch-CycleGAN-and-pix2pix/models/models.py", line 19, in create_model
    model.initialize(opt)
  File "/home/sgolest1/Desktop/AAA/JPEG/vision/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 47, in initialize
    self.load_network(self.netG_A, 'G_A', which_epoch)
  File "/home/sgolest1/Desktop/AAA/JPEG/vision/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 360, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:48`

**Comment by junyanz** [comment]
It looks fine to me. We have 
Conv2d(1, 100, kernel_size=(7, 7), stride=(1, 1))
 Conv2d(100, 1, kernel_size=(7, 7), stride=(1, 1))
which means it takes an 1-channel image as input, and produces an 1-channel image. 
I wonder if you have changed the ndf/ngf during training/test. 
It would be great if can also print the network for your training script.

**Comment by isalirezag** [comment]
I did change both ndf/ngf and also made sure that it is the same at testing stage.
I dont see why it can be an issue though :)
