### ISSUE TITLE
Facing issue while testing the cycleGAN model

### ISSUE THREAD

**Issue by kalai2033** [junyanz/pytorch-CycleGAN-and-pix2pix#980]
Hi,
   I am getting this error while testing the cycle gan model that i trained for my dataset. I used the following command and got following error.

!python test.py --dataroot ctest --dataset_mode single --model test --results_dir results_cyc --netG resnet_9blocks --preprocess none --name cyclebw  --norm instance --checkpoints_dir apr3 --input_nc 1 --output_nc 1

Traceback (most recent call last):
  File "test.py", line 47, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/home/kalai/exp/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "/home/kalai/exp/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 198, in load_networks
    net.load_state_dict(state_dict)
  File "/home/kalai/anaconda3/envs/my_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Missing key(s) in state_dict: "model.10.conv_block.6.weight", "model.10.conv_block.6.bias", "model.11.conv_block.6.weight", "model.11.conv_block.6.bias", "model.12.conv_block.6.weight", "model.12.conv_block.6.bias", "model.13.conv_block.6.weight", "model.13.conv_block.6.bias", "model.14.conv_block.6.weight", "model.14.conv_block.6.bias", "model.15.conv_block.6.weight", "model.15.conv_block.6.bias", "model.16.conv_block.6.weight", "model.16.conv_block.6.bias", "model.17.conv_block.6.weight", "model.17.conv_block.6.bias", "model.18.conv_block.6.weight", "model.18.conv_block.6.bias". 
	Unexpected key(s) in state_dict: "model.10.conv_block.5.weight", "model.10.conv_block.5.bias", "model.11.conv_block.5.weight", "model.11.conv_block.5.bias", "model.12.conv_block.5.weight", "model.12.conv_block.5.bias", "model.13.conv_block.5.weight", "model.13.conv_block.5.bias", "model.14.conv_block.5.weight", "model.14.conv_block.5.bias", "model.15.conv_block.5.weight", "model.15.conv_block.5.bias", "model.16.conv_block.5.weight", "model.16.conv_block.5.bias", "model.17.conv_block.5.weight", "model.17.conv_block.5.bias", "model.18.conv_block.5.weight", "model.18.conv_block.5.bias". 

When i use --model cycle_gan flag im getting different error.

Command:
!python test.py --dataroot ctest --dataset_mode single --model cycle_gan --results_dir results_cyc --netG resnet_9blocks --preprocess none --name cyclebw  --norm instance --checkpoints_dir apr3 --input_nc 1 --output_nc 1

Error:
Traceback (most recent call last):
  File "test.py", line 59, in <module>
    model.set_input(data)  # unpack data from data loader
  File "/home/kalai/exp/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 109, in set_input
    self.real_B = input['B' if AtoB else 'A'].to(self.device)
KeyError: 'B'

**Comment by junyanz** [comment]
1. You may want to add the flag `--no_droptout` when you use `--model test`. Just make sure your training and test flags are the same. 
2. If you use `--model cycle_gan` for testing, you should use `--dataset_mode unaligned`.

**Comment by kalai2033** [comment]
@junyanz Thanks a lot. It worked.

**Comment by mehwhatever0** [comment]
@junyanz 
Why doesn't `TestModel` set `no_dropout=True` by default? It seems strange to me because `CycleGANModel` does this: https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/f13aab8148bd5f15b9eb47b690496df8dadbab0c/models/cycle_gan_model.py#L39 `TestModel` is only used for testing `CycleGANModel`'s results so it should be logical to have the same behavior by default for them.
