### ISSUE TITLE
RuntimeError: CUDA out of memory and size mismatch

### ISSUE THREAD

**Issue by kpagels** [junyanz/pytorch-CycleGAN-and-pix2pix#984]
I know this question has been asked many times and im sorry if I am just repeating what the others are asking. I tried to read all the answers and see if it could help me. I have two questions:

1) 
When I resize my images to 32x32 there is no problem. But when I try to resize the images to 64x64 or 128x128 I receive the RuntimeError. I have an GeRTX2080ti GPU and actually more GPUs available if needed. As far as I know 64x64 images are not that large? I see others training with much higher resolution then this. 
Do you know what can cause this error? 
`
RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 10.76 GiB total capacity; 9.54 GiB already allocated; 15.56 MiB free; 396.10 MiB cached)
`

2) 
When I change the batchsize to other then 100 I get the following error: This is for batchsize 32: RuntimeError: size mismatch, m1: [32 x 2304], m2: [256 x 1024] at /tmp/pip-req-build-zfu01l1o/aten/src/THC/generic/THCTensorMathBlas.cu:290
Why is it that I cant change the batchsize to e.g. 32?

**Comment by junyanz** [comment]
Does the code work for batchSize=1 and image size =128? BatchSize=100 might be too big for your GPU memory. Not sure if the generator will work for images with 32x32. `unet_128` and `unet_256` will not work. `resnet_6blocks` and `resnet_9blocks` might work.

**Comment by kpagels** [comment]
Hi again. There is something I forgot to mention. I am using the CyCADA code and when I change`--model cycle_gan` and run with batchSize=1, image size = 128 it uses 1.7GB of memory and runs without any problem. When I change batchSize=16, image size = 128 it uses 9GB of memory. But with batchSize=32 it runs out of memory. Ok so there is no problem when I run the `--model cycle_gan`.

But when I change the `--model cycle_gan_semantic` to your CyCADA method for **domain adaptation** it does not work with batchSize = 1 and image size = 128. Then it returns the following error:

`RuntimeError: size mismatch, m1: [1 x 12544], m2: [256 x 1024] at /tmp/pip-req-build-zfu01l1o/aten/src/THC/generic/THCTensorMathBlas.cu:290`

When I try to keep the batchSize = 1 and change image size to 64 I get the following error:

`RuntimeError: size mismatch, m1: [1 x 2304], m2: [256 x 1024] at /tmp/pip-req-build-zfu01l1o/aten/src/THC/generic/THCTensorMathBlas.cu:290`

When I keep the batchSize = 1 and change image size = 32 I get the following error:

`ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])` 

When I change the batchSize = 16 and keep image size = 32 it runs and uses 1.7GB

Is there something I am missing about the `--model cycle_gan_semantic`? Should the input dimensions of the two datasets be different? Or cant I use image size = 128 for both datasets? Or should the size of the dataset A and B be of some fixed size?

**Comment by junyanz** [comment]
I am not familiar with `--model cycle_gan_semantic`. I recommend that you post the question on cycada repo or send an email to the leading author.

**Comment by kpagels** [comment]
Ok. I just thought you were also author of “ CyCADA: Cycle-Consistent Adversarial Domain Adaptation   https://arxiv.org/abs/1711.03213”?

 And Judy Hoffman are not replying on the issues on the github page. But ill try to send her a mail.

**Comment by junyanz** [comment]
Yes. But that network was not implemented by me. Please send an email. Thanks.
