### ISSUE TITLE
train the pix2pix that it's slow!

### ISSUE THREAD

**Issue by HiIcy** [junyanz/pytorch-CycleGAN-and-pix2pix#985]
What parameter need I to modification for speeding trianging?

**Comment by junyanz** [comment]
Training should be reasonably fast on a modern GPU. If you want faster training, you can use lower-resolution images and smaller networks. If you use 128x128 images, you can use `unet_128`.

**Comment by HiIcy** [comment]
@junyanz  okay!thank your reply!!I will try it.
but a another problem,I use the `facade` dataset with the size 90M,I find out the gan loss is steep,it is likely difficult to restrain oneself. So how many step it need? thank you,boss!

**Comment by junyanz** [comment]
You can use the default parameters `--n_epochs 200 --n_epochs_decay 200`.

**Comment by HiIcy** [comment]
oh,thanks! I use the default `readme`'s `facade` dataset,and i still can't  get the effect like your model,
my train command as follow:
`python train.py --dataroot ./datasets/facades --name facade1930 --model pix2pix --direction BtoA --dataset_mode aligned --crop_size 512 --load_size 512 --epoch 1000`
Besides,I always get the black image when I test,and I check the test image certainly! what cause this?

**Comment by junyanz** [comment]
Could you use `--n_epochs 200 --n_epochs_decay 200`? `--epoch` is used for other [purpose](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L53).

**Comment by HiIcy** [comment]
yes,I already used default parameters! I try to use my custom `generator` with your `train code`,I can get the similar effect,but I can't reproduce the effect on my `train code`,I ever try to change my code in the light of your code,but it's useless!Is there anything else I should pay attention to?thanks!

**Comment by junyanz** [comment]
It's hard to know unless I read your code. Unfortunately, I don't have the capacity to look at your code in detail. My general advice is that you start from our codebase, and change one thing at a time, and see when it breaks.

**Comment by HiIcy** [comment]
It's ok,I'm very, very grateful for your help！
