### ISSUE TITLE
Unable to access monet2photohires images

### ISSUE THREAD

**Issue by Adrian-1234** [junyanz/pytorch-CycleGAN-and-pix2pix#987]
Unable to access the above images in https://people.eecs.berkeley.edu/~taesung_park/CycleGAN/datasets/

Returns permission denied.

**Comment by taesungp** [comment]
Hi Adrian-1234, the high res dataset is not supposed to be public. So we removed the dataset. The pretrained models were trained to be run on the lower res dataset. Sorry for confusion.
