### ISSUE TITLE
About pix2pix test

### ISSUE THREAD

**Issue by KevinMarkVine** [junyanz/pytorch-CycleGAN-and-pix2pix#994]
When I used the dataset Facades to test my pix2pix model, I found that only half of the images were tested and there were only 50 images. I want to know why

**Comment by junyanz** [comment]
You can set `--num_test`. The default value is 50.

**Comment by KevinMarkVine** [comment]
> You can set `--num_test`. The default value is 50.

oh! I ignored this option, Thanks!!
