### ISSUE TITLE
edges2shoes, edges2handbag training details

### ISSUE THREAD

**Issue by EndlessSora** [junyanz/pytorch-CycleGAN-and-pix2pix#999]
Hi @junyanz , just to confirm a small training detail: did you perform random jitter (i.e., set `--load_size 286 --crop_size 256`) and mirroring (i.e., **NOT** set `--no_flip`) for edges2shoes and edges2handbag datasets? I found that you wrote this detail in _6.2. Training details_ section of your paper w.r.t. other datasets, but not for these two edge datasets. 

Many thanks for your help~ :)

**Comment by junyanz** [comment]
For edges2shoes, we didn't do cropping and flipping as the dataset is large enough. Also, random cropping sometimes will break the boundary of shoes. For edges2handbags, we might have used flipping. But we didn't use cropping.

**Comment by EndlessSora** [comment]
Thanks for your clear and prompt response, Prof. Zhu! :wink:
